import HardyTheorem.AFECriticalDyadicCanonicalSelector

#check HardyTheorem.AFE.measurable_criticalAfeCutoff
#check HardyTheorem.AFE.continuous_dyadicMovingPrefixMollifiedPolynomial
#check HardyTheorem.AFE.dyadicClampedCriticalPrefixMollifiedPolynomial
#check HardyTheorem.AFE.measurable_dyadicClampedCriticalPrefixMollifiedPolynomial
#check HardyTheorem.AFE.criticalAfeCutoff_succ_le_pow_of_mem_Icc
#check HardyTheorem.AFE.dyadicClampedCriticalPrefix_eq_of_cutoff_succ_le
#check HardyTheorem.AFE.criticalAfeMainSum_mul_mollifier_eq_dyadicClampedPrefix
#check HardyTheorem.AFE.integral_gaussian_normSq_dyadicClampedCriticalPrefix_le

#print axioms HardyTheorem.AFE.criticalAfeMainSum_mul_mollifier_eq_dyadicClampedPrefix
#print axioms HardyTheorem.AFE.integral_gaussian_normSq_dyadicClampedCriticalPrefix_le
