import HardyTheorem.AFECriticalHalfRangeRemainder

#check HardyTheorem.AFE.criticalAfeRemainderWindowBound_le_halfRange
#check HardyTheorem.AFE.criticalAfeRemainderWindowBound_le_halfRange_const
#check HardyTheorem.AFE.setIntegral_gaussian_normSq_criticalAfeProduct_le_halfRange
#check HardyTheorem.AFE.exists_dyadic_strict_upper_le_two_mul
#check HardyTheorem.AFE.exists_dyadic_setIntegral_gaussian_normSq_criticalAfeProduct_le_halfRange

#print axioms HardyTheorem.AFE.criticalAfeRemainderWindowBound_le_halfRange
#print axioms HardyTheorem.AFE.criticalAfeRemainderWindowBound_le_halfRange_const
#print axioms HardyTheorem.AFE.setIntegral_gaussian_normSq_criticalAfeProduct_le_halfRange
#print axioms HardyTheorem.AFE.exists_dyadic_strict_upper_le_two_mul
#print axioms HardyTheorem.AFE.exists_dyadic_setIntegral_gaussian_normSq_criticalAfeProduct_le_halfRange
