import HardyTheorem.AFECriticalDyadicCanonicalSelector

#check HardyTheorem.AFE.measurable_criticalAfeCutoff
#check HardyTheorem.AFE.continuous_dyadicMovingPrefixMollifiedPolynomial
#check HardyTheorem.AFE.dyadicClampedCriticalPrefixMollifiedPolynomial
#check HardyTheorem.AFE.measurable_dyadicClampedCriticalPrefixMollifiedPolynomial
#check HardyTheorem.AFE.criticalAfeCutoff_succ_le_pow_of_mem_Icc
#check HardyTheorem.AFE.dyadicClampedCriticalPrefix_eq_of_cutoff_succ_le
#check HardyTheorem.AFE.criticalAfeMainSum_mul_mollifier_eq_dyadicClampedPrefix
#check HardyTheorem.AFE.criticalAfeDualSum_eq_conj_mainSum
#check HardyTheorem.AFE.criticalAfeDualProduct_normSq_eq_mainProduct
#check HardyTheorem.AFE.integrable_gaussian_normSq_dyadicClampedCriticalPrefix
#check HardyTheorem.AFE.integral_gaussian_normSq_dyadicClampedCriticalPrefix_le
#check HardyTheorem.AFE.setIntegral_gaussian_normSq_criticalAfeMain_mul_mollifier_le
#check HardyTheorem.AFE.setIntegral_gaussian_normSq_criticalAfeDualProduct_le

#print axioms HardyTheorem.AFE.criticalAfeMainSum_mul_mollifier_eq_dyadicClampedPrefix
#print axioms HardyTheorem.AFE.setIntegral_gaussian_normSq_criticalAfeMain_mul_mollifier_le
#print axioms HardyTheorem.AFE.setIntegral_gaussian_normSq_criticalAfeDualProduct_le
#print axioms HardyTheorem.AFE.integral_gaussian_normSq_dyadicClampedCriticalPrefix_le
