import HardyTheorem.AFEWeightedPoissonVelocityBounds

open HardyTheorem AFE

#check weightedPoissonVelocity_neg_nat
#check abs_weightedPoissonVelocity_of_nonneg_frequency
#check time_div_le_abs_weightedPoissonVelocity_of_nonneg_frequency
#check frequency_le_abs_weightedPoissonVelocity_of_nonneg_frequency
#check left_endpoint_gap_le_abs_weightedPoissonVelocity_neg_nat
#check right_endpoint_gap_le_abs_weightedPoissonVelocity_neg_nat

#print axioms abs_weightedPoissonVelocity_of_nonneg_frequency
#print axioms left_endpoint_gap_le_abs_weightedPoissonVelocity_neg_nat
#print axioms right_endpoint_gap_le_abs_weightedPoissonVelocity_neg_nat
