import PrimeNumberTheorem.CarlsonMeanSquareContourBridge

open PrimeNumberTheorem

#check CarlsonZeroDensity.exists_regularizedCarlson_fixedRight_count_le_mollifiedMeanSquare_add_explicit_boundary_of_leftWindow_constantRight

#print axioms CarlsonZeroDensity.exists_regularizedCarlson_fixedRight_count_le_mollifiedMeanSquare_add_explicit_boundary_of_leftWindow_constantRight
