import PrimeNumberTheorem.CarlsonGaussianPoleFreeBoundaryContinuity

open Complex Set MeasureTheory
open scoped ENNReal MeasureTheory

namespace PrimeNumberTheorem.CarlsonZeroDensity

#check exists_integrable_carlsonGaussianPoleFreeSection_sq_bound_on_half_four
#check continuousOn_norm_sq_carlsonGaussianPoleFreeLpValueTotal_real
#check norm_sq_carlsonGaussianPoleFreeLpValueTotal_le_interp_on_closed_strip
#check norm_sq_carlsonGaussianPoleFreeLpValueTotal_le_of_endpoint_bounds

#print axioms exists_integrable_carlsonGaussianPoleFreeSection_sq_bound_on_half_four
#print axioms continuousOn_norm_sq_carlsonGaussianPoleFreeLpValueTotal_real
#print axioms norm_sq_carlsonGaussianPoleFreeLpValueTotal_le_interp_on_closed_strip
#print axioms norm_sq_carlsonGaussianPoleFreeLpValueTotal_le_of_endpoint_bounds

end PrimeNumberTheorem.CarlsonZeroDensity
