import PrimeNumberTheorem.CarlsonHalfRangeProductIntegrable

#check PrimeNumberTheorem.CarlsonZeroDensity.exists_norm_sq_linearLogSelbergMollifiedZetaProduct_le_polynomial
#check PrimeNumberTheorem.CarlsonZeroDensity.exists_norm_sq_linearLogSelbergMollifiedZetaProduct_le_centeredPolynomial
#check PrimeNumberTheorem.CarlsonZeroDensity.integrable_gaussian_norm_sq_linearLogSelbergMollifiedZetaProduct
#check PrimeNumberTheorem.CarlsonZeroDensity.carlsonHalfRangeProductTail
#check PrimeNumberTheorem.CarlsonZeroDensity.integral_gaussian_product_eq_setIntegral_add_tail
#check PrimeNumberTheorem.CarlsonZeroDensity.integral_gaussian_product_le_halfRange_scale_add_tail

#print axioms PrimeNumberTheorem.CarlsonZeroDensity.exists_norm_sq_linearLogSelbergMollifiedZetaProduct_le_polynomial
#print axioms PrimeNumberTheorem.CarlsonZeroDensity.exists_norm_sq_linearLogSelbergMollifiedZetaProduct_le_centeredPolynomial
#print axioms PrimeNumberTheorem.CarlsonZeroDensity.integrable_gaussian_norm_sq_linearLogSelbergMollifiedZetaProduct
#print axioms PrimeNumberTheorem.CarlsonZeroDensity.integral_gaussian_product_eq_setIntegral_add_tail
#print axioms PrimeNumberTheorem.CarlsonZeroDensity.integral_gaussian_product_le_halfRange_scale_add_tail
