import PrimeNumberTheorem.CarlsonGaussianDetectorCovering

open Complex Set MeasureTheory

namespace PrimeNumberTheorem.CarlsonZeroDensity

#check norm_add_one_div_sub_one_le_five_of_re_eq_two_thirds
#check norm_twoScaleMollifiedZetaError_le_five_mul_poleFree_two_thirds
#check continuous_twoScaleMollifiedZetaError_vertical_two_thirds
#check integral_gaussian_norm_sq_twoScaleMollifiedZetaError_two_thirds_le
#check integral_indicator_Icc_norm_sq_twoScaleMollifiedZetaError_two_thirds_le

#print axioms norm_add_one_div_sub_one_le_five_of_re_eq_two_thirds
#print axioms norm_twoScaleMollifiedZetaError_le_five_mul_poleFree_two_thirds
#print axioms continuous_twoScaleMollifiedZetaError_vertical_two_thirds
#print axioms integral_gaussian_norm_sq_twoScaleMollifiedZetaError_two_thirds_le
#print axioms integral_indicator_Icc_norm_sq_twoScaleMollifiedZetaError_two_thirds_le

end PrimeNumberTheorem.CarlsonZeroDensity
