import PrimeNumberTheorem.CarlsonHalfRangeProductIntegrable

#check PrimeNumberTheorem.CarlsonZeroDensity.exists_uniform_norm_sq_linearLogSelbergMollifiedZetaProduct_le_polynomial
#check PrimeNumberTheorem.CarlsonZeroDensity.gaussianPolynomialMomentEight
#check PrimeNumberTheorem.CarlsonZeroDensity.integral_centeredPolynomialEight_mul_halfGaussian_le
#check PrimeNumberTheorem.CarlsonZeroDensity.exists_norm_sq_linearLogSelbergMollifiedZetaProduct_le_polynomial
#check PrimeNumberTheorem.CarlsonZeroDensity.exists_norm_sq_linearLogSelbergMollifiedZetaProduct_le_centeredPolynomial
#check PrimeNumberTheorem.CarlsonZeroDensity.integrable_gaussian_norm_sq_linearLogSelbergMollifiedZetaProduct
#check PrimeNumberTheorem.CarlsonZeroDensity.carlsonHalfRangeProductTail
#check PrimeNumberTheorem.CarlsonZeroDensity.exists_carlsonHalfRangeProductTail_le
#check PrimeNumberTheorem.CarlsonZeroDensity.halfRange_center_separation
#check PrimeNumberTheorem.CarlsonZeroDensity.exists_carlsonHalfRangeProductTail_le_broadScale
#check PrimeNumberTheorem.CarlsonZeroDensity.integral_gaussian_product_eq_setIntegral_add_tail
#check PrimeNumberTheorem.CarlsonZeroDensity.integral_gaussian_product_le_halfRange_scale_add_tail

#print axioms PrimeNumberTheorem.CarlsonZeroDensity.exists_norm_sq_linearLogSelbergMollifiedZetaProduct_le_polynomial
#print axioms PrimeNumberTheorem.CarlsonZeroDensity.exists_uniform_norm_sq_linearLogSelbergMollifiedZetaProduct_le_polynomial
#print axioms PrimeNumberTheorem.CarlsonZeroDensity.integral_centeredPolynomialEight_mul_halfGaussian_le
#print axioms PrimeNumberTheorem.CarlsonZeroDensity.exists_norm_sq_linearLogSelbergMollifiedZetaProduct_le_centeredPolynomial
#print axioms PrimeNumberTheorem.CarlsonZeroDensity.integrable_gaussian_norm_sq_linearLogSelbergMollifiedZetaProduct
#print axioms PrimeNumberTheorem.CarlsonZeroDensity.integral_gaussian_product_eq_setIntegral_add_tail
#print axioms PrimeNumberTheorem.CarlsonZeroDensity.exists_carlsonHalfRangeProductTail_le
#print axioms PrimeNumberTheorem.CarlsonZeroDensity.exists_carlsonHalfRangeProductTail_le_broadScale
#print axioms PrimeNumberTheorem.CarlsonZeroDensity.integral_gaussian_product_le_halfRange_scale_add_tail
