import PrimeNumberTheorem.CarlsonConreyCriticalBoundaryReduction

open Complex Set MeasureTheory

namespace PrimeNumberTheorem.CarlsonZeroDensity

#check conreyOuterMultiplier_sub_innerMultiplier_eq_one
#check twoScaleMollifiedZetaError_eq_conrey_linear_combination
#check norm_sq_twoScaleMollifiedZetaError_le_conrey_components
#check integral_gaussian_norm_sq_twoScaleMollifiedZetaError_half_le_of_components
#check norm_sq_carlsonGaussianPoleFreeLpValue_half_le_error_integral
#check norm_sq_carlsonGaussianPoleFreeLpValue_half_le_of_conrey_components
#check norm_sq_linearLogSelbergMollifiedZetaError_le_product
#check integrable_carlsonGaussianWeight
#check integral_gaussian_norm_sq_linearLogSelbergMollifiedZetaError_le_of_product
#check norm_sq_carlsonGaussianPoleFreeLpValue_half_le_of_conrey_product_components

#print axioms conreyOuterMultiplier_sub_innerMultiplier_eq_one
#print axioms twoScaleMollifiedZetaError_eq_conrey_linear_combination
#print axioms norm_sq_twoScaleMollifiedZetaError_le_conrey_components
#print axioms integral_gaussian_norm_sq_twoScaleMollifiedZetaError_half_le_of_components
#print axioms norm_sq_carlsonGaussianPoleFreeLpValue_half_le_error_integral
#print axioms norm_sq_carlsonGaussianPoleFreeLpValue_half_le_of_conrey_components
#print axioms norm_sq_linearLogSelbergMollifiedZetaError_le_product
#print axioms integrable_carlsonGaussianWeight
#print axioms integral_gaussian_norm_sq_linearLogSelbergMollifiedZetaError_le_of_product
#print axioms norm_sq_carlsonGaussianPoleFreeLpValue_half_le_of_conrey_product_components

end PrimeNumberTheorem.CarlsonZeroDensity
