import PrimeNumberTheorem.CarlsonGaussianPoleFreeHadamard

open Complex Set MeasureTheory
open scoped ENNReal MeasureTheory

namespace PrimeNumberTheorem.CarlsonZeroDensity

#check carlsonGaussianHilbertSection_eq_real_shift
#check norm_carlsonGaussianPoleFreeLpValueTotal_eq_real_part
#check diffContOnCl_carlsonGaussianPoleFreeLpValueTotal_on_inner_strip
#check bddAbove_norm_carlsonGaussianPoleFreeLpValueTotal_on_inner_closed_strip
#check norm_sq_carlsonGaussianPoleFreeLpValueTotal_le_interp_on_inner_strip

#print axioms carlsonGaussianHilbertSection_eq_real_shift
#print axioms norm_carlsonGaussianPoleFreeLpValueTotal_eq_real_part
#print axioms diffContOnCl_carlsonGaussianPoleFreeLpValueTotal_on_inner_strip
#print axioms bddAbove_norm_carlsonGaussianPoleFreeLpValueTotal_on_inner_closed_strip
#print axioms norm_sq_carlsonGaussianPoleFreeLpValueTotal_le_interp_on_inner_strip

end PrimeNumberTheorem.CarlsonZeroDensity
