import PrimeNumberTheorem.SingleLayerForcingSeparatedDensity
import PrimeNumberTheorem.CarlsonMeanSquareContourBridge
import HardyTheorem.TwoScaleSelbergMollifier
import PrimeNumberTheorem.CarlsonTwoScaleDetector
import PrimeNumberTheorem.CarlsonTwoScaleDetectorGrowth

#print axioms PrimeNumberTheorem.carlson_endpoint_max_ge_optimum
#print axioms PrimeNumberTheorem.carlson_endpoint_max_eq_optimum_iff
#print axioms PrimeNumberTheorem.carlson_saved_endpoint_max_ge_optimum
#print axioms PrimeNumberTheorem.carlson_saved_endpoint_max_eq_optimum_iff
#print axioms PrimeNumberTheorem.di_interpolated_exponent_lt_target
#print axioms PrimeNumberTheorem.ZeroDensityEventualMajorant.isBigO
#print axioms PrimeNumberTheorem.CarlsonDIImprovedDensityCertificate.isBigO
#print axioms PrimeNumberTheorem.powerGrowth_arbitraryLogGap_contradiction
#print axioms PrimeNumberTheorem.singleLayerForcing_density_contradiction
#print axioms PrimeNumberTheorem.singleLayerForcing_DI_contradiction
#print axioms PrimeNumberTheorem.no_nontrivial_zero_re_gt_14_over_17_of_forcing_and_DI
#print axioms PrimeNumberTheorem.CarlsonZeroDensity.exists_regularizedCarlson_fixedRight_count_le_mollifiedMeanSquare_add_explicit_boundary_of_leftWindow_constantRight
#print axioms HardyTheorem.twoScaleSelbergWeight_eq_one
#print axioms HardyTheorem.twoScaleSelbergCoeff_eq_moebius
#print axioms HardyTheorem.twoScaleMollifiedZetaCoeff_eq_zero
#print axioms HardyTheorem.twoScaleSelbergWeight_mem_Icc
#print axioms HardyTheorem.abs_twoScaleSelbergCoeff_le_one
#print axioms HardyTheorem.norm_twoScaleSelbergMollifier_le_natCast
#print axioms HardyTheorem.twoScaleSelbergCoeff_one
#print axioms HardyTheorem.twoScaleSelbergWeight_eq_linear_combination
#print axioms HardyTheorem.twoScaleSelbergCoeff_eq_linear_combination
#print axioms HardyTheorem.twoScaleSelbergMollifier_eq_linear_combination
#print axioms HardyTheorem.analyticAt_twoScaleSelbergMollifier
#print axioms HardyTheorem.tendsto_twoScaleSelbergMollifier_real_atTop
#print axioms HardyTheorem.exists_twoScaleSelbergMollifier_ne_zero
#print axioms HardyTheorem.analyticOrderAt_twoScaleSelbergMollifier_ne_top
#print axioms PrimeNumberTheorem.CarlsonZeroDensity.analyticAt_twoScaleMollifiedZetaError_of_ne_one
#print axioms PrimeNumberTheorem.CarlsonZeroDensity.analyticAt_twoScaleCarlsonZeroDetector_of_ne_one
#print axioms PrimeNumberTheorem.CarlsonZeroDensity.analyticOnNhd_regularizedTwoScaleCarlsonZeroDetector_re_gt
#print axioms PrimeNumberTheorem.CarlsonZeroDensity.twoScaleCarlsonZeroDetector_factorization
#print axioms PrimeNumberTheorem.CarlsonZeroDensity.twoScaleCarlsonZeroDetector_eq_zero_of_zeta_eq_zero
#print axioms PrimeNumberTheorem.CarlsonZeroDensity.analyticOrderNatAt_riemannZeta_le_twoScaleCarlsonZeroDetector
#print axioms PrimeNumberTheorem.CarlsonZeroDensity.regularizedTwoScaleCarlsonZeroDetector_eq_sub_one_sq_mul
#print axioms PrimeNumberTheorem.CarlsonZeroDensity.eight_ninths_le_norm_twoScaleCarlsonZeroDetector_of_norm_error_le
#print axioms PrimeNumberTheorem.CarlsonZeroDensity.one_le_norm_regularizedTwoScaleCarlsonZeroDetector_of_four_le_re
#print axioms PrimeNumberTheorem.CarlsonZeroDensity.norm_twoScaleMollifiedZetaError_le_five_div_thirty_six_of_four_le_re
#print axioms PrimeNumberTheorem.CarlsonZeroDensity.analyticOrderAt_regularizedTwoScaleCarlsonZeroDetector_ne_top
#print axioms PrimeNumberTheorem.CarlsonZeroDensity.exists_norm_regularizedTwoScaleCarlsonZeroDetector_le_fixedJensenSphere
#print axioms PrimeNumberTheorem.CarlsonZeroDensity.exists_regularizedTwoScaleCarlsonFactorDiskZeroMass_le_logPolynomial
#print axioms PrimeNumberTheorem.CarlsonZeroDensity.exists_regularizedTwoScaleCarlsonFactorDiskZeroMass_le_logPolynomial_of_two_le_inner
#print axioms PrimeNumberTheorem.CarlsonZeroDensity.exists_regularizedTwoScaleCarlsonInnerFactorDiskZeroMass_le_logPolynomial
#print axioms PrimeNumberTheorem.CarlsonZeroDensity.exists_regularizedTwoScaleCarlsonZeroDetector_fixedJensenFactor_center_lower
#print axioms PrimeNumberTheorem.CarlsonZeroDensity.mem_regularizedTwoScaleCarlsonFactorDiskZeroSupport_iff_zero
#print axioms PrimeNumberTheorem.CarlsonZeroDensity.exists_regularizedTwoScaleCarlsonZeroDetector_goodFactor_logDeriv_le
#print axioms PrimeNumberTheorem.CarlsonZeroDensity.exists_regularizedTwoScaleCarlson_horizontal_logDeriv_le_factorDisk
