import PrimeNumberTheorem.CarlsonHorizontalContour

open Complex Set

namespace PrimeNumberTheorem
namespace CarlsonZeroDensity

#check exists_regularizedCarlson_fixedRight_count_with_explicit_top
#print axioms exists_regularizedCarlson_fixedRight_count_with_explicit_top

#check sub_mul_zeroDensityCount_le_low_global_add_regularizedCarlsonWeightedZeroSum
#check exists_regularizedCarlson_fixedRight_count_with_explicit_horizontals
#check exists_regularizedCarlson_fixedRight_count_with_explicit_horizontals_of_leftWindow
#check exists_regularizedCarlson_fixedRight_count_le_left_add_explicit_boundary
#check exists_regularizedCarlson_fixedRight_count_le_left_add_explicit_boundary_of_leftWindow
#check exists_integral_log_norm_regularizedCarlsonZeroDetector_le_geometricCoverExplicit
#check exists_regularizedCarlson_fixedRight_count_le_geometricCover_add_explicit_boundary
#check exists_integral_log_norm_regularizedCarlsonZeroDetector_le_sharpGeometricCoverExplicit
#check exists_integral_log_norm_carlsonZeroDetector_le_sharpGeometricCoverExplicit_of_regularizedBoundary
#check exists_regularizedCarlson_fixedRight_count_le_sharpGeometricCover_add_explicit_boundary
#check exists_regularizedCarlson_fixedRight_count_le_sharpGeometricCover_add_explicit_boundary_of_leftWindow
#check carlsonSharpGeometricCoverExplicitBound
#check exists_regularizedCarlson_fixedRight_count_le_cancelledSharpGeometricCover_add_explicit_boundary_of_leftWindow
#check exists_regularizedCarlson_fixedRight_count_le_cancelledSharpGeometricCover_add_explicit_boundary_of_leftWindow_constantRight
#print axioms
  sub_mul_zeroDensityCount_le_low_global_add_regularizedCarlsonWeightedZeroSum
#print axioms
  exists_regularizedCarlson_fixedRight_count_with_explicit_horizontals
#print axioms
  exists_regularizedCarlson_fixedRight_count_with_explicit_horizontals_of_leftWindow
#print axioms
  exists_regularizedCarlson_fixedRight_count_le_left_add_explicit_boundary
#print axioms
  exists_regularizedCarlson_fixedRight_count_le_left_add_explicit_boundary_of_leftWindow
#print axioms
  exists_integral_log_norm_regularizedCarlsonZeroDetector_le_geometricCoverExplicit
#print axioms
  exists_regularizedCarlson_fixedRight_count_le_geometricCover_add_explicit_boundary
#print axioms
  exists_integral_log_norm_regularizedCarlsonZeroDetector_le_sharpGeometricCoverExplicit
#print axioms
  exists_integral_log_norm_carlsonZeroDetector_le_sharpGeometricCoverExplicit_of_regularizedBoundary
#print axioms
  exists_regularizedCarlson_fixedRight_count_le_sharpGeometricCover_add_explicit_boundary
#print axioms
  exists_regularizedCarlson_fixedRight_count_le_sharpGeometricCover_add_explicit_boundary_of_leftWindow
#print axioms
  exists_regularizedCarlson_fixedRight_count_le_cancelledSharpGeometricCover_add_explicit_boundary_of_leftWindow
#print axioms
  exists_regularizedCarlson_fixedRight_count_le_cancelledSharpGeometricCover_add_explicit_boundary_of_leftWindow_constantRight

end CarlsonZeroDensity
end PrimeNumberTheorem
