import HardyTheorem.ConreyExplicitRightVertical

open Complex

namespace HardyTheorem

#check conreyExplicitDegreeOneHeightMain
#check conreyExplicitDegreeOneHeightMain_eq
#check conreyExplicitDegreeOneHeightMain_re
#check conreyExplicitDegreeOneHeightMain_im
#check one_third_le_conreyExplicitDegreeOneHeightMain_re
#check conreyExplicitDegreeOneHeightMain_re_le_one
#check one_sub_conreyExplicitDegreeOneHeightMain_re_eq
#check norm_conreyExplicitDegreeOneHeightMain_eq_re
#check conreyExplicitRightVerticalProduct
#check norm_conreyExplicitRightVerticalProduct_sub_heightMain_le
#check conreyExplicitRightVerticalProduct_ne_zero
#check abs_log_sub_log_le_six_mul_abs_sub
#check abs_log_le_three_mul_one_sub
#check integral_log_conrey_height_compensation_one_exp_le
#check abs_log_norm_conreyExplicitRightVerticalProduct_le

#print axioms conreyExplicitDegreeOneHeightMain_eq
#print axioms one_third_le_conreyExplicitDegreeOneHeightMain_re
#print axioms conreyExplicitDegreeOneHeightMain_re_le_one
#print axioms one_sub_conreyExplicitDegreeOneHeightMain_re_eq
#print axioms norm_conreyExplicitDegreeOneHeightMain_eq_re
#print axioms norm_conreyExplicitRightVerticalProduct_sub_heightMain_le
#print axioms conreyExplicitRightVerticalProduct_ne_zero
#print axioms abs_log_sub_log_le_six_mul_abs_sub
#print axioms abs_log_le_three_mul_one_sub
#print axioms integral_log_conrey_height_compensation_one_exp_le
#print axioms abs_log_norm_conreyExplicitRightVerticalProduct_le

end HardyTheorem
