import HardyTheorem.ConreyRightArgument

open HardyTheorem

#check norm_conreyExplicitRightVerticalProduct_sub_const_low_le_one_twentieth
#check two_fifths_le_conreyExplicitRightVerticalProduct_low_re
#check three_tenths_le_conreyExplicitRightVerticalProduct_high_re
#check three_tenths_le_conreyExplicitRightVerticalProduct_global_re
#check conreyExplicitRightVerticalFunction
#check analyticAt_conreyExplicitRightVerticalFunction
#check intervalIntegral_re_logDeriv_conreyExplicitRightVertical_eq_arg_sub
#check abs_intervalIntegral_re_logDeriv_conreyExplicitRightVertical_le_pi

#print axioms norm_conreyExplicitRightVerticalProduct_sub_const_low_le_one_twentieth
#print axioms two_fifths_le_conreyExplicitRightVerticalProduct_low_re
#print axioms three_tenths_le_conreyExplicitRightVerticalProduct_high_re
#print axioms three_tenths_le_conreyExplicitRightVerticalProduct_global_re
#print axioms analyticAt_conreyExplicitRightVerticalFunction
#print axioms intervalIntegral_re_logDeriv_conreyExplicitRightVertical_eq_arg_sub
#print axioms abs_intervalIntegral_re_logDeriv_conreyExplicitRightVertical_le_pi
