import HardyTheorem.ConreyHorizontalJensenGrowth

namespace HardyTheorem

#check logDeriv_conreyH_eq_of_re_pos_of_ne_one
#check logDeriv_conreyH_eq
#check seven_fourths_le_im_of_mem_conreyHorizontalJensenOuterClosedBall
#check norm_conreyMollifierCoefficient_le_one
#check norm_conreyExplicitMollifier_le_natCast_of_re_nonneg
#check conreyHorizontalJensenHeightBase
#check one_le_conreyHorizontalJensenHeightBase
#check abs_im_add_three_le_conreyHorizontalJensenHeightBase
#check exists_norm_riemannZeta_add_deriv_le_conreyHorizontalJensenOuterClosedBall

#print axioms logDeriv_conreyH_eq_of_re_pos_of_ne_one
#print axioms logDeriv_conreyH_eq
#print axioms seven_fourths_le_im_of_mem_conreyHorizontalJensenOuterClosedBall
#print axioms norm_conreyMollifierCoefficient_le_one
#print axioms norm_conreyExplicitMollifier_le_natCast_of_re_nonneg
#print axioms one_le_conreyHorizontalJensenHeightBase
#print axioms abs_im_add_three_le_conreyHorizontalJensenHeightBase
#print axioms exists_norm_riemannZeta_add_deriv_le_conreyHorizontalJensenOuterClosedBall

end HardyTheorem
