import HardyTheorem.ConreyHorizontalJensenCenter

namespace HardyTheorem

#check one_sixth_le_norm_conreyExplicitRightVerticalProduct

#print axioms one_sixth_le_norm_conreyExplicitRightVerticalProduct

end HardyTheorem
