import HardyTheorem.ConreyHorizontalJensenGeometry

namespace HardyTheorem

#check conreyHorizontalRightEdge
#check conreyHorizontalLeftEdge
#check conreyHorizontalJensenCenter
#check conreyHorizontalJensenInnerRadius
#check conreyHorizontalJensenOuterRadius
#check conreyHorizontalJensenRectangle
#check conreyHorizontalJensenRectangle_subset_innerClosedBall
#check conreyHorizontalJensenInnerRadius_pos
#check conreyHorizontalJensenInnerRadius_lt_outerRadius
#check quarter_le_re_of_mem_conreyHorizontalJensenOuterClosedBall
#check ne_one_of_mem_conreyHorizontalJensenOuterClosedBall
#check analyticOnNhd_conreyExplicitMollifiedV1_horizontalJensenOuterClosedBall

#print axioms conreyHorizontalJensenRectangle_subset_innerClosedBall
#print axioms conreyHorizontalJensenInnerRadius_pos
#print axioms conreyHorizontalJensenInnerRadius_lt_outerRadius
#print axioms quarter_le_re_of_mem_conreyHorizontalJensenOuterClosedBall
#print axioms ne_one_of_mem_conreyHorizontalJensenOuterClosedBall
#print axioms analyticOnNhd_conreyExplicitMollifiedV1_horizontalJensenOuterClosedBall

end HardyTheorem

