import HardyTheorem.ConreyExplicitRightVerticalLow

namespace HardyTheorem

#check log_le_div_hundred_of_ge_forty_thousand
#check norm_logDeriv_conreyH_movingRight_low_le
#check norm_conreyExplicitV1_sub_const_low_le
#check conreyExplicitRightVerticalProduct_low_norm_bounds
#check abs_log_norm_conreyExplicitRightVerticalProduct_low_le_two
#check integral_abs_log_norm_conreyExplicitRightVerticalProduct_low_le
#check four_mul_log_le_exp_div_of_ge_forty_thousand
#check intervalIntegrable_abs_log_norm_conreyExplicitRightVerticalProduct_global
#check integral_abs_log_norm_conreyExplicitRightVerticalProduct_global_le

#print axioms log_le_div_hundred_of_ge_forty_thousand
#print axioms norm_logDeriv_conreyH_movingRight_low_le
#print axioms norm_conreyExplicitV1_sub_const_low_le
#print axioms conreyExplicitRightVerticalProduct_low_norm_bounds
#print axioms abs_log_norm_conreyExplicitRightVerticalProduct_low_le_two
#print axioms integral_abs_log_norm_conreyExplicitRightVerticalProduct_low_le
#print axioms four_mul_log_le_exp_div_of_ge_forty_thousand
#print axioms intervalIntegrable_abs_log_norm_conreyExplicitRightVerticalProduct_global
#print axioms integral_abs_log_norm_conreyExplicitRightVerticalProduct_global_le

end HardyTheorem
