import RiemannExplorer.DeBruijnNewman

#print axioms RiemannExplorer.DeBruijnNewman.phiTerm_zero
#print axioms RiemannExplorer.DeBruijnNewman.abs_phiTerm_le
#print axioms RiemannExplorer.DeBruijnNewman.summable_phiTerm_all
#print axioms RiemannExplorer.DeBruijnNewman.summable_phiTerm
#print axioms RiemannExplorer.DeBruijnNewman.norm_cos_le_exp_abs_im
#print axioms RiemannExplorer.DeBruijnNewman.norm_cos_mul_ofReal_le_exp
#print axioms RiemannExplorer.DeBruijnNewman.continuous_phi
#print axioms RiemannExplorer.DeBruijnNewman.abs_phi_le
#print axioms RiemannExplorer.DeBruijnNewman.heat_decay_eventually_le
#print axioms RiemannExplorer.DeBruijnNewman.heat_integrand_integrable
#print axioms RiemannExplorer.DeBruijnNewman.heat_integrand_integrable_target_proved
#print axioms RiemannExplorer.DeBruijnNewman.norm_sin_le_exp_abs_im
#print axioms RiemannExplorer.DeBruijnNewman.norm_sin_mul_ofReal_le_exp
#print axioms RiemannExplorer.DeBruijnNewman.heat_integrand_hasDerivAt
#print axioms RiemannExplorer.DeBruijnNewman.differentiable_deBruijnNewmanH
#print axioms RiemannExplorer.DeBruijnNewman.deBruijnNewmanH_even
#print axioms RiemannExplorer.DeBruijnNewman.h_even_entire
#print axioms RiemannExplorer.DeBruijnNewman.h_even_entire_target_proved
#print axioms RiemannExplorer.DeBruijnNewman.hasDerivAt_thetaS
#print axioms RiemannExplorer.DeBruijnNewman.hasDerivAt_thetaT
#print axioms RiemannExplorer.DeBruijnNewman.hasDerivAt_thetaTD
#print axioms RiemannExplorer.DeBruijnNewman.phiKernelG_eq
#print axioms RiemannExplorer.DeBruijnNewman.phi_eq_exp_mul_phiKernelG
