import MathlibAux.DriftingExponentialPolynomial

#print axioms MathlibAux.norm_driftingExponentialPolynomial_sub_exponentialPolynomial_le
#print axioms MathlibAux.exponentialPolynomial_eq_mergedFrequencyPolynomial
#print axioms MathlibAux.integral_normSq_driftingExponentialPolynomial_ge
#print axioms MathlibAux.integral_normSq_driftingExponentialPolynomial_ge_merged
#print axioms MathlibAux.integral_normSq_driftingExponentialPolynomial_pos_merged
#print axioms MathlibAux.integral_normSq_driftingExponentialPolynomial_pos
