import MathlibAux.DyadicPrefixDecomposition

open Complex
open scoped BigOperators

#check MathlibAux.dyadicPrefixBlock
#check MathlibAux.dyadicPrefixIds
#check MathlibAux.card_dyadicPrefixIds_le
#check MathlibAux.sum_dyadicPrefixBlocks
#check MathlibAux.normSq_sum_Ico_le_dyadicPrefixBlocks
#check MathlibAux.dyadicPrefixTree
#check MathlibAux.dyadicPrefixIds_subset_tree
#check MathlibAux.normSq_sum_Ico_le_dyadicPrefixTree
#check MathlibAux.dyadicPrefixTree_subset_product_range

#print axioms MathlibAux.sum_dyadicPrefixBlocks
#print axioms MathlibAux.normSq_sum_Ico_le_dyadicPrefixBlocks
#print axioms MathlibAux.dyadicPrefixIds_subset_tree
#print axioms MathlibAux.normSq_sum_Ico_le_dyadicPrefixTree
#print axioms MathlibAux.dyadicPrefixTree_subset_product_range
