import PrimeNumberTheorem.ExceptionalZeroAmplificationGateInputSupplier

#print axioms PrimeNumberTheorem.ExceptionalZeroAmplificationGate.amplificationGateInputs_hlower
#print axioms PrimeNumberTheorem.ExceptionalZeroAmplificationGate.amplificationGateInputs_hgap
#print axioms PrimeNumberTheorem.ExceptionalZeroAmplificationGate.amplificationGateInputs_of_assembly
#print axioms PrimeNumberTheorem.ExceptionalZeroAmplificationGate.no_nontrivial_zero_re_gt_two_thirds_of_assembly
#print axioms PrimeNumberTheorem.ExceptionalZeroAmplificationGate.zeroDensityZerosFinset_card_le_zeroDensityCount
