import PrimeNumberTheorem.ExceptionalZeroDetectOrCount

#print axioms PrimeNumberTheorem.ExceptionalZeroDetectOrCount.insert_new_nontrivialZero_strict_growth
#print axioms PrimeNumberTheorem.ExceptionalZeroDetectOrCount.union_disjoint_nontrivialZeroPacket_strict_growth
#print axioms PrimeNumberTheorem.ExceptionalZeroDetectOrCount.exists_strictly_larger_recordedZeroSet_of_new_nontrivialZero
#print axioms PrimeNumberTheorem.ExceptionalZeroDetectOrCount.exists_strictly_larger_recordedZeroSet_of_detect_or_count
