import PrimeNumberTheorem.ExceptionalZeroDyadicCapacityReindex

open PrimeNumberTheorem.VKEdgePiOverTwo

#print axioms dynamicComplementZeroPacket_eq_zeroOrdinateUnitBucket_sdiff_of_dyadic
#print axioms dynamicComplementDyadicSquareReciprocalCapacity_eq_actual
#print axioms dynamicComplementDyadicLinearReciprocalCapacity_eq_actual
#print axioms exists_dynamicComplementDyadicOccupancy_le_log
#print axioms low_actualZetaDyadicZero_mem_rightHigherExclusionSet
#print axioms exists_rightHigherDyadicSquareCapacity_le_log_linear
#print axioms rightHigherActualZetaDyadicLinearCapacity_le_zeroDensityCount
