import PrimeNumberTheorem.ExceptionalZeroTargetDyadicGramSchur

open PrimeNumberTheorem.VKEdgePiOverTwo

#print axioms dynamicComplementZeroPacket_card_le_dyadicOccupancy
#print axioms finiteZeroClusterCoefficientAt_norm_sq_eq
#print axioms dynamicComplementDyadicGaussianMajorantEnergy_le_targetSquareCapacity
#print axioms dynamicComplementDyadicCenteredFrozenGaussianSecondMoment_le_targetSquareCapacity
#print axioms rightHigherDyadicCenteredFrozenGaussianSecondMoment_le_targetSquareCapacity
#print axioms rightHigherDyadic_fartherRight_or_all_re_le
#print axioms rightHigherDyadicTargetSquareCapacity_le_unweighted_of_re_le
#print axioms rightHigherDyadic_fartherRight_or_gram_le_unweighted
