import PrimeNumberTheorem.ExceptionalZeroDyadicSquareMultiplicity
open PrimeNumberTheorem
#print axioms mem_actualZetaDyadicZeroBlock_iff_exists_mem_zeroOrdinateUnitBucket
#print axioms actualZetaDyadicZeroBlock_eq_biUnion_zeroOrdinateUnitBucket
#print axioms squareMultiplicityCapacity_le_max_mul_linearMultiplicityCapacity
#print axioms squareMultiplicityCapacity_sdiff_le
#print axioms ExplicitFormulaAux.exists_analyticOrderNatAt_riemannZeta_le_log_im_of_nontrivialZero
#print axioms actualZetaDyadicSquareReciprocalCapacityExcluding_le_linear
#print axioms exists_actualZetaDyadicSquareReciprocalCapacityExcluding_le_log_linear
