import PrimeNumberTheorem.ExceptionalZeroDetectOrCountSharp

#print axioms PrimeNumberTheorem.ExceptionalZeroDetectOrCount.exists_strictly_larger_recordedZeroSet_of_fullMovingGaussianSecondMoment_pos
#print axioms PrimeNumberTheorem.ExceptionalZeroDetectOrCount.exists_strictly_larger_recordedZeroSet_of_remainder_energy_gt_three_errors
