import PrimeNumberTheorem.ExplicitFormulaNormalizedWindowRemainder

#print axioms PrimeNumberTheorem.ExplicitFormulaResidues.tendsto_normalizedWindowRemainderEnvelope_proportional_atTop_nhds_zero
#print axioms PrimeNumberTheorem.ExplicitFormulaResidues.eventually_exists_uniform_goodHeight_normalized_proportional_window_remainder_lt
