import PrimeNumberTheorem.ExplicitFormulaSpatialVariation

#print axioms PrimeNumberTheorem.ExplicitFormulaAux.norm_zeroTerm_sub_zeroTerm_le_abs_sub
#print axioms PrimeNumberTheorem.ExplicitFormulaAux.norm_finiteNontrivialZeroSumWithMultiplicity_sub_le
#print axioms PrimeNumberTheorem.ExplicitFormulaAux.norm_main_sub_finiteZeroSum_sub_le
#print axioms PrimeNumberTheorem.ExplicitFormulaAux.exists_norm_main_sub_finiteZeroSum_sub_le_mul_log
