import PrimeNumberTheorem.ExplicitFormulaNormalizedPowerHeightWindowRemainder

#print axioms PrimeNumberTheorem.ExplicitFormulaResidues.normalizedPowerHeightWindowRemainderEnvelope
#print axioms PrimeNumberTheorem.ExplicitFormulaResidues.tendsto_normalizedPowerHeightWindowRemainderEnvelope_proportional_atTop_nhds_zero
#print axioms PrimeNumberTheorem.ExplicitFormulaResidues.eventually_exists_uniform_goodHeight_normalized_powerHeight_proportional_window_remainder_lt
