import PrimeNumberTheorem.ExplicitFormulaNormalizedWindowRemainder

#print axioms PrimeNumberTheorem.ExplicitFormulaResidues.tendsto_exp_mul_one_add_sq_atTop_nhds_zero_of_neg
#print axioms PrimeNumberTheorem.ExplicitFormulaResidues.exists_uniform_goodHeight_exp_half_norm_real_explicitFormulaApproxWithMultiplicity_sub_chebyshevPsi0_le
#print axioms PrimeNumberTheorem.ExplicitFormulaResidues.tendsto_normalizedWindowRemainderEnvelope_atTop_nhds_zero
#print axioms PrimeNumberTheorem.ExplicitFormulaResidues.eventually_exists_uniform_goodHeight_normalized_window_remainder_lt
