import HardyTheorem.HardyPhaseDyadicSecondMoment

#check HardyTheorem.hardyPhaseLinearizedDyadicSecondMomentConstant
#check HardyTheorem.integral_normSq_hardyPhaseLinearizedSum_le_dyadic_mul
#check HardyTheorem.exists_integral_normSq_hardyPhaseLinearizedSum_le_mul
#print axioms HardyTheorem.integral_normSq_hardyPhaseLinearizedSum_le_dyadic_mul
#print axioms HardyTheorem.exists_integral_normSq_hardyPhaseLinearizedSum_le_mul
