import HardyTheorem.HardyLittlewoodLiteratureCount

#print axioms HardyTheorem.criticalLineOddZeroCount_le_positiveCriticalLineOddZeroCount_add_one
#print axioms HardyTheorem.positiveCriticalLineOddZeroCount_le_positiveCriticalLineZeroMultiplicityCount
#print axioms HardyTheorem.hardy_littlewood_positive_odd_lower_bound_target_proved
#print axioms HardyTheorem.hardy_littlewood_positive_multiplicity_lower_bound_target_proved
