import HardyTheorem.HardyIntegralBasics
import HardyTheorem.OscillatoryIntegral
import HardyTheorem.FirstZetaApproximation
import HardyTheorem.VerticalGammaAsymptotic
import HardyTheorem.HardyIntegralUpperBound
import HardyTheorem.HardyIntegralContradiction
import HardyTheorem.CriticalLineMultiplicity
import HardyTheorem.AnalyticSignChange
import HardyTheorem.ShortIntervalMeanValue
import HardyTheorem.HardyModelApproximation
import HardyTheorem.CriticalLineShortDirichlet
import HardyTheorem.HardyShortSignedMeanSquare
import HardyTheorem.HardyPhaseCorrelation
import MathlibAux.DirichletPolynomialMeanSquare

#print axioms HardyTheorem.abs_hardyZ_eq_norm_riemannZeta
#print axioms HardyTheorem.eventually_abs_integral_hardyZ_eq_integral_norm_zeta_of_bounded_zeros
#print axioms HardyTheorem.OscillatoryIntegral.norm_integral_cexp_phase_le_of_monotone_deriv
#print axioms HardyTheorem.OscillatoryIntegral.norm_integral_cexp_phase_le_of_second_deriv
#print axioms HardyTheorem.OscillatoryIntegral.deriv_hardyPhase
#print axioms HardyTheorem.OscillatoryIntegral.iteratedDeriv_two_hardyPhase
#print axioms HardyTheorem.OscillatoryIntegral.norm_integral_cexp_hardyPhase_le
#print axioms HardyTheorem.OscillatoryIntegral.norm_integral_rpow_smul_cexp_phase_le_of_monotone_deriv
#print axioms HardyTheorem.OscillatoryIntegral.norm_integral_rpow_smul_cexp_fourierMellinPhase_le
#print axioms HardyTheorem.intervalIntegral_centeredFloorError_cpow_eq_bernoulliTwo
#print axioms HardyTheorem.exists_norm_intervalIntegral_periodizedBernoulli_two_mellin_le
#print axioms HardyTheorem.exists_norm_intervalIntegral_periodizedBernoulli_two_cpow_le
#print axioms HardyTheorem.exists_norm_integral_Ioi_periodizedBernoulli_two_cpow_le
#print axioms HardyTheorem.integral_Ioi_centeredFloorError_cpow_eq_bernoulliTwo
#print axioms HardyTheorem.exists_norm_mul_integral_Ioi_floorError_cpow_le
#print axioms HardyTheorem.exists_riemannZeta_first_approximation
#print axioms HardyTheorem.criticalLineZetaFirstApprox
#print axioms HardyTheorem.exists_norm_riemannZeta_critical_line_le_sqrt
#print axioms HardyTheorem.exists_integral_norm_riemannZeta_critical_line_ge_mul
#print axioms HardyTheorem.exists_abs_integral_hardyZ_le_rpow_three_quarters
#print axioms HardyTheorem.hardyZ_zero_set_not_isBounded
#print axioms HardyTheorem.hardy_zeros_unbounded_target_proved
#print axioms HardyTheorem.hardy_theorem_target_proved
#print axioms HardyTheorem.odd_analyticOrderNatAt_of_local_sign_change
#print axioms HardyTheorem.card_le_criticalLineOddZeroCount_of_pairwiseDisjoint_hits
#print axioms HardyTheorem.exists_hardyShortAbsIntegral_le_mul_sqrt
#print axioms HardyTheorem.mul_integral_abs_hardyZ_interior_le_integral_hardyShortAbsIntegral
#print axioms HardyTheorem.exists_integral_hardyShortAbsIntegral_ge_mul
#print axioms HardyTheorem.exists_norm_rotated_riemannZeta_sub_thetaModel_dirichletPolynomial_le_inv_sqrt
#print axioms HardyTheorem.integral_criticalLineDirichletPolynomial_eq_shortPolynomial
#print axioms HardyTheorem.norm_criticalLineShortDirichletCoeff_le_two_div
#print axioms HardyTheorem.norm_criticalLineShortDirichletCoeff_le_abs_delta
#print axioms HardyTheorem.integral_normSq_criticalLineShortDirichletPolynomial_le
#print axioms MathlibAux.integral_normSq_intervalIntegral_exponentialPolynomial_le
#print axioms HardyTheorem.exists_abs_hardyShortIntegral_sub_hardyFirstModelShortIntegral_le
#print axioms HardyTheorem.OscillatoryIntegral.deriv_hardyPhaseCorrelation
#print axioms HardyTheorem.OscillatoryIntegral.iteratedDeriv_two_hardyPhaseCorrelation
#print axioms HardyTheorem.OscillatoryIntegral.deriv_hardyPhaseCorrelation_same_shift
#print axioms HardyTheorem.OscillatoryIntegral.abs_log_sub_log_le_div
#print axioms HardyTheorem.OscillatoryIntegral.deriv_hardyPhaseCorrelation_eq_log_gap_add
#print axioms HardyTheorem.OscillatoryIntegral.abs_deriv_hardyPhaseCorrelation_sub_log_gap_le
#print axioms MathlibAux.norm_integral_cexp_linear_le
#print axioms MathlibAux.integral_normSq_exponentialPolynomial_le
#print axioms HardyTheorem.norm_integral_inv_nat_cpow_criticalLine_le
#print axioms HardyTheorem.norm_integral_criticalLineDirichletTail_le
#print axioms HardyTheorem.norm_integral_criticalLineDirichletTail_cutoff_le
#print axioms HardyTheorem.norm_integral_criticalLineDirichletTail_cutoff_isLittleO
#print axioms HardyTheorem.exists_norm_integral_Ioi_verticalStirlingBernoulliKernel_le_inv
#print axioms HardyTheorem.exists_norm_integral_Ioi_zero_verticalStirlingBernoulliKernel_le_inv
#print axioms HardyTheorem.digamma_eq_stirling_with_periodizedBernoulli
#print axioms ZeroFreeRegion.riemannZeta_eq_pole_add_floorError_integral_of_pos_re
#print axioms ZeroFreeRegion.riemannZeta_eq_dirichletPolynomial_add_pole_add_floorErrorTail
