import HardyTheorem.HardyIntegralBasics
import HardyTheorem.OscillatoryIntegral
import HardyTheorem.FirstZetaApproximation
import HardyTheorem.VerticalGammaAsymptotic
import HardyTheorem.HardyIntegralUpperBound
import HardyTheorem.HardyIntegralContradiction

#print axioms HardyTheorem.abs_hardyZ_eq_norm_riemannZeta
#print axioms HardyTheorem.eventually_abs_integral_hardyZ_eq_integral_norm_zeta_of_bounded_zeros
#print axioms HardyTheorem.OscillatoryIntegral.norm_integral_cexp_phase_le_of_monotone_deriv
#print axioms HardyTheorem.OscillatoryIntegral.norm_integral_cexp_phase_le_of_second_deriv
#print axioms HardyTheorem.OscillatoryIntegral.deriv_hardyPhase
#print axioms HardyTheorem.OscillatoryIntegral.iteratedDeriv_two_hardyPhase
#print axioms HardyTheorem.OscillatoryIntegral.norm_integral_cexp_hardyPhase_le
#print axioms HardyTheorem.OscillatoryIntegral.norm_integral_rpow_smul_cexp_phase_le_of_monotone_deriv
#print axioms HardyTheorem.OscillatoryIntegral.norm_integral_rpow_smul_cexp_fourierMellinPhase_le
#print axioms HardyTheorem.intervalIntegral_centeredFloorError_cpow_eq_bernoulliTwo
#print axioms HardyTheorem.exists_norm_intervalIntegral_periodizedBernoulli_two_mellin_le
#print axioms HardyTheorem.exists_norm_intervalIntegral_periodizedBernoulli_two_cpow_le
#print axioms HardyTheorem.exists_norm_integral_Ioi_periodizedBernoulli_two_cpow_le
#print axioms HardyTheorem.integral_Ioi_centeredFloorError_cpow_eq_bernoulliTwo
#print axioms HardyTheorem.exists_norm_mul_integral_Ioi_floorError_cpow_le
#print axioms HardyTheorem.exists_riemannZeta_first_approximation
#print axioms HardyTheorem.criticalLineZetaFirstApprox
#print axioms HardyTheorem.exists_integral_norm_riemannZeta_critical_line_ge_mul
#print axioms HardyTheorem.exists_abs_integral_hardyZ_le_rpow_three_quarters
#print axioms HardyTheorem.hardyZ_zero_set_not_isBounded
#print axioms HardyTheorem.hardy_zeros_unbounded_target_proved
#print axioms HardyTheorem.hardy_theorem_target_proved
#print axioms HardyTheorem.norm_integral_inv_nat_cpow_criticalLine_le
#print axioms HardyTheorem.norm_integral_criticalLineDirichletTail_le
#print axioms HardyTheorem.norm_integral_criticalLineDirichletTail_cutoff_le
#print axioms HardyTheorem.norm_integral_criticalLineDirichletTail_cutoff_isLittleO
#print axioms HardyTheorem.exists_norm_integral_Ioi_verticalStirlingBernoulliKernel_le_inv
#print axioms HardyTheorem.exists_norm_integral_Ioi_zero_verticalStirlingBernoulliKernel_le_inv
#print axioms HardyTheorem.digamma_eq_stirling_with_periodizedBernoulli
#print axioms ZeroFreeRegion.riemannZeta_eq_pole_add_floorError_integral_of_pos_re
#print axioms ZeroFreeRegion.riemannZeta_eq_dirichletPolynomial_add_pole_add_floorErrorTail
