import HardyTheorem.HardyPhaseHilbertShiftIntegral

#check HardyTheorem.hardyPhaseCorrelationOffDiagonalShiftKernel
#check HardyTheorem.integrable_hardyPhaseCorrelationOffDiagonalShiftKernel
#check HardyTheorem.hardyPhaseCorrelationOffDiagonal_shift_fubini
#check HardyTheorem.hardyPhaseCorrelationOffDiagonal_shift_fubini_dyadic
#check HardyTheorem.norm_integral_integral_integral_hardyPhaseCorrelationOffDiagonal_dyadic_le
#check HardyTheorem.norm_integral_integral_integral_hardyPhaseCorrelationOffDiagonal_le_of_upper

#print axioms HardyTheorem.integrable_hardyPhaseCorrelationOffDiagonalShiftKernel
#print axioms HardyTheorem.hardyPhaseCorrelationOffDiagonal_shift_fubini
#print axioms HardyTheorem.hardyPhaseCorrelationOffDiagonal_shift_fubini_dyadic
#print axioms HardyTheorem.norm_integral_integral_integral_hardyPhaseCorrelationOffDiagonal_dyadic_le
#print axioms HardyTheorem.norm_integral_integral_integral_hardyPhaseCorrelationOffDiagonal_le_of_upper
