import HardyTheorem.HardyLittlewoodLiteratureCount

namespace HardyTheorem

#check positiveCriticalLineOddZerosFinset
#check positiveCriticalLineOddZeroCount
#check mem_positiveCriticalLineOddZerosFinset
#check criticalLineOddZeroCount_le_positiveCriticalLineOddZeroCount_add_one
#check positiveCriticalLineOddZeroCount_le_positiveCriticalLineZeroMultiplicityCount
#check hardy_littlewood_positive_odd_lower_bound_target
#check hardy_littlewood_positive_odd_lower_bound_target_proved
#check hardy_littlewood_positive_multiplicity_lower_bound_target
#check hardy_littlewood_positive_multiplicity_lower_bound_target_proved

example : hardy_littlewood_positive_odd_lower_bound_target :=
  hardy_littlewood_positive_odd_lower_bound_target_proved

example : hardy_littlewood_positive_multiplicity_lower_bound_target :=
  hardy_littlewood_positive_multiplicity_lower_bound_target_proved

end HardyTheorem
