import HardyTheorem.HardyPhaseLinearization

#check HardyTheorem.OscillatoryIntegral.hardyPhaseLinearizedShortIntegral
#check HardyTheorem.OscillatoryIntegral.abs_hardyPhase_linearization_error_le
#check HardyTheorem.OscillatoryIntegral.norm_hardyPhaseShortIntegral_sub_linearized_le
#check HardyTheorem.OscillatoryIntegral.norm_hardyPhaseLinearizedShortIntegral_le_length
#check HardyTheorem.OscillatoryIntegral.norm_hardyPhaseLinearizedShortIntegral_le_min
#check HardyTheorem.OscillatoryIntegral.norm_hardyPhaseShortIntegral_le_min_add_linearization_error
#check HardyTheorem.OscillatoryIntegral.norm_hardyPhaseShortIntegral_le_length_add_linearization_error

#print axioms HardyTheorem.OscillatoryIntegral.abs_hardyPhase_linearization_error_le
#print axioms HardyTheorem.OscillatoryIntegral.norm_hardyPhaseShortIntegral_sub_linearized_le
#print axioms HardyTheorem.OscillatoryIntegral.norm_hardyPhaseShortIntegral_le_min_add_linearization_error
#print axioms HardyTheorem.OscillatoryIntegral.norm_hardyPhaseShortIntegral_le_length_add_linearization_error
