import PrimeNumberTheorem.MWKFCubicAFECompletedReassembly

#print axioms PrimeNumberTheorem.MWKFCubic.cubicAFEDyadicCompletionCorrection_eq_finiteSum
#print axioms PrimeNumberTheorem.MWKFCubic.integrable_cubicAFEDyadicCompletionCorrection
#print axioms PrimeNumberTheorem.MWKFCubic.integral_cubicAFEDyadicCompletionCorrection_eq_zeroModes
#print axioms PrimeNumberTheorem.MWKFCubic.hasSum_cubicAFECompletedZeroModeBox
#print axioms PrimeNumberTheorem.MWKFCubic.hasSum_cubicAFECompletedNonzeroModeBox
#print axioms PrimeNumberTheorem.MWKFCubic.cubicAFECompletedBoundary_zero_add_nonzero
#print axioms PrimeNumberTheorem.MWKFCubic.tsum_cubicAFECompletedModes_eq_original
