import PrimeNumberTheorem.MWKFCubicAFEDyadicTimeIntegral

#print axioms PrimeNumberTheorem.MWKFCubic.mem_cubicAFEProgressionDyadicIndices
#print axioms PrimeNumberTheorem.MWKFCubic.cubicAFEProgressionDyadicCutoff_zero_of_not_mem_indices
#print axioms PrimeNumberTheorem.MWKFCubic.integrable_cubicAFECombinedSummandFinite
#print axioms PrimeNumberTheorem.MWKFCubic.tsum_cubicAFEDyadicProgression_eq_finsetSum
#print axioms PrimeNumberTheorem.MWKFCubic.integral_tsum_cubicAFEDyadicProgression
#print axioms PrimeNumberTheorem.MWKFCubic.integrable_cubicAFEDyadicPoissonTerm
#print axioms PrimeNumberTheorem.MWKFCubic.integral_cubicAFEDyadicPoissonTerm_eq
#print axioms PrimeNumberTheorem.MWKFCubic.cubicAFEProgressionIntegral_eq_dyadicPoisson
#print axioms PrimeNumberTheorem.MWKFCubic.summable_integral_cubicAFEDyadicPoissonTerm
