import PrimeNumberTheorem.MWKFCubicAFEDyadicBoundary

#print axioms PrimeNumberTheorem.MWKFCubic.cubicAFEDyadicLowerWeight_nonneg
#print axioms PrimeNumberTheorem.MWKFCubic.cubicAFEDyadicLowerWeight_le_one
#print axioms PrimeNumberTheorem.MWKFCubic.cubicAFEDyadicLowerWeight_zero
#print axioms PrimeNumberTheorem.MWKFCubic.cubicAFEDyadicLowerWeight_one
#print axioms PrimeNumberTheorem.MWKFCubic.contDiff_cubicAFEDyadicLowerWeight
#print axioms PrimeNumberTheorem.MWKFCubic.hasSum_cubicAFEDyadicWindow_allReal
#print axioms PrimeNumberTheorem.MWKFCubic.hasSum_cubicAFEProgressionDyadicCutoff_allReal
#print axioms PrimeNumberTheorem.MWKFCubic.hasSum_cubicAFEProgressionDyadicKernel_allReal
#print axioms PrimeNumberTheorem.MWKFCubic.hasSum_norm_cubicAFEProgressionDyadicKernel_allReal
