import PrimeNumberTheorem.MWKFCubicAFECompletedCutoff

#print axioms PrimeNumberTheorem.MWKFCubic.cubicAFEDyadicWindow_shift
#print axioms PrimeNumberTheorem.MWKFCubic.cubicAFEDyadicWindow_zero_of_lower_scale
#print axioms PrimeNumberTheorem.MWKFCubic.cubicAFEProgressionCompletedCutoff
#print axioms PrimeNumberTheorem.MWKFCubic.tsupport_cubicAFEProgressionCompletedCutoff_subset
#print axioms PrimeNumberTheorem.MWKFCubic.cubicAFEProgressionCompletedCutoff_shift
#print axioms PrimeNumberTheorem.MWKFCubic.hasSum_cubicAFEProgressionCompletedCutoff
#print axioms PrimeNumberTheorem.MWKFCubic.cubicAFEProgressionCompletedCutoff_zero_on_progression
