import PrimeNumberTheorem.MWKFCubicAFECompletedMoment

#print axioms PrimeNumberTheorem.MWKFCubic.cubicAFECompletedBoundaryPhysicalKernel_eq_boundary_add_correction
#print axioms PrimeNumberTheorem.MWKFCubic.integrable_cubicAFECompletedBoundaryPhysicalKernel
#print axioms PrimeNumberTheorem.MWKFCubic.hasSum_cubicAFECompletedZeroModeBox_physical
#print axioms PrimeNumberTheorem.MWKFCubic.summable_shift_cubicAFECompletedModes
#print axioms PrimeNumberTheorem.MWKFCubic.cubicAFECompletedMomentFinite_eq_frequency
#print axioms PrimeNumberTheorem.MWKFCubic.cubicAFEMollifiedMomentFinite_eq_diagonal_add_completed
#print axioms PrimeNumberTheorem.MWKFCubic.tendsto_cubicAFEDiagonal_add_completed
