import PrimeNumberTheorem.MWKFCubicAFEInfiniteCompletedMoment

#print axioms PrimeNumberTheorem.MWKFCubic.cubicAFECompletedNonzeroModeMomentVertical_eq
#print axioms PrimeNumberTheorem.MWKFCubic.tendsto_cubicAFECompletedNonzeroModeMomentFinite_height
#print axioms PrimeNumberTheorem.MWKFCubic.cubicMollifiedSecondMoment_eq_completed_modes
#print axioms PrimeNumberTheorem.MWKFCubic.cubicMollifiedSecondMoment_eq_completed_principal_remainder
