import PrimeNumberTheorem.MWKFCubicAFEMollifierReassembly

namespace PrimeNumberTheorem.MWKFCubic

#check cubicAFEMollifiedApproximation
#check cubicAFEMollifierPairApproximation
#check tendsto_cubicAFEMollifiedApproximation
#check cubicAFEMollifiedApproximation_eq_pairSum
#check summable_cubicAFEWeightFinite
#check cubicAFECombinedSummandFinite
#check summable_cubicAFECombinedSummandFinite
#check cubicAFEMollifierPairApproximation_eq_tsum

end PrimeNumberTheorem.MWKFCubic
