import PrimeNumberTheorem.MWKFCubicAFEJointSmooth

#print axioms PrimeNumberTheorem.MWKFCubic.contDiff_cubicAFEScalar_joint
#print axioms PrimeNumberTheorem.MWKFCubic.contDiff_cubicAFELogProductWeightFinite_joint
#print axioms PrimeNumberTheorem.MWKFCubic.contDiffOn_cubicAFERealProductWeightFinite_joint
#print axioms PrimeNumberTheorem.MWKFCubic.contDiffOn_cubicAFEProgressionPhysicalSummand_joint
#print axioms PrimeNumberTheorem.MWKFCubic.contDiff_cubicAFEProgressionCutoffSummand_joint
#print axioms PrimeNumberTheorem.MWKFCubic.contDiff_integral_cubicAFEProgressionCutoffSummand
#print axioms PrimeNumberTheorem.MWKFCubic.hasCompactSupport_integral_cubicAFEProgressionCutoffSummand
#print axioms PrimeNumberTheorem.MWKFCubic.cubicAFEIntegratedProgressionSchwartz
