import PrimeNumberTheorem.MWKFCubicAFEExactDecomposition

#print axioms PrimeNumberTheorem.MWKFCubic.cubicMollifiedSecondMoment_zero
#print axioms PrimeNumberTheorem.MWKFCubic.cubicMollifiedSecondMoment_eq_fixedDepth_principal_remainder
#print axioms PrimeNumberTheorem.MWKFCubic.cubicMollifiedSecondMoment_eq_completionSchedule_principal_remainder
#print axioms PrimeNumberTheorem.MWKFCubic.cubic_actual_long_mollifier_asymptotic_of_completionSchedule_estimates
#print axioms PrimeNumberTheorem.MWKFCubic.cubic_actual_long_mollifier_asymptotic_of_fixedDepth_estimates
