import PrimeNumberTheorem.MWKFCubicAFEZeroMode

#print axioms PrimeNumberTheorem.MWKFCubic.summable_cubicAFENonzeroFrequencyCoefficient
#print axioms PrimeNumberTheorem.MWKFCubic.cubicAFEFrequencyBoxFinite_eq_zero_add_nonzero
#print axioms PrimeNumberTheorem.MWKFCubic.cubicAFEFrequencyCoefficient_zero
#print axioms PrimeNumberTheorem.MWKFCubic.cubicAFEZeroModeBoxFinite_eq_physicalIntegral
#print axioms PrimeNumberTheorem.MWKFCubic.cubicAFEZeroModeBoxFinite_eq_integratedKernel
#print axioms PrimeNumberTheorem.MWKFCubic.sum_cubicAFEFrequencyBoxFinite_eq_zero_add_nonzero
