import PrimeNumberTheorem.MWKFCubicAFEJointKernel

#print axioms PrimeNumberTheorem.MWKFCubic.continuous_cubicAFELogProductWeightFinite_joint
#print axioms PrimeNumberTheorem.MWKFCubic.continuousOn_cubicAFERealProductWeightFinite_joint
#print axioms PrimeNumberTheorem.MWKFCubic.continuousOn_cubicAFEProgressionPhysicalSummand_joint
#print axioms PrimeNumberTheorem.MWKFCubic.continuous_cubicAFEProgressionCutoffSummand_joint
#print axioms PrimeNumberTheorem.MWKFCubic.hasCompactSupport_cubicAFEProgressionCutoffSummand_joint
