import PrimeNumberTheorem.MWKFCubicAFEMollifierReassembly

#print axioms PrimeNumberTheorem.MWKFCubic.tendsto_cubicAFEMollifiedApproximation
#print axioms PrimeNumberTheorem.MWKFCubic.cubicAFEMollifiedApproximation_eq_pairSum
#print axioms PrimeNumberTheorem.MWKFCubic.summable_cubicAFECombinedSummandFinite
#print axioms PrimeNumberTheorem.MWKFCubic.cubicAFEMollifierPairApproximation_eq_tsum
#print axioms PrimeNumberTheorem.MWKFCubic.cubicAFEMollifiedApproximation_eq_tripleSum
#print axioms PrimeNumberTheorem.MWKFCubic.cubicAFECombinedSummandFinite_eq_exp
#print axioms PrimeNumberTheorem.MWKFCubic.cubicAFECombinedSummandFinite_eq_on_diagonal
