import PrimeNumberTheorem.MWKFCubicAFEDyadicReassembly

#print axioms PrimeNumberTheorem.MWKFCubic.cubicAFEProgressionDyadicCutoff_nonneg
#print axioms PrimeNumberTheorem.MWKFCubic.cubicAFEProgressionDyadicCutoff_scales
#print axioms PrimeNumberTheorem.MWKFCubic.summable_cubicAFEProgression_dyadic_weighted
#print axioms PrimeNumberTheorem.MWKFCubic.tsum_cubicAFEProgression_eq_dyadic
#print axioms PrimeNumberTheorem.MWKFCubic.summable_cubicAFEProgressionSummand
#print axioms PrimeNumberTheorem.MWKFCubic.cubicAFEDyadicPoissonTerm_eq_cutoffSum
#print axioms PrimeNumberTheorem.MWKFCubic.cubicAFEShiftFiber_eq_dyadicPoisson
#print axioms PrimeNumberTheorem.MWKFCubic.summable_cubicAFEDyadicPoissonTerm
#print axioms PrimeNumberTheorem.MWKFCubic.cubicAFEProgressionIntegral_eq_dyadic
#print axioms PrimeNumberTheorem.MWKFCubic.summable_cubicAFEProgressionDyadicIntegral
