import PrimeNumberTheorem.MWKFCubicAFECompletedPoisson

#print axioms PrimeNumberTheorem.MWKFCubic.summable_cubicAFECompletedFrequencyCoefficient
#print axioms PrimeNumberTheorem.MWKFCubic.cubicAFECompletedFrequencyBox_eq_progression
#print axioms PrimeNumberTheorem.MWKFCubic.cubicAFECompletedFrequencyCoefficient_zero
#print axioms PrimeNumberTheorem.MWKFCubic.cubicAFECompletedFrequencyBox_eq_zero_add_nonzero
#print axioms PrimeNumberTheorem.MWKFCubic.cubicAFECompletedFrequencyBox_lower_scale
#print axioms PrimeNumberTheorem.MWKFCubic.cubicAFECompletedLowerScale_zero_add_nonzero
#print axioms PrimeNumberTheorem.MWKFCubic.cubicAFECompletedFrequencyCoefficient_shift
#print axioms PrimeNumberTheorem.MWKFCubic.cubicAFECompletedFrequencyBox_shift
