import PrimeNumberTheorem.MWKFCubicEulerAnalytic

open PrimeNumberTheorem.MWKFCubic

#check analyticOnNhd_mwkfPrimeCorrectionFactor_openStrip

#print axioms analyticOnNhd_mwkfPrimeCorrectionFactor_openStrip
