import PrimeNumberTheorem.MWKFCubicFinal

open Filter Asymptotics

namespace PrimeNumberTheorem.MWKFCubic

#check cubicMainConstant
#check cubic_long_mollifier_asymptotic_of_exact_inputs
#check cubic_actual_long_mollifier_asymptotic_of_exact_inputs

end PrimeNumberTheorem.MWKFCubic
