import PrimeNumberTheorem.MWKFCubicAFEFrequencyMoment

#print axioms PrimeNumberTheorem.MWKFCubic.integral_cubicAFEDyadicPoissonTerm_eq_frequencyBox
#print axioms PrimeNumberTheorem.MWKFCubic.summable_cubicAFEFrequencyBoxFinite
#print axioms PrimeNumberTheorem.MWKFCubic.summable_shift_cubicAFEFrequencyBoxFinite
#print axioms PrimeNumberTheorem.MWKFCubic.cubicAFEDyadicPoissonMomentFinite_eq_frequency
#print axioms PrimeNumberTheorem.MWKFCubic.cubicAFEMollifiedMomentFinite_eq_diagonal_add_frequency
#print axioms PrimeNumberTheorem.MWKFCubic.tendsto_cubicAFEDiagonal_add_frequency
