import PrimeNumberTheorem.MWKFCubicAFECombinedPhase

#print axioms PrimeNumberTheorem.MWKFCubic.cubicAFECombinedArithmeticFactor_eq_exp
#print axioms PrimeNumberTheorem.MWKFCubic.cubicAFECombinedArithmeticFactor_eq_on_diagonal
