import PrimeNumberTheorem.PrimeSideDetectorMainPole

#print axioms PrimeNumberTheorem.PrimeSideDetector.finiteDirichletDetectorAtOne_eq_positive_sub_negative
#print axioms PrimeNumberTheorem.PrimeSideDetector.finiteDirichletDetectorAtOne_pos_of_nonnegative
#print axioms PrimeNumberTheorem.PrimeSideDetector.finiteDirichletDetectorAtOne_ne_zero_of_nonnegative
#print axioms PrimeNumberTheorem.PrimeSideDetector.finiteDirichletDetectorAtOne_eq_zero_iff_mass_balance
#print axioms PrimeNumberTheorem.PrimeSideDetector.positive_and_negative_coefficients_of_vanishes_at_one
