import PrimeNumberTheorem.QPowerDetectorAlgebra
import PrimeNumberTheorem.QPowerDetectorMass

#print axioms PrimeNumberTheorem.PrimeSideDetector.qPowerNode_one
#print axioms PrimeNumberTheorem.PrimeSideDetector.evalRealPolynomial_realNodeFactor_self
#print axioms PrimeNumberTheorem.PrimeSideDetector.evalRealPolynomial_conjugatePairFactor_left
#print axioms PrimeNumberTheorem.PrimeSideDetector.evalRealPolynomial_conjugatePairFactor_right
#print axioms PrimeNumberTheorem.PrimeSideDetector.evalRealPolynomial_realLinearInterpolator
#print axioms PrimeNumberTheorem.PrimeSideDetector.normalizedQPowerPolynomial_eval_target
#print axioms PrimeNumberTheorem.PrimeSideDetector.normalizedQPowerPolynomial_eval_main
#print axioms PrimeNumberTheorem.PrimeSideDetector.normalizedQPowerPolynomial_eval_realNode
#print axioms PrimeNumberTheorem.PrimeSideDetector.normalizedQPowerPolynomial_eval_pairNode
#print axioms PrimeNumberTheorem.PrimeSideDetector.qPowerDetector_eq_polynomial_eval
#print axioms PrimeNumberTheorem.PrimeSideDetector.qPowerDetector_eq_coeff_sum
#print axioms PrimeNumberTheorem.PrimeSideDetector.normalizedQPowerDetector_at_target
#print axioms PrimeNumberTheorem.PrimeSideDetector.normalizedQPowerDetector_at_one
#print axioms PrimeNumberTheorem.PrimeSideDetector.polynomial_eval_eq_positive_sub_negative
#print axioms PrimeNumberTheorem.PrimeSideDetector.polynomialNegativeMassAt_eq_half_weightedL1At
#print axioms PrimeNumberTheorem.PrimeSideDetector.normalizedQPowerPolynomial_negativeMass_eq_half
#print axioms PrimeNumberTheorem.PrimeSideDetector.polynomialWeightedL1At_mul_le
#print axioms PrimeNumberTheorem.PrimeSideDetector.polynomialWeightedL1At_realNodeFactor_le
#print axioms PrimeNumberTheorem.PrimeSideDetector.polynomialWeightedL1At_conjugatePairFactor_le
#print axioms PrimeNumberTheorem.PrimeSideDetector.normalizedQPowerPolynomial_weightedL1_le
