import PrimeNumberTheorem.QPowerDetectorScaleBarrier

#print axioms PrimeNumberTheorem.PrimeSideDetector.norm_evalRealPolynomial_le_polynomialWeightedL1At_norm
#print axioms PrimeNumberTheorem.PrimeSideDetector.polynomialWeightedL1At_le_ratio_pow_of_natDegree_le
#print axioms PrimeNumberTheorem.PrimeSideDetector.norm_qPowerNode
#print axioms PrimeNumberTheorem.PrimeSideDetector.qPowerDetector_weightedL1At_one_lower
#print axioms PrimeNumberTheorem.PrimeSideDetector.qPowerDetector_negativeMassAt_one_lower
#print axioms PrimeNumberTheorem.PrimeSideDetector.qPowerDetector_supportCompatible_negativeMass_loss
