import PrimeNumberTheorem.RiemannVonMangoldt.ZetaArgumentBound

#print axioms PrimeNumberTheorem.RiemannVonMangoldt.abs_integral_im_shiftedDivisorPrincipalPart_le_pi_mul_mass
#print axioms PrimeNumberTheorem.RiemannVonMangoldt.exists_abs_zetaHorizontalArgumentVariation_le_log
