import PrimeNumberTheorem.RiemannVonMangoldt.CriticalLinePartition

#print axioms PrimeNumberTheorem.RiemannVonMangoldt.isNontrivialZero_criticalLineReflection
#print axioms PrimeNumberTheorem.RiemannVonMangoldt.analyticOrderNatAt_riemannZeta_conj_of_nontrivialZero
#print axioms PrimeNumberTheorem.RiemannVonMangoldt.analyticOrderNatAt_riemannZeta_criticalLineReflection_of_nontrivialZero
#print axioms PrimeNumberTheorem.RiemannVonMangoldt.riemannZeroCount_eq_positiveCriticalLine_add_two_mul_zeroDensityCount
#print axioms PrimeNumberTheorem.RiemannVonMangoldt.riemannZeroCount_add_halfMultiplicity_eq_criticalLine_add_two_mul_zeroDensityCount
#print axioms PrimeNumberTheorem.RiemannVonMangoldt.riemannZeroCount_eq_criticalLine_add_two_mul_zeroDensityCount
