import HardyTheorem.SelbergRefinedUniformFourierMass

namespace HardyTheorem

#check exists_integral_normSq_selbergExplicitInverseFourierKernel_low_le_refined_uniform
#check exists_integral_normSq_selbergExplicitInverseFourierKernel_high_le_refined_uniform

#print axioms exists_integral_normSq_selbergExplicitInverseFourierKernel_low_le_refined_uniform
#print axioms exists_integral_normSq_selbergExplicitInverseFourierKernel_high_le_refined_uniform

end HardyTheorem
