import HardyTheorem.SelbergSqrtZetaCompleteProductHighEnergy

#print axioms HardyTheorem.selbergSqrtZetaCompleteProductFiber_eq_divisorsAntidiagonal_filter_box
#print axioms HardyTheorem.selbergSqrtZetaCompleteProductCoeff_eq_invSqrt_mul_boxedDivisorSum
#print axioms HardyTheorem.selbergSqrtZetaCompleteProductHighEnergy_eq_boxedDivisorEnergy
