import HardyTheorem.SelbergSqrtZetaActualHighRangeEnergy
import HardyTheorem.SelbergSqrtZetaComparableNearDiagonalSchur
import HardyTheorem.SelbergSqrtZetaCompleteProductHighEnergy

-- Actual complete/high-range energy
#check HardyTheorem.selbergSqrtZetaShortCompleteRangePairSum_eq_shortConvolution
#check HardyTheorem.normSq_selbergSqrtZetaShortDirichletCollectedCoeff_eq_signedPairSum_sq_div
#check HardyTheorem.normSq_sliding_selbergSqrtZetaShortDirichletCollectedCoeff_le_signedPairSum
#check HardyTheorem.sum_normSq_sliding_selbergSqrtZetaShortDirichletCollectedCoeff_completeHighRange_le_signedPairEnergy
#check HardyTheorem.sum_normSq_sliding_selbergSqrtZetaShortDirichletCollectedCoeff_le_lowRange_add_signedPairEnergy_add_actualTail
#check HardyTheorem.sum_normSq_sliding_selbergSqrtZetaShortDirichletCollectedCoeff_le_lowRange_add_signedPairEnergy_add_logDecay_mul_rationalEnergy
#check HardyTheorem.sum_normSq_sliding_selbergSqrtZetaShortDirichletCollectedCoeff_le_lowRange_add_signedPairEnergy_add_logDecay_mul_mixedTailEnergy
#check HardyTheorem.selbergSqrtZetaShortDirichletGapSum_le_signedPairEnergy_add_actualTail_add_offDiagonal
#check HardyTheorem.selbergSqrtZetaShortDirichletGapSum_le_signedPairEnergy_add_logDecay_mul_rationalEnergy_add_offDiagonal
#check HardyTheorem.selbergSqrtZetaShortDirichletGapSum_le_signedPairEnergy_add_logDecay_mul_mixedTailEnergy_add_offDiagonal

-- Comparable near-diagonal reduction
#check HardyTheorem.inv_abs_log_nat_sub_log_nat_le_max_div_dist
#check HardyTheorem.selbergSqrtZetaComparableNearDiagonalBudget
#check HardyTheorem.selbergSqrtZetaComparableNearDiagonalSquareBudget
#check HardyTheorem.selbergSqrtZetaComparableGapBudget_le_nearDiagonal
#check HardyTheorem.selbergSqrtZetaComparableNearDiagonalBudget_le_square
#check HardyTheorem.selbergSqrtZeta_frequencyGap_le_nearDiagonalSquare_add_far
#check HardyTheorem.selbergSqrtZetaShortDirichletGapSum_le_nearDiagonalSquare_add_far

-- Schur/harmonic control of the comparable near diagonal
#check HardyTheorem.sum_inv_natDist_Ioc_le_two_mul_harmonic
#check HardyTheorem.sum_comparable_max_div_natDist_le_four_mul_self_mul_harmonic
#check HardyTheorem.comparableNearDiagonalSquareSum_le_weightedHarmonic
#check HardyTheorem.selbergSqrtZetaComparableNearDiagonalSquareBudget_le_weightedHarmonic
#check HardyTheorem.selbergSqrtZetaComparableNearDiagonalSquareBudget_le_globalHarmonic
#check HardyTheorem.selbergSqrtZetaComparableNearDiagonalSquareBudget_le_globalLog

-- Complete-product high energy
#check HardyTheorem.selbergSqrtZetaCompleteProductFiber_eq_divisorsAntidiagonal_filter_box
#check HardyTheorem.selbergSqrtZetaCompleteProductCoeff_eq_invSqrt_mul_boxedDivisorSum
#check HardyTheorem.selbergSqrtZetaCompleteProductHighEnergy_eq_boxedDivisorEnergy
