import HardyTheorem.SelbergSqrtZetaSignedRationalNoncarrierPlainEnergyBound

#check HardyTheorem.sum_normSq_selbergSqrtZetaSignedRationalNoncarrierCoeff_add_carrier_eq_full
#check HardyTheorem.sum_normSq_selbergSqrtZetaSignedRationalNoncarrierCoeff_eq_full_sub_carrier
#check HardyTheorem.sum_normSq_selbergSqrtZetaSignedRationalNoncarrierCoeff_eq_reducedPairCompleteBoundary_erase_one
#check HardyTheorem.sum_normSq_selbergSqrtZetaSignedRationalNoncarrierCoeff_le_reducedPairComplete_add_boundary_erase_one
#check HardyTheorem.sum_normSq_selbergSqrtZetaSignedRationalNoncarrierCoeff_le_completeHigh_add_boundaryTaper
