import HardyTheorem.SelbergSqrtZetaRestrictedPairMoment

#print axioms HardyTheorem.card_selbergShortCompleteRangePairs_le_divisors_sq
#print axioms HardyTheorem.card_selbergShortCompleteRangePairs_eq_sum_productMultiplicity
#print axioms HardyTheorem.sum_card_sq_selbergShortCompleteRangePairs_mul_inv_eq_lcmHarmonic
#print axioms HardyTheorem.sum_card_sq_selbergShortCompleteRangePairs_mul_inv_eq_doubleLcmHarmonic
#print axioms HardyTheorem.sum_card_sq_selbergShortCompleteRangePairs_mul_inv_le_totientSquares
#print axioms HardyTheorem.weighted_highRange_selbergShortCompleteRangePairs_le_completeMoment
#print axioms HardyTheorem.weighted_highRange_selbergShortCompleteRangePairs_le_totientSquares
#print axioms HardyTheorem.weighted_highRange_selbergShortCompleteRangePairs_le_log_mul_totientSquares
