import HardyTheorem.SelbergMollifiedTripleConstant

#check HardyTheorem.selbergMollifiedTripleConstantPairs
#check HardyTheorem.selbergMollifiedTripleKey_eq_one_iff
#check HardyTheorem.selbergMollifiedTripleFiber_one_eq_constantPairs_image
#check HardyTheorem.selbergMollifiedTripleCollectedCoeff_one_eq_constantPairs
#check HardyTheorem.selbergMollifiedTripleCoeff_constant_eq
#check HardyTheorem.selbergMollifiedTripleCollectedCoeff_one_eq_real_sum

#print axioms HardyTheorem.selbergMollifiedTripleKey_eq_one_iff
#print axioms HardyTheorem.selbergMollifiedTripleCollectedCoeff_one_eq_constantPairs
#print axioms HardyTheorem.selbergMollifiedTripleCollectedCoeff_one_eq_real_sum
