import HardyTheorem.SelbergSqrtZetaSignedReducedPairCompleteCancellation

open scoped BigOperators

#check HardyTheorem.sum_sq_selbergSqrtZetaCompleteRatioCoeff_eq_productCoeff
#check HardyTheorem.selbergSqrtZetaCompleteRatioCoeff_reduced_eq_completeTerm
#check HardyTheorem.sum_selbergSqrtZetaSignedReducedPairCompleteEnergy_le_productEnergy
#check HardyTheorem.sum_selbergSqrtZetaSignedReducedPairCompleteEnergy_le_nineteen_fourths_add_high
