import HardyTheorem.SelbergSqrtZetaSignedReducedPairCompleteMainTerm

#check HardyTheorem.selbergSqrtZetaSignedReducedRayCompleteWeight_eq_min_coordinateWeights
#check HardyTheorem.sum_selbergSqrtZetaSignedReducedPairCompleteEnergy_eq_min_coordinateWeights
#check HardyTheorem.sum_selbergSqrtZetaSignedReducedPairCompleteEnergy_le_denominatorCoordinateBudget
#check HardyTheorem.sum_selbergSqrtZetaSignedReducedPairCompleteEnergy_le_numeratorCoordinateBudget
