import HardyTheorem.SelbergSqrtZetaSignedBoundaryScale

#print axioms HardyTheorem.selbergSqrtZetaSignedCoprimeRayBoundaryScaleSupport_facts
#print axioms HardyTheorem.selbergSqrtZetaSignedCoprimeRayBoundaryScaleSupport_eq_filter_min_div
#print axioms HardyTheorem.selbergSqrtZetaSignedCoprimeRayBoundaryScaleSupport_mem_Ioc
#print axioms HardyTheorem.selbergSqrtZetaSignedCoprimeRayBoundaryScaleSupport_subset_Ioc
#print axioms HardyTheorem.selbergSqrtZetaSignedCoprimeRayBoundaryScaleSupport_card_le
#print axioms HardyTheorem.selbergSqrtZetaSignedCoprimeRayBoundaryScaleSupport_sum_inv_le
