import HardyTheorem.SelbergSqrtZetaSignedRationalCoefficientReducedPairEnergy

#check HardyTheorem.sum_normSq_selbergSqrtZetaSignedRationalCoeff_eq_reducedPairEnergy
#check HardyTheorem.sum_normSq_selbergSqrtZetaSignedRationalCoeff_le_reducedPairComplete_add_boundary
