import HardyTheorem.SelbergDiagonalRemainderAbsorption

open HardyTheorem

#check selbergDiagonalRemainderAbsorptionScale
#check selbergDiagonalRemainderScale_identity
#check selbergDiagonalRemainderTerm_le_target
