import HardyTheorem.SelbergShortCompleteRangeEnergy

namespace Test.SelbergShortCompleteRangeEnergyContract

#check HardyTheorem.Icc_one_filter_dvd_eq_image_mul
#check HardyTheorem.selbergShortLcmHarmonicKernel_one_eq_inv_mul_harmonic
#check HardyTheorem.natCast_lcm_inv_eq_gcd_mul_inv_mul_inv
#check HardyTheorem.natCast_gcd_eq_sum_totient_commonDivisors
#check HardyTheorem.selbergShortDoubleMoebiusCoeff_eq_zero_of_pred_sq_lt
#check HardyTheorem.sum_selbergShortDoubleMoebiusCoeff_eq_effectiveSupport
#check HardyTheorem.sum_double_selbergShortDoubleMoebiusCoeff_eq_effectiveSupport
#check HardyTheorem.sum_completeRangePairWeight_mul_kernel_eq_collected
#check HardyTheorem.sum_completeRangeQuadrupleWeight_mul_kernel_eq_doubleCollected
#check HardyTheorem.selbergShortCompleteRangeCoeff_sq_eq_lcmSum
#check HardyTheorem.normSq_selbergShortDirichletCollectedCoeff_eq_convolution_sq_mul_inv
#check HardyTheorem.sum_normSq_selbergShortDirichletCollectedCoeff_eq_lcmKernel
#check HardyTheorem.sum_normSq_selbergShortDirichletCollectedCoeff_completeRange_eq_lcmHarmonic
#check HardyTheorem.sum_normSq_selbergShortDirichletCollectedCoeff_nonconstantRange_eq_lcmHarmonic_sub_one
#check HardyTheorem.sum_normSq_selbergShortDirichletCollectedCoeff_completeRange_eq_doubleLcmHarmonic
#check HardyTheorem.sum_normSq_selbergShortDirichletCollectedCoeff_completeRange_eq_effectiveDoubleLcmHarmonic
#check HardyTheorem.sum_normSq_selbergShortDirichletCollectedCoeff_nonconstantRange_eq_doubleLcmHarmonic_sub_one
#check HardyTheorem.selbergShortDoubleMoebius_reciprocalLcmQuadratic_eq_totientSquares
#check HardyTheorem.selbergShortDoubleMoebius_reciprocalLcmQuadratic_nonneg

#print axioms HardyTheorem.Icc_one_filter_dvd_eq_image_mul
#print axioms HardyTheorem.selbergShortLcmHarmonicKernel_one_eq_inv_mul_harmonic
#print axioms HardyTheorem.natCast_lcm_inv_eq_gcd_mul_inv_mul_inv
#print axioms HardyTheorem.natCast_gcd_eq_sum_totient_commonDivisors
#print axioms HardyTheorem.selbergShortDoubleMoebiusCoeff_eq_zero_of_pred_sq_lt
#print axioms HardyTheorem.sum_selbergShortDoubleMoebiusCoeff_eq_effectiveSupport
#print axioms HardyTheorem.sum_double_selbergShortDoubleMoebiusCoeff_eq_effectiveSupport
#print axioms HardyTheorem.sum_completeRangePairWeight_mul_kernel_eq_collected
#print axioms HardyTheorem.sum_completeRangeQuadrupleWeight_mul_kernel_eq_doubleCollected
#print axioms HardyTheorem.sum_normSq_selbergShortDirichletCollectedCoeff_eq_lcmKernel
#print axioms HardyTheorem.sum_normSq_selbergShortDirichletCollectedCoeff_completeRange_eq_lcmHarmonic
#print axioms HardyTheorem.sum_normSq_selbergShortDirichletCollectedCoeff_nonconstantRange_eq_lcmHarmonic_sub_one
#print axioms HardyTheorem.sum_normSq_selbergShortDirichletCollectedCoeff_completeRange_eq_doubleLcmHarmonic
#print axioms HardyTheorem.sum_normSq_selbergShortDirichletCollectedCoeff_completeRange_eq_effectiveDoubleLcmHarmonic
#print axioms HardyTheorem.sum_normSq_selbergShortDirichletCollectedCoeff_nonconstantRange_eq_doubleLcmHarmonic_sub_one
#print axioms HardyTheorem.selbergShortDoubleMoebius_reciprocalLcmQuadratic_eq_totientSquares
#print axioms HardyTheorem.selbergShortDoubleMoebius_reciprocalLcmQuadratic_nonneg

end Test.SelbergShortCompleteRangeEnergyContract
