import HardyTheorem.SelbergSqrtZetaGapDecomposition
import HardyTheorem.SelbergSqrtZetaRestrictedPairMoment
import HardyTheorem.SelbergSqrtZetaRestrictedPairMomentBound
import HardyTheorem.SelbergSqrtZetaSmallAbsSharpBudget

open HardyTheorem

#check selbergSqrtZetaShortDirichletGapSum_eq_slidingExponentialGapSum
#check selbergSqrtZetaShortDirichletGapSum_le_diagonal_add_offDiagonal

#check selbergShortRestrictedPairProductMultiplicity
#check selbergShortCompleteRangePairs_subset_divisors_product
#check card_selbergShortCompleteRangePairs_le_divisors_sq
#check card_selbergShortCompleteRangePairs_eq_sum_productMultiplicity
#check sum_completeRangePair_kernel_eq_productMultiplicity
#check sum_completeRangeQuadruple_kernel_eq_doubleProductMultiplicity
#check card_selbergShortCompleteRangePairs_sq_eq_card_quadruples
#check sum_card_sq_selbergShortCompleteRangePairs_mul_inv_eq_lcmHarmonic
#check sum_card_sq_selbergShortCompleteRangePairs_mul_inv_eq_doubleLcmHarmonic
#check harmonic_natCast_mono
#check sum_card_sq_selbergShortCompleteRangePairs_mul_inv_le_totientSquares
#check weighted_highRange_selbergShortCompleteRangePairs_le_completeMoment
#check weighted_highRange_selbergShortCompleteRangePairs_le_totientSquares
#check weighted_highRange_selbergShortCompleteRangePairs_le_log_mul_totientSquares

#check sum_selbergShortRestrictedPairProductMultiplicity_eq_sq
#check sum_selbergShortRestrictedPairProductMultiplicity_mul_inv_eq_harmonic_sq
#check totientSquares_selbergShortRestrictedPairProductMultiplicity_le
#check weighted_highRange_selbergShortCompleteRangePairs_le_logPolynomial
#check weighted_highRange_selbergSqrtZetaShortCollectedTripleFiberEnergy_le_logPolynomial
#check sum_normSq_sliding_selbergSqrtZetaShortDirichletCollectedCoeff_le_lowRange_add_logPolynomialHighRange

#check selbergSqrtZetaComparableGapBudget
#check selbergSqrtZetaFarGapBudget
#check selbergSqrtZetaCollectedCoeffL1
#check selbergSqrtZeta_frequencyGap_eq_comparable_add_farGap
#check selbergSqrtZeta_farGap_le_l1
#check selbergSqrtZeta_frequencyGap_le_comparable_add_far
#check selbergSqrtZetaShortDirichletGapSum_le_comparable_add_far
