import HardyTheorem.SelbergSqrtZetaSignedPhasePolynomial

#print axioms HardyTheorem.conj_selbergSqrtZetaMollifier_criticalLine_eq_sum
#print axioms HardyTheorem.criticalLineDirichletPolynomial_mul_sqrtZetaMollifier_mul_conj_eq_signedTripleSum
#print axioms HardyTheorem.criticalLineDirichletPolynomial_mul_sqrtZetaMollifier_mul_conj_eq_signedTriplePolynomial
#print axioms HardyTheorem.selbergSqrtZetaSignedPhasePolynomial_eq_exp_mul_signedTriplePolynomial
#print axioms HardyTheorem.exp_I_thetaModel_mul_criticalLinePolynomial_mul_sqrtZetaMollifier_mul_conj_eq_signedPhasePolynomial
