import HardyTheorem.SelbergSqrtZetaSignedAutocorrelationShiftBudget
import HardyTheorem.SelbergSqrtZetaSignedModelL2Arithmetic
import HardyTheorem.SelbergSqrtZetaSignedRationalCoefficientEnergySharp
import HardyTheorem.SelbergSqrtZetaSignedRationalLocalSeparationArithmetic
import HardyTheorem.SelbergSqrtZetaSignedRationalPacking
import HardyTheorem.SelbergSqrtZetaSignedRationalShortModel
import HardyTheorem.SelbergSqrtZetaSignedRationalSquareEnvelope
import HardyTheorem.SelbergSqrtZetaSignedRationalWindowEnvelope

open HardyTheorem

#check selbergSqrtZetaMollifiedAutocorrelationShiftKernel
#check selbergSqrtZetaSignedThetaModelAutocorrelationShiftKernel
#check integrable_selbergSqrtZetaSignedAutocorrelationShiftKernels
#check exists_abs_integral_integral_integral_selbergSqrtZetaMollifiedAutocorrelation_sub_signedThetaModel_le

#check selbergSqrtZetaSignedModelL2Budget_eq_rational_energy_add_gap

#check selbergSqrtZetaSignedRationalPairCoeff
#check selbergSqrtZetaSignedRationalCoeff_re_eq_pairSum
#check sum_normSq_selbergSqrtZetaSignedRationalCoeff_eq_crossProduct
#check sum_normSq_selbergSqrtZetaSignedRationalPairCoeff_eq_product
#check sum_normSq_selbergSqrtZetaSignedRationalCoeff_eq_product_add_offDiagonal
#check sum_normSq_selbergSqrtZetaSignedRationalCoeff_le_product_add_abs_offDiagonal

#check one_div_nat_mul_sq_le_localFrequencySeparation_of_mem_rationalSupport
#check sum_normSq_div_localFrequencySeparation_le_arithmeticEnergy
#check integral_normSq_rationalCollectedPolynomial_le_arithmeticEnergy

#check selbergSqrtZetaSignedRationalFrequencyBallSupport
#check card_sub_one_div_nat_mul_sq_le_two_mul_radius

#check selbergSqrtZetaSignedRationalShortModel
#check integral_selbergSqrtZetaSignedComplexModel_shift_eq_rationalShortModel
#check normSq_integral_selbergSqrtZetaSignedComplexModel_shift_eq_rationalShortModel
#check integral_normSq_integral_selbergSqrtZetaSignedComplexModel_shift_eq_rationalShortModel

#check sum_sq_stationaryMinReciprocalEnvelope_rationalSupport_le

#check selbergSqrtZetaSignedRationalWindowEnvelopeSum
#check norm_integral_selbergSqrtZetaSignedComplexModel_shift_le_rationalWindowEnvelopeSum
