import HardyTheorem.SelbergSqrtZetaSignedCarrierNoncarrierEndpoint

#print axioms HardyTheorem.intervalIntegrable_normSq_selbergSqrtZetaSignedRationalShortModel
#print axioms HardyTheorem.intervalIntegrable_normSq_selbergSqrtZetaSignedRationalNoncarrierShortModel
#print axioms HardyTheorem.integral_normSq_selbergSqrtZetaSignedRationalNoncarrierShortModel_le_eraseBudget
#print axioms HardyTheorem.integral_normSq_selbergSqrtZetaSignedRationalShortModel_le_carrier_add_noncarrierEraseBudget
#print axioms HardyTheorem.selbergSqrtZetaSignedRationalNoncarrierEraseBudget_le_explicitBudget
#print axioms HardyTheorem.integral_normSq_selbergSqrtZetaSignedRationalShortModel_le_carrier_add_noncarrierExplicitBudget
