import HardyTheorem.SelbergDiagonalKernelIntegral

open MeasureTheory Set

namespace HardyTheorem

#check measurable_selbergEulerFloorPowerSum
#check measurable_selbergEulerFloorError
#check integrableOn_selbergDiagonalEulerErrorIntegrand_Ioi
#check norm_integral_selbergDiagonalEulerErrorIntegrand_Ioi_le
#check selbergDiagonalMainCoefficient
#check selberg_rpow_main_algebra
#check selbergEtaSqrtMainCancellation
#check selbergDiagonalEulerMainIntegrand_eq
#check selbergDiagonalConstantCoefficient
#check selbergDiagonalEulerConstantIntegrand_eq
#check integral_Ioi_gaussian_eq_full_sub_lower
#check integral_Ioi_weightedGaussian_eq_full_sub_lower
#check integral_selbergDiagonalEulerMainIntegrand_Ioi
#check integral_selbergDiagonalEulerConstantIntegrand_Ioi
#check selbergDiagonalFloorKernel
#check selbergDiagonalEulerRemainder
#check integrableOn_selbergDiagonalEulerMainIntegrand_Ioi
#check integrableOn_selbergDiagonalEulerConstantIntegrand_Ioi
#check selbergDiagonalFloorKernel_eq_three_integrals
#check selbergDiagonalFloorKernel_exact_decomposition
#check selbergDiagonalTitchMain
#check selbergDiagonalLowCorrection
#check selbergDiagonalFullConstantTerm_eq
#check selbergDiagonalFloorKernel_eq_titchMain_sub_correction_add_remainder
#check norm_selbergDiagonalEulerRemainder_le
#check selbergDiagonalMainCoefficient_nonneg
#check selbergDiagonalMainCoefficient_mul_scale
#check abs_selbergDiagonalMainLowTerm_le
#check abs_selbergDiagonalConstantCoefficient_le
#check selbergDiagonalConstantScaleCancellation
#check abs_selbergDiagonalConstantLowTerm_le
#check abs_selbergDiagonalLowCorrection_le
#check abs_selbergDiagonalLowCorrection_le_three
#check abs_selbergDiagonalFloorKernel_sub_titchMain_le
#check integrableOn_selbergDiagonalFloorKernelIntegrand_Ioi

end HardyTheorem
