import HardyTheorem.SelbergSqrtZetaSignedReducedRayBoundaryEnergy

#print axioms HardyTheorem.sum_inv_snd_selbergSqrtZetaSignedDenominatorFiber_le_harmonic
#print axioms HardyTheorem.sq_sum_selbergSqrtZetaSignedDenominatorFiber_taper_le_harmonic_mul_weightedEnergy
#print axioms HardyTheorem.selbergSqrtZetaSignedReducedRayBoundaryTerm_sq_le_harmonicEnergy
#print axioms HardyTheorem.selbergSqrtZetaSignedReducedRayBoundaryTerm_sq_le_harmonicMass_mul_denominatorEnergy
#print axioms HardyTheorem.selbergSqrtZetaSignedReducedRayBoundaryTerm_sq_le_harmonicTail_mul_denominatorEnergy
