import HardyTheorem.SelbergSqrtZetaSignedCoprimeRayLogExpansion

#print axioms HardyTheorem.selbergSqrtZetaSignedDenominatorCollectedRealCoeff_eq_invSqrt_mul_arithmeticCoeff
#print axioms HardyTheorem.selbergSqrtZetaSignedRationalPairCoeff_coprimeRay_eq_invSqrt_mul_invScale
#print axioms HardyTheorem.selbergSqrtZetaSignedCoprimeRayScaleSum_eq_invSqrt_mul_bilinearScaleSum
#print axioms HardyTheorem.selbergSqrtZetaTaperedCoeff_eq_coeff_sub_invLog_mul_logCoeff
#print axioms HardyTheorem.selbergSqrtZetaSignedCoprimeRayBilinearScaleSum_taper_eq_logExpansion
#print axioms HardyTheorem.selbergSqrtZetaSignedCoprimeRayScaleSum_eq_invSqrt_mul_logExpansion
