import HardyTheorem.SelbergSqrtZetaSignedApproximation

#print axioms HardyTheorem.selbergSqrtZetaMollifiedHardyZ_eq_rotatedZeta_re_mul_normSq
#print axioms HardyTheorem.exists_abs_selbergSqrtZetaMollifiedHardyZ_sub_signedThetaModel_le_normSq
#print axioms HardyTheorem.exists_abs_selbergSqrtZetaMollifiedHardyZ_sub_signedThetaModel_le_majorant
#print axioms HardyTheorem.exists_abs_selbergSqrtZetaMollifiedHardyZ_sub_signedThetaModel_le_four_mul
#print axioms HardyTheorem.exists_abs_selbergSqrtZetaMollifiedAutocorrelation_sub_signedThetaModel_le
