import HardyTheorem.SelbergSqrtZetaSignedRationalGapBudget

#print axioms HardyTheorem.selbergSqrtZetaSignedRational_pos_of_mem
#print axioms HardyTheorem.selbergSqrtZetaSignedRationalFrequency_sub_eq_log_div
#print axioms HardyTheorem.sum_collectedFrequencyGap_eq_rationalGapBudget
#print axioms HardyTheorem.norm_integral_integral_integral_selbergSqrtZetaSignedOrdinaryCorrelation_le_rational_gap
