import HardyTheorem.SelbergSqrtZetaSignedBoundaryScale
import HardyTheorem.SelbergSqrtZetaSignedFullTaper
import HardyTheorem.SelbergSqrtZetaSignedRationalReducedPairSupport
import HardyTheorem.SelbergSqrtZetaSignedRationalReducedRayEnergy
import HardyTheorem.SelbergSqrtZetaSignedReducedRayCompleteBoundary
import HardyTheorem.SelbergSqrtZetaSignedBoundaryLargeN
import HardyTheorem.SelbergSqrtZetaSignedRationalCarrierDecomposition
import HardyTheorem.SelbergSqrtZetaSignedRationalReducedPairEnergy
import HardyTheorem.SelbergSqrtZetaSignedReducedRayBoundaryEnergy
import HardyTheorem.SelbergSqrtZetaSignedRationalCoefficientReducedPairEnergy
import HardyTheorem.SelbergSqrtZetaSignedRationalReducedPairShortModel
import HardyTheorem.SelbergSqrtZetaSignedReducedRayBoundaryTaperEnergy

open HardyTheorem

#check selbergSqrtZetaSignedCoprimeRayBoundaryScaleSupport_facts
#check selbergSqrtZetaSignedCoprimeRayBoundaryScaleSupport_eq_filter_min_div
#check selbergSqrtZetaSignedCoprimeRayBoundaryScaleSupport_mem_Ioc
#check selbergSqrtZetaSignedCoprimeRayBoundaryScaleSupport_subset_Ioc
#check selbergSqrtZetaSignedCoprimeRayBoundaryScaleSupport_card_le
#check selbergSqrtZetaSignedCoprimeRayBoundaryScaleSupport_sum_inv_le

#check zeta_mul_selbergSqrtZetaFullTapered
#check zeta_mul_selbergSqrtZetaFullTapered_apply
#check selbergSqrtZetaSignedCoprimeRayComplete_fullTaper_eq_twoFactors
#check selbergSqrtZetaSignedCoprimeRayComplete_logExpansion_eq_twoFactors

#check selbergSqrtZetaSignedCanonicalReducedPair
#check selbergSqrtZetaSignedReducedPairKey
#check selbergSqrtZetaSignedRationalReducedPairSupport
#check selbergSqrtZetaSignedCanonicalReducedPair_key_eq
#check selbergSqrtZetaSignedCanonicalReducedPair_key_of_pos_coprime
#check selbergSqrtZetaSignedRationalReducedPairSupport_mem_iff
#check selbergSqrtZetaSignedReducedPairKey_injOn
#check selbergSqrtZetaSignedRationalSupport_unique_reducedPair
#check image_selbergSqrtZetaSignedReducedPairKey_reducedPairSupport
#check sum_selbergSqrtZetaSignedRationalSupport_eq_reducedPairSupport

#check normSq_div_localFrequencySeparation_le_reducedRayWeight
#check normSq_div_localFrequencySeparation_le_reducedRayBilinearWeight
#check normSq_div_localFrequencySeparation_le_reducedRayLogExpansionWeight

#check selbergSqrtZetaSignedReducedRayCompleteTerm
#check selbergSqrtZetaSignedReducedRayBoundaryTerm
#check selbergSqrtZetaSignedCoprimeRayBilinearScaleSum_eq_complete_add_boundary
#check normSq_div_localFrequencySeparation_le_reducedRayCompleteBoundaryWeight

#check selbergSqrtZetaSignedDenominatorFiber_eq_divisorsAntidiagonal_filter_snd
#check selbergSqrtZetaSignedCoprimeRayScaleSupport_eq_Icc_of_b_mul_X_le_N
#check selbergSqrtZetaSignedCoprimeRayBoundaryScaleSupport_eq_Ioc_of_b_mul_X_le_N
#check selbergSqrtZetaSignedReducedRayBoundaryTerm_eq_stable_Ioc
#check selbergSqrtZetaSignedReducedRayBoundaryTerm_eq_stable_Ioc_of_sq_le
#check selbergSqrtZetaSignedCoprimeRayBoundaryScaleSupport_numerator_lt_denominator
#check selbergSqrtZetaSignedCoprimeRayBoundaryScaleSupport_eq_empty_of_denominator_le_numerator
#check selbergSqrtZetaSignedReducedRayBoundaryTerm_eq_zero_of_denominator_le_numerator

#check one_mem_selbergSqrtZetaSignedRationalSupport
#check selbergSqrtZetaSignedRationalNoncarrierSupport
#check selbergSqrtZetaSignedRationalNoncarrierShortModel
#check selbergSqrtZetaSignedRationalShortModel_eq_carrier_add_noncarrier
#check selbergSqrtZetaSignedRationalCoeff_one_eq_complete_add_boundary
#check norm_thetaFrequencyShortIntegral_zero_le_of_base_frequency
#check norm_selbergSqrtZetaSignedRationalCarrier_le_of_base_frequency
#check quarter_log_le_deriv_thetaModel
#check norm_thetaFrequencyShortIntegral_zero_le_thirtytwo_div_log
#check norm_selbergSqrtZetaSignedRationalCarrier_le_thirtytwo_div_log
#check norm_selbergSqrtZetaSignedRationalShortModel_le_carrier_add_noncarrier

#check sum_normSq_div_localFrequencySeparation_le_reducedPairBilinearEnergy
#check sum_normSq_div_localFrequencySeparation_le_reducedPairCompleteBoundaryEnergy
#check sum_normSq_div_localFrequencySeparation_le_reducedPairComplete_add_boundary

#check sum_inv_snd_selbergSqrtZetaSignedDenominatorFiber_le_harmonic
#check sq_sum_selbergSqrtZetaSignedDenominatorFiber_taper_le_harmonic_mul_weightedEnergy
#check sum_weightedSq_selbergSqrtZetaSignedDenominatorFiber_le_globalTaperEnergy
#check sum_weightedSq_selbergSqrtZetaSignedDenominatorFiber_le_globalLinearTaperEnergy
#check sq_sum_selbergSqrtZetaSignedDenominatorFiber_taper_le_uniformLinearTaperEnergy
#check selbergSqrtZetaSignedReducedRayBoundaryTerm_sq_le_harmonicEnergy
#check selbergSqrtZetaSignedReducedRayBoundaryTerm_sq_le_harmonicMass_mul_denominatorEnergy
#check selbergSqrtZetaSignedReducedRayBoundaryTerm_sq_le_harmonicTail_mul_denominatorEnergy
#check selbergSqrtZetaSignedReducedRayBoundaryTerm_sq_le_harmonicTail_sq_mul_uniformLinearTaperEnergy

#check sum_normSq_selbergSqrtZetaSignedRationalCoeff_eq_reducedPairEnergy
#check sum_normSq_selbergSqrtZetaSignedRationalCoeff_le_reducedPairComplete_add_boundary
#check integral_normSq_selbergSqrtZetaSignedRationalShortModel_le_reducedPairComplete_add_boundary
#check sum_Icc_mul_sq_selbergMoebiusWeight_le_four_mul_sq_div_log_sq
#check selbergSqrtZetaSignedReducedRayBoundaryTerm_sq_le_four_mul_harmonicTail_sq_mul_harmonic_mul_sq_div_log_sq
