import HardyTheorem.SelbergSqrtZetaSignedRationalReducedSeparation

#print axioms HardyTheorem.one_div_one_add_X_mul_min_le_abs_sub_frequency_reduced_of_mem
#print axioms HardyTheorem.one_div_one_add_X_mul_min_le_localFrequencySeparation_reduced
#print axioms HardyTheorem.one_div_localFrequencySeparation_le_one_add_X_mul_min_reduced
#print axioms HardyTheorem.normSq_div_localFrequencySeparation_le_reducedWeight
