import HardyTheorem.SelbergSqrtZetaSignedRationalShortKernelLocalSeparation

#print axioms HardyTheorem.selbergSqrtZetaSignedRationalFixedShiftPhaseSum_eq_factorized
#print axioms HardyTheorem.selbergSqrtZetaSignedRationalFixedShiftPhaseSum_eq_modelCorrelation
#print axioms HardyTheorem.integral_normSq_selbergSqrtZetaSignedRationalShortModel_eq_re_fixedShiftPhaseSum
#print axioms HardyTheorem.norm_integral_selbergSqrtZetaSignedRationalFixedShiftPhaseSum_le_localSeparation
#print axioms HardyTheorem.norm_integral_integral_integral_selbergSqrtZetaSignedRationalFixedShiftPhaseSum_le_localSeparation
#print axioms HardyTheorem.integral_normSq_selbergSqrtZetaSignedRationalShortModel_le_localSeparation
