import HardyTheorem.SelbergSqrtZetaSignedReducedPairCompleteMainTerm

#print axioms HardyTheorem.selbergSqrtZetaSignedReducedRayCompleteWeight_eq_min_coordinateWeights
#print axioms HardyTheorem.sum_selbergSqrtZetaSignedReducedPairCompleteEnergy_eq_min_coordinateWeights
#print axioms HardyTheorem.sum_selbergSqrtZetaSignedReducedPairCompleteEnergy_le_denominatorCoordinateBudget
#print axioms HardyTheorem.sum_selbergSqrtZetaSignedReducedPairCompleteEnergy_le_numeratorCoordinateBudget
