import HardyTheorem.SelbergSqrtZetaGoodWindowMeasure

#print axioms HardyTheorem.exists_hardyZ_localSignChange_of_selbergSqrtZetaGoodStart
#print axioms HardyTheorem.selberg_odd_zero_proportion_target_of_sqrtZeta_good_window_bounds
