import HardyTheorem.SelbergSqrtZetaSignedRationalReducedPairEnergy

#check HardyTheorem.sum_normSq_div_localFrequencySeparation_le_reducedPairBilinearEnergy
#check HardyTheorem.sum_normSq_div_localFrequencySeparation_le_reducedPairCompleteBoundaryEnergy
#check HardyTheorem.sum_normSq_div_localFrequencySeparation_le_reducedPairComplete_add_boundary
