import HardyTheorem.SelbergMollifiedHardyPhasePolynomial

#check HardyTheorem.selbergMollifiedHardyPhaseFrequency
#check HardyTheorem.selbergMollifiedHardyPhasePolynomial
#check HardyTheorem.selbergMollifiedHardyPhaseCollectedPolynomial
#check HardyTheorem.selbergMollifiedHardyPhasePolynomial_eq_exp_mul_triplePolynomial
#check HardyTheorem.selbergMollifiedHardyPhaseCollectedPolynomial_eq_exp_mul_collectedPolynomial
#check HardyTheorem.selbergMollifiedHardyPhasePolynomial_eq_collectedPolynomial
#check HardyTheorem.exp_I_thetaModel_mul_criticalLinePolynomial_mul_mollifier_mul_conj_eq_phasePolynomial
#check HardyTheorem.exp_I_thetaModel_mul_criticalLinePolynomial_mul_mollifier_mul_conj_eq_collectedPhasePolynomial

#print axioms HardyTheorem.selbergMollifiedHardyPhasePolynomial_eq_exp_mul_triplePolynomial
#print axioms HardyTheorem.selbergMollifiedHardyPhaseCollectedPolynomial_eq_exp_mul_collectedPolynomial
#print axioms HardyTheorem.selbergMollifiedHardyPhasePolynomial_eq_collectedPolynomial
#print axioms HardyTheorem.exp_I_thetaModel_mul_criticalLinePolynomial_mul_mollifier_mul_conj_eq_phasePolynomial
#print axioms HardyTheorem.exp_I_thetaModel_mul_criticalLinePolynomial_mul_mollifier_mul_conj_eq_collectedPhasePolynomial
