import HardyTheorem.SelbergSqrtZetaSignedRationalNoncarrierWeightedEnergyBound

#check HardyTheorem.sum_normSq_div_fullLocalSeparation_reducedPairErase_le_completeBoundaryWeightedEnergy
#check HardyTheorem.sum_normSq_div_fullLocalSeparation_reducedPairErase_le_complete_add_boundary
#check HardyTheorem.sum_normSq_div_fullLocalSeparation_reducedPairErase_le_complete_add_explicitBoundary
