import HardyTheorem.SelbergSqrtZetaSignedAutocorrelationShiftBudget

#print axioms HardyTheorem.integrable_selbergSqrtZetaSignedAutocorrelationShiftKernels
#print axioms HardyTheorem.exists_abs_integral_integral_integral_selbergSqrtZetaMollifiedAutocorrelation_sub_signedThetaModel_le
