import HardyTheorem.SelbergHardyLagLinearization
import HardyTheorem.SelbergSqrtZetaExcessiveTotalBudgetL2
import HardyTheorem.SelbergSqrtZetaSignedRationalCoprimeRayCoeff
import HardyTheorem.SelbergSqrtZetaSignedRationalFourierBudget
import HardyTheorem.SelbergSqrtZetaSignedRationalShortKernelLocalSeparation
import HardyTheorem.SelbergSqrtZetaSignedRationalShortKernelSeparation

open HardyTheorem

#check thetaLagPhase
#check thetaLagReferenceFrequency
#check hasDerivAt_thetaLagPhase
#check deriv_thetaLagPhase_zero
#check thetaLagReferenceFrequency_eq
#check abs_deriv_thetaLagPhase_sub_referenceFrequency_le
#check abs_thetaLagPhase_sub_linearized_le
#check abs_thetaLagPhase_sub_linearized_le_window_sq
#check abs_cos_thetaLagPhase_sub_cos_linearized_le
#check abs_cos_thetaLagPhase_shift_sub_cos_frozen_le
#check abs_squareIntegral_cos_thetaLagPhase_le
#check abs_squareIntegral_cos_thetaLagPhase_shift_le
#check abs_squareIntegral_cos_thetaLagPhase_shift_le_stationaryEnvelope

#check exists_volume_selbergSqrtZetaExcessiveSignedMassStarts_inter_Icc_le_T_div_24_of_totalShiftBudgetL2_le

#check selbergSqrtZetaSignedDenominatorCollectedRealCoeff
#check selbergSqrtZetaSignedNumeratorRealCoeff
#check selbergSqrtZetaSignedDenominatorCollectedCoeff_re_eq
#check selbergSqrtZetaSignedNumeratorCoeff_re_eq
#check selbergSqrtZetaSignedRationalPairCoeff_coprimeRay_eq
#check selbergSqrtZetaSignedRationalPairCoeff_coprimeRay_eq_explicit
#check selbergSqrtZetaSignedRationalPairCoeff_coprimeRay_product_eq_explicit
#check selbergSqrtZetaSignedNumeratorRealCoeff_nonneg_iff
#check selbergSqrtZetaSignedNumeratorRealCoeff_nonpos_iff
#check selbergSqrtZetaSignedDenominator_bounds_of_mem
#check selbergSqrtZetaSignedCoprimeRayScales_pair_support_facts
#check selbergSqrtZetaSignedCoprimeRayScaleSupport
#check selbergSqrtZetaSignedCoprimeRayScales_mem_fixedScaleSupport
#check selbergSqrtZetaSignedCoprimeRayCorrelation_eq_sq_sub_diagonal

#check integral_normSq_selbergSqrtZetaSignedRationalShortModel_le_five_mul_modelL2Budget

#check selbergSqrtZetaSignedRationalFixedShiftPhaseSum
#check selbergSqrtZetaSignedRationalFixedShiftPhaseSum_eq_factorized
#check selbergSqrtZetaSignedRationalFixedShiftPhaseSum_eq_modelCorrelation
#check integral_normSq_selbergSqrtZetaSignedRationalShortModel_eq_re_fixedShiftPhaseSum
#check norm_integral_selbergSqrtZetaSignedRationalFixedShiftPhaseSum_le_localSeparation
#check norm_integral_integral_integral_selbergSqrtZetaSignedRationalFixedShiftPhaseSum_le_localSeparation
#check integral_normSq_selbergSqrtZetaSignedRationalShortModel_le_localSeparation

#check H_div_T_le_abs_frequency_sub_of_mem_ne
#check eq_of_mem_of_abs_frequency_sub_lt_H_div_T
#check norm_selbergSqrtZetaSignedRationalShortKernel_le_of_mem_ne
