import HardyTheorem.SelbergSqrtZetaRectangularParseval

#print axioms HardyTheorem.selbergSqrtZetaRectangularProductSupport_subset_collectedSupport
#print axioms HardyTheorem.selbergSqrtZetaShortDirichletCollectedCoeff_eq_zero_of_not_mem_rectangularProductSupport
#print axioms HardyTheorem.sum_normSq_selbergSqrtZetaShortDirichletCollectedCoeff_rectangularProductSupport_eq_signedRationalEnergy
#print axioms HardyTheorem.sum_normSq_selbergSqrtZetaShortDirichletCollectedCoeff_eq_signedRationalEnergy
#print axioms HardyTheorem.sum_normSq_sliding_selbergSqrtZetaShortDirichletCollectedCoeff_tail_le_logDecay_mul_signedRationalEnergy
