import HardyTheorem.SelbergSqrtZetaSignedRawEnergy
import HardyTheorem.SelbergSqrtZetaSignedPseudoFiberBudget
import HardyTheorem.SelbergSqrtZetaSignedRationalRealCollected
import HardyTheorem.SelbergSqrtZetaSignedDiagonalShiftBudget
import HardyTheorem.SelbergSqrtZetaSignedModelShiftDecomposition
import HardyTheorem.SelbergSqrtZetaSignedOrdinaryShiftBudget

open HardyTheorem

#check card_selbergSqrtZetaSignedPhaseSupport
#check card_selbergSqrtZetaSignedCollectedFrequencySupport_le
#check sum_sum_normSq_selbergSqrtZetaSignedPhaseCoeff_fibers
#check sum_selbergSqrtZetaSignedFrequencyFiberCard_mul_energy_le_raw
#check sum_sum_mul_norm_selbergSqrtZetaSignedCollectedCoeff_le_raw_energy

#check norm_integral_integral_integral_selbergSqrtZetaSignedComplexModel_mul_shift_le_fiber_budget

#check selbergSqrtZetaSignedRationalFrequency_injOn
#check selbergSqrtZetaSignedCollectedCoeff_rationalFrequency
#check image_rationalFrequency_rationalSupport
#check sum_normSq_collectedCoeff_eq_rationalCoeff

#check selbergSqrtZetaSignedDiagonalShiftKernel
#check integrable_selbergSqrtZetaSignedDiagonalShiftKernel
#check norm_integral_integral_integral_selbergSqrtZetaSignedCollectedCorrelationDiagonal_le_energy
#check norm_integral_integral_integral_selbergSqrtZetaSignedCollectedCorrelationDiagonal_le_rational_energy
#check norm_integral_integral_integral_selbergSqrtZetaSignedCollectedCorrelationDiagonal_le_fiber_budget

#check selbergSqrtZetaSignedOrdinaryShiftKernel
#check selbergSqrtZetaSignedThetaShiftKernel
#check integrable_selbergSqrtZetaSignedOrdinaryShiftKernel
#check integrable_selbergSqrtZetaSignedThetaShiftKernel
#check integral_selbergSqrtZetaSignedThetaShiftKernel_eq
#check abs_integral_integral_integral_selbergSqrtZetaSignedThetaModel_mul_shift_le

#check norm_integral_integral_integral_selbergSqrtZetaSignedOrdinaryCorrelation_le_energy
#check norm_integral_integral_integral_selbergSqrtZetaSignedOrdinaryCorrelation_le_rational_energy
#check norm_integral_integral_integral_selbergSqrtZetaSignedOrdinaryCorrelation_le
