import HardyTheorem.SelbergSqrtZetaSignedPhasePolynomial

#check HardyTheorem.selbergSqrtZetaSignedPhaseSupport
#check HardyTheorem.selbergSqrtZetaSignedPhaseCoeff
#check HardyTheorem.selbergSqrtZetaSignedPhaseFrequency
#check HardyTheorem.selbergSqrtZetaSignedTriplePolynomial
#check HardyTheorem.selbergSqrtZetaSignedPhasePolynomial
#check HardyTheorem.conj_selbergSqrtZetaMollifier_criticalLine_eq_sum
#check HardyTheorem.criticalLineDirichletPolynomial_mul_sqrtZetaMollifier_mul_conj_eq_signedTriplePolynomial
#check HardyTheorem.selbergSqrtZetaSignedPhasePolynomial_eq_exp_mul_signedTriplePolynomial
#check HardyTheorem.exp_I_thetaModel_mul_criticalLinePolynomial_mul_sqrtZetaMollifier_mul_conj_eq_signedPhasePolynomial

#print axioms HardyTheorem.conj_selbergSqrtZetaMollifier_criticalLine_eq_sum
#print axioms HardyTheorem.criticalLineDirichletPolynomial_mul_sqrtZetaMollifier_mul_conj_eq_signedTriplePolynomial
#print axioms HardyTheorem.selbergSqrtZetaSignedPhasePolynomial_eq_exp_mul_signedTriplePolynomial
#print axioms HardyTheorem.exp_I_thetaModel_mul_criticalLinePolynomial_mul_sqrtZetaMollifier_mul_conj_eq_signedPhasePolynomial
