import HardyTheorem.SelbergMollifiedTripleCollected

#check HardyTheorem.selbergMollifiedTripleKey
#check HardyTheorem.selbergMollifiedTripleCollectedSupport
#check HardyTheorem.selbergMollifiedTripleFiber
#check HardyTheorem.selbergMollifiedTripleCollectedCoeff
#check HardyTheorem.selbergMollifiedTripleCollectedFrequency
#check HardyTheorem.selbergMollifiedTripleCollectedPolynomial
#check HardyTheorem.selbergMollifiedTripleKey_pos_of_mem
#check HardyTheorem.selbergMollifiedTripleFrequency_eq_collectedFrequency_key
#check HardyTheorem.selbergMollifiedTripleKey_eq_imp_frequency_eq
#check HardyTheorem.selbergMollifiedTripleFrequency_eq_iff_key_eq
#check HardyTheorem.selbergMollifiedTriplePolynomial_eq_collectedPolynomial

#print axioms HardyTheorem.selbergMollifiedTripleKey_pos_of_mem
#print axioms HardyTheorem.selbergMollifiedTripleFrequency_eq_iff_key_eq
#print axioms HardyTheorem.selbergMollifiedTriplePolynomial_eq_collectedPolynomial
