import HardyTheorem.SelbergSqrtZetaExcessiveReducedPairEndpoint
import HardyTheorem.SelbergSqrtZetaSignedReducedPairCompleteMainTerm
import HardyTheorem.SelbergSqrtZetaSignedReducedPairCompleteCancellation
import HardyTheorem.SelbergSqrtZetaReducedPairSplitEnergyLowerBound
import HardyTheorem.SelbergSqrtZetaSignedRationalCarrierEnergy
import HardyTheorem.SelbergSqrtZetaSignedRationalNoncarrierEnergy
import HardyTheorem.SelbergSqrtZetaSignedReducedPairCompleteUnweighted

open HardyTheorem

#check selbergSqrtZetaSignedReducedPairSplitEnergy
#check selbergSqrtZetaSignedReducedPairShortModelBudget
#check selbergSqrtZetaSignedReducedPairShortModelBudget_le_of_splitEnergy_le
#check integral_normSq_selbergSqrtZetaSignedRationalShortModel_le_reducedPairBudget
#check exists_integral_sq_selbergSqrtZetaSignedShortIntegral_le_reducedPairBudget_add_error
#check exists_volume_selbergSqrtZetaExcessiveSignedMassStarts_inter_Icc_le_T_div_24_of_reducedPairBudget_le
#check exists_volume_selbergSqrtZetaExcessiveSignedMassStarts_inter_Icc_le_T_div_24_of_reducedPairSplitEnergy_le

#check selbergSqrtZetaSignedReducedRayCompleteWeight_eq_min_coordinateWeights
#check sum_selbergSqrtZetaSignedReducedPairCompleteEnergy_eq_min_coordinateWeights
#check sum_selbergSqrtZetaSignedReducedPairCompleteEnergy_le_denominatorCoordinateBudget
#check sum_selbergSqrtZetaSignedReducedPairCompleteEnergy_le_numeratorCoordinateBudget

#check selbergSqrtZetaCompleteIndexSupport
#check selbergSqrtZetaCompletePairSupport
#check selbergSqrtZetaCompleteRatioKey
#check selbergSqrtZetaCompleteProductKey
#check selbergSqrtZetaCompleteRatioSupport
#check selbergSqrtZetaCompleteProductSupport
#check selbergSqrtZetaCompleteRatioFiber
#check selbergSqrtZetaCompleteProductFiber
#check selbergSqrtZetaCompleteNumeratorCoeff
#check selbergSqrtZetaCompleteDenominatorCoeff
#check selbergSqrtZetaCompletePairCoeff
#check selbergSqrtZetaCompleteRatioCoeff
#check selbergSqrtZetaCompleteProductCoeff
#check sum_sq_selbergSqrtZetaCompleteRatioCoeff_eq_productCoeff
#check selbergSqrtZetaCompleteRatioCoeff_reduced_eq_completeTerm
#check selbergSqrtZetaCompleteProductCoeff_eq_collected_div_sqrt
#check selbergSqrtZetaCompleteProductHighEnergy
#check sum_sq_selbergSqrtZetaCompleteProductCoeff_le_nineteen_fourths_add_high
#check sum_selbergSqrtZetaSignedReducedPairCompletePlainEnergy_le_nineteen_fourths_add_high
#check sum_selbergSqrtZetaSignedReducedPairCompleteEnergy_le_productEnergy
#check sum_selbergSqrtZetaSignedReducedPairCompleteEnergy_le_nineteen_fourths_add_high

#check two_le_selbergSqrtZetaSignedReducedPairSplitEnergy
#check not_selbergSqrtZetaSignedReducedPairSplitEnergy_le_one_div_768

#check selbergSqrtZetaCompleteRatioCoeff_one_eq_diagonal
#check selbergSqrtZetaCompleteRatioCoeff_one_eq_tapered_diagonal
#check abs_selbergSqrtZetaCompleteRatioCoeff_one_le_harmonic
#check selbergSqrtZetaSignedReducedRayBoundaryTerm_one_one_eq_zero
#check selbergSqrtZetaSignedRationalCoeff_one_eq_completeRatioCoeff
#check norm_selbergSqrtZetaSignedRationalCoeff_one_le_one_add_log
#check norm_selbergSqrtZetaSignedRationalCarrier_le_one_add_log_mul_thirtytwo_div_log
#check norm_selbergSqrtZetaSignedRationalShortModel_le_log_carrier_add_noncarrier
#check normSq_selbergSqrtZetaSignedRationalCoeff_one_le_nineteen_fourths_add_high

#check selbergSqrtZetaSignedRationalNoncarrierPolynomial
#check image_selbergSqrtZetaSignedReducedPairKey_reducedPairSupport_erase_one
#check sum_selbergSqrtZetaSignedRationalNoncarrierSupport_eq_reducedPairSupport_erase_one
#check sum_normSq_noncarrier_eq_reducedPairSupport_erase_one
#check sum_normSq_div_fullLocalSeparation_noncarrier_eq_reducedPairSupport_erase_one
#check sum_normSq_div_localFrequencySeparation_noncarrier_le_erase_full
#check noncarrierEnergy_add_carrierEnergy_le_fullEnergy
#check integral_normSq_selbergSqrtZetaSignedRationalNoncarrierPolynomial_le_localSeparation

#check selbergSqrtZetaCompleteRatioSupport_subset_signedRationalSupport
#check sum_selbergSqrtZetaSignedReducedPairCompleteUnweighted_erase_one_add_carrier_eq_productEnergy
#check sum_selbergSqrtZetaSignedReducedPairCompleteUnweighted_erase_one_eq_productEnergy_sub_carrier
#check sum_selbergSqrtZetaSignedReducedPairCompleteUnweighted_erase_one_le_productEnergy
