import HardyTheorem.SelbergSqrtZetaSignedRationalCoefficientReducedPairEnergy

#print axioms HardyTheorem.sum_normSq_selbergSqrtZetaSignedRationalCoeff_eq_reducedPairEnergy
#print axioms HardyTheorem.sum_normSq_selbergSqrtZetaSignedRationalCoeff_le_reducedPairComplete_add_boundary
