import HardyTheorem.SelbergSqrtZetaSignedReducedPairCompleteUnweighted

#print axioms HardyTheorem.selbergSqrtZetaCompleteRatioSupport_subset_signedRationalSupport
#print axioms HardyTheorem.sum_selbergSqrtZetaSignedReducedPairCompleteUnweighted_erase_one_add_carrier_eq_productEnergy
#print axioms HardyTheorem.sum_selbergSqrtZetaSignedReducedPairCompleteUnweighted_erase_one_eq_productEnergy_sub_carrier
#print axioms HardyTheorem.sum_selbergSqrtZetaSignedReducedPairCompleteUnweighted_erase_one_le_productEnergy
