import HardyTheorem.SelbergSqrtZetaShortExpansion

#print axioms HardyTheorem.norm_selbergSqrtZetaMollifier_criticalLine_le_majorant
#print axioms HardyTheorem.criticalLineDirichletPolynomial_mul_sqrtZetaMollifier_sq_eq_tripleSum
#print axioms HardyTheorem.criticalLineDirichletPolynomial_mul_sqrtZetaMollifier_sq_eq_exponentialPolynomial
#print axioms HardyTheorem.exists_selbergSqrtZetaMollifiedZetaFirstApprox
#print axioms HardyTheorem.selbergSqrtZetaShortDirichletTriplePolynomial_eq_collectedPolynomial
#print axioms HardyTheorem.selbergSqrtZetaShortDirichletCollectedCoeff_one
#print axioms HardyTheorem.selbergSqrtZetaShortDirichletCollectedPolynomial_sub_one_eq
#print axioms HardyTheorem.selbergSqrtZetaMollifiedShortDirichletPolynomial_eq_slidingCollected
#print axioms HardyTheorem.integral_normSq_selbergSqrtZetaMollifiedShortDirichletPolynomial_le_gapSum
