import HardyTheorem.SelbergMollifiedTripleMeanSquare

#check HardyTheorem.selbergMollifiedTripleCollectedKey_pos_of_mem
#check HardyTheorem.selbergMollifiedTripleCollectedFrequency_injective_on_support
#check HardyTheorem.one_mem_selbergMollifiedTripleCollectedSupport
#check HardyTheorem.selbergMollifiedTripleCollectedPolynomial_sub_constant_eq
#check HardyTheorem.selbergMollifiedTripleNonconstantShortIntegral_eq_sliding
#check HardyTheorem.integral_normSq_selbergMollifiedTripleNonconstantShortIntegral_le

#print axioms HardyTheorem.selbergMollifiedTripleCollectedPolynomial_sub_constant_eq
#print axioms HardyTheorem.integral_normSq_selbergMollifiedTripleNonconstantShortIntegral_le
