import HardyTheorem.SelbergSqrtZetaComparableNearDiagonalSchur

#print axioms HardyTheorem.sum_inv_natDist_Ioc_le_two_mul_harmonic
#print axioms HardyTheorem.sum_comparable_max_div_natDist_le_four_mul_self_mul_harmonic
#print axioms HardyTheorem.comparableNearDiagonalSquareSum_le_weightedHarmonic
#print axioms HardyTheorem.selbergSqrtZetaComparableNearDiagonalSquareBudget_le_weightedHarmonic
#print axioms HardyTheorem.selbergSqrtZetaComparableNearDiagonalSquareBudget_le_globalHarmonic
#print axioms HardyTheorem.selbergSqrtZetaComparableNearDiagonalSquareBudget_le_globalLog
