import HardyTheorem.SelbergSqrtZetaSignedRationalLocalSeparationArithmetic

#print axioms HardyTheorem.one_div_nat_mul_sq_le_localFrequencySeparation_of_mem_rationalSupport
#print axioms HardyTheorem.sum_normSq_div_localFrequencySeparation_le_arithmeticEnergy
#print axioms HardyTheorem.integral_normSq_rationalCollectedPolynomial_le_arithmeticEnergy
