import HardyTheorem.SelbergSqrtZetaSignedRationalFourierTransfer

#print axioms HardyTheorem.integrable_selbergSqrtZetaSignedTruncatedPhase
#print axioms HardyTheorem.memLp_two_selbergSqrtZetaSignedTruncatedPhase
#print axioms HardyTheorem.integral_selbergSqrtZetaSignedTruncatedPhase_eq_rationalShortModel
#print axioms HardyTheorem.integral_normSq_selbergSqrtZetaSignedRationalShortModel_le_fourier_low_high
