import HardyTheorem.SelbergSqrtZetaSignedRationalCoprimeRayReindex

#print axioms HardyTheorem.selbergSqrtZetaSignedCoprimeRayScales_coprime
#print axioms HardyTheorem.selbergSqrtZetaSignedCoprimeRayScales_denominator_pos
#print axioms HardyTheorem.selbergSqrtZetaSignedCoprimeRayScales_scale_facts
#print axioms HardyTheorem.selbergSqrtZetaSignedRationalCoefficientOffDiagonal_eq_coprimeRayScaleSum
#print axioms HardyTheorem.sum_normSq_selbergSqrtZetaSignedRationalCoeff_eq_product_add_coprimeRayScaleSum
