import HardyTheorem.SelbergSqrtZetaSignedCompleteDenominator

#print axioms HardyTheorem.zeta_mul_selbergSqrtZetaLogCoeff
#print axioms HardyTheorem.selbergSqrtZetaSignedDenominatorFiber_eq_divisorsAntidiagonal
#print axioms HardyTheorem.sum_selbergSqrtZetaSignedDenominatorFiber_eq_zeta_mul
#print axioms HardyTheorem.selbergSqrtZetaSignedDenominatorArithmeticCoeff_eq_zeta_mul
#print axioms HardyTheorem.selbergSqrtZetaSignedCoprimeRayBilinearScaleSum_eq_complete_zeta_add_boundary
#print axioms HardyTheorem.selbergSqrtZetaSignedCoprimeRayComplete_singleLog_eq_logRatio
#print axioms HardyTheorem.selbergSqrtZetaSignedCoprimeRayComplete_singleLog_diagonal_eq_zero
