import HardyTheorem.SelbergSqrtZetaExcessiveTotalBudget

#print axioms HardyTheorem.integral_sq_selbergSqrtZetaSignedShortIntegral_eq_fixedShiftSquare
#print axioms HardyTheorem.exists_volume_selbergSqrtZetaExcessiveSignedMassStarts_inter_Icc_le_T_div_24_of_totalShiftBudget_le
#print axioms HardyTheorem.exists_volume_selbergSqrtZetaExcessiveSignedMassStarts_inter_Icc_le_T_div_24_of_totalShiftBudget_modelSupBound_le
