import HardyTheorem.SelbergUniformWindowFourierMass

namespace HardyTheorem

#check exists_abs_selbergJ_le_uniform_unit_window
#check exists_integral_normSq_selbergPhysicalThetaKernel_low_le_uniform_unit_window
#check exists_integral_normSq_selbergPhysicalThetaKernel_high_le_uniform_unit_window
#check exists_integral_normSq_selbergNonconstantInverseFourierKernel_low_le_uniform_unit_window
#check exists_integral_normSq_selbergNonconstantInverseFourierKernel_high_le_uniform_unit_window

#print axioms exists_abs_selbergJ_le_uniform_unit_window
#print axioms exists_integral_normSq_selbergPhysicalThetaKernel_low_le_uniform_unit_window
#print axioms exists_integral_normSq_selbergPhysicalThetaKernel_high_le_uniform_unit_window
#print axioms exists_integral_normSq_selbergNonconstantInverseFourierKernel_low_le_uniform_unit_window
#print axioms exists_integral_normSq_selbergNonconstantInverseFourierKernel_high_le_uniform_unit_window

end HardyTheorem
