import HardyTheorem.SelbergSqrtZetaComparableNearDiagonal

#print axioms HardyTheorem.inv_abs_log_nat_sub_log_nat_le_max_div_dist
#print axioms HardyTheorem.selbergSqrtZetaComparableGapBudget_le_nearDiagonal
#print axioms HardyTheorem.selbergSqrtZetaComparableNearDiagonalBudget_le_square
#print axioms HardyTheorem.selbergSqrtZeta_frequencyGap_le_nearDiagonalSquare_add_far
#print axioms HardyTheorem.selbergSqrtZetaShortDirichletGapSum_le_nearDiagonalSquare_add_far
