import HardyTheorem.SelbergSqrtZetaSignedActualFourierBudget
import HardyTheorem.SelbergSqrtZetaSignedCoprimeRayLogExpansion

open HardyTheorem

#check exists_integral_sq_selbergSqrtZetaSignedShortIntegral_le_modelL2Budget_add_error

#check selbergSqrtZetaSignedDenominatorArithmeticCoeff
#check selbergSqrtZetaSignedCoprimeRayBilinearScaleSum
#check selbergSqrtZetaSignedDenominatorCollectedRealCoeff_eq_invSqrt_mul_arithmeticCoeff
#check selbergSqrtZetaSignedRationalPairCoeff_coprimeRay_eq_invSqrt_mul_invScale
#check selbergSqrtZetaSignedCoprimeRayScaleSum_eq_invSqrt_mul_bilinearScaleSum
#check selbergSqrtZetaTaperedCoeff_eq_coeff_sub_invLog_mul_logCoeff
#check selbergSqrtZetaSignedCoprimeRayBilinearScaleSum_taper_eq_logExpansion
#check selbergSqrtZetaSignedCoprimeRayScaleSum_eq_invSqrt_mul_logExpansion
