import HardyTheorem.SelbergSqrtZetaSignedRationalCoefficientEnergySharp

#print axioms HardyTheorem.selbergSqrtZetaSignedRationalCoeff_re_eq_pairSum
#print axioms HardyTheorem.sum_normSq_selbergSqrtZetaSignedRationalCoeff_eq_crossProduct
#print axioms HardyTheorem.sum_normSq_selbergSqrtZetaSignedRationalPairCoeff_eq_product
#print axioms HardyTheorem.sum_normSq_selbergSqrtZetaSignedRationalCoeff_eq_product_add_offDiagonal
#print axioms HardyTheorem.sum_normSq_selbergSqrtZetaSignedRationalCoeff_le_product_add_abs_offDiagonal
