import HardyTheorem.SelbergSignedMassSecondMoment

#print axioms HardyTheorem.selbergSignedShortIntegral_eq_slidingWindowMass
#print axioms HardyTheorem.continuous_selbergSignedShortIntegral
#print axioms HardyTheorem.integral_sq_signedShortIntegral_eq_correlation
#print axioms HardyTheorem.volume_selbergExcessiveSignedMassStarts_inter_Icc_le_signedSecondMoment
#print axioms HardyTheorem.volume_selbergExcessiveSignedMassStarts_inter_Icc_le_T_div_24_of_correlation_le
