import HardyTheorem.SelbergSqrtZetaSignedModelContinuity

#print axioms HardyTheorem.continuousOn_selbergSqrtZetaSignedThetaModel_Icc_of_pos
#print axioms HardyTheorem.continuousOn_selbergSqrtZetaSignedThetaModel_Icc_T_two_mul_T
