import HardyTheorem.SelbergMollifiedDirichlet

open Complex

namespace HardyTheorem

#check selbergMollifiedDirichletPairs
#check selbergMollifiedDirichletCoeff
#check criticalLineDirichletPolynomial_mul_selbergMoebiusMollifier_eq_doubleSum
#check criticalLineDirichletPolynomial_mul_selbergMoebiusMollifier_eq_convolutionSum
#check selbergMollifiedDirichletCoeff_eq_zero_of_not_mem
#check abs_selbergMollifiedDirichletCoeff_le_card_divisorsAntidiagonal

#print axioms criticalLineDirichletPolynomial_mul_selbergMoebiusMollifier_eq_doubleSum
#print axioms criticalLineDirichletPolynomial_mul_selbergMoebiusMollifier_eq_convolutionSum
#print axioms abs_selbergMollifiedDirichletCoeff_le_card_divisorsAntidiagonal

end HardyTheorem
