import HardyTheorem.SelbergSqrtZetaSignedRationalShortKernelPhase

#print axioms HardyTheorem.deriv_selbergSqrtZetaSignedRationalShortKernelPhase
#print axioms HardyTheorem.iteratedDeriv_two_selbergSqrtZetaSignedRationalShortKernelPhase
#print axioms HardyTheorem.abs_deriv_selbergSqrtZetaSignedRationalShortKernelPhase_sub_frequencyGap_le
#print axioms HardyTheorem.half_abs_frequencyGap_le_abs_deriv_selbergSqrtZetaSignedRationalShortKernelPhase
#print axioms HardyTheorem.norm_integral_cexp_selbergSqrtZetaSignedRationalShortKernelPhase_le_of_frequencyGap
