import HardyTheorem.SelbergSqrtZetaExcessiveArithmeticEndpoint
import HardyTheorem.SelbergSqrtZetaSignedCompleteDenominator
import HardyTheorem.SelbergSqrtZetaSignedRationalCoeffCoprimeRayReindex

open HardyTheorem

#check exists_volume_selbergSqrtZetaExcessiveSignedMassStarts_inter_Icc_le_T_div_24_of_modelEnergy_le

#check zeta_mul_selbergSqrtZetaLogCoeff
#check selbergSqrtZetaSignedDenominatorFiber_eq_divisorsAntidiagonal
#check sum_selbergSqrtZetaSignedDenominatorFiber_eq_zeta_mul
#check selbergSqrtZetaSignedDenominatorArithmeticCoeff_eq_zeta_mul
#check selbergSqrtZetaSignedCoprimeRayCompleteScaleSupport
#check selbergSqrtZetaSignedCoprimeRayBoundaryScaleSupport
#check selbergSqrtZetaSignedCoprimeRayBilinearScaleSum_eq_complete_zeta_add_boundary
#check selbergSqrtZetaSignedCoprimeRayComplete_singleLog_eq_logRatio
#check selbergSqrtZetaSignedCoprimeRayComplete_singleLog_diagonal_eq_zero

#check selbergSqrtZetaSignedRationalCoeff_reduced_eq_coprimeRayScaleSum
