import HardyTheorem.SelbergSqrtZetaSignedRationalCarrierEnergy

#check HardyTheorem.sum_range_selbergSqrtZetaLocalCoeff_eq
#check HardyTheorem.abs_sum_range_selbergSqrtZetaLocalCoeff_le_one
#check HardyTheorem.zeta_mul_selbergSqrtZetaCoeff_apply_prime_pow
#check HardyTheorem.abs_zeta_mul_selbergSqrtZetaCoeff_le_one
#check HardyTheorem.selbergSqrtZetaCompleteRatioCoeff_one_eq_diagonal
#check HardyTheorem.selbergSqrtZetaCompleteRatioCoeff_one_eq_tapered_diagonal
#check HardyTheorem.abs_selbergSqrtZetaCompleteRatioCoeff_one_le_harmonic
#check HardyTheorem.selbergSqrtZetaSignedReducedRayBoundaryTerm_one_one_eq_zero
#check HardyTheorem.selbergSqrtZetaSignedRationalCoeff_one_eq_completeRatioCoeff
#check HardyTheorem.norm_selbergSqrtZetaSignedRationalCoeff_one_le_one_add_log
#check HardyTheorem.norm_selbergSqrtZetaSignedRationalCarrier_le_one_add_log_mul_thirtytwo_div_log
#check HardyTheorem.norm_selbergSqrtZetaSignedRationalShortModel_le_log_carrier_add_noncarrier
#check HardyTheorem.normSq_selbergSqrtZetaSignedRationalCoeff_one_le_nineteen_fourths_add_high
