import HardyTheorem.SelbergSqrtZetaCollectedArithmetic

#print axioms HardyTheorem.two_mul_selbergSqrtZeta_mul_logCoeff
#print axioms HardyTheorem.selbergMoebiusLogCoeff_mul_zeta
#print axioms HardyTheorem.selbergSqrtZetaCoeff_sq_mul_zeta
#print axioms HardyTheorem.four_mul_selbergSqrtZetaLogCoeff_sq_mul_zeta
#print axioms HardyTheorem.selbergSqrtZetaFullTapered_apply
#print axioms HardyTheorem.selbergSqrtZetaScaledTapered_apply
#print axioms HardyTheorem.selbergSqrtZetaScaledTapered_collected
#print axioms HardyTheorem.selbergSqrtZetaScaledTapered_eq_log_smul
#print axioms HardyTheorem.selbergSqrtZetaFullTapered_collected_denominator_free
#print axioms HardyTheorem.selbergSqrtZetaFullTapered_collected
#print axioms HardyTheorem.selbergShortTaperedSqrtZeta_eq_full_of_le
#print axioms HardyTheorem.selbergShortTaperedSqrtZeta_sq_eq_full_sq_of_le
#print axioms HardyTheorem.selbergShortTaperedSqrtZeta_collected_eq_full_of_le
#print axioms HardyTheorem.selbergShortTaperedSqrtZeta_collected_apply_of_le
