import HardyTheorem.SelbergSqrtZetaSmallAbsGapBound

#print axioms HardyTheorem.exists_selbergSqrtZetaAbsShortIntegral_ge_sub_mollifiedPolynomial
#print axioms HardyTheorem.exists_volume_selbergSqrtZetaSmallAbsoluteMassStarts_inter_Icc_le_gapSum
