import HardyTheorem.SelbergSqrtZetaSignedRationalReducedSeparation

#check HardyTheorem.one_div_one_add_X_mul_min_le_abs_sub_frequency_reduced_of_mem
#check HardyTheorem.one_div_one_add_X_mul_min_le_localFrequencySeparation_reduced
#check HardyTheorem.one_div_localFrequencySeparation_le_one_add_X_mul_min_reduced
#check HardyTheorem.normSq_div_localFrequencySeparation_le_reducedWeight
