import HardyTheorem.SelbergSqrtZetaCollectedWeightedEnergy

#print axioms HardyTheorem.card_selbergShortDirichletTriples_le_sq
#print axioms HardyTheorem.mul_normSq_selbergSqrtZetaShortDirichletCollectedCoeff_le_sq_sq
#print axioms HardyTheorem.sum_mul_normSq_selbergSqrtZetaShortDirichletCollectedCoeff_le_mul_sq_sq
#print axioms HardyTheorem.sum_mul_normSq_selbergSqrtZetaShortDirichletCollectedCoeff_le_mul_pow_six
