import HardyTheorem.SelbergShortTopRangeVanishing

namespace Test.SelbergShortTopRangeVanishingContract

#check HardyTheorem.selbergMoebiusCoeff_self_eq_zero
#check HardyTheorem.selbergShortDirichletCollectedCoeff_eq_zero_of_topRange
#check HardyTheorem.sliding_selbergShortDirichletCollectedCoeff_eq_zero_of_topRange
#check HardyTheorem.sum_normSq_sliding_selbergShortDirichletCollectedCoeff_eq_effectiveSupport

#print axioms HardyTheorem.selbergMoebiusCoeff_self_eq_zero
#print axioms HardyTheorem.selbergShortDirichletCollectedCoeff_eq_zero_of_topRange
#print axioms HardyTheorem.sum_normSq_sliding_selbergShortDirichletCollectedCoeff_eq_effectiveSupport

end Test.SelbergShortTopRangeVanishingContract
