import HardyTheorem.SelbergSqrtZetaRectangularParseval

#check HardyTheorem.selbergSqrtZetaRectangularProductSupport
#check HardyTheorem.selbergSqrtZetaRectangularProductSupport_subset_collectedSupport
#check HardyTheorem.selbergSqrtZetaShortDirichletCollectedCoeff_eq_zero_of_not_mem_rectangularProductSupport
#check HardyTheorem.sum_normSq_selbergSqrtZetaShortDirichletCollectedCoeff_rectangularProductSupport_eq_signedRationalEnergy
#check HardyTheorem.sum_normSq_selbergSqrtZetaShortDirichletCollectedCoeff_eq_signedRationalEnergy

