import HardyTheorem.SelbergJPairAlgebra

open HardyTheorem

#check selbergPhysicalGaussianTerm
#check selbergPhysicalSquareRatio
#check selbergPhysicalPairDamping
#check selbergPhysicalPairSignedFrequency
#check selbergPhysicalPairIntegrand
#check selbergGaussianThetaTerm_log_eq_physical
#check selbergPhysicalGaussian_mul_conj_eq_pairIntegrand
#check selbergPhysicalPairSignedFrequency_neg_of_forward
#check selbergPhysicalPairSignedFrequency_pos_of_reverse
#check selbergPhysicalPairIntegrand_forward_eq_conj_normalized
#check selbergPhysicalPairIntegrand_reverse_eq_normalized
#check selbergPhysicalPairDamping_pos
#check selbergPhysicalPairGapFrequency_pos_of_forward
#check norm_integral_Ioi_selbergPhysicalPairIntegrand_forward_le
#check norm_integral_Ioi_selbergPhysicalPairIntegrand_reverse_le
