import HardyTheorem.SelbergSqrtZetaMixedProductTailReducedPair

open HardyTheorem

#check selbergSqrtZetaRectangularProductKey
#check selbergSqrtZetaRectangularProductSupport
#check selbergSqrtZetaRectangularRawCoeff
#check selbergSqrtZetaRectangularMixedProductKey
#check selbergSqrtZetaSignedRationalMixedProductTailEnergy
#check selbergSqrtZetaSignedRationalBoundaryTaperSummand
#check selbergSqrtZetaSignedRationalBoundaryTaperBudget

#check selbergSqrtZetaRectangularProductSupport_subset_collectedSupport
#check selbergSqrtZetaShortDirichletCollectedCoeff_eq_zero_of_not_mem_rectangularProductSupport
#check sum_normSq_selbergSqrtZetaShortDirichletCollectedCoeff_rectangularProductSupport_eq_signedRationalEnergy
#check sum_normSq_selbergSqrtZetaShortDirichletCollectedCoeff_eq_signedRationalEnergy
#check sum_normSq_sliding_selbergSqrtZetaShortDirichletCollectedCoeff_tail_le_logDecay_mul_signedRationalEnergy
#check sum_normSq_selbergSqrtZetaShortDirichletCollectedCoeff_rectangularProductTail_eq_signedRationalMixedProductTailEnergy
#check sum_normSq_selbergSqrtZetaShortDirichletCollectedCoeff_tail_eq_signedRationalMixedProductTailEnergy
#check sum_normSq_sliding_selbergSqrtZetaShortDirichletCollectedCoeff_tail_le_logDecay_mul_signedRationalMixedProductTailEnergy
#check sum_normSq_lowProduct_add_signedRationalMixedProductTailEnergy_eq_signedRationalEnergy
#check selbergSqrtZetaSignedRationalMixedProductTailEnergy_eq_signedRationalEnergy_sub_lowProduct
#check selbergSqrtZetaSignedRationalMixedProductTailEnergy_nonneg
#check selbergSqrtZetaSignedRationalMixedProductTailEnergy_antitone_cutoff
#check selbergSqrtZetaSignedRationalMixedProductTailEnergy_le_reducedPairComplete_add_boundary_sub_lowProduct
#check selbergSqrtZetaSignedRationalMixedProductTailEnergy_le_completeProductHigh_add_boundary_sub_lowProduct
#check sum_selbergSqrtZetaSignedReducedPairCompletePlainEnergy_le_nineteen_fourths_add_high
#check sum_inv_Ioc_eq_harmonic_sub
#check selbergSqrtZetaSignedRationalReducedPairSupport_coordinate_bounds
#check sum_inv_boundaryScaleIoc_le_harmonic_div
#check selbergSqrtZetaSignedRationalBoundaryTaperSummand_le_harmonicRay
#check selbergSqrtZetaSignedRationalBoundaryTaperBudget_eq_filter_numerator_lt_denominator
#check selbergSqrtZetaSignedRationalBoundaryTaperBudget_le_harmonicRaySum
#check selbergSqrtZetaSignedRationalBoundaryTaperBudget_le_harmonicPolynomial
#check selbergSqrtZetaSignedRationalBoundaryTaperBudget_le_logPolynomial
#check sum_selbergSqrtZetaSignedRationalBoundaryPlain_le_boundaryTaperBudget
#check selbergSqrtZetaSignedRationalMixedProductTailEnergy_le_completeProductHigh_add_boundaryTaper_sub_lowProduct
