import HardyTheorem.SelbergSqrtZetaShortCollected

#print axioms HardyTheorem.selbergSqrtZetaShortDirichletCollectedCoeff_eq_pairSum
#print axioms HardyTheorem.selbergSqrtZetaShortCompleteRangePairSum_eq_arithmetic
#print axioms HardyTheorem.selbergSqrtZetaShortDirichletCollectedCoeff_eq_arithmetic
#print axioms HardyTheorem.selbergSqrtZetaShortDirichletCollectedCoeff_eq_lowRange
#print axioms HardyTheorem.sum_normSq_sliding_selbergSqrtZetaShortDirichletCollectedCoeff_lowRange_le
#print axioms HardyTheorem.sum_normSq_sliding_selbergSqrtZetaShortDirichletCollectedCoeff_le_lowRange_add_highRange
