import HardyTheorem.SelbergSqrtZetaLowRangeSliding

#print axioms HardyTheorem.selbergSqrtZetaArithmeticDirichletCoeff_eq_lowRange
#print axioms HardyTheorem.normSq_selbergSqrtZetaLowRangeDirichletCoeff
#print axioms HardyTheorem.sum_normSq_selbergSqrtZetaLowRangeDirichletCoeff_le_fifteen_fourths
#print axioms HardyTheorem.normSq_slidingExponentialCoefficient_le_mul_sq
#print axioms HardyTheorem.sum_normSq_sliding_selbergSqrtZetaLowRangeDirichletCoeff_le
