import HardyTheorem.SelbergSqrtZetaSignedRationalShortKernelPhase

#check HardyTheorem.deriv_selbergSqrtZetaSignedRationalShortKernelPhase
#check HardyTheorem.abs_deriv_selbergSqrtZetaSignedRationalShortKernelPhase_sub_frequencyGap_le
#check HardyTheorem.half_abs_frequencyGap_le_abs_deriv_selbergSqrtZetaSignedRationalShortKernelPhase
#check HardyTheorem.iteratedDeriv_two_selbergSqrtZetaSignedRationalShortKernelPhase
#check HardyTheorem.norm_integral_cexp_selbergSqrtZetaSignedRationalShortKernelPhase_le_of_frequencyGap
