import HardyTheorem.SelbergShortHighRangeEnergy

namespace Test.SelbergShortHighRangeEnergyContract

#check HardyTheorem.selbergShortCollectedPairFiberEnergy
#check HardyTheorem.normSq_sliding_selbergShortDirichletCollectedCoeff_le_pairFiber_mul_min_sq
#check HardyTheorem.normSq_sliding_selbergShortDirichletCollectedCoeff_le_pairFiber_div_log
#check HardyTheorem.sum_normSq_sliding_selbergShortDirichletCollectedCoeff_highRange_le_pairFiber_mul_min_sq
#check HardyTheorem.sum_normSq_sliding_selbergShortDirichletCollectedCoeff_highRange_le_pairFiber_div_log
#check HardyTheorem.sum_normSq_sliding_selbergShortDirichletCollectedCoeff_le_lowRange_add_pairFiberMinHighRange
#check HardyTheorem.sum_normSq_sliding_selbergShortDirichletCollectedCoeff_le_lowRange_add_pairFiberHighRange

#print axioms HardyTheorem.normSq_sliding_selbergShortDirichletCollectedCoeff_le_pairFiber_mul_min_sq
#print axioms HardyTheorem.normSq_sliding_selbergShortDirichletCollectedCoeff_le_pairFiber_div_log
#print axioms HardyTheorem.sum_normSq_sliding_selbergShortDirichletCollectedCoeff_le_lowRange_add_pairFiberMinHighRange
#print axioms HardyTheorem.sum_normSq_sliding_selbergShortDirichletCollectedCoeff_le_lowRange_add_pairFiberHighRange

end Test.SelbergShortHighRangeEnergyContract
