import HardyTheorem.SelbergSqrtZetaSignedRationalCarrierEnergy

#print axioms HardyTheorem.sum_range_selbergSqrtZetaLocalCoeff_eq
#print axioms HardyTheorem.abs_sum_range_selbergSqrtZetaLocalCoeff_le_one
#print axioms HardyTheorem.zeta_mul_selbergSqrtZetaCoeff_apply_prime_pow
#print axioms HardyTheorem.abs_zeta_mul_selbergSqrtZetaCoeff_le_one
#print axioms HardyTheorem.selbergSqrtZetaCompleteRatioCoeff_one_eq_diagonal
#print axioms HardyTheorem.selbergSqrtZetaCompleteRatioCoeff_one_eq_tapered_diagonal
#print axioms HardyTheorem.abs_selbergSqrtZetaCompleteRatioCoeff_one_le_harmonic
#print axioms HardyTheorem.selbergSqrtZetaSignedReducedRayBoundaryTerm_one_one_eq_zero
#print axioms HardyTheorem.selbergSqrtZetaSignedRationalCoeff_one_eq_completeRatioCoeff
#print axioms HardyTheorem.norm_selbergSqrtZetaSignedRationalCoeff_one_le_one_add_log
#print axioms HardyTheorem.norm_selbergSqrtZetaSignedRationalCarrier_le_one_add_log_mul_thirtytwo_div_log
#print axioms HardyTheorem.norm_selbergSqrtZetaSignedRationalShortModel_le_log_carrier_add_noncarrier
#print axioms HardyTheorem.normSq_selbergSqrtZetaSignedRationalCoeff_one_le_nineteen_fourths_add_high
