import HardyTheorem.SelbergSqrtZetaSignedCollectedEnergy

#print axioms HardyTheorem.sum_normSq_selbergSqrtZetaSignedCollectedCoeff_le_fiber_budget
#print axioms HardyTheorem.norm_selbergSqrtZetaSignedCollectedCorrelationDiagonal_le_energy
#print axioms HardyTheorem.norm_selbergSqrtZetaSignedCollectedCorrelationDiagonal_le_fiber_budget
