import HardyTheorem.SelbergSqrtZetaSignedCollectedPhase

#print axioms HardyTheorem.selbergSqrtZetaSignedCollectedTriplePolynomial_eq_signedTriplePolynomial
#print axioms HardyTheorem.selbergSqrtZetaSignedPhasePolynomial_eq_exp_mul_collectedTriplePolynomial
#print axioms HardyTheorem.selbergSqrtZetaSignedComplexModel_eq_exp_mul_exp_mul_collectedTriplePolynomial
