import HardyTheorem.SelbergSqrtZetaSignedRationalReducedPairEnergy

#print axioms HardyTheorem.sum_normSq_div_localFrequencySeparation_le_reducedPairBilinearEnergy
#print axioms HardyTheorem.sum_normSq_div_localFrequencySeparation_le_reducedPairCompleteBoundaryEnergy
#print axioms HardyTheorem.sum_normSq_div_localFrequencySeparation_le_reducedPairComplete_add_boundary
