import HardyTheorem.SelbergSqrtZetaRestrictedPairMomentBound

#print axioms HardyTheorem.sum_selbergShortRestrictedPairProductMultiplicity_mul_inv_eq_harmonic_sq
#print axioms HardyTheorem.totientSquares_selbergShortRestrictedPairProductMultiplicity_le
#print axioms HardyTheorem.weighted_highRange_selbergShortCompleteRangePairs_le_logPolynomial
#print axioms HardyTheorem.sum_normSq_sliding_selbergSqrtZetaShortDirichletCollectedCoeff_le_lowRange_add_logPolynomialHighRange
