import HardyTheorem.SelbergSqrtZetaSignedRationalShortKernelLocalSeparation

#check HardyTheorem.selbergSqrtZetaSignedRationalFixedShiftPhaseSum
#check HardyTheorem.selbergSqrtZetaSignedRationalFixedShiftPhaseSum_eq_factorized
#check HardyTheorem.selbergSqrtZetaSignedRationalFixedShiftPhaseSum_eq_modelCorrelation
#check HardyTheorem.integral_normSq_selbergSqrtZetaSignedRationalShortModel_eq_re_fixedShiftPhaseSum
#check HardyTheorem.norm_integral_selbergSqrtZetaSignedRationalFixedShiftPhaseSum_le_localSeparation
#check HardyTheorem.norm_integral_integral_integral_selbergSqrtZetaSignedRationalFixedShiftPhaseSum_le_localSeparation
#check HardyTheorem.integral_normSq_selbergSqrtZetaSignedRationalShortModel_le_localSeparation
