import HardyTheorem.SelbergSqrtZetaExcessiveReducedPairEndpoint

#print axioms HardyTheorem.integral_normSq_selbergSqrtZetaSignedRationalShortModel_le_reducedPairBudget
#print axioms HardyTheorem.exists_integral_sq_selbergSqrtZetaSignedShortIntegral_le_reducedPairBudget_add_error
#print axioms HardyTheorem.exists_volume_selbergSqrtZetaExcessiveSignedMassStarts_inter_Icc_le_T_div_24_of_reducedPairBudget_le
