import HardyTheorem.SelbergSqrtZetaLocal

#print axioms HardyTheorem.selbergSqrtZetaLocalCoeff_zero
#print axioms HardyTheorem.selbergSqrtZetaLocalCoeff_one
#print axioms HardyTheorem.selbergSqrtZetaEulerFactor_sq
#print axioms HardyTheorem.sum_antidiagonal_selbergSqrtZetaLocalCoeff_mul
#print axioms HardyTheorem.selbergSqrtZetaEulerFactor_mul_derivative
#print axioms HardyTheorem.coeff_selbergSqrtZetaEulerWeightedDerivative
#print axioms HardyTheorem.selbergSqrtZetaEulerWeightedDerivative_sq_identity
#print axioms HardyTheorem.coeff_selbergSqrtZetaEulerWeightedDerivative_sq_recurrence
#print axioms HardyTheorem.coeff_selbergSqrtZetaEulerWeightedDerivative_sq
#print axioms HardyTheorem.sum_antidiagonal_mul_selbergSqrtZetaLocalCoeff_mul
#print axioms HardyTheorem.sum_antidiagonal_selbergSqrtZetaLocalTaperedCoeff_mul
#print axioms HardyTheorem.sum_range_selbergSqrtZetaLocalTaperedConvolution
