import HardyTheorem.SelbergSqrtZetaSignedRationalNoncarrierShortKernel

#check HardyTheorem.selbergSqrtZetaSignedRationalNoncarrierFixedShiftPhaseSum_eq_factorized
#check HardyTheorem.integral_normSq_selbergSqrtZetaSignedRationalNoncarrierShortModel_eq_re_fixedShiftPhaseSum
#check HardyTheorem.norm_integral_selbergSqrtZetaSignedRationalNoncarrierFixedShiftPhaseSum_le_localSeparation
#check HardyTheorem.integral_normSq_selbergSqrtZetaSignedRationalNoncarrierShortModel_le_localSeparation
