import HardyTheorem.SelbergSqrtZetaSignedRationalNoncarrierEnergy

#print axioms PrimeNumberTheorem.DirichletPolynomial.localFrequencySeparation_mono_of_subset
#print axioms HardyTheorem.image_selbergSqrtZetaSignedReducedPairKey_reducedPairSupport_erase_one
#print axioms HardyTheorem.sum_selbergSqrtZetaSignedRationalNoncarrierSupport_eq_reducedPairSupport_erase_one
#print axioms HardyTheorem.sum_normSq_noncarrier_eq_reducedPairSupport_erase_one
#print axioms HardyTheorem.sum_normSq_div_fullLocalSeparation_noncarrier_eq_reducedPairSupport_erase_one
#print axioms HardyTheorem.sum_normSq_div_localFrequencySeparation_noncarrier_le_erase_full
#print axioms HardyTheorem.noncarrierEnergy_add_carrierEnergy_le_fullEnergy
#print axioms HardyTheorem.integral_normSq_selbergSqrtZetaSignedRationalNoncarrierPolynomial_le_localSeparation
