import HardyTheorem.SelbergMollifierMeanSquare

open Complex

namespace HardyTheorem

#check selbergMoebiusCriticalLineCoeff
#check selbergMoebiusMollifier_criticalLine_eq_logExponentialPolynomial
#check sum_normSq_selbergMoebiusCriticalLineCoeff_le
#check normSq_selbergMoebiusCriticalLineCoeff_le_inv
#check sum_normSq_selbergMoebiusCriticalLineCoeff_le_one_add_log
#check integral_normSq_selbergMoebiusMollifier_le
#check integral_normSq_selbergMoebiusMollifier_le_one_add_log

#print axioms selbergMoebiusMollifier_criticalLine_eq_logExponentialPolynomial
#print axioms sum_normSq_selbergMoebiusCriticalLineCoeff_le
#print axioms sum_normSq_selbergMoebiusCriticalLineCoeff_le_one_add_log
#print axioms integral_normSq_selbergMoebiusMollifier_le
#print axioms integral_normSq_selbergMoebiusMollifier_le_one_add_log

end HardyTheorem
