import HardyTheorem.SelbergSqrtZetaSignedRationalCarrierDecomposition

#check HardyTheorem.one_mem_selbergSqrtZetaSignedRationalSupport
#check HardyTheorem.selbergSqrtZetaSignedRationalNoncarrierSupport
#check HardyTheorem.selbergSqrtZetaSignedRationalNoncarrierShortModel
#check HardyTheorem.selbergSqrtZetaSignedRationalShortModel_eq_carrier_add_noncarrier
#check HardyTheorem.selbergSqrtZetaSignedRationalCoeff_one_eq_complete_add_boundary
#check HardyTheorem.norm_thetaFrequencyShortIntegral_zero_le_of_base_frequency
#check HardyTheorem.norm_selbergSqrtZetaSignedRationalCarrier_le_of_base_frequency
#check HardyTheorem.quarter_log_le_deriv_thetaModel
#check HardyTheorem.norm_thetaFrequencyShortIntegral_zero_le_thirtytwo_div_log
#check HardyTheorem.norm_selbergSqrtZetaSignedRationalCarrier_le_thirtytwo_div_log
#check HardyTheorem.norm_selbergSqrtZetaSignedRationalShortModel_le_carrier_add_noncarrier
