import HardyTheorem.SelbergShortLowRangeEnergy

namespace Test.SelbergShortLowRangeEnergyContract

#check HardyTheorem.normSq_sliding_selbergShortDirichletCollectedCoeff_le
#check HardyTheorem.sum_normSq_sliding_selbergShortDirichletCollectedCoeff_lowRange_le_harmonic
#check HardyTheorem.sum_normSq_sliding_selbergShortDirichletCollectedCoeff_lowRange_le_log
#check HardyTheorem.sum_normSq_sliding_selbergShortDirichletCollectedCoeff_le_lowRange_add_highRange

#print axioms HardyTheorem.normSq_sliding_selbergShortDirichletCollectedCoeff_le
#print axioms HardyTheorem.sum_normSq_sliding_selbergShortDirichletCollectedCoeff_lowRange_le_log
#print axioms HardyTheorem.sum_normSq_sliding_selbergShortDirichletCollectedCoeff_le_lowRange_add_highRange

end Test.SelbergShortLowRangeEnergyContract
