import HardyTheorem.SelbergSqrtZetaSignedTotalShiftBudget

#print axioms HardyTheorem.exists_abs_integral_integral_integral_selbergSqrtZetaMollifiedAutocorrelation_le_totalShiftBudget
#print axioms HardyTheorem.exists_abs_integral_integral_integral_selbergSqrtZetaMollifiedAutocorrelation_le_totalShiftBudget_modelSupBound
