import HardyTheorem.SelbergOffDiagonalParameter

namespace HardyTheorem

#check selbergOffDiagonalGaussianParameter
#check delta_div_sq_le_selbergOffDiagonalGaussianParameter
#check delta_div_sq_le_capped_offDiagonalParameter
#check log_two_div_capped_offDiagonalParameter_le
#check log_one_div_capped_offDiagonalParameter_le
#check tsum_offDiagonalGaussianHarmonic_le_uniform
#check tsum_offDiagonalGaussianLogHarmonic_le_uniform
#check tsum_offDiagonalDampedBracket_le_uniform

end HardyTheorem
