import HardyTheorem.SelbergSqrtZetaSignedRationalReducedPairSupport

#print axioms HardyTheorem.selbergSqrtZetaSignedRationalReducedPairSupport_mem_iff
#print axioms HardyTheorem.selbergSqrtZetaSignedRationalSupport_unique_reducedPair
#print axioms HardyTheorem.image_selbergSqrtZetaSignedReducedPairKey_reducedPairSupport
#print axioms HardyTheorem.sum_selbergSqrtZetaSignedRationalSupport_eq_reducedPairSupport
