import HardyTheorem.SelbergSqrtZetaMixedProductTailReducedPair

#print axioms HardyTheorem.selbergSqrtZetaRectangularProductSupport_subset_collectedSupport
#print axioms HardyTheorem.selbergSqrtZetaShortDirichletCollectedCoeff_eq_zero_of_not_mem_rectangularProductSupport
#print axioms HardyTheorem.sum_normSq_selbergSqrtZetaShortDirichletCollectedCoeff_rectangularProductSupport_eq_signedRationalEnergy
#print axioms HardyTheorem.sum_normSq_selbergSqrtZetaShortDirichletCollectedCoeff_eq_signedRationalEnergy
#print axioms HardyTheorem.sum_normSq_sliding_selbergSqrtZetaShortDirichletCollectedCoeff_tail_le_logDecay_mul_signedRationalEnergy
#print axioms HardyTheorem.sum_normSq_selbergSqrtZetaShortDirichletCollectedCoeff_rectangularProductTail_eq_signedRationalMixedProductTailEnergy
#print axioms HardyTheorem.sum_normSq_selbergSqrtZetaShortDirichletCollectedCoeff_tail_eq_signedRationalMixedProductTailEnergy
#print axioms HardyTheorem.sum_normSq_sliding_selbergSqrtZetaShortDirichletCollectedCoeff_tail_le_logDecay_mul_signedRationalMixedProductTailEnergy
#print axioms HardyTheorem.sum_normSq_lowProduct_add_signedRationalMixedProductTailEnergy_eq_signedRationalEnergy
#print axioms HardyTheorem.selbergSqrtZetaSignedRationalMixedProductTailEnergy_eq_signedRationalEnergy_sub_lowProduct
#print axioms HardyTheorem.selbergSqrtZetaSignedRationalMixedProductTailEnergy_nonneg
#print axioms HardyTheorem.selbergSqrtZetaSignedRationalMixedProductTailEnergy_antitone_cutoff
#print axioms HardyTheorem.selbergSqrtZetaSignedRationalMixedProductTailEnergy_le_reducedPairComplete_add_boundary_sub_lowProduct
#print axioms HardyTheorem.selbergSqrtZetaSignedRationalMixedProductTailEnergy_le_completeProductHigh_add_boundary_sub_lowProduct
#print axioms HardyTheorem.sum_selbergSqrtZetaSignedReducedPairCompletePlainEnergy_le_nineteen_fourths_add_high
#print axioms HardyTheorem.sum_inv_Ioc_eq_harmonic_sub
#print axioms HardyTheorem.selbergSqrtZetaSignedRationalReducedPairSupport_coordinate_bounds
#print axioms HardyTheorem.sum_inv_boundaryScaleIoc_le_harmonic_div
#print axioms HardyTheorem.selbergSqrtZetaSignedRationalBoundaryTaperSummand_le_harmonicRay
#print axioms HardyTheorem.selbergSqrtZetaSignedRationalBoundaryTaperBudget_eq_filter_numerator_lt_denominator
#print axioms HardyTheorem.selbergSqrtZetaSignedRationalBoundaryTaperBudget_le_harmonicRaySum
#print axioms HardyTheorem.sum_selbergSqrtZetaSignedRationalBoundaryPlain_le_boundaryTaperBudget
#print axioms HardyTheorem.selbergSqrtZetaSignedRationalMixedProductTailEnergy_le_completeProductHigh_add_boundaryTaper_sub_lowProduct
