import HardyTheorem.SelbergSqrtZetaSignedCollectedGapBound

#print axioms HardyTheorem.selbergSqrtZetaSignedCommonCorrelationPhase_eq
#print axioms HardyTheorem.selbergSqrtZetaSignedComplexModel_mul_conj_shift_eq_diagonal_add_offDiagonal'
#print axioms HardyTheorem.norm_integral_selbergSqrtZetaSignedComplexCorrelation_sub_diagonal_le
#print axioms HardyTheorem.norm_integral_selbergSqrtZetaSignedComplexCorrelation_sub_diagonal_le_coeff
