import HardyTheorem.SelbergStrictCancellationZeroCover

namespace HardyTheorem

#check exists_selbergCompletedMollifiedF_ne_zero_Ioo
#check exists_hardyZ_localSignChange_of_selbergCompleted_strictCancellationStart
#check measure_strictCancellationStarts_selbergCompleted_le_oddZeroCount_mul
#check exists_pos_mul_log_le_criticalLineOddZeroCount_two_mul_selberg
#check selberg_odd_zero_proportion_target_proved_mainline
#check selberg_zero_proportion_target_proved_mainline

#print axioms measure_strictCancellationStarts_selbergCompleted_le_oddZeroCount_mul
#print axioms exists_pos_mul_log_le_criticalLineOddZeroCount_two_mul_selberg
#print axioms selberg_odd_zero_proportion_target_proved_mainline
#print axioms selberg_zero_proportion_target_proved_mainline

end HardyTheorem
