import HardyTheorem.SelbergSqrtZetaSignedAutocorrelationShiftBudgetL2

open HardyTheorem

#check exists_abs_integral_selbergSqrtZetaMollifiedAutocorrelation_sub_signedThetaModel_le_L2
#check exists_abs_integral_integral_integral_selbergSqrtZetaMollifiedAutocorrelation_sub_signedThetaModel_le_L2

#print axioms exists_abs_integral_selbergSqrtZetaMollifiedAutocorrelation_sub_signedThetaModel_le_L2
#print axioms exists_abs_integral_integral_integral_selbergSqrtZetaMollifiedAutocorrelation_sub_signedThetaModel_le_L2
