import HardyTheorem.SelbergSqrtZetaExcessiveReducedPairEndpoint

#check HardyTheorem.selbergSqrtZetaSignedReducedPairShortModelBudget
#check HardyTheorem.selbergSqrtZetaSignedReducedPairSplitEnergy
#check HardyTheorem.integral_normSq_selbergSqrtZetaSignedRationalShortModel_le_reducedPairBudget
#check HardyTheorem.exists_integral_sq_selbergSqrtZetaSignedShortIntegral_le_reducedPairBudget_add_error
#check HardyTheorem.exists_volume_selbergSqrtZetaExcessiveSignedMassStarts_inter_Icc_le_T_div_24_of_reducedPairBudget_le
#check HardyTheorem.selbergSqrtZetaSignedReducedPairShortModelBudget_le_of_splitEnergy_le
#check HardyTheorem.exists_volume_selbergSqrtZetaExcessiveSignedMassStarts_inter_Icc_le_T_div_24_of_reducedPairSplitEnergy_le
