import HardyTheorem.SelbergSqrtZetaSignedRationalNoncarrierWeightedEnergyBound

#print axioms HardyTheorem.sum_normSq_div_fullLocalSeparation_reducedPairErase_le_completeBoundaryWeightedEnergy
#print axioms HardyTheorem.sum_normSq_div_fullLocalSeparation_reducedPairErase_le_complete_add_boundary
#print axioms HardyTheorem.sum_normSq_div_fullLocalSeparation_reducedPairErase_le_complete_add_explicitBoundary
