import HardyTheorem.SelbergSqrtZetaComparableNearDiagonal

open Complex

namespace Test.SelbergSqrtZetaComparableNearDiagonalContract

#check HardyTheorem.inv_abs_log_nat_sub_log_nat_le_max_div_dist
#check HardyTheorem.selbergSqrtZetaComparableNearDiagonalBudget
#check HardyTheorem.selbergSqrtZetaComparableNearDiagonalSquareBudget
#check HardyTheorem.selbergSqrtZetaComparableGapBudget_le_nearDiagonal
#check HardyTheorem.selbergSqrtZetaComparableNearDiagonalBudget_le_square
#check HardyTheorem.selbergSqrtZeta_frequencyGap_le_nearDiagonalSquare_add_far
#check HardyTheorem.selbergSqrtZetaShortDirichletGapSum_le_nearDiagonalSquare_add_far

end Test.SelbergSqrtZetaComparableNearDiagonalContract
