import HardyTheorem.SelbergSqrtZetaSignedRationalShortModel

#print axioms HardyTheorem.integral_selbergSqrtZetaSignedComplexModel_shift_eq_rationalShortModel
#print axioms HardyTheorem.normSq_integral_selbergSqrtZetaSignedComplexModel_shift_eq_rationalShortModel
#print axioms HardyTheorem.integral_normSq_integral_selbergSqrtZetaSignedComplexModel_shift_eq_rationalShortModel
