import HardyTheorem.SelbergSqrtZetaActualHighRangeEnergy

#print axioms HardyTheorem.selbergSqrtZetaShortCompleteRangePairSum_eq_shortConvolution
#print axioms HardyTheorem.normSq_selbergSqrtZetaShortDirichletCollectedCoeff_eq_signedPairSum_sq_div
#print axioms HardyTheorem.normSq_sliding_selbergSqrtZetaShortDirichletCollectedCoeff_le_signedPairSum
#print axioms HardyTheorem.sum_normSq_sliding_selbergSqrtZetaShortDirichletCollectedCoeff_completeHighRange_le_signedPairEnergy
#print axioms HardyTheorem.sum_normSq_sliding_selbergSqrtZetaShortDirichletCollectedCoeff_le_lowRange_add_signedPairEnergy_add_actualTail
#print axioms HardyTheorem.selbergSqrtZetaShortDirichletGapSum_le_signedPairEnergy_add_actualTail_add_offDiagonal
