import HardyTheorem.SelbergSqrtZetaSignedRationalNoncarrierPlainEnergyBound

#print axioms HardyTheorem.sum_normSq_selbergSqrtZetaSignedRationalNoncarrierCoeff_add_carrier_eq_full
#print axioms HardyTheorem.sum_normSq_selbergSqrtZetaSignedRationalNoncarrierCoeff_eq_full_sub_carrier
#print axioms HardyTheorem.sum_normSq_selbergSqrtZetaSignedRationalNoncarrierCoeff_eq_reducedPairCompleteBoundary_erase_one
#print axioms HardyTheorem.sum_normSq_selbergSqrtZetaSignedRationalNoncarrierCoeff_le_reducedPairComplete_add_boundary_erase_one
#print axioms HardyTheorem.sum_normSq_selbergSqrtZetaSignedRationalNoncarrierCoeff_le_completeHigh_add_boundaryTaper
