import HardyTheorem.SelbergSqrtZetaSignedRationalCollected

#print axioms HardyTheorem.selbergSqrtZetaSignedRationalKey_pos_of_mem
#print axioms HardyTheorem.selbergSqrtZetaSignedPhaseFrequency_eq_rationalFrequency_key
#print axioms HardyTheorem.selbergSqrtZetaSignedPhaseFrequency_eq_iff_rationalKey_eq
#print axioms HardyTheorem.selbergSqrtZetaSignedTriplePolynomial_eq_rationalCollectedPolynomial
