import HardyTheorem.SelbergSqrtZetaSignedReducedRayBoundaryEnergy

#check HardyTheorem.sum_inv_snd_selbergSqrtZetaSignedDenominatorFiber_le_harmonic
#check HardyTheorem.sq_sum_selbergSqrtZetaSignedDenominatorFiber_taper_le_harmonic_mul_weightedEnergy
#check HardyTheorem.selbergSqrtZetaSignedReducedRayBoundaryTerm_sq_le_harmonicEnergy
#check HardyTheorem.selbergSqrtZetaSignedReducedRayBoundaryTerm_sq_le_harmonicMass_mul_denominatorEnergy
#check HardyTheorem.selbergSqrtZetaSignedReducedRayBoundaryTerm_sq_le_harmonicTail_mul_denominatorEnergy
#check HardyTheorem.sum_weightedSq_selbergSqrtZetaSignedDenominatorFiber_le_globalTaperEnergy
#check HardyTheorem.sum_weightedSq_selbergSqrtZetaSignedDenominatorFiber_le_globalLinearTaperEnergy
#check HardyTheorem.sq_sum_selbergSqrtZetaSignedDenominatorFiber_taper_le_uniformLinearTaperEnergy
#check HardyTheorem.selbergSqrtZetaSignedReducedRayBoundaryTerm_sq_le_harmonicTail_sq_mul_uniformLinearTaperEnergy
