import HardyTheorem.SelbergJOffDiagonalPhysical

open HardyTheorem

#check selbergPhysicalPairMollifierCoefficient
#check norm_selbergPhysicalPairMollifierCoefficient_le
#check selbergPhysicalOffDiagonalPairContribution
#check selbergPhysicalPairDamping_first_le
#check norm_selbergPhysicalOffDiagonalPairContribution_forward_le
#check selbergPhysicalForwardFixedSum
#check norm_selbergPhysicalForwardFixedSum_le
#check selbergPhysicalForwardRaySum
#check summable_selbergPhysicalForwardFixedSum_add_one
#check norm_selbergPhysicalForwardRaySum_le
#check selbergPhysicalPositiveOffDiagonalSum
#check norm_selbergPhysicalPositiveOffDiagonalSum_le
#check selbergPhysicalReverseOffDiagonalSum
#check norm_selbergPhysicalReverseOffDiagonalSum_le
#check selbergPhysicalOffDiagonalSum
#check norm_selbergPhysicalOffDiagonalSum_le_oscillatoryMajorant
