import HardyTheorem.SelbergSqrtZetaSignedRationalReducedRayEnergy

#check HardyTheorem.normSq_div_localFrequencySeparation_le_reducedRayWeight
#check HardyTheorem.normSq_div_localFrequencySeparation_le_reducedRayBilinearWeight
#check HardyTheorem.normSq_div_localFrequencySeparation_le_reducedRayLogExpansionWeight
