import HardyTheorem.SelbergShortPrimeObstruction

#check HardyTheorem.selbergShortCollectedDirichletConvolution_eq_primeCoefficient
#check HardyTheorem.selbergShortDirichletCollectedCoeff_eq_primeCoefficient
#check HardyTheorem.selbergShortCollectedDirichletConvolution_prime_le_neg_half

#print axioms HardyTheorem.selbergShortCollectedDirichletConvolution_eq_primeCoefficient
#print axioms HardyTheorem.selbergShortDirichletCollectedCoeff_eq_primeCoefficient
#print axioms HardyTheorem.selbergShortCollectedDirichletConvolution_prime_le_neg_half
