import HardyTheorem.SelbergSqrtZetaSignedRationalCarrierDecomposition

#print axioms HardyTheorem.one_mem_selbergSqrtZetaSignedRationalSupport
#print axioms HardyTheorem.selbergSqrtZetaSignedRationalShortModel_eq_carrier_add_noncarrier
#print axioms HardyTheorem.selbergSqrtZetaSignedRationalCoeff_one_eq_complete_add_boundary
#print axioms HardyTheorem.norm_thetaFrequencyShortIntegral_zero_le_of_base_frequency
#print axioms HardyTheorem.quarter_log_le_deriv_thetaModel
#print axioms HardyTheorem.norm_thetaFrequencyShortIntegral_zero_le_thirtytwo_div_log
#print axioms HardyTheorem.norm_selbergSqrtZetaSignedRationalCarrier_le_thirtytwo_div_log
#print axioms HardyTheorem.norm_selbergSqrtZetaSignedRationalShortModel_le_carrier_add_noncarrier
