import HardyTheorem.SelbergSqrtZetaSignedActualFourierTransfer
import HardyTheorem.SelbergSqrtZetaSignedAutocorrelationShiftBudgetL2
import HardyTheorem.SelbergSqrtZetaSignedRationalFourierTransfer
import HardyTheorem.SelbergSqrtZetaSignedRationalReducedRatio
import HardyTheorem.SelbergSqrtZetaSignedRationalShortKernel
import HardyTheorem.SelbergSqrtZetaSignedRationalWindowEnergy
import HardyTheorem.SelbergSqrtZetaSignedTotalShiftBudget

open HardyTheorem

#check intervalIntegrable_normSq_selbergSqrtZetaSignedRationalShortModel
#check exists_integral_sq_selbergSqrtZetaSignedShortIntegral_le_rationalShortModel_add_error

#check exists_abs_integral_selbergSqrtZetaMollifiedAutocorrelation_sub_signedThetaModel_le_L2
#check exists_abs_integral_integral_integral_selbergSqrtZetaMollifiedAutocorrelation_sub_signedThetaModel_le_L2

#check selbergSqrtZetaSignedTruncatedPhase
#check integrable_selbergSqrtZetaSignedTruncatedPhase
#check memLp_two_selbergSqrtZetaSignedTruncatedPhase
#check integral_selbergSqrtZetaSignedTruncatedPhase_eq_rationalShortModel
#check integral_normSq_selbergSqrtZetaSignedRationalShortModel_le_fourier_low_high

#check crossProduct_eq_iff_exists_coprime_scales

#check selbergSqrtZetaSignedRationalShortKernel
#check selbergSqrtZetaSignedRationalShortKernelPhase
#check selbergSqrtZetaSignedRationalShortKernel_eq_triple
#check integral_normSq_selbergSqrtZetaSignedRationalShortModel_eq_re_kernelSum

#check thetaFrequencyShortIntegralEnvelope_le_stationary_add_error
#check sq_sum_norm_mul_thetaFrequencyShortIntegralEnvelope_le
#check norm_sq_integral_selbergSqrtZetaSignedComplexModel_shift_le_rationalEnergy

#check selbergSqrtZetaSignedOrdinaryGapShiftBudget
#check selbergSqrtZetaSignedDiagonalShiftBudget
#check selbergSqrtZetaSignedPseudoShiftFiberBudget
#check selbergSqrtZetaSignedModelTransferShiftBudget
#check selbergSqrtZetaSignedTotalShiftBudget
#check exists_abs_integral_integral_integral_selbergSqrtZetaMollifiedAutocorrelation_le_totalShiftBudget
#check exists_abs_integral_integral_integral_selbergSqrtZetaMollifiedAutocorrelation_le_totalShiftBudget_modelSupBound
