import HardyTheorem.SelbergSqrtZetaHighRangeEnergy

#print axioms HardyTheorem.card_selbergShortDirichletTriples_le_completeRangePairs
#print axioms HardyTheorem.normSq_selbergSqrtZetaShortDirichletCollectedCoeff_le_tripleFiber
#print axioms HardyTheorem.normSq_selbergSqrtZetaShortDirichletTripleCoeff_le_inv
#print axioms HardyTheorem.selbergSqrtZetaShortCollectedTripleFiberEnergy_le_card_sq_div
#print axioms HardyTheorem.selbergSqrtZetaShortCollectedTripleFiberEnergy_le_completePair_card_sq_div
#print axioms HardyTheorem.normSq_sliding_selbergSqrtZetaShortDirichletCollectedCoeff_le_tripleFiber_mul_min_sq
#print axioms HardyTheorem.sum_normSq_sliding_selbergSqrtZetaShortDirichletCollectedCoeff_highRange_le_tripleFiberMin
#print axioms HardyTheorem.sum_normSq_sliding_selbergSqrtZetaShortDirichletCollectedCoeff_highRange_le_cardSq
#print axioms HardyTheorem.sum_normSq_sliding_selbergSqrtZetaShortDirichletCollectedCoeff_highRange_le_completePairCardSq
#print axioms HardyTheorem.sum_normSq_sliding_selbergSqrtZetaShortDirichletCollectedCoeff_le_lowRange_add_tripleFiberMinHighRange
#print axioms HardyTheorem.sum_normSq_sliding_selbergSqrtZetaShortDirichletCollectedCoeff_le_lowRange_add_cardSqHighRange
#print axioms HardyTheorem.sum_normSq_sliding_selbergSqrtZetaShortDirichletCollectedCoeff_le_lowRange_add_completePairCardSqHighRange
