import HardyTheorem.SelbergJAbsoluteFubini

open HardyTheorem

#check selbergPhysicalExpandedPairIntegrand
#check selbergPhysicalPairDamping_eq_parameters
#check selbergPhysicalPairDamping_ge_uniform
#check norm_selbergPhysicalPairMollifierCoefficient_le_one
#check norm_selbergPhysicalExpandedPairIntegrand_le_linearGaussian
#check integrableOn_selbergPhysicalExpandedPairIntegrand
#check integral_norm_selbergPhysicalExpandedPairIntegrand_le_productGaussian
#check summable_integral_norm_selbergPhysicalExpandedPairIntegrand
#check hasSum_integral_selbergPhysicalExpandedPairIntegrand
