import HardyTheorem.SelbergSqrtZetaRestrictedPairMomentBound

namespace Test.SelbergSqrtZetaRestrictedPairMomentBoundContract

#check HardyTheorem.sum_selbergShortRestrictedPairProductMultiplicity_mul_inv_eq_harmonic_sq
#check HardyTheorem.totientSquares_selbergShortRestrictedPairProductMultiplicity_le
#check HardyTheorem.weighted_highRange_selbergShortCompleteRangePairs_le_logPolynomial
#check HardyTheorem.sum_normSq_sliding_selbergSqrtZetaShortDirichletCollectedCoeff_le_lowRange_add_logPolynomialHighRange

end Test.SelbergSqrtZetaRestrictedPairMomentBoundContract
