import HardyTheorem.SelbergSqrtZetaSignedCarrierNoncarrierEndpoint

-- Plain noncarrier coefficient energy
#check HardyTheorem.sum_normSq_selbergSqrtZetaSignedRationalNoncarrierCoeff_add_carrier_eq_full
#check HardyTheorem.sum_normSq_selbergSqrtZetaSignedRationalNoncarrierCoeff_eq_full_sub_carrier
#check HardyTheorem.sum_normSq_selbergSqrtZetaSignedRationalNoncarrierCoeff_eq_reducedPairCompleteBoundary_erase_one
#check HardyTheorem.sum_normSq_selbergSqrtZetaSignedRationalNoncarrierCoeff_le_reducedPairComplete_add_boundary_erase_one
#check HardyTheorem.selbergSqrtZetaSignedRationalNoncarrierBoundaryTaperBudget
#check HardyTheorem.sum_normSq_selbergSqrtZetaSignedRationalNoncarrierCoeff_le_completeHigh_add_boundaryTaper

-- Actual short-window noncarrier kernel
#check HardyTheorem.selbergSqrtZetaSignedRationalNoncarrierFixedShiftPhaseSum
#check HardyTheorem.selbergSqrtZetaSignedRationalNoncarrierFixedShiftPhaseSum_eq_factorized
#check HardyTheorem.intervalIntegrable_normSq_selbergSqrtZetaSignedRationalNoncarrierShortModel
#check HardyTheorem.integral_normSq_selbergSqrtZetaSignedRationalNoncarrierShortModel_eq_re_fixedShiftPhaseSum
#check HardyTheorem.norm_integral_selbergSqrtZetaSignedRationalNoncarrierFixedShiftPhaseSum_le_localSeparation
#check HardyTheorem.integral_normSq_selbergSqrtZetaSignedRationalNoncarrierShortModel_le_localSeparation
#check HardyTheorem.integral_normSq_selbergSqrtZetaSignedRationalNoncarrierShortModel_le_reducedPairEraseBudget

-- Weighted noncarrier energy
#check HardyTheorem.sum_normSq_div_fullLocalSeparation_reducedPairErase_le_completeBoundaryWeightedEnergy
#check HardyTheorem.sum_normSq_div_fullLocalSeparation_reducedPairErase_le_complete_add_boundary
#check HardyTheorem.sum_normSq_div_fullLocalSeparation_reducedPairErase_le_complete_add_explicitBoundary

-- Carrier/noncarrier endpoint
#check HardyTheorem.selbergSqrtZetaSignedRationalNoncarrierEraseBudget
#check HardyTheorem.selbergSqrtZetaSignedRationalNoncarrierPlainExplicitBudget
#check HardyTheorem.selbergSqrtZetaSignedRationalNoncarrierWeightedExplicitBudget
#check HardyTheorem.selbergSqrtZetaSignedRationalNoncarrierExplicitBudget
#check HardyTheorem.selbergSqrtZetaSignedRationalNoncarrierEraseBudget_le_explicitBudget
#check HardyTheorem.integral_normSq_selbergSqrtZetaSignedRationalNoncarrierShortModel_le_eraseBudget
#check HardyTheorem.integral_normSq_selbergSqrtZetaSignedRationalShortModel_le_carrier_add_noncarrierEraseBudget
#check HardyTheorem.integral_normSq_selbergSqrtZetaSignedRationalShortModel_le_carrier_add_noncarrierExplicitBudget
