import HardyTheorem.SelbergSqrtZetaSignedAutocorrelationTransfer
import HardyTheorem.SelbergSqrtZetaSignedDenominatorCollected
import HardyTheorem.SelbergSqrtZetaSignedLagIntegral
import HardyTheorem.SelbergSqrtZetaSignedPseudoLeOrdinary
import HardyTheorem.SelbergSqrtZetaSignedRationalEnergy
import HardyTheorem.SelbergSqrtZetaSignedRationalGapBudget
import HardyTheorem.SelbergSqrtZetaSignedRationalLocalSeparation
import HardyTheorem.SelbergSqrtZetaSignedRationalSeparation
import HardyTheorem.SelbergSqrtZetaSignedRationalWindow

open HardyTheorem

#check exists_abs_integral_selbergSqrtZetaMollifiedAutocorrelation_sub_signedThetaModel_le

#check selbergSqrtZetaSignedDenominatorRawSupport
#check selbergSqrtZetaSignedDenominatorKey
#check selbergSqrtZetaSignedDenominatorSupport
#check selbergSqrtZetaSignedDenominatorFiber
#check selbergSqrtZetaSignedDenominatorCoeff
#check selbergSqrtZetaSignedDenominatorCollectedCoeff
#check selbergSqrtZetaSignedNumeratorSupport
#check selbergSqrtZetaSignedNumeratorCoeff
#check selbergSqrtZetaSignedDenominatorNumeratorKey
#check selbergSqrtZetaSignedDenominatorNumeratorSupport
#check selbergSqrtZetaSignedDenominatorNumeratorFiber
#check selbergSqrtZetaSignedDenominator_pos_of_mem
#check selbergSqrtZetaSignedPhaseCoeff_eq_denominator_mul_numerator
#check sum_selbergSqrtZetaSignedPhaseCoeff_fixed_denominatorNumerator
#check selbergSqrtZetaSignedRationalCoeff_eq_denominatorCollected

#check selbergSqrtZetaSignedShortIntegral_eq_slidingWindowMass
#check continuous_selbergSqrtZetaSignedShortIntegral
#check integral_sq_selbergSqrtZetaSignedShortIntegral_eq_correlation
#check integral_sq_selbergSqrtZetaSignedShortIntegral_eq_lagIntegral
#check volume_selbergSqrtZetaExcessiveSignedMassStarts_inter_Icc_le_secondMoment
#check volume_selbergSqrtZetaExcessiveSignedMassStarts_inter_Icc_le_T_div_24_of_lagIntegral_le

#check selbergSqrtZetaSignedOrdinaryShiftKernel_fubini
#check norm_integral_integral_integral_selbergSqrtZetaSignedComplexModel_mul_shift_le_conj_shift

#check sum_normSq_selbergSqrtZetaSignedRationalCoeff_le_fiber_budget

#check selbergSqrtZetaSignedRational_pos_of_mem
#check selbergSqrtZetaSignedRationalFrequency_sub_eq_log_div
#check selbergSqrtZetaSignedRationalGapBudget
#check sum_collectedFrequencyGap_eq_rationalGapBudget
#check norm_integral_integral_integral_selbergSqrtZetaSignedOrdinaryCorrelation_le_rational_gap

#check integral_normSq_selbergSqrtZetaSignedRationalCollectedPolynomial_le_localSeparation

#check one_div_sq_nat_mul_le_abs_sub_of_mem_selbergSqrtZetaSignedRationalSupport
#check one_div_nat_mul_sq_le_abs_sub_frequency_of_mem_selbergSqrtZetaSignedRationalSupport
#check selbergSqrtZetaSignedNearFrequencySupport
#check card_selbergSqrtZetaSignedNearFrequencySupport_le_one
#check selbergSqrtZetaSignedNearStationarySupport
#check card_selbergSqrtZetaSignedNearStationarySupport_le_one
#check one_div_two_mul_nat_mul_sq_le_abs_thetaDerivative_add_frequency_of_mem_not_near
#check two_div_abs_thetaDerivative_add_frequency_le_four_mul_nat_mul_sq_of_mem_not_near

#check selbergSqrtZetaSignedPhasePolynomial_eq_sum_rational_thetaFrequency
#check integral_selbergSqrtZetaSignedPhasePolynomial_shift_eq_sum_thetaFrequencyShortIntegral
#check integral_selbergSqrtZetaSignedComplexModel_shift_eq_sum_thetaFrequencyShortIntegral
