import HardyTheorem.SelbergOffDiagonalFixedSide

namespace HardyTheorem

#check selberg_reciprocal_square_gap_weight_le
#check selberg_nat_reciprocal_square_gap_weight_le
#check selberg_nat_square_gap_pos
#check selbergFixedSideSquareSum
#check selbergFixedSideSquareSum_nonneg
#check selberg_gap_factor_le_two_dampedBracket
#check selberg_fixed_m_gap_majorant_le
#check selberg_fixed_side_square_sum_le_dampedBracket
#check summable_selbergFixedSideSquareSum_add_one
#check tsum_selbergFixedSideSquareSum_add_one_le

end HardyTheorem
