import HardyTheorem.SelbergSqrtZetaSignedCollectedL1

#print axioms HardyTheorem.sq_sum_norm_selbergSqrtZetaSignedCollectedCoeff_le_card_mul_energy
#print axioms HardyTheorem.sum_sum_mul_norm_selbergSqrtZetaSignedCollectedCoeff_le_card_mul_energy
#print axioms HardyTheorem.sum_sum_mul_norm_selbergSqrtZetaSignedCollectedCoeff_le_fiber_budget
