import HardyTheorem.SelbergResidueFourierMass

open HardyTheorem

#check norm_selbergSqrtZetaPsi_zero_le
#check norm_selbergSqrtZetaPsi_one_le
#check norm_selbergSqrtZetaPsi_one_mul_zero_le
#check normSq_selbergResidueInverseFourierKernel
#check normSq_selbergSqrtZetaPsi_one_mul_zero_le_fourth
#check selberg_fourth_power_le_delta_neg_half
#check normSq_selbergResidueInverseFourierKernel_le_exp_mul_delta_neg_half
#check integral_normSq_selbergResidueInverseFourierKernel_low_le_delta_neg_half
#check integral_normSq_selbergResidueInverseFourierKernel_div_sq_high_le
#check exists_integral_normSq_selbergResidueInverseFourierKernel_low_le
#check exists_integral_normSq_selbergResidueInverseFourierKernel_high_le
