import HardyTheorem.SelbergSqrtZetaExcessiveTotalBudget
import HardyTheorem.SelbergSqrtZetaSignedRationalCoprimeRayReindex
import HardyTheorem.SelbergSqrtZetaSignedRationalReducedSeparation
import HardyTheorem.SelbergSqrtZetaSignedRationalShortKernelPhase
import HardyTheorem.SelbergSqrtZetaSignedTotalShiftBudgetL2
import HardyTheorem.SelbergSqrtZetaSignedTruncatedEnergy

open HardyTheorem

#check integral_sq_selbergSqrtZetaSignedShortIntegral_eq_fixedShiftSquare
#check exists_volume_selbergSqrtZetaExcessiveSignedMassStarts_inter_Icc_le_T_div_24_of_totalShiftBudget_le
#check exists_volume_selbergSqrtZetaExcessiveSignedMassStarts_inter_Icc_le_T_div_24_of_totalShiftBudget_modelSupBound_le

#check SelbergSqrtZetaSignedCoprimeRayScales
#check selbergSqrtZetaSignedCoprimeRayScales_leftPair
#check selbergSqrtZetaSignedCoprimeRayScales_rightPair
#check selbergSqrtZetaSignedRationalOffDiagonalCoprimeRayScaleSupport
#check selbergSqrtZetaSignedCoprimeRayScales_coprime
#check selbergSqrtZetaSignedCoprimeRayScales_denominator_pos
#check selbergSqrtZetaSignedCoprimeRayScales_scale_facts
#check selbergSqrtZetaSignedRationalCoefficientOffDiagonal_eq_coprimeRayScaleSum
#check sum_normSq_selbergSqrtZetaSignedRationalCoeff_eq_product_add_coprimeRayScaleSum

#check one_div_one_add_X_mul_min_le_abs_sub_frequency_reduced_of_mem
#check one_div_one_add_X_mul_min_le_localFrequencySeparation_reduced
#check one_div_localFrequencySeparation_le_one_add_X_mul_min_reduced
#check normSq_div_localFrequencySeparation_le_reducedWeight

#check deriv_selbergSqrtZetaSignedRationalShortKernelPhase
#check iteratedDeriv_two_selbergSqrtZetaSignedRationalShortKernelPhase
#check abs_deriv_selbergSqrtZetaSignedRationalShortKernelPhase_sub_frequencyGap_le
#check half_abs_frequencyGap_le_abs_deriv_selbergSqrtZetaSignedRationalShortKernelPhase
#check norm_integral_cexp_selbergSqrtZetaSignedRationalShortKernelPhase_le_of_frequencyGap
#check norm_selbergSqrtZetaSignedRationalShortKernel_le_of_frequencyGap

#check selbergSqrtZetaSignedModelTransferShiftBudgetL2
#check selbergSqrtZetaSignedTotalShiftBudgetL2
#check exists_abs_integral_integral_integral_selbergSqrtZetaMollifiedAutocorrelation_le_totalShiftBudgetL2

#check integral_normSq_selbergSqrtZetaSignedTruncatedPhase_eq_phasePolynomial
#check integral_normSq_selbergSqrtZetaSignedTruncatedPhase_eq_collectedTriplePolynomial
#check integral_normSq_selbergSqrtZetaSignedTruncatedPhase_le_modelL2Budget
