import HardyTheorem.SelbergMollifiedGaussianPolynomial

open Complex MeasureTheory

#check HardyTheorem.sum_normSq_selbergMollifiedCriticalLineCoeff_full_le
#check HardyTheorem.criticalLineDirichletPolynomial_mul_selbergMoebiusMollifier_eq_exponentialPolynomial
#check HardyTheorem.integral_gaussian_normSq_criticalLineDirichletPolynomial_mul_selbergMoebiusMollifier_le
#print axioms HardyTheorem.sum_normSq_selbergMollifiedCriticalLineCoeff_full_le
#print axioms HardyTheorem.integral_gaussian_normSq_criticalLineDirichletPolynomial_mul_selbergMoebiusMollifier_le
