import HardyTheorem.SelbergSqrtZetaSignedRationalNoncarrierEnergy

#check PrimeNumberTheorem.DirichletPolynomial.localFrequencySeparation_mono_of_subset
#check HardyTheorem.sum_normSq_div_localFrequencySeparation_noncarrier_le_erase_full
#check HardyTheorem.noncarrierEnergy_add_carrierEnergy_le_fullEnergy
#check HardyTheorem.integral_normSq_selbergSqrtZetaSignedRationalNoncarrierPolynomial_le_localSeparation
#check HardyTheorem.image_selbergSqrtZetaSignedReducedPairKey_reducedPairSupport_erase_one
#check HardyTheorem.sum_selbergSqrtZetaSignedRationalNoncarrierSupport_eq_reducedPairSupport_erase_one
#check HardyTheorem.sum_normSq_noncarrier_eq_reducedPairSupport_erase_one
#check HardyTheorem.sum_normSq_div_fullLocalSeparation_noncarrier_eq_reducedPairSupport_erase_one
