import HardyTheorem.SelbergSqrtZetaSignedRationalNoncarrierShortKernel

#print axioms HardyTheorem.selbergSqrtZetaSignedRationalNoncarrierFixedShiftPhaseSum_eq_factorized
#print axioms HardyTheorem.integral_normSq_selbergSqrtZetaSignedRationalNoncarrierShortModel_eq_re_fixedShiftPhaseSum
#print axioms HardyTheorem.norm_integral_selbergSqrtZetaSignedRationalNoncarrierFixedShiftPhaseSum_le_localSeparation
#print axioms HardyTheorem.integral_normSq_selbergSqrtZetaSignedRationalNoncarrierShortModel_le_localSeparation
#print axioms HardyTheorem.integral_normSq_selbergSqrtZetaSignedRationalNoncarrierShortModel_le_reducedPairEraseBudget
