import MathlibAux.SlidingLagCosineBudget

open MeasureTheory Set

namespace MathlibAux

#check abs_lagIntegral_le_cosine_main_add_uniform_error
#check abs_lagIntegral_le_cosine_main_add_uniform_error_of_nonneg
#check abs_squareIntegral_le_cosine_difference_main_add_uniform_error

end MathlibAux
