import PrimeNumberTheorem.SmoothedErrorTransfer

#print axioms PrimeNumberTheorem.ExplicitFormulaResidues.norm_secondOrderExplicitFormulaIntegrand_odd_vertical_le_of_pos
#print axioms PrimeNumberTheorem.ExplicitFormulaResidues.norm_secondOrderExplicitFormulaIntegrand_odd_vertical_le
#print axioms PrimeNumberTheorem.ExplicitFormulaResidues.norm_secondOrderLeftXDifference_odd_le_of_pos
#print axioms PrimeNumberTheorem.ExplicitFormulaResidues.norm_secondOrderLeftXDifference_odd_le
#print axioms PrimeNumberTheorem.ExplicitFormulaResidues.norm_secondOrderExplicitFormulaIntegrand_horizontal_le_of_logDeriv_le_of_re_le
#print axioms PrimeNumberTheorem.ExplicitFormulaResidues.exists_goodHeight_Icc_norm_secondOrderHorizontalXDifference_le
#print axioms PrimeNumberTheorem.ExplicitFormulaResidues.norm_secondOrderContourRemainder_sub_le_edgeDifferences
#print axioms PrimeNumberTheorem.ExplicitFormulaResidues.norm_secondOrderHorizontalXDifference_right_le
#print axioms PrimeNumberTheorem.ExplicitFormulaResidues.norm_secondOrderHorizontalXDifference_right_neg_height_le
#print axioms PrimeNumberTheorem.chebyshevPsi_bounds_of_smoothedApproximation
#print axioms PrimeNumberTheorem.ExplicitFormulaResidues.exists_chebyshevPsi_bounds_of_secondOrderExplicitFormula
#print axioms PrimeNumberTheorem.ExplicitFormulaResidues.secondOrder_poleCandidate_mem_interior_negativeOdd_rectangle_of_goodHeight
#print axioms PrimeNumberTheorem.ExplicitFormulaResidues.exists_goodHeight_Icc_norm_secondOrderContourRemainder_sub_neg_one_le
#print axioms MathlibAux.boundaryRectIntegral_inv_sq_zero_of_mem
#print axioms MathlibAux.boundaryRectIntegral_eq_double_pole_add_finite_simple_pole_residue_sum
#print axioms PrimeNumberTheorem.ExplicitFormulaResidues.exists_boundaryRectIntegral_secondOrderExplicitFormulaIntegrand_crossing_zero
#print axioms PrimeNumberTheorem.ExplicitFormulaResidues.exists_scaledRightIntegral_eq_residue_sum_sub_secondOrderContourRemainder_crossing_zero
#print axioms PrimeNumberTheorem.ExplicitFormulaResidues.exists_norm_residue_sum_sub_contourRemainder_sub_smoothedPsi_le_crossing_zero
