import ZeroFreeRegion.VinogradovKorobov.VinogradovCoupledTailIteration

open ZeroFreeRegion.VinogradovKorobov

#check normalizedVinogradovMixedCoupledTailIteratedNormMoment
#check normalizedVinogradovMixedCoupledTailIteratedNormMoment_zero
#check normalizedVinogradovMixedCoupledTailIteratedNormMoment_succ
#check norm_normalizedVinogradovMixedModConditionedMoment_le_coupledTailIterated
#check normalizedVinogradovMixedCoupledTailIteratedNormMoment_le_uniformLeaf
#check VinogradovResidualTailNoWrap.mono_length
#check vinogradovTailLengthEnvelope_noWrap_condition_implies_root
#check normalizedVinogradovMixedCoupledTailIteratedNormMoment_le_completeBlockFactorialTail
#check norm_normalizedVinogradovMixedModConditionedMoment_le_coupledTailIteratedCompleteBlockFactorialTail

#print axioms norm_normalizedVinogradovMixedModConditionedMoment_le_coupledTailIterated
#print axioms normalizedVinogradovMixedCoupledTailIteratedNormMoment_le_uniformLeaf
#print axioms VinogradovResidualTailNoWrap.mono_length
#print axioms vinogradovTailLengthEnvelope_noWrap_condition_implies_root
#print axioms normalizedVinogradovMixedCoupledTailIteratedNormMoment_le_completeBlockFactorialTail
#print axioms norm_normalizedVinogradovMixedModConditionedMoment_le_coupledTailIteratedCompleteBlockFactorialTail
