import ZeroFreeRegion.VinogradovKorobov.VinogradovWeightedConditioning

open ZeroFreeRegion.VinogradovKorobov

#check vinogradovPowerSumDifferenceInt
#check vinogradovPowerSumDifferenceInt_zero
#check vinogradovPowerSumDifferenceInt_affine
#check vinogradovPowerSumDifferenceInt_affine_one
#check vinogradovPowerSumDifferenceInt_scale
#check IsVinogradovWeightedSolutionInt
#check isVinogradovWeightedSolutionInt_iff_modEq
#check isVinogradovWeightedSolutionInt_affine_iff_triangular
#check weightedAffineRescale_counterexample
#check IsVinogradovMixedAffineEquationInt
#check IsVinogradovMixedAffineEquationInt.centered_powerSum_eq
#check IsVinogradovMixedAffineEquationInt.centered_modEq
#check IsVinogradovMixedAffineEquationInt.centered_weightedSolution
#check IsVinogradovWeightedSolutionInt.affine_degreeOne_rescale
#check IsVinogradovWeightedSolutionInt.scale_rescale
