import ZeroFreeRegion.VinogradovKorobov.VinogradovCoupledTailRecurrence

open ZeroFreeRegion.VinogradovKorobov

#check normalizedVinogradovMixedOneStepRefinedNormAverage
#check norm_normalizedVinogradovMixedModConditionedMoment_le_oneStepCoupledRefinement
#check normalizedVinogradovMixedOneStepRefinedNormAverage_eq_nextScale
#check norm_normalizedVinogradovMixedModConditionedMoment_le_nextScaleCoupledSum

#print axioms norm_normalizedVinogradovMixedModConditionedMoment_le_oneStepCoupledRefinement
#print axioms normalizedVinogradovMixedOneStepRefinedNormAverage_eq_nextScale
#print axioms norm_normalizedVinogradovMixedModConditionedMoment_le_nextScaleCoupledSum
