import ZeroFreeRegion.VinogradovKorobov.VinogradovLowDegreePsi

open ZeroFreeRegion.VinogradovKorobov

#check vinogradovLowDegreePart
#check exists_vinogradovLowDegreePart_factor
#check exists_vinogradovTranslatedLowDegreePsi
#check exists_vinogradovTranslatedSpacedLowDegreePsi
#check vinogradovRowScale_le_of_budget
#check exists_vinogradovTranslatedSpacedLowDegreePsi_of_budget
#check coeff_vinogradovLowDegreePart_of_pos_le
#check exists_eq_vinogradovLowDegreePart_add_tail
#check exists_vinogradovTranslatedSpacedDilationNormalForm_of_budget
#check coeff_vinogradovLowDegreePart_eq_zero_of_lt
#check primePower_dvd_coeff_dilation_sub_lowDegreePart
#check exists_vinogradovPolynomialDilation_eq_lowDegreePart_add_scaledTail
#check exists_vinogradovTranslatedSpacedDilationNormalForm_with_tailScale
#check exists_vinogradovTranslatedSpacedLowerSystem_to_farScale
#check eval_vinogradovLowDegreePart
#check vinogradovRowScale_le_last
#check eval_vinogradovTranslatedLowDegreePsi_modEq_monomial
#check vinogradovTranslatedLowDegreePsi_sumDifference_modEq_powerSum
#check vinogradovUnscaledTranslatedSpacedSystem_to_farScale_via_unitTwist
