import ZeroFreeRegion.VinogradovKorobov.VinogradovMixedNormalizedConditioning

open ZeroFreeRegion.VinogradovKorobov

#check vinogradovOuterWeightedNormalizedConditionedMoment
#check vinogradovOuterWeightedNormalizedConditionedMoment_le_refinement
#check vinogradovResidueMass_pow_mul_normalizedMoment_eq_norm_pow
#check vinogradovOuterWeightedNormalizedConditionedMoment_to_raw
#check vinogradovMixedTailPhaseTerm
#check vinogradovMixedMainOuterWeight
#check vinogradovMixedNormalizedResidueMoment
#check vinogradovMixedNormalizedResidueMoment_le_refinement
#check vinogradovMixedRawResidueNormMoment
#check vinogradovMixedNormalizedResidueMoment_to_raw

#print axioms vinogradovOuterWeightedNormalizedConditionedMoment_le_refinement
#print axioms vinogradovOuterWeightedNormalizedConditionedMoment_to_raw
#print axioms vinogradovMixedNormalizedResidueMoment_le_refinement
#print axioms vinogradovMixedNormalizedResidueMoment_to_raw
