import ZeroFreeRegion.VinogradovKorobov.VinogradovMixedTailMoment

open ZeroFreeRegion.VinogradovKorobov

#check vinogradovIntSolutionPairSet
#check normalizedVinogradovIntNormMoment
#check normalizedVinogradovIntNormMoment_eq_solutionPairSetCard
#check normalizedVinogradovMixedTailNormMoment_eq_solutionPairSetCard
#check IsVinogradovSolutionIntMod.affine_residual_modEq
#check vinogradovMixedTailSolutionPair_residual_modEq

#print axioms normalizedVinogradovIntNormMoment_eq_solutionPairSetCard
#print axioms normalizedVinogradovMixedTailNormMoment_eq_solutionPairSetCard
#print axioms IsVinogradovSolutionIntMod.affine_residual_modEq
#print axioms vinogradovMixedTailSolutionPair_residual_modEq
