import ZeroFreeRegion.VinogradovKorobov.VinogradovMixedDecomposition

open ZeroFreeRegion.VinogradovKorobov

#check sum_vinogradovResidueClassSum_eq_full
#check vinogradovMixedMainWeylSum_eq_residueClassSum
#check vinogradovWeylSumMod_eq_sum_mixedMainWeylSum
#check norm_vinogradovWeylSumMod_pow_le_double_mixedMainConditioning
#check vinogradovMixedMainWeylSum_eq_shiftedTailWeylSum
#check norm_vinogradovWeylSumMod_pow_le_shiftedMixedConditioning
#check normalizedVinogradovMomentMod_eq_norm_average
#check normalizedVinogradovShiftedAllCenterMixedMomentSum
#check norm_normalizedVinogradovMomentMod_le_shiftedAllCenterMixedMomentSum
#check exists_coprime_shifted_center_factor_of_exactScale
#check normalizedVinogradovShiftedExactScaleMixedMomentSum
#check normalizedVinogradovShiftedExactScaleMixedMomentSum_le_farScaleMoment
#check normalizedVinogradovShiftedTerminalMixedMomentSum
#check normalizedVinogradovShiftedTerminalMixedMomentSum_le_trivial
#check normalizedVinogradovShiftedAllCenterMixedMomentSum_eq_exactScales_add_terminal
#check normalizedVinogradovShiftedAllCenterMixedMomentSum_le_exactScales_add_terminal
#check norm_normalizedVinogradovMomentMod_le_shiftedExactScales_add_terminal
#check normalizedVinogradovShiftedExactScaleMixedMomentSum_le_trivial
#check normalizedVinogradovShiftedAllCenterMixedMomentSum_le_cutoffScales_add_trivial
#check norm_normalizedVinogradovMomentMod_le_cutoffScales_add_trivial
