import ZeroFreeRegion.VinogradovKorobov.VinogradovTranslatedMeanValue

open ZeroFreeRegion.VinogradovKorobov

#check vinogradovTranslatedSpacedSolutionPairSet
#check mem_vinogradovTranslatedSpacedSolutionPairSet_iff
#check vinogradovTranslatedSpacedSolutionPairSet_subset_farScale
#check card_vinogradovTranslatedSpacedSolutionPairSet_le_solutionCount
#check card_vinogradovTranslatedSpacedSolutionPairSet_le_normalizedMoment
#check card_vinogradovTranslatedSpacedSolutionPairSet_le_of_meanValueEstimate
