import ZeroFreeRegion.VinogradovKorobov.VinogradovTriangularElimination

#check ZeroFreeRegion.VinogradovKorobov.IsVinogradovBinomialCoefficientMatrix
#check ZeroFreeRegion.VinogradovKorobov.IsVinogradovHomogeneousCongruenceSystem
#check ZeroFreeRegion.VinogradovKorobov.intMatrix_mulVec_eq_zero_of_homogeneousCongruenceSystem
#check ZeroFreeRegion.VinogradovKorobov.intMatrix_homogeneous_elimination_of_isUnit_det
#check ZeroFreeRegion.VinogradovKorobov.vinogradovBinomial_homogeneous_elimination
