import ZeroFreeRegion.VinogradovKorobov.VinogradovTerminalTailRecurrence

open ZeroFreeRegion.VinogradovKorobov

#check norm_normalizedVinogradovMixedModConditionedMoment_sq_le_nextScaleTail
#check normalizedVinogradovShiftedTerminalMixedMomentSum_sq_le_nextScaleTail

#print axioms norm_normalizedVinogradovMixedModConditionedMoment_sq_le_nextScaleTail
#print axioms normalizedVinogradovShiftedTerminalMixedMomentSum_sq_le_nextScaleTail
