import ZeroFreeRegion.VinogradovKorobov.VinogradovCutoffParameters

open ZeroFreeRegion.VinogradovKorobov

#check VinogradovCutoffExponentParameters
#check VinogradovCutoffExponentParameters.scale_le
#check isVinogradovResidueSolution_one_one_iff
#check vinogradovSolutionCountMod_complete_one
#check normalizedVinogradovMomentMod_complete_one
#check norm_normalizedVinogradovMomentMod_complete_one
#check normalizedVinogradovCutoffRecurrenceBound
#check norm_normalizedVinogradovMomentMod_le_of_cutoffExponentParameters
#check vinogradovQuadraticUnitCutoffExponentParameters
#check vinogradovFarScale_quadratic_unitCutoff
#check norm_normalizedVinogradovMomentMod_le_quadraticUnitCutoff
#check vinogradovFarScale_quadratic
#check vinogradovQuadraticFullCutoffExponentParameters
#check norm_normalizedVinogradovMomentMod_le_quadraticFullCutoff
#check eq_of_mem_vinogradovCenterPairCongruentSet_self
#check shifted_centerDifference_eq_primePower_of_terminal_self
#check normalizedVinogradovShiftedTerminalMixedMomentSum_le_farScaleMoment_self
#check normalizedVinogradovShiftedAllCenterMixedMomentSum_le_allScales_self
#check norm_normalizedVinogradovMomentMod_le_allScales_self
#check normalizedVinogradovQuadraticAllScalesBound
#check norm_normalizedVinogradovMomentMod_le_quadraticAllScales
