import ZeroFreeRegion.VinogradovKorobov.ZetaStrip
import ZeroFreeRegion.VinogradovKorobov.TwoAProcessLogSum
import ZeroFreeRegion.VinogradovKorobov.ScaledTwoAProcessLogSum
import ZeroFreeRegion.VinogradovKorobov.ExplicitTwoAProcessBound
import ZeroFreeRegion.VinogradovKorobov.RecursiveAProcess
import ZeroFreeRegion.VinogradovKorobov.HighOrderLogDifference
import ZeroFreeRegion.VinogradovKorobov.HighOrderZetaPhase
import ZeroFreeRegion.VinogradovKorobov.RecursiveZetaAProcess
import ZeroFreeRegion.VinogradovKorobov.RecursiveZetaBounds

#print axioms ZeroFreeRegion.VinogradovKorobov.vanDerCorputFundamentalInequality
#print axioms ZeroFreeRegion.VinogradovKorobov.phaseTerm_mul_conj_shift
#print axioms ZeroFreeRegion.VinogradovKorobov.norm_linearPhaseSum_le_min
#print axioms ZeroFreeRegion.VinogradovKorobov.reciprocal_exp_sub_one_eq
#print axioms ZeroFreeRegion.VinogradovKorobov.norm_reciprocal_chord_inv_le
#print axioms ZeroFreeRegion.VinogradovKorobov.sum_norm_reciprocal_exp_sub_one_eq
#print axioms ZeroFreeRegion.VinogradovKorobov.kusminLandau_endpoint_bound
#print axioms ZeroFreeRegion.VinogradovKorobov.kusminLandau_endpoint_bound_antitone
#print axioms ZeroFreeRegion.VinogradovKorobov.kusminLandau_antitone_two_pi_div
#print axioms ZeroFreeRegion.VinogradovKorobov.logarithmicCorrelation_kusminLandau_endpoint_bound
#print axioms ZeroFreeRegion.VinogradovKorobov.logarithmicCorrelation_kusminLandau_explicit
#print axioms ZeroFreeRegion.VinogradovKorobov.norm_zetaOscillation_correlationSum_le_endpoint
#print axioms ZeroFreeRegion.VinogradovKorobov.vanDerCorputRangeInequality
#print axioms ZeroFreeRegion.VinogradovKorobov.vanDerCorputRangeOfCorrelationBounds
#print axioms ZeroFreeRegion.VinogradovKorobov.weighted_reciprocal_sum_le
#print axioms ZeroFreeRegion.VinogradovKorobov.vanDerCorputZetaOscillationWithKusminLandauOfFractionTurn
#print axioms ZeroFreeRegion.VinogradovKorobov.vanDerCorputZetaOscillationExplicit
#print axioms ZeroFreeRegion.VinogradovKorobov.norm_zetaOscillation_sum_sq_le_harmonic
#print axioms ZeroFreeRegion.VinogradovKorobov.norm_zetaOscillation_square_height_block_lt_trivial
#print axioms ZeroFreeRegion.VinogradovKorobov.weighted_sum_eq_endpoint_add_partial_sums
#print axioms ZeroFreeRegion.VinogradovKorobov.norm_weighted_sum_le_first_mul
#print axioms ZeroFreeRegion.VinogradovKorobov.inv_nat_cpow_eq_dirichletWeight_mul_zetaOscillation
#print axioms ZeroFreeRegion.VinogradovKorobov.norm_dirichletBlock_le_weight_mul
#print axioms ZeroFreeRegion.VinogradovKorobov.zetaOscillationHarmonicBound_mono_length
#print axioms ZeroFreeRegion.VinogradovKorobov.logarithmic_prefix_margin_of_scale
#print axioms ZeroFreeRegion.VinogradovKorobov.norm_zetaOscillation_prefix_le_max_sqrt_harmonic
#print axioms ZeroFreeRegion.VinogradovKorobov.norm_dirichletBlock_le_weight_mul_harmonic_end_of_scale
#print axioms ZeroFreeRegion.VinogradovKorobov.dirichletInterval_add_length
#print axioms ZeroFreeRegion.VinogradovKorobov.dirichletInterval_mul_length
#print axioms ZeroFreeRegion.VinogradovKorobov.norm_dirichletInterval_mul_le_sum_harmonic_of_scale
#print axioms ZeroFreeRegion.VinogradovKorobov.norm_dirichletInterval_le_length
#print axioms ZeroFreeRegion.VinogradovKorobov.criticalLineZetaFirstApprox_dirichletInterval
#print axioms ZeroFreeRegion.VinogradovKorobov.norm_riemannZeta_criticalLine_le_harmonic_of_scale
#print axioms ZeroFreeRegion.VinogradovKorobov.norm_criticalLine_dirichletInterval_one_le_two_sqrt
#print axioms ZeroFreeRegion.VinogradovKorobov.norm_riemannZeta_criticalLine_le_harmonic_sqrt_initial_of_scale
#print axioms ZeroFreeRegion.VinogradovKorobov.stripZetaFirstApprox_dirichletInterval
#print axioms ZeroFreeRegion.VinogradovKorobov.norm_riemannZeta_strip_le_harmonic_of_scale
#print axioms ZeroFreeRegion.VinogradovKorobov.norm_iteratedPhase_sum_sq_le_two_aProcess
#print axioms ZeroFreeRegion.VinogradovKorobov.logSecondDifference_eq
#print axioms ZeroFreeRegion.VinogradovKorobov.antitoneOn_logSecondDifferenceDecrement
#print axioms ZeroFreeRegion.VinogradovKorobov.kusminLandau_negative_antitone_two_pi_div
#print axioms ZeroFreeRegion.VinogradovKorobov.iteratedShiftedZetaPhase_two_kusminLandau_range
#print axioms ZeroFreeRegion.VinogradovKorobov.norm_zetaOscillation_sum_sq_le_two_aProcess
#print axioms ZeroFreeRegion.VinogradovKorobov.div_eightyOne_cube_le_logSecondDifferenceDecrement
#print axioms ZeroFreeRegion.VinogradovKorobov.iteratedShiftedZetaPhase_two_kusminLandau_scaled_range_of_start_scale
#print axioms ZeroFreeRegion.VinogradovKorobov.norm_zetaOscillation_sum_sq_le_scaled_two_aProcess_const
#print axioms ZeroFreeRegion.VinogradovKorobov.aProcessSquaredBound_le_sqrt_reciprocal
#print axioms ZeroFreeRegion.VinogradovKorobov.aProcess_scaledCorrelation_le_refinedInnerBound
#print axioms ZeroFreeRegion.VinogradovKorobov.norm_zetaOscillation_sum_sq_le_refined_two_aProcess_equal
#print axioms ZeroFreeRegion.VinogradovKorobov.norm_phaseSum_sq_le_recursiveAProcess
#print axioms ZeroFreeRegion.VinogradovKorobov.iteratedShiftIntegral_tower_eq_signedDifference
#print axioms ZeroFreeRegion.VinogradovKorobov.neg_realIteratedLogDifference_bounds
#print axioms ZeroFreeRegion.VinogradovKorobov.iterated_shiftedZetaPhase_kusminLandau_range
#print axioms ZeroFreeRegion.VinogradovKorobov.iterated_shiftedZetaPhase_decrement_pos
#print axioms ZeroFreeRegion.VinogradovKorobov.recursiveZetaAProcessValid_to_generic
#print axioms ZeroFreeRegion.VinogradovKorobov.norm_zetaPhase_sum_sq_le_recursiveAProcess
#print axioms ZeroFreeRegion.VinogradovKorobov.zetaAProcessLeafValid_of_scale
#print axioms ZeroFreeRegion.VinogradovKorobov.recursiveZetaAProcessValid_of_scale
#print axioms ZeroFreeRegion.VinogradovKorobov.norm_zetaPhase_sum_sq_le_recursiveAProcess_of_scale
#print axioms ZeroFreeRegion.VinogradovKorobov.zetaAProcessUniformLeafDeltaLower_le
#print axioms ZeroFreeRegion.VinogradovKorobov.zetaAProcessLeafSquaredBound_le_uniform
#print axioms ZeroFreeRegion.VinogradovKorobov.recursiveAProcessSquaredBound_le_coarse
#print axioms ZeroFreeRegion.VinogradovKorobov.recursiveZetaAProcessScaleValid_to_uniformGeneric
#print axioms ZeroFreeRegion.VinogradovKorobov.norm_zetaPhase_sum_sq_le_uniformCoarseRecursiveAProcess
