import ZeroFreeRegion.VinogradovKorobov.FordShortSumBridge
import ZeroFreeRegion.VinogradovKorobov.FordDoubleHolder
import ZeroFreeRegion.VinogradovKorobov.FordPowerSumFibers
import ZeroFreeRegion.VinogradovKorobov.FordIncompleteSupportMoment
import ZeroFreeRegion.VinogradovKorobov.FordNearInteger
import ZeroFreeRegion.VinogradovKorobov.VinogradovIncompleteMoment
import ZeroFreeRegion.VinogradovKorobov.VinogradovIncompleteSupportMoment

#print axioms ZeroFreeRegion.VinogradovKorobov.norm_dirichletInterval_le_weight_mul_of_prefix_bound
#print axioms ZeroFreeRegion.VinogradovKorobov.norm_dirichletInterval_le_fordShortSumScale
#print axioms ZeroFreeRegion.VinogradovKorobov.norm_dirichletInterval_le_sum_fordShortSumScale
#print axioms ZeroFreeRegion.VinogradovKorobov.norm_riemannZeta_strip_le_sum_fordShortSumScale
#print axioms ZeroFreeRegion.VinogradovKorobov.incompleteVinogradovSolutionSelector_eq_indicator
#print axioms ZeroFreeRegion.VinogradovKorobov.normalizedIncompleteVinogradovMomentMod_eq_solutionCount
#print axioms ZeroFreeRegion.VinogradovKorobov.isIncompleteVinogradovSolutionMod_one_iff
#print axioms ZeroFreeRegion.VinogradovKorobov.incompleteVinogradovSolutionCountMod_one_eq
#print axioms ZeroFreeRegion.VinogradovKorobov.normalizedIncompleteVinogradovMomentMod_one_eq
#print axioms ZeroFreeRegion.VinogradovKorobov.IsVinogradovSolutionMod.toIncomplete
#print axioms ZeroFreeRegion.VinogradovKorobov.vinogradovSolutionCountMod_le_incomplete
#print axioms ZeroFreeRegion.VinogradovKorobov.normalizedIncompleteMomentOnMod_eq_solutionCount
#print axioms ZeroFreeRegion.VinogradovKorobov.norm_incompleteWeylSumOnMod_le_card
#print axioms ZeroFreeRegion.VinogradovKorobov.incompleteSolutionCountOnMod_le_total
#print axioms ZeroFreeRegion.VinogradovKorobov.normalizedIncompleteVinogradovSupportMomentMod_eq_solutionCount
#print axioms ZeroFreeRegion.VinogradovKorobov.norm_incompleteVinogradovSupportWeylSumMod_le_card
#print axioms ZeroFreeRegion.VinogradovKorobov.incompleteVinogradovSupportSolutionCountMod_le_total
#print axioms ZeroFreeRegion.VinogradovKorobov.NNReal.pow_two_mul_sum_le_mass_mul_sq_mul_moment
#print axioms ZeroFreeRegion.VinogradovKorobov.nnnorm_sum_natCast_mul_pow_le_fordDoubleHolder
#print axioms ZeroFreeRegion.VinogradovKorobov.isVinogradovSolutionNat_iff_powerSumVector_eq
#print axioms ZeroFreeRegion.VinogradovKorobov.sum_vinogradovPowerSumMultiplicity_eq
#print axioms ZeroFreeRegion.VinogradovKorobov.sum_sq_vinogradovPowerSumMultiplicity_eq_solutionCountNat
#print axioms ZeroFreeRegion.VinogradovKorobov.nnnorm_fordPowerSumWeightedAmplitude_pow_le
#print axioms ZeroFreeRegion.VinogradovKorobov.sum_norm_incompleteVinogradovSupportWeylSumMod_pow_two_mul_eq
#print axioms ZeroFreeRegion.VinogradovKorobov.mem_fordNearIntegerSet
#print axioms ZeroFreeRegion.VinogradovKorobov.card_fordNearIntegerSet_le
#print axioms ZeroFreeRegion.VinogradovKorobov.card_fordNearIntegerSet_le_scaled
