import ZeroFreeRegion.VinogradovKorobov.VinogradovShiftedTerminalScale

open ZeroFreeRegion.VinogradovKorobov

#check vinogradovShiftedCenterDifferenceNat
#check vinogradovShiftedCenterDifferenceNat_pos
#check intCast_vinogradovShiftedCenterDifferenceNat
#check primePower_dvd_vinogradovShiftedCenterDifferenceNat_of_terminal
#check vinogradovShiftedCenterDifferenceNat_lt_nextPower
#check padicValNat_vinogradovShiftedCenterDifferenceNat_mem_Icc
#check exists_coprime_shifted_terminal_center_factor
#check vinogradovShiftedTerminalExactScaleSet
#check sum_vinogradovCenterPairCongruentSet_eq_shiftedTerminalExactScales
#check normalizedVinogradovShiftedTerminalMixedMomentSum_eq_higherExactScales
#check normalizedVinogradovShiftedTerminalExactScaleMixedMomentSum_le_farScaleMoment
#check normalizedVinogradovShiftedTerminalMixedMomentSum_le_higherExactScales
#check not_terminal_elimination_budget_of_main_scale_gt_tail_scale

#print axioms vinogradovShiftedCenterDifferenceNat_pos
#print axioms intCast_vinogradovShiftedCenterDifferenceNat
#print axioms primePower_dvd_vinogradovShiftedCenterDifferenceNat_of_terminal
#print axioms vinogradovShiftedCenterDifferenceNat_lt_nextPower
#print axioms padicValNat_vinogradovShiftedCenterDifferenceNat_mem_Icc
#print axioms exists_coprime_shifted_terminal_center_factor
#print axioms sum_vinogradovCenterPairCongruentSet_eq_shiftedTerminalExactScales
#print axioms normalizedVinogradovShiftedTerminalMixedMomentSum_eq_higherExactScales
#print axioms normalizedVinogradovShiftedTerminalExactScaleMixedMomentSum_le_farScaleMoment
#print axioms normalizedVinogradovShiftedTerminalMixedMomentSum_le_higherExactScales
#print axioms not_terminal_elimination_budget_of_main_scale_gt_tail_scale
