import ZeroFreeRegion.VinogradovKorobov.VinogradovPrimePowerTargetFiber

open ZeroFreeRegion.VinogradovKorobov

#check vinogradovPrimePowerTargetFiberSet
#check mem_vinogradovPrimePowerTargetFiberSet_iff
#check card_vinogradovPrimePowerTargetFiberSet_zero_le_factorial
#check vinogradovPrimePowerTargetFiberLiftSet
#check card_vinogradovPrimePowerTargetFiberLiftSet_le
#check vinogradovPrimePowerTargetFiberLiftAmbientEquiv
#check vinogradovPrimePowerTargetFiberLiftAmbientEquiv_apply_val
#check mem_vinogradovPrimePowerTargetFiberLiftSet_iff_image_mem
#check map_vinogradovPrimePowerTargetFiberLiftSet_eq
#check card_vinogradovPrimePowerTargetFiberSet_succ_le
#check card_vinogradovPrimePowerTargetFiberSet_le_factorial
#check vinogradovPrimePowerFixedRightNonsingularSet
#check card_vinogradovPrimePowerFixedRightNonsingularSet_le
#check vinogradovPrimePowerFixedRightAmbientEquiv
#check mem_vinogradovPrimePowerFixedRightNonsingularSet_iff_image_mem
#check map_vinogradovPrimePowerFixedRightNonsingularSet_eq
#check card_vinogradovPrimePowerNonsingularSolutionSet_le_fixed_right
