import ZeroFreeRegion.VinogradovKorobov.VinogradovMixedRecurrence

open ZeroFreeRegion.VinogradovKorobov

#check normalizedVinogradovAllCenterMixedMomentSum
#check normalizedVinogradovAllCenterMixedMomentSum_eq_exactScales_add_terminal
#check normalizedVinogradovAllCenterMixedMomentSum_le_exactScales_add_terminal
#check normalizedVinogradovAllCenterMixedMomentAverage
#check normalizedVinogradovAllCenterMixedMomentAverage_le_exactScales_add_terminal

#print axioms normalizedVinogradovAllCenterMixedMomentSum_eq_exactScales_add_terminal
#print axioms normalizedVinogradovAllCenterMixedMomentSum_le_exactScales_add_terminal
#print axioms normalizedVinogradovAllCenterMixedMomentAverage_le_exactScales_add_terminal
