import ZeroFreeRegion.VinogradovKorobov.VinogradovSpacedPolynomial

#check ZeroFreeRegion.VinogradovKorobov.vinogradovPolynomialSumDifference
#check ZeroFreeRegion.VinogradovKorobov.dvd_vinogradovPolynomialSumDifference_affine
#check ZeroFreeRegion.VinogradovKorobov.vinogradovSpacedPolynomial
#check ZeroFreeRegion.VinogradovKorobov.eval_vinogradovSpacedPolynomial
#check ZeroFreeRegion.VinogradovKorobov.vinogradovPolynomialSumDifference_spaced_eq
#check ZeroFreeRegion.VinogradovKorobov.vinogradovPolynomialSumDifference_spaced_affine_modEq_monomial
#check ZeroFreeRegion.VinogradovKorobov.monomial_modEq_zero_of_spaced_affine_modEq_zero
#check ZeroFreeRegion.VinogradovKorobov.vinogradovSpaced_highDegree_to_farScale_of_scales
