import ZeroFreeRegion.VinogradovKorobov.VinogradovTranslatedCoefficientMatrix

open ZeroFreeRegion.VinogradovKorobov

#check exists_vinogradovTranslatedCoefficientMatrix
#check isUnit_det_vinogradovTranslatedCoefficientMatrix
#check exists_vinogradovTranslatedCoefficientMatrix_twoSidedInverse
#check exists_vinogradovTranslatedCoefficientMatrix_leftInverse
#check coeff_vinogradovPolynomialDilation_matrixCombination
#check coeff_vinogradovTranslatedMatrixCombination_dilation
#check coeff_vinogradovTranslatedMatrixCombination_dilation_modEq_identity
#check primePower_dvd_coeff_vinogradovTranslatedMatrixCombination_dilation
