import ZeroFreeRegion.VinogradovKorobov.VinogradovTailRefinement

open ZeroFreeRegion.VinogradovKorobov

#check vinogradovMixedTailResidueWeylSum
#check vinogradovMixedTailValue_modEq_refinedCenter
#check sum_vinogradovMixedTailResidueWeylSum_eq
#check norm_vinogradovIntWeylSum_pow_le_tailResidueRefinement
#check normalizedVinogradovMixedTailOneStepRefinedNormMoment
#check normalizedVinogradovMixedTailNormMoment_le_oneStepRefinement

#print axioms sum_vinogradovMixedTailResidueWeylSum_eq
#print axioms vinogradovMixedTailValue_modEq_refinedCenter
#print axioms norm_vinogradovIntWeylSum_pow_le_tailResidueRefinement
#print axioms normalizedVinogradovMixedTailNormMoment_le_oneStepRefinement
