import ZeroFreeRegion.VinogradovKorobov.FordIncompleteSupportMoment

#print axioms ZeroFreeRegion.VinogradovKorobov.incompleteVinogradovSolutionSelector_eq_indicator
#print axioms ZeroFreeRegion.VinogradovKorobov.normalizedIncompleteVinogradovMomentMod_eq_solutionCount
#print axioms ZeroFreeRegion.VinogradovKorobov.isIncompleteVinogradovSolutionMod_one_iff
#print axioms ZeroFreeRegion.VinogradovKorobov.incompleteVinogradovSolutionCountMod_one_eq
#print axioms ZeroFreeRegion.VinogradovKorobov.normalizedIncompleteVinogradovMomentMod_one_eq
#print axioms ZeroFreeRegion.VinogradovKorobov.IsVinogradovSolutionMod.toIncomplete
#print axioms ZeroFreeRegion.VinogradovKorobov.vinogradovSolutionCountMod_le_incomplete
#print axioms ZeroFreeRegion.VinogradovKorobov.normalizedIncompleteMomentOnMod_eq_solutionCount
#print axioms ZeroFreeRegion.VinogradovKorobov.norm_incompleteWeylSumOnMod_le_card
#print axioms ZeroFreeRegion.VinogradovKorobov.incompleteSolutionCountOnMod_le_total
#print axioms ZeroFreeRegion.VinogradovKorobov.normalizedIncompleteMomentOnMod_interval_eq
#print axioms ZeroFreeRegion.VinogradovKorobov.normalizedIncompleteVinogradovSupportMomentMod_eq_solutionCount
#print axioms ZeroFreeRegion.VinogradovKorobov.norm_incompleteVinogradovSupportWeylSumMod_le_card
#print axioms ZeroFreeRegion.VinogradovKorobov.incompleteVinogradovSupportSolutionCountMod_le_total
#print axioms ZeroFreeRegion.VinogradovKorobov.sum_norm_incompleteVinogradovSupportWeylSumMod_pow_two_mul_eq
