import ZeroFreeRegion.VinogradovKorobov.ZetaStrip
import ZeroFreeRegion.VinogradovKorobov.TwoAProcessLogSum
import ZeroFreeRegion.VinogradovKorobov.ScaledTwoAProcessLogSum
import ZeroFreeRegion.VinogradovKorobov.ExplicitTwoAProcessBound
import ZeroFreeRegion.VinogradovKorobov.RecursiveAProcess
import ZeroFreeRegion.VinogradovKorobov.HighOrderLogDifference
import ZeroFreeRegion.VinogradovKorobov.HighOrderZetaPhase
import ZeroFreeRegion.VinogradovKorobov.RecursiveZetaAProcess
import ZeroFreeRegion.VinogradovKorobov.RecursiveZetaBounds
import ZeroFreeRegion.VinogradovKorobov.AProcessSchedule
import ZeroFreeRegion.VinogradovKorobov.ConstantAProcessSchedule
import ZeroFreeRegion.VinogradovKorobov.RecursiveReciprocalEnvelope
import ZeroFreeRegion.VinogradovKorobov.HybridAProcessEnvelope
import ZeroFreeRegion.VinogradovKorobov.PowerDecayAProcess
import ZeroFreeRegion.VinogradovKorobov.ConstantPowerDecayAProcess
import ZeroFreeRegion.VinogradovKorobov.ZeroFreeClosure
import ZeroFreeRegion.VinogradovKorobov.ZetaGrowthToLogDerivative
import ZeroFreeRegion.VinogradovKorobov.ParameterizedZeroRepulsion
import ZeroFreeRegion.VinogradovKorobov.VinogradovMeanValue
import ZeroFreeRegion.VinogradovKorobov.VinogradovMoment
import ZeroFreeRegion.VinogradovKorobov.VinogradovLifting
import ZeroFreeRegion.VinogradovKorobov.VinogradovBounds
import ZeroFreeRegion.VinogradovKorobov.VinogradovQuadratic
import ZeroFreeRegion.VinogradovKorobov.VinogradovMonotonicity
import ZeroFreeRegion.VinogradovKorobov.VinogradovNewton
import ZeroFreeRegion.VinogradovKorobov.VinogradovDiagonal
import ZeroFreeRegion.VinogradovKorobov.VinogradovSymmetry
import ZeroFreeRegion.VinogradovKorobov.VinogradovCongruence
import ZeroFreeRegion.VinogradovKorobov.VinogradovPrimePowerFiber

#print axioms ZeroFreeRegion.VinogradovKorobov.vanDerCorputFundamentalInequality
#print axioms ZeroFreeRegion.VinogradovKorobov.phaseTerm_mul_conj_shift
#print axioms ZeroFreeRegion.VinogradovKorobov.norm_linearPhaseSum_le_min
#print axioms ZeroFreeRegion.VinogradovKorobov.reciprocal_exp_sub_one_eq
#print axioms ZeroFreeRegion.VinogradovKorobov.norm_reciprocal_chord_inv_le
#print axioms ZeroFreeRegion.VinogradovKorobov.sum_norm_reciprocal_exp_sub_one_eq
#print axioms ZeroFreeRegion.VinogradovKorobov.kusminLandau_endpoint_bound
#print axioms ZeroFreeRegion.VinogradovKorobov.kusminLandau_endpoint_bound_antitone
#print axioms ZeroFreeRegion.VinogradovKorobov.kusminLandau_antitone_two_pi_div
#print axioms ZeroFreeRegion.VinogradovKorobov.logarithmicCorrelation_kusminLandau_endpoint_bound
#print axioms ZeroFreeRegion.VinogradovKorobov.logarithmicCorrelation_kusminLandau_explicit
#print axioms ZeroFreeRegion.VinogradovKorobov.norm_zetaOscillation_correlationSum_le_endpoint
#print axioms ZeroFreeRegion.VinogradovKorobov.vanDerCorputRangeInequality
#print axioms ZeroFreeRegion.VinogradovKorobov.vanDerCorputRangeOfCorrelationBounds
#print axioms ZeroFreeRegion.VinogradovKorobov.weighted_reciprocal_sum_le
#print axioms ZeroFreeRegion.VinogradovKorobov.vanDerCorputZetaOscillationWithKusminLandauOfFractionTurn
#print axioms ZeroFreeRegion.VinogradovKorobov.vanDerCorputZetaOscillationExplicit
#print axioms ZeroFreeRegion.VinogradovKorobov.norm_zetaOscillation_sum_sq_le_harmonic
#print axioms ZeroFreeRegion.VinogradovKorobov.norm_zetaOscillation_square_height_block_lt_trivial
#print axioms ZeroFreeRegion.VinogradovKorobov.weighted_sum_eq_endpoint_add_partial_sums
#print axioms ZeroFreeRegion.VinogradovKorobov.norm_weighted_sum_le_first_mul
#print axioms ZeroFreeRegion.VinogradovKorobov.inv_nat_cpow_eq_dirichletWeight_mul_zetaOscillation
#print axioms ZeroFreeRegion.VinogradovKorobov.norm_dirichletBlock_le_weight_mul
#print axioms ZeroFreeRegion.VinogradovKorobov.zetaOscillationHarmonicBound_mono_length
#print axioms ZeroFreeRegion.VinogradovKorobov.logarithmic_prefix_margin_of_scale
#print axioms ZeroFreeRegion.VinogradovKorobov.norm_zetaOscillation_prefix_le_max_sqrt_harmonic
#print axioms ZeroFreeRegion.VinogradovKorobov.norm_dirichletBlock_le_weight_mul_harmonic_end_of_scale
#print axioms ZeroFreeRegion.VinogradovKorobov.dirichletInterval_add_length
#print axioms ZeroFreeRegion.VinogradovKorobov.dirichletInterval_mul_length
#print axioms ZeroFreeRegion.VinogradovKorobov.norm_dirichletInterval_mul_le_sum_harmonic_of_scale
#print axioms ZeroFreeRegion.VinogradovKorobov.norm_dirichletInterval_le_length
#print axioms ZeroFreeRegion.VinogradovKorobov.criticalLineZetaFirstApprox_dirichletInterval
#print axioms ZeroFreeRegion.VinogradovKorobov.norm_riemannZeta_criticalLine_le_harmonic_of_scale
#print axioms ZeroFreeRegion.VinogradovKorobov.norm_criticalLine_dirichletInterval_one_le_two_sqrt
#print axioms ZeroFreeRegion.VinogradovKorobov.norm_riemannZeta_criticalLine_le_harmonic_sqrt_initial_of_scale
#print axioms ZeroFreeRegion.VinogradovKorobov.stripZetaFirstApprox_dirichletInterval
#print axioms ZeroFreeRegion.VinogradovKorobov.norm_riemannZeta_strip_le_harmonic_of_scale
#print axioms ZeroFreeRegion.VinogradovKorobov.norm_iteratedPhase_sum_sq_le_two_aProcess
#print axioms ZeroFreeRegion.VinogradovKorobov.logSecondDifference_eq
#print axioms ZeroFreeRegion.VinogradovKorobov.antitoneOn_logSecondDifferenceDecrement
#print axioms ZeroFreeRegion.VinogradovKorobov.kusminLandau_negative_antitone_two_pi_div
#print axioms ZeroFreeRegion.VinogradovKorobov.iteratedShiftedZetaPhase_two_kusminLandau_range
#print axioms ZeroFreeRegion.VinogradovKorobov.norm_zetaOscillation_sum_sq_le_two_aProcess
#print axioms ZeroFreeRegion.VinogradovKorobov.div_eightyOne_cube_le_logSecondDifferenceDecrement
#print axioms ZeroFreeRegion.VinogradovKorobov.iteratedShiftedZetaPhase_two_kusminLandau_scaled_range_of_start_scale
#print axioms ZeroFreeRegion.VinogradovKorobov.norm_zetaOscillation_sum_sq_le_scaled_two_aProcess_const
#print axioms ZeroFreeRegion.VinogradovKorobov.aProcessSquaredBound_le_sqrt_reciprocal
#print axioms ZeroFreeRegion.VinogradovKorobov.aProcess_scaledCorrelation_le_refinedInnerBound
#print axioms ZeroFreeRegion.VinogradovKorobov.norm_zetaOscillation_sum_sq_le_refined_two_aProcess_equal
#print axioms ZeroFreeRegion.VinogradovKorobov.norm_phaseSum_sq_le_recursiveAProcess
#print axioms ZeroFreeRegion.VinogradovKorobov.iteratedShiftIntegral_tower_eq_signedDifference
#print axioms ZeroFreeRegion.VinogradovKorobov.neg_realIteratedLogDifference_bounds
#print axioms ZeroFreeRegion.VinogradovKorobov.iterated_shiftedZetaPhase_kusminLandau_range
#print axioms ZeroFreeRegion.VinogradovKorobov.iterated_shiftedZetaPhase_decrement_pos
#print axioms ZeroFreeRegion.VinogradovKorobov.recursiveZetaAProcessValid_to_generic
#print axioms ZeroFreeRegion.VinogradovKorobov.norm_zetaPhase_sum_sq_le_recursiveAProcess
#print axioms ZeroFreeRegion.VinogradovKorobov.zetaAProcessLeafValid_of_scale
#print axioms ZeroFreeRegion.VinogradovKorobov.recursiveZetaAProcessValid_of_scale
#print axioms ZeroFreeRegion.VinogradovKorobov.norm_zetaPhase_sum_sq_le_recursiveAProcess_of_scale
#print axioms ZeroFreeRegion.VinogradovKorobov.norm_iteratedPhase_sum_sq_le_trivial
#print axioms ZeroFreeRegion.VinogradovKorobov.norm_iteratedZetaPhase_sum_sq_le_hybridLeaf
#print axioms ZeroFreeRegion.VinogradovKorobov.zetaAProcessUniformLeafDeltaLower_le
#print axioms ZeroFreeRegion.VinogradovKorobov.zetaAProcessLeafSquaredBound_le_uniform
#print axioms ZeroFreeRegion.VinogradovKorobov.zetaAProcessUniformLeafDeltaLower_mul_prod_le
#print axioms ZeroFreeRegion.VinogradovKorobov.zetaAProcessLeafSquaredBound_le_product
#print axioms ZeroFreeRegion.VinogradovKorobov.recursiveAProcessSquaredBound_le_coarse
#print axioms ZeroFreeRegion.VinogradovKorobov.recursiveZetaAProcessScaleValid_to_uniformGeneric
#print axioms ZeroFreeRegion.VinogradovKorobov.norm_zetaPhase_sum_sq_le_uniformCoarseRecursiveAProcess
#print axioms ZeroFreeRegion.VinogradovKorobov.zetaAProcessHybridLeafSquaredBound_le_productMin
#print axioms ZeroFreeRegion.VinogradovKorobov.norm_zetaPhase_sum_sq_le_hybridProductRecursiveAProcess_of_scale
#print axioms ZeroFreeRegion.VinogradovKorobov.recursiveZetaAProcessScaleValid_of_schedule
#print axioms ZeroFreeRegion.VinogradovKorobov.norm_zetaPhase_sum_sq_le_scheduledCoarseRecursiveAProcess
#print axioms ZeroFreeRegion.VinogradovKorobov.recursiveZetaAProcessHybridValid_of_schedule
#print axioms ZeroFreeRegion.VinogradovKorobov.norm_zetaPhase_sum_sq_le_scheduledHybridRecursiveAProcess
#print axioms ZeroFreeRegion.VinogradovKorobov.norm_zetaPhase_sum_sq_le_constantScheduledCoarseRecursiveAProcess
#print axioms ZeroFreeRegion.VinogradovKorobov.norm_zetaPhase_sum_sq_le_constantAProcessSquaredEnvelope
#print axioms ZeroFreeRegion.VinogradovKorobov.constantAProcessSquaredEnvelope_le_of_supersolution
#print axioms ZeroFreeRegion.VinogradovKorobov.norm_zetaPhase_sum_sq_le_constantAProcess_supersolution
#print axioms ZeroFreeRegion.VinogradovKorobov.aProcessSquaredBound_le_of_sq_reciprocal
#print axioms ZeroFreeRegion.VinogradovKorobov.aProcessSquaredBound_mono
#print axioms ZeroFreeRegion.VinogradovKorobov.aProcessSquaredBound_nonneg
#print axioms ZeroFreeRegion.VinogradovKorobov.recursiveAProcessSquaredBound_nonneg
#print axioms ZeroFreeRegion.VinogradovKorobov.aProcessSquaredBound_mul_sq_le_of_scaled_children
#print axioms ZeroFreeRegion.VinogradovKorobov.refinedRecursiveAProcessSquaredBound_nonneg
#print axioms ZeroFreeRegion.VinogradovKorobov.recursiveAProcessSquaredBound_mul_prod_sq_le_refined
#print axioms ZeroFreeRegion.VinogradovKorobov.zetaAProcessProductLeafSquaredBound_mul_prod_sq
#print axioms ZeroFreeRegion.VinogradovKorobov.recursiveZetaAProcessScaleValid_to_productGeneric
#print axioms ZeroFreeRegion.VinogradovKorobov.norm_zetaPhase_sum_sq_le_scheduledRefinedRecursiveAProcess
#print axioms ZeroFreeRegion.VinogradovKorobov.constantRefinedAProcessSquaredEnvelope_nonneg
#print axioms ZeroFreeRegion.VinogradovKorobov.refinedRecursiveAProcessSquaredBound_const
#print axioms ZeroFreeRegion.VinogradovKorobov.refinedRecursiveAProcessSquaredBound_const_root
#print axioms ZeroFreeRegion.VinogradovKorobov.norm_zetaPhase_sum_sq_le_constantRefinedAProcessSquaredEnvelope
#print axioms ZeroFreeRegion.VinogradovKorobov.constantRefinedAProcessSquaredEnvelope_le_of_finite_supersolution
#print axioms ZeroFreeRegion.VinogradovKorobov.norm_zetaPhase_sum_sq_le_constantRefined_finite_supersolution
#print axioms ZeroFreeRegion.VinogradovKorobov.constantAProcessGain_eq_rpow
#print axioms ZeroFreeRegion.VinogradovKorobov.constantAProcessPowerSupersolution_step
#print axioms ZeroFreeRegion.VinogradovKorobov.constantRefinedAProcessSquaredEnvelope_le_powerSupersolution
#print axioms ZeroFreeRegion.VinogradovKorobov.norm_zetaPhase_sum_lt_length_of_constantAProcessPowerSaving
#print axioms ZeroFreeRegion.VinogradovKorobov.zetaAProcessUniformLeafSquaredBound_normalized_le_of_scale
#print axioms ZeroFreeRegion.VinogradovKorobov.norm_zetaPhase_sum_lt_length_of_constantAProcessScaleSaving
#print axioms ZeroFreeRegion.VinogradovKorobov.constantAProcessCoefficient_le_log_sq
#print axioms ZeroFreeRegion.VinogradovKorobov.constantAProcessCoefficient_lt_gain_of_log_sq_lt_rpow
#print axioms ZeroFreeRegion.VinogradovKorobov.norm_zetaPhase_sum_lt_length_of_constantAProcessExplicitSaving
#print axioms ZeroFreeRegion.VinogradovKorobov.sqrt_constantAProcessGain_eq_rpow
#print axioms ZeroFreeRegion.VinogradovKorobov.norm_zetaPhase_sum_le_constantAProcessExplicitPower
#print axioms ZeroFreeRegion.VinogradovKorobov.norm_zetaOscillation_prefix_le_max_constantAProcessExplicitPower
#print axioms ZeroFreeRegion.VinogradovKorobov.norm_dirichletInterval_le_weight_mul_constantAProcessExplicitPower
#print axioms ZeroFreeRegion.VinogradovKorobov.dirichletInterval_division_blocks
#print axioms ZeroFreeRegion.VinogradovKorobov.norm_dirichletInterval_le_sum_constantAProcessExplicitPower
#print axioms ZeroFreeRegion.VinogradovKorobov.norm_riemannZeta_strip_le_sum_constantAProcessExplicitPower
#print axioms ZeroFreeRegion.VinogradovKorobov.zetaAProcessUniformLeafDeltaLower_antitone_endpoint
#print axioms ZeroFreeRegion.VinogradovKorobov.dirichletWeight_le_of_le
#print axioms ZeroFreeRegion.VinogradovKorobov.norm_dirichletInterval_le_sum_constantAProcessExplicitPower_of_global_scale
#print axioms ZeroFreeRegion.VinogradovKorobov.norm_dirichletInterval_le_numBlocks_mul_constantAProcessExplicitPower
#print axioms ZeroFreeRegion.VinogradovKorobov.constantAProcessBlockConditions_of_global_scale
#print axioms ZeroFreeRegion.VinogradovKorobov.norm_riemannZeta_strip_le_numBlocks_constantAProcessExplicitPower
#print axioms ZeroFreeRegion.VinogradovKorobov.zetaAProcessProductLeafSquaredBound_eq_div_prod_sq
#print axioms ZeroFreeRegion.VinogradovKorobov.zetaAProcessHybridProductLeafSquaredBound_le_envelope
#print axioms ZeroFreeRegion.VinogradovKorobov.recursiveAProcessSquaredBound_le_hybridProductEnvelope
#print axioms ZeroFreeRegion.VinogradovKorobov.norm_zetaPhase_sum_sq_le_hybridProductEnvelope_of_scale
#print axioms ZeroFreeRegion.VinogradovKorobov.sum_Icc_rpow_neg_le_envelope
#print axioms ZeroFreeRegion.VinogradovKorobov.weighted_rpow_neg_sum_le_envelope
#print axioms ZeroFreeRegion.VinogradovKorobov.aProcessSquaredBound_le_sqrt_add_rpow
#print axioms ZeroFreeRegion.VinogradovKorobov.hybridProductLeafSquaredEnvelope_le_power
#print axioms ZeroFreeRegion.VinogradovKorobov.hybridProductRecursiveAProcessSquaredBound_le_powerDecay
#print axioms ZeroFreeRegion.VinogradovKorobov.norm_zetaPhase_sum_sq_le_powerDecayEnvelope_of_scale
#print axioms ZeroFreeRegion.VinogradovKorobov.finiteRpowSumEnvelope_div_le_rpow
#print axioms ZeroFreeRegion.VinogradovKorobov.aProcessPowerDecayExponent_eq
#print axioms ZeroFreeRegion.VinogradovKorobov.aProcessPowerDecayCoefficient_succ_le_rpow
#print axioms ZeroFreeRegion.VinogradovKorobov.constantPowerDecayCoefficientMajorant_nonneg
#print axioms ZeroFreeRegion.VinogradovKorobov.aProcessPowerDecayCoefficient_const_le_majorant
#print axioms ZeroFreeRegion.VinogradovKorobov.norm_zetaPhase_sum_sq_le_constantPowerDecayMajorant
#print axioms ZeroFreeRegion.VinogradovKorobov.vinogradov_korobov_zero_free_region_iff_width
#print axioms ZeroFreeRegion.VinogradovKorobov.vinogradovKorobovScale_pos
#print axioms ZeroFreeRegion.VinogradovKorobov.vinogradovKorobovEta_pos
#print axioms ZeroFreeRegion.VinogradovKorobov.log_log_div_vinogradovKorobovEta_eq_scale
#print axioms ZeroFreeRegion.VinogradovKorobov.vinogradovKorobovWidth_eq_div_scale
#print axioms ZeroFreeRegion.VinogradovKorobov.vinogradovKorobovScale_mono
#print axioms ZeroFreeRegion.VinogradovKorobov.three_four_one_zero_free_high_height_of_width
#print axioms ZeroFreeRegion.VinogradovKorobov.vinogradov_korobov_zero_free_region_of_log_deriv_bounds_at_three
#print axioms ZeroFreeRegion.VinogradovKorobov.vinogradovKorobovWidth_le_at_three
#print axioms ZeroFreeRegion.VinogradovKorobov.compact_patch_vinogradov_korobov_zero_free_region
#print axioms ZeroFreeRegion.VinogradovKorobov.fixedJensenLogEnvelope_le_constant_mul_one_add
#print axioms ZeroFreeRegion.VinogradovKorobov.norm_regularized_logDeriv_riemannZeta_le_of_fixed_jensen_log_growth
#print axioms ZeroFreeRegion.VinogradovKorobov.re_neg_deriv_div_riemannZeta_le_neg_inv_add_of_fixed_jensen_log_growth
#print axioms ZeroFreeRegion.VinogradovKorobov.re_neg_deriv_div_riemannZeta_le_of_fixed_jensen_log_growth
#print axioms ZeroFreeRegion.VinogradovKorobov.norm_regularized_logDeriv_riemannZeta_le_of_parameterized_jensen_growth
#print axioms ZeroFreeRegion.VinogradovKorobov.re_neg_deriv_div_riemannZeta_le_neg_inv_add_of_parameterized_jensen_growth
#print axioms ZeroFreeRegion.VinogradovKorobov.re_neg_deriv_div_riemannZeta_le_of_parameterized_jensen_growth
#print axioms ZeroFreeRegion.VinogradovKorobov.sum_stdAddChar_mul
#print axioms ZeroFreeRegion.VinogradovKorobov.normalized_sum_stdAddChar_mul
#print axioms ZeroFreeRegion.VinogradovKorobov.vinogradovSolutionSelector_eq_indicator
#print axioms ZeroFreeRegion.VinogradovKorobov.sum_vinogradovSolutionSelector_eq_count
#print axioms ZeroFreeRegion.VinogradovKorobov.vinogradovWeylSumMod_pow
#print axioms ZeroFreeRegion.VinogradovKorobov.conj_stdAddChar
#print axioms ZeroFreeRegion.VinogradovKorobov.conj_vinogradovWeylSumMod_pow
#print axioms ZeroFreeRegion.VinogradovKorobov.vinogradovTuplePhaseMod_eq_sum_powerSum
#print axioms ZeroFreeRegion.VinogradovKorobov.vinogradovTuplePhaseMod_sub_eq
#print axioms ZeroFreeRegion.VinogradovKorobov.stdAddChar_tuple_mul_neg_tuple
#print axioms ZeroFreeRegion.VinogradovKorobov.sum_stdAddChar_coefficient_pairing
#print axioms ZeroFreeRegion.VinogradovKorobov.normalized_sum_tuplePair_eq_selector
#print axioms ZeroFreeRegion.VinogradovKorobov.normalizedVinogradovMomentMod_eq_solutionCount
#print axioms ZeroFreeRegion.VinogradovKorobov.natCast_vinogradovPowerSumNat
#print axioms ZeroFreeRegion.VinogradovKorobov.IsVinogradovSolutionNat.toMod
#print axioms ZeroFreeRegion.VinogradovKorobov.IsVinogradovSolutionMod.toNat_of_lt
#print axioms ZeroFreeRegion.VinogradovKorobov.vinogradovPowerSumNat_le
#print axioms ZeroFreeRegion.VinogradovKorobov.isVinogradovSolutionMod_iff_nat_of_scale
#print axioms ZeroFreeRegion.VinogradovKorobov.vinogradovSolutionCountMod_eq_nat_of_scale
#print axioms ZeroFreeRegion.VinogradovKorobov.vinogradovSolutionCountMod_eq_nat_of_topScale
#print axioms ZeroFreeRegion.VinogradovKorobov.normalizedVinogradovMomentMod_eq_natCount_of_topScale
#print axioms ZeroFreeRegion.VinogradovKorobov.vinogradovSolutionCountNat_le_total
#print axioms ZeroFreeRegion.VinogradovKorobov.pow_le_vinogradovSolutionCountNat
#print axioms ZeroFreeRegion.VinogradovKorobov.isVinogradovSolutionNat_one_iff
#print axioms ZeroFreeRegion.VinogradovKorobov.vinogradovSolutionCountNat_one
#print axioms ZeroFreeRegion.VinogradovKorobov.normalizedVinogradovMomentMod_one
#print axioms ZeroFreeRegion.VinogradovKorobov.fixed_left_solution_count_le
#print axioms ZeroFreeRegion.VinogradovKorobov.vinogradovSolutionCountNat_le_firstPower
#print axioms ZeroFreeRegion.VinogradovKorobov.norm_normalizedVinogradovMomentMod_le_firstPower
#print axioms ZeroFreeRegion.VinogradovKorobov.pair_eq_or_swap_of_sum_sq
#print axioms ZeroFreeRegion.VinogradovKorobov.isVinogradovSolutionNat_two_eq_or_swap
#print axioms ZeroFreeRegion.VinogradovKorobov.fixed_left_quadratic_solution_count_le_two
#print axioms ZeroFreeRegion.VinogradovKorobov.vinogradovSolutionCountNat_two_two_le
#print axioms ZeroFreeRegion.VinogradovKorobov.norm_normalizedVinogradovMomentMod_two_two_le
#print axioms ZeroFreeRegion.VinogradovKorobov.IsVinogradovSolutionNat.mono_degree
#print axioms ZeroFreeRegion.VinogradovKorobov.vinogradovSolutionCountNat_antitone_degree
#print axioms ZeroFreeRegion.VinogradovKorobov.vinogradovSolutionCountNat_two_le_of_two_le_degree
#print axioms ZeroFreeRegion.VinogradovKorobov.norm_normalizedVinogradovMomentMod_le_of_count
#print axioms ZeroFreeRegion.VinogradovKorobov.norm_normalizedVinogradovMomentMod_two_le_of_two_le_degree
#print axioms ZeroFreeRegion.VinogradovKorobov.multiset_eq_of_powerSums_eq
#print axioms ZeroFreeRegion.VinogradovKorobov.IsVinogradovSolutionNat.multiset_eq
#print axioms ZeroFreeRegion.VinogradovKorobov.fixed_left_solution_count_le_factorial
#print axioms ZeroFreeRegion.VinogradovKorobov.vinogradovSolutionCountNat_le_diagonal
#print axioms ZeroFreeRegion.VinogradovKorobov.norm_normalizedVinogradovMomentMod_le_diagonal
#print axioms ZeroFreeRegion.VinogradovKorobov.IsVinogradovSolutionInt.translate
#print axioms ZeroFreeRegion.VinogradovKorobov.IsVinogradovSolutionInt.scale
#print axioms ZeroFreeRegion.VinogradovKorobov.isVinogradovSolutionInt_translate_iff
#print axioms ZeroFreeRegion.VinogradovKorobov.isVinogradovSolutionInt_scale_iff
#print axioms ZeroFreeRegion.VinogradovKorobov.IsVinogradovSolutionNat.toInt
#print axioms ZeroFreeRegion.VinogradovKorobov.exists_affineCoordinates_of_forall_modEq
#print axioms ZeroFreeRegion.VinogradovKorobov.isVinogradovSolutionInt_affine_iff
#print axioms ZeroFreeRegion.VinogradovKorobov.IsVinogradovSolutionInt.rescale_of_common_modEq
#print axioms ZeroFreeRegion.VinogradovKorobov.vinogradovMeanValueEstimate_diagonal
#print axioms ZeroFreeRegion.VinogradovKorobov.norm_normalizedVinogradovMomentMod_le_of_meanValueEstimate
#print axioms ZeroFreeRegion.VinogradovKorobov.sum_norm_vinogradovWeylSumMod_pow_two_mul_eq
#print axioms ZeroFreeRegion.VinogradovKorobov.card_largeVinogradovCoefficientSet_mul_pow_le
#print axioms ZeroFreeRegion.VinogradovKorobov.card_largeVinogradovCoefficientSet_mul_pow_le_of_meanValueEstimate
#print axioms ZeroFreeRegion.VinogradovKorobov.norm_vinogradovWeylSumMod_le
#print axioms ZeroFreeRegion.VinogradovKorobov.sum_norm_vinogradovWeylSumMod_pow_add_le
#print axioms ZeroFreeRegion.VinogradovKorobov.vinogradovSolutionCountMod_add_le
#print axioms ZeroFreeRegion.VinogradovKorobov.vinogradovSolutionCountNat_add_le
#print axioms ZeroFreeRegion.VinogradovKorobov.vinogradovCriticalWeight_one
#print axioms ZeroFreeRegion.VinogradovKorobov.vinogradovMeanValueEstimate_linear
#print axioms ZeroFreeRegion.VinogradovKorobov.vinogradovPowerSumJacobian_eq_diagonal_mul_vandermonde_transpose
#print axioms ZeroFreeRegion.VinogradovKorobov.det_vinogradovPowerSumJacobian
#print axioms ZeroFreeRegion.VinogradovKorobov.det_vinogradovPowerSumJacobian_ne_zero
#print axioms ZeroFreeRegion.VinogradovKorobov.det_vinogradovPowerSumJacobian_zmod_ne_zero
#print axioms ZeroFreeRegion.VinogradovKorobov.int_pow_add_mul_modEq_sq
#print axioms ZeroFreeRegion.VinogradovKorobov.vinogradovPowerSumInt_affine_modEq_sq
#print axioms ZeroFreeRegion.VinogradovKorobov.existsUnique_mulVec_eq_of_det_ne_zero
#print axioms ZeroFreeRegion.VinogradovKorobov.existsUnique_vinogradovPowerSumJacobian_zmod_mulVec_eq
#print axioms ZeroFreeRegion.VinogradovKorobov.vinogradovPowerSumInt_affine_corrections_unique_mod_prime
#print axioms ZeroFreeRegion.VinogradovKorobov.exists_vinogradovPowerSumInt_affine_lift_mod_prime_sq
#print axioms ZeroFreeRegion.VinogradovKorobov.exists_unique_mod_vinogradovPowerSumInt_affine_lift_mod_prime_sq
#print axioms ZeroFreeRegion.VinogradovKorobov.vinogradovPowerSumInt_affine_modEq_mul_of_dvd
#print axioms ZeroFreeRegion.VinogradovKorobov.vinogradovPowerSumInt_affine_corrections_unique_mod_prime_at_scale
#print axioms ZeroFreeRegion.VinogradovKorobov.exists_unique_mod_vinogradovPowerSumInt_affine_lift_mod_prime_at_scale
#print axioms ZeroFreeRegion.VinogradovKorobov.exists_unique_mod_vinogradovPowerSumInt_affine_lift_mod_prime_pow_succ
#print axioms ZeroFreeRegion.VinogradovKorobov.vinogradovPowerSumInt_modEq
#print axioms ZeroFreeRegion.VinogradovKorobov.card_vinogradovPrimePowerCorrectionSet_eq_one
#print axioms ZeroFreeRegion.VinogradovKorobov.card_vinogradovNonsingularResidueSet
#print axioms ZeroFreeRegion.VinogradovKorobov.card_nonsingular_add_card_singular
#print axioms ZeroFreeRegion.VinogradovKorobov.card_vinogradovSingularResidueSet
#print axioms ZeroFreeRegion.VinogradovKorobov.card_vinogradovNonsingularPrimePowerLiftSet
#print axioms ZeroFreeRegion.VinogradovKorobov.pow_sub_descFactorial_le_sq_mul_pow_pred
#print axioms ZeroFreeRegion.VinogradovKorobov.card_vinogradovSingularResidueSet_le_sq_mul_pow_pred
