import ZeroFreeRegion.VinogradovKorobov.VinogradovTranslatedBlockDecomposition

open ZeroFreeRegion.VinogradovKorobov

#check vinogradovSolutionCountMod_mono_length
#check norm_normalizedTranslatedVinogradovMomentMod_mono_length
#check normalizedTranslatedVinogradovMomentMod_eq_norm_average
#check vinogradovTranslatedWeylSumMod_add_length
#check vinogradovTranslatedWeylSumMod_mul_length
#check vinogradovTranslatedWeylSumMod_division_blocks
#check norm_normalizedTranslatedVinogradovMomentMod_le_division_blocks
#check primeCubic_completeBlockSaving_sq_lt_trivial
#check norm_normalizedTranslatedVinogradovMomentMod_le_primeCubic_blockCoverSaving
