import ZeroFreeRegion.VinogradovKorobov.VinogradovMixedRecurrence

open ZeroFreeRegion.VinogradovKorobov

#check VinogradovMixedMainFarScalePairMem
#check vinogradovResidueSolutionPairSet
#check card_vinogradovResidueSolutionPairSet
#check vinogradovMixedMainFarScalePairSet
#check mem_vinogradovMixedMainFarScalePairSet_iff
#check vinogradovMixedMainAffineCoordinatePair
#check vinogradovMixedMainAffineCoordinatePair_spec
#check vinogradovMixedMainFarScaleResidueMap
#check vinogradovMixedMainFarScaleResidueMap_mem
#check vinogradovMixedMainFarScaleResidueMap_injOn
#check card_vinogradovMixedMainFarScalePairSet_le_solutionCount
#check vinogradovMixedModConditionedSolutionSet_subset_mainFarScale_product
#check card_vinogradovMixedModConditionedSolutionSet_le_mainFarScale
#check card_vinogradovMixedModConditionedSolutionSet_le_solutionCount
#check norm_normalizedVinogradovMixedModConditionedMoment_le_mainFarScale
#check norm_normalizedVinogradovMixedModConditionedMoment_le_farScaleMoment
#check norm_normalizedVinogradovMixedModConditionedMoment_le_primePowerStrata
#check vinogradovUnitSeparatedCenterPairSet
#check mem_vinogradovUnitSeparatedCenterPairSet_iff
#check normalizedVinogradovUnitSeparatedMixedMomentSum
#check normalizedVinogradovUnitSeparatedMixedMomentSum_le_farScaleMoment
#check card_vinogradovUnitSeparatedCenterPairSet
#check normalizedVinogradovUnitSeparatedMixedMomentSum_le_farScaleMoment_explicit
#check normalizedVinogradovUnitSeparatedMixedMomentAverage
#check normalizedVinogradovUnitSeparatedMixedMomentAverage_le_farScaleMoment
#check vinogradovCenterPairExactScaleSet
#check card_vinogradovCenterPairExactScaleSet
#check normalizedVinogradovExactScaleMixedMomentSum
#check normalizedVinogradovExactScaleMixedMomentSum_le_farScaleMoment
#check normalizedVinogradovExactScaleMixedMomentAverage
#check normalizedVinogradovExactScaleMixedMomentAverage_le_farScaleMoment
#check vinogradovCenterPairCongruentSet
#check sum_vinogradovCenterPairCongruentSet_eq_exact_add_next
#check sum_vinogradovCenterPairCongruentSet_zero_eq_exactScales_add
#check sum_univ_centerPairs_eq_exactScales_add_terminal
#check card_vinogradovCenterPairCongruentSet_self
#check card_vinogradovMixedModConditionedSolutionSet_le_trivial
#check norm_normalizedVinogradovMixedModConditionedMoment_le_trivial
#check normalizedVinogradovTerminalMixedMomentSum
#check normalizedVinogradovTerminalMixedMomentSum_le_trivial
#check normalizedVinogradovAllCenterMixedMomentSum
#check normalizedVinogradovAllCenterMixedMomentSum_eq_exactScales_add_terminal
#check normalizedVinogradovAllCenterMixedMomentSum_le_exactScales_add_terminal
#check normalizedVinogradovAllCenterMixedMomentAverage
#check normalizedVinogradovAllCenterMixedMomentAverage_le_exactScales_add_terminal

#print axioms vinogradovMixedModConditionedSolutionSet_subset_mainFarScale_product
#print axioms card_vinogradovResidueSolutionPairSet
#print axioms vinogradovMixedMainFarScaleResidueMap_injOn
#print axioms card_vinogradovMixedMainFarScalePairSet_le_solutionCount
#print axioms card_vinogradovMixedModConditionedSolutionSet_le_mainFarScale
#print axioms card_vinogradovMixedModConditionedSolutionSet_le_solutionCount
#print axioms norm_normalizedVinogradovMixedModConditionedMoment_le_mainFarScale
#print axioms norm_normalizedVinogradovMixedModConditionedMoment_le_farScaleMoment
#print axioms norm_normalizedVinogradovMixedModConditionedMoment_le_primePowerStrata
#print axioms normalizedVinogradovUnitSeparatedMixedMomentSum_le_farScaleMoment
#print axioms card_vinogradovUnitSeparatedCenterPairSet
#print axioms normalizedVinogradovUnitSeparatedMixedMomentSum_le_farScaleMoment_explicit
#print axioms normalizedVinogradovUnitSeparatedMixedMomentAverage_le_farScaleMoment
#print axioms card_vinogradovCenterPairExactScaleSet
#print axioms normalizedVinogradovExactScaleMixedMomentSum_le_farScaleMoment
#print axioms normalizedVinogradovExactScaleMixedMomentAverage_le_farScaleMoment
#print axioms sum_vinogradovCenterPairCongruentSet_eq_exact_add_next
#print axioms sum_vinogradovCenterPairCongruentSet_zero_eq_exactScales_add
#print axioms sum_univ_centerPairs_eq_exactScales_add_terminal
#print axioms card_vinogradovCenterPairCongruentSet_self
#print axioms card_vinogradovMixedModConditionedSolutionSet_le_trivial
#print axioms norm_normalizedVinogradovMixedModConditionedMoment_le_trivial
#print axioms normalizedVinogradovTerminalMixedMomentSum_le_trivial
#print axioms normalizedVinogradovAllCenterMixedMomentSum_eq_exactScales_add_terminal
#print axioms normalizedVinogradovAllCenterMixedMomentSum_le_exactScales_add_terminal
#print axioms normalizedVinogradovAllCenterMixedMomentAverage_le_exactScales_add_terminal
