import ZeroFreeRegion.VinogradovKorobov.VinogradovTailIteration

open ZeroFreeRegion.VinogradovKorobov

#check normalizedVinogradovMixedTailIteratedNormMoment
#check normalizedVinogradovMixedTailIteratedNormMoment_zero
#check normalizedVinogradovMixedTailIteratedNormMoment_succ
#check normalizedVinogradovMixedTailNormMoment_le_iterated
#check vinogradovTailPathLength
#check vinogradovTailResidueLength_le_ceilDiv
#check vinogradovTailPathLength_le_one_of_length_le_pow
#check normalizedVinogradovMixedTailNormMoment_le_trivial
#check normalizedVinogradovMixedTailIteratedNormMoment_le_leafCount
#check normalizedVinogradovMixedTailNormMoment_le_iterated_trivial
#check vinogradovTailLengthEnvelope
#check vinogradovTailLengthEnvelope_zero
#check vinogradovTailLengthEnvelope_succ
#check vinogradovTailLengthEnvelope_mono
#check normalizedVinogradovMixedTailIteratedNormMoment_le_uniformLeaf
#check normalizedVinogradovMixedTailIteratedNormMoment_le_firstPower
#check normalizedVinogradovMixedTailNormMoment_le_iteratedFirstPower
#check vinogradovTailLength_le_pow_mul_envelope
#check vinogradovTailLengthEnvelope_firstPower_condition_implies_root

#print axioms normalizedVinogradovMixedTailIteratedNormMoment_zero
#print axioms normalizedVinogradovMixedTailIteratedNormMoment_succ
#print axioms normalizedVinogradovMixedTailNormMoment_le_iterated
#print axioms vinogradovTailResidueLength_le_ceilDiv
#print axioms vinogradovTailPathLength_le_one_of_length_le_pow
#print axioms normalizedVinogradovMixedTailNormMoment_le_trivial
#print axioms normalizedVinogradovMixedTailIteratedNormMoment_le_leafCount
#print axioms normalizedVinogradovMixedTailNormMoment_le_iterated_trivial
#print axioms vinogradovTailLengthEnvelope_zero
#print axioms vinogradovTailLengthEnvelope_succ
#print axioms vinogradovTailLengthEnvelope_mono
#print axioms normalizedVinogradovMixedTailIteratedNormMoment_le_uniformLeaf
#print axioms normalizedVinogradovMixedTailIteratedNormMoment_le_firstPower
#print axioms normalizedVinogradovMixedTailNormMoment_le_iteratedFirstPower
#print axioms vinogradovTailLength_le_pow_mul_envelope
#print axioms vinogradovTailLengthEnvelope_firstPower_condition_implies_root
