import ZeroFreeRegion.VinogradovKorobov.VinogradovMultiBlockCollisionFiber

open ZeroFreeRegion.VinogradovKorobov

#check vinogradovCollisionDeletedIndex
#check vinogradovCollisionKeptIndex
#check VinogradovMultiBlockCollisionReducedIndex
#check vinogradovCollisionKeptReducedIndex
#check vinogradovMultiBlockCollisionReconstruct
#check vinogradovMultiBlockCollisionReconstruct_deleted
#check vinogradovMultiBlockCollisionReconstruct_kept
#check VinogradovMultiBlockCollisionFiber
#check vinogradovMultiBlockCollisionFiberEquiv
#check card_vinogradovMultiBlockCollisionDeletedIndex
#check card_vinogradovMultiBlockCollisionReducedIndex
#check card_vinogradovMultiBlockCollisionReducedIndex_block
#check card_vinogradovMultiBlockCollisionFiber
#check vinogradovMultiBlockCollisionFiberEmbedding
#check vinogradovFixedMultiBlockCollisionTupleSet
#check mem_vinogradovFixedMultiBlockCollisionTupleSet_iff
#check card_vinogradovFixedMultiBlockCollisionTupleSet
#check vinogradovFixedMultiBlockCollisionUnionSet
#check mem_vinogradovFixedMultiBlockCollisionUnionSet_iff
#check vinogradovFixedMultiBlockCollisionUnionSet_eq_singular
#check card_vinogradovFixedMultiBlockCollisionUnionSet_le
