import ZeroFreeRegion.VinogradovKorobov.VinogradovTailResidueReparameterization

open ZeroFreeRegion.VinogradovKorobov

#check vinogradovPositiveResidueRepresentative
#check vinogradovTailResidueLength
#check vinogradovTailResidueIndex
#check vinogradovTailResidueIndex_mem
#check card_vinogradovResidueClassFinset_eq_tailResidueLength
#check vinogradovMixedTailResidueWeylSum_eq_refinedTailWeylSum
#check normalizedVinogradovMixedTailOneStepRefinedNormMoment_eq_nextScale
#check normalizedVinogradovMixedTailNormMoment_le_nextScaleResidueSum

#print axioms vinogradovTailResidueIndex_mem
#print axioms card_vinogradovResidueClassFinset_eq_tailResidueLength
#print axioms vinogradovMixedTailResidueWeylSum_eq_refinedTailWeylSum
#print axioms normalizedVinogradovMixedTailOneStepRefinedNormMoment_eq_nextScale
#print axioms normalizedVinogradovMixedTailNormMoment_le_nextScaleResidueSum
