import ZeroFreeRegion.VinogradovKorobov.VinogradovConditionedMoment

open ZeroFreeRegion.VinogradovKorobov

#check vinogradovWeightedResidueWeylSum
#check vinogradovWeightedConditionedMoment
#check vinogradovWeightedConditionedMoment_le_refinement
