import ZeroFreeRegion.VinogradovKorobov.VinogradovPrimePowerCollisionFiber

open ZeroFreeRegion.VinogradovKorobov

#check vinogradovPrimePowerFixedCollisionAmbientSet
#check mem_vinogradovPrimePowerFixedCollisionAmbientSet_iff
#check card_vinogradovPrimePowerFixedCollisionAmbientSet_zero
#check vinogradovPrimePowerLiftAmbientEquiv_fixedCollision_iff
#check vinogradovPrimePowerFixedCollisionAmbientLiftSet
#check card_vinogradovPrimePowerFixedCollisionAmbientLiftSet
#check mem_vinogradovPrimePowerFixedCollisionAmbientLiftSet_iff_image_mem
#check map_vinogradovPrimePowerFixedCollisionAmbientLiftSet_eq
#check card_vinogradovPrimePowerFixedCollisionAmbientSet_succ
#check card_vinogradovPrimePowerFixedCollisionAmbientSet_eq_base_mul_pow
#check card_vinogradovPrimePowerFixedCollisionAmbientSet
#check vinogradovPrimePowerFixedCollisionAmbientUnionSet
#check mem_vinogradovPrimePowerFixedCollisionAmbientUnionSet_iff
#check vinogradovPrimePowerFixedCollisionAmbientUnionSet_eq_singular
#check card_vinogradovPrimePowerFixedCollisionAmbientUnionSet_le
#check card_vinogradovPrimePowerMultiBlockSingularAmbientSet_le_collision
