import ZeroFreeRegion.VinogradovKorobov.VinogradovMixedHolder

open ZeroFreeRegion.VinogradovKorobov

#check normalizedVinogradovMixedMainNormMoment
#check normalizedVinogradovMixedTailNormMoment
#check normalizedVinogradovMixedModConditionedMoment_eq_norm_product_average
#check norm_normalizedVinogradovMixedModConditionedMoment_sq_le_separateMoments

#print axioms normalizedVinogradovMixedModConditionedMoment_eq_norm_product_average
#print axioms norm_normalizedVinogradovMixedModConditionedMoment_sq_le_separateMoments
