import ZeroFreeRegion.VinogradovKorobov.VinogradovResidueMassAudit

open ZeroFreeRegion.VinogradovKorobov

#check vinogradovResidueMassSq_one_eq_card
#check vinogradovResidueMass_one_sq_eq_card
#check vinogradovResidueMass_one_evenPow_eq_card_pow
#check vinogradovResidueMassSq_one_eq_tailResidueLength
#check vinogradovResidueMass_one_evenPow_eq_tailResidueLength_pow
#check vinogradovMixedNormalizedResidueMoment_one_to_raw
#check card_vinogradovResidueClassFinset_completePrimePowerBlock
#check card_vinogradovResidueClassFinset_nestedPrimePowerBlock
#check vinogradovResidueMass_one_evenPow_eq_nestedPrimePowerBlock_pow
#check vinogradovMixedRawResidueNormMoment_one_le_refinement_via_normalized

#print axioms vinogradovResidueMassSq_one_eq_card
#print axioms vinogradovResidueMass_one_evenPow_eq_card_pow
#print axioms vinogradovResidueMassSq_one_eq_tailResidueLength
#print axioms vinogradovMixedNormalizedResidueMoment_one_to_raw
#print axioms card_vinogradovResidueClassFinset_nestedPrimePowerBlock
#print axioms vinogradovMixedRawResidueNormMoment_one_le_refinement_via_normalized
