import ZeroFreeRegion.VinogradovKorobov.VinogradovLowDiversityPrimePower

open ZeroFreeRegion.VinogradovKorobov

#check vinogradovPrimePowerBaseLeftResidue
#check vinogradovPrimePowerBaseRightResidue
#check vinogradovPrimePowerLiftAmbientEquiv_leftResidue
#check vinogradovPrimePowerLiftAmbientEquiv_rightResidue
#check vinogradovPrimePowerLowDiversityAmbientSet
#check mem_vinogradovPrimePowerLowDiversityAmbientSet_iff
#check vinogradovPrimePowerLowDiversityBaseZeroEquiv
#check card_vinogradovPrimePowerLowDiversityAmbientSet_zero_le
#check vinogradovPrimePowerLowDiversityAmbientLiftSet
#check card_vinogradovPrimePowerLowDiversityAmbientLiftSet
#check mem_vinogradovPrimePowerLowDiversityAmbientLiftSet_iff_image_mem
#check map_vinogradovPrimePowerLowDiversityAmbientLiftSet_eq
#check card_vinogradovPrimePowerLowDiversityAmbientSet_succ
#check card_vinogradovPrimePowerLowDiversityAmbientSet_le
