import ZeroFreeRegion.VinogradovKorobov.VinogradovMixedMoment

open ZeroFreeRegion.VinogradovKorobov

#check VinogradovMixedMainResidueMem
#check vinogradovMixedModSolutionSelector
#check vinogradovMixedModSolutionSelector_eq_indicator
#check normalizedVinogradovMixedModExpandedMoment
#check normalizedVinogradovMixedModExpandedMoment_eq_solutionSetCard
#check vinogradovMixedMainWeylSum
#check vinogradovMixedMainWeylSum_pow
#check conj_vinogradovMixedMainWeylSum_pow
#check normalizedVinogradovMixedModConditionedMoment
#check normalizedVinogradovMixedModConditionedMoment_eq_expandedMoment
#check normalizedVinogradovMixedModConditionedMoment_eq_solutionSetCard

#print axioms vinogradovMixedModSolutionSelector_eq_indicator
#print axioms normalizedVinogradovMixedModExpandedMoment_eq_solutionSetCard
#print axioms vinogradovMixedMainWeylSum_pow
#print axioms normalizedVinogradovMixedModConditionedMoment_eq_solutionSetCard
