import ZeroFreeRegion.VinogradovKorobov.VinogradovMixedSchedule

open ZeroFreeRegion.VinogradovKorobov

#check normalizedVinogradovUnitSeparatedMixedMomentAverage_le_optimizedBalancedTail_sqrt
#check norm_normalizedVinogradovMixedModConditionedMoment_le_min_farScale_completeBlockFactorialTail
#check normalizedVinogradovShiftedExactScaleMixedMomentSum_le_card_mul_min_farScale_completeBlockFactorialTail
#check normalizedVinogradovShiftedAllCenterMixedMomentSum_le_hybridExactScales_add_terminal
#check norm_normalizedVinogradovMomentMod_le_hybridExactScales_add_terminal

#print axioms normalizedVinogradovUnitSeparatedMixedMomentAverage_le_optimizedBalancedTail_sqrt
#print axioms norm_normalizedVinogradovMixedModConditionedMoment_le_min_farScale_completeBlockFactorialTail
#print axioms normalizedVinogradovShiftedExactScaleMixedMomentSum_le_card_mul_min_farScale_completeBlockFactorialTail
#print axioms normalizedVinogradovShiftedAllCenterMixedMomentSum_le_hybridExactScales_add_terminal
#print axioms norm_normalizedVinogradovMomentMod_le_hybridExactScales_add_terminal
