import ZeroFreeRegion.VinogradovKorobov.VinogradovMixedConditionedSolution

open ZeroFreeRegion.VinogradovKorobov

#check vinogradovMixedConditionedSolutionSet
#check mem_vinogradovMixedConditionedSolutionSet_iff
#check VinogradovMixedConditionedSolutionMem.centered_weightedSolution
#check VinogradovMixedConditionedSolutionMem.exists_main_affineCoordinates
#check VinogradovMixedConditionedSolutionMem.exists_farScale_powerSumCongruences
#check IsVinogradovMixedAffineCongruenceInt
#check IsVinogradovMixedAffineCongruenceInt.centered_modEq
#check vinogradovMixedModConditionedSolutionSet
#check mem_vinogradovMixedModConditionedSolutionSet_iff
#check VinogradovMixedModConditionedSolutionMem.exists_farScale_powerSumCongruences

#print axioms VinogradovMixedConditionedSolutionMem.centered_weightedSolution
#print axioms VinogradovMixedConditionedSolutionMem.exists_main_affineCoordinates
#print axioms VinogradovMixedConditionedSolutionMem.exists_farScale_powerSumCongruences
#print axioms IsVinogradovMixedAffineCongruenceInt.centered_modEq
#print axioms VinogradovMixedModConditionedSolutionMem.exists_farScale_powerSumCongruences
