import ZeroFreeRegion.VinogradovKorobov.VinogradovPrimePowerTargetFiber

open ZeroFreeRegion.VinogradovKorobov

#check vinogradovPrimePowerTargetFiberSet
#check mem_vinogradovPrimePowerTargetFiberSet_iff
#check card_vinogradovPrimePowerTargetFiberSet_zero_le_factorial
