import ZeroFreeRegion.VinogradovKorobov.VinogradovCorrectionFiber

open ZeroFreeRegion.VinogradovKorobov

#check vinogradovPrimePowerCorrectionPairEquiv
#check vinogradovPrimePowerCorrectionPairEquiv_apply_fst
#check vinogradovPrimePowerCorrectionPairEquiv_apply_snd
#check vinogradovPrimePowerCorrectionSolutionSet
#check mem_vinogradovPrimePowerCorrectionSolutionSet_iff
#check vinogradovPrimePowerBaseLeftInt
#check vinogradovPrimePowerBaseRightInt
#check vinogradovPrimePowerLiftAmbientEquiv_fst_val_add_one
#check vinogradovPrimePowerLiftAmbientEquiv_snd_val_add_one
#check vinogradovPrimePowerCorrectionSolutionSet_powerSum_modEq
#check vinogradovPairCorrectionLinearMap_eq_of_mem_correctionSolutionSet
#check card_vinogradovPrimePowerCorrectionSolutionSet_le_fiber
#check card_vinogradovPrimePowerCorrectionSolutionSet_le_card_ker
#check card_vinogradovPrimePowerCorrectionSolutionSet_le_pow_rankDefect
#check card_vinogradovPrimePowerCorrectionSolutionSet_le_pow_pred
#check card_vinogradovPrimePowerFixedCollisionSolutionLiftSet_le_rankDefects
#check card_vinogradovPrimePowerFixedCollisionSolutionLiftSet_le_of_rank
#check card_vinogradovPrimePowerFixedCollisionSolutionLiftSet_le_pow_pred
#check card_vinogradovPrimePowerFixedCollisionSolutionSet_succ_le_pow_pred
