import ZeroFreeRegion.VinogradovKorobov.VinogradovSingularWitness

open ZeroFreeRegion.VinogradovKorobov

#check VinogradovCollisionWitness
#check vinogradovCollisionWitnessSet
#check mem_vinogradovCollisionWitnessSet_iff
#check vinogradovCollisionWitnessSet_nonempty_iff
#check vinogradovMultiBlockCollisionWitnessSet
#check mem_vinogradovMultiBlockCollisionWitnessSet_iff
#check vinogradovMultiBlockCollisionWitnessSet_nonempty_iff
#check VinogradovCollisionReducedIndex
#check vinogradovCollisionFiberEquiv
#check vinogradovCollisionFiberEquiv_apply
#check vinogradovCollisionFiberEquiv_symm_apply
#check card_vinogradovCollisionReducedIndex
#check card_vinogradovCollisionFiber
#check vinogradovCollisionFiberEmbedding
#check card_vinogradovFixedCollisionTupleSet
#check mem_vinogradovFixedCollisionTupleSet_iff
#check vinogradovFixedCollisionUnionSet
#check mem_vinogradovFixedCollisionUnionSet_iff
#check vinogradovFixedCollisionUnionSet_eq_singular
#check card_vinogradovFixedCollisionUnionSet_le
#check vinogradovSelectedBlockIndex_pair_injective
#check vinogradovCollisionWitness_selected_left_ne_selected_right
#check vinogradovCollisionWitness_selected_right_injective
