import ZeroFreeRegion.VinogradovKorobov.VinogradovCorrectionRankStrata

open ZeroFreeRegion.VinogradovKorobov

#check vinogradovPrimePowerPairJacobianRank
#check vinogradovPrimePowerFixedCollisionHighRankSolutionSet
#check vinogradovPrimePowerFixedCollisionLowRankSolutionSet
#check mem_vinogradovPrimePowerFixedCollisionHighRankSolutionSet_iff
#check mem_vinogradovPrimePowerFixedCollisionLowRankSolutionSet_iff
#check vinogradovPrimePowerFixedCollision_rank_partition
#check vinogradovPrimePowerFixedCollision_rank_disjoint
#check vinogradovPrimePowerFixedCollisionHighRankLiftSet
#check vinogradovPrimePowerFixedCollisionLowRankLiftSet
#check vinogradovPrimePowerFixedCollision_rank_lift_partition
#check vinogradovPrimePowerFixedCollision_rank_lift_disjoint
#check card_vinogradovPrimePowerFixedCollisionSolutionLiftSet_eq_rank_add
#check card_vinogradovPrimePowerFixedCollisionHighRankLiftSet_le
#check card_vinogradovPrimePowerFixedCollisionSolutionSet_succ_le_rank_split
#check vinogradovPrimePowerPairJacobianRank_lt_both_not_injective
#check vinogradovPrimePowerPairJacobianRank_lt_no_injective_selection
#check vinogradovPrimePowerFixedCollisionLowRankSolutionSet_subset_lowDiversity
#check vinogradovPrimePowerFixedCollisionLowRankLiftSet_subset_lowDiversity
#check card_vinogradovPrimePowerFixedCollisionLowRankLiftSet_le_lowDiversity
#check card_vinogradovPrimePowerFixedCollisionSolutionSet_succ_le_fullRank_lowDiversity
