import ZeroFreeRegion.VinogradovKorobov.VinogradovResidueMassAudit

#print axioms ZeroFreeRegion.VinogradovKorobov.vinogradovResidueMassSq_one_eq_card
#print axioms ZeroFreeRegion.VinogradovKorobov.vinogradovResidueMass_one_sq_eq_card
#print axioms ZeroFreeRegion.VinogradovKorobov.vinogradovResidueMass_one_evenPow_eq_card_pow
#print axioms ZeroFreeRegion.VinogradovKorobov.vinogradovResidueMassSq_one_eq_tailResidueLength
#print axioms ZeroFreeRegion.VinogradovKorobov.vinogradovResidueMass_one_evenPow_eq_tailResidueLength_pow
#print axioms ZeroFreeRegion.VinogradovKorobov.vinogradovMixedNormalizedResidueMoment_one_to_raw
#print axioms ZeroFreeRegion.VinogradovKorobov.card_vinogradovResidueClassFinset_completePrimePowerBlock
#print axioms ZeroFreeRegion.VinogradovKorobov.card_vinogradovResidueClassFinset_nestedPrimePowerBlock
#print axioms ZeroFreeRegion.VinogradovKorobov.vinogradovResidueMass_one_evenPow_eq_nestedPrimePowerBlock_pow
#print axioms ZeroFreeRegion.VinogradovKorobov.vinogradovMixedRawResidueNormMoment_one_le_refinement_via_normalized
