import ZeroFreeRegion.VinogradovKorobov.VinogradovMixedTailMoment

open ZeroFreeRegion.VinogradovKorobov

#check vinogradovIntSolutionPairSet
#check normalizedVinogradovIntNormMoment
#check normalizedVinogradovIntNormMoment_eq_solutionPairSetCard
#check normalizedVinogradovMixedTailNormMoment_eq_solutionPairSetCard
#check IsVinogradovSolutionIntMod.affine_residual_modEq
#check vinogradovMixedTailSolutionPair_residual_modEq
#check IsVinogradovResidualTailSolution
#check vinogradovResidualTailSolutionPairSet
#check vinogradovIntSolutionPairSet_tail_subset_residual
#check normalizedVinogradovMixedTailNormMoment_le_residualSolutionPairSetCard
#check vinogradovResidualTailSolutionPairProjection
#check vinogradovResidualTailSolutionPairProjection_injOn
#check card_vinogradovResidualTailSolutionPairSet_le_firstPower
#check normalizedVinogradovMixedTailNormMoment_le_firstPower

#print axioms normalizedVinogradovIntNormMoment_eq_solutionPairSetCard
#print axioms normalizedVinogradovMixedTailNormMoment_eq_solutionPairSetCard
#print axioms IsVinogradovSolutionIntMod.affine_residual_modEq
#print axioms vinogradovMixedTailSolutionPair_residual_modEq
#print axioms vinogradovIntSolutionPairSet_tail_subset_residual
#print axioms normalizedVinogradovMixedTailNormMoment_le_residualSolutionPairSetCard
#print axioms vinogradovResidualTailSolutionPairProjection_injOn
#print axioms card_vinogradovResidualTailSolutionPairSet_le_firstPower
#print axioms normalizedVinogradovMixedTailNormMoment_le_firstPower
