import ZeroFreeRegion.VinogradovKorobov.VinogradovPrimePowerTargetMultiBlock

open ZeroFreeRegion.VinogradovKorobov

#check card_vinogradovPrimePowerFirstNonsingularSolutionSet_le_target_fibers
#check card_vinogradovPrimePowerSomeBlockNonsingularSolutionSet_le_target_fibers
#check vinogradovPrimePowerMultiBlockSolutionCount_le_target_fibers
#check norm_normalizedVinogradovMomentMod_primePowerMultiBlock_le_target_fibers
#check vinogradovWeightedPrimePowerMultiBlockSolutionCount_le_target_fibers
#check norm_normalizedVinogradovWeightedMomentMod_primePowerMultiBlock_le_target_fibers
