import ZeroFreeRegion.VinogradovKorobov.VinogradovRectangularJacobian

open ZeroFreeRegion.VinogradovKorobov

#check vinogradovRectangularPowerSumJacobian
#check vinogradovRectangularPowerSumJacobian_eq_square
#check vinogradovRectangularPowerSumJacobian_mulVec_extendByZero
#check vinogradovPowerSumInt_affine_modEq_sq_rectangular
#check vinogradovPowerSumInt_affine_modEq_mul_of_dvd_rectangular
#check vinogradovPairCorrectionLinearMap
#check vinogradovPairCorrectionLinearMap_apply
#check one_le_finrank_vinogradovPairCorrectionLinearMap_range
#check finrank_vinogradovPairCorrectionLinearMap_range_eq_of_left_injective
#check finrank_vinogradovPairCorrectionLinearMap_range_eq_of_right_injective
#check finrank_vinogradovPairCorrectionLinearMap_range_eq_of_left_selection
#check finrank_vinogradovPairCorrectionLinearMap_range_eq_of_right_selection
#check not_exists_left_selection_of_finrank_vinogradovPairCorrectionLinearMap_range_lt
#check not_exists_right_selection_of_finrank_vinogradovPairCorrectionLinearMap_range_lt
#check not_injective_left_of_finrank_vinogradovPairCorrectionLinearMap_range_lt
#check not_injective_right_of_finrank_vinogradovPairCorrectionLinearMap_range_lt
#check card_linearMap_fiber_eq_zero_fiber
#check card_linearMap_zero_fiber_eq_card_ker
#check vinogradovPairCorrectionFiberSet
#check mem_vinogradovPairCorrectionFiberSet_iff
#check card_vinogradovPairCorrectionFiberSet_eq_zero_fiber
#check card_vinogradovPairCorrectionFiberSet_eq_card_ker
#check card_vinogradovPairCorrectionFiberSet_eq_pow_rankDefect
#check vinogradovPairCorrectionLinearMap_eq_of_affine_solutions
