import ZeroFreeRegion.VinogradovKorobov.VinogradovTranslatedBlockMoment

open ZeroFreeRegion.VinogradovKorobov

#check vinogradovTranslatedPowerSumMod
#check IsVinogradovTranslatedSolutionMod
#check vinogradovTranslatedSolutionCountMod
#check vinogradovTranslatedPhaseMod
#check vinogradovTranslatedWeylSumMod
#check normalizedTranslatedVinogradovMomentMod
#check isVinogradovTranslatedSolutionMod_iff_unshifted
#check vinogradovTranslatedSolutionCountMod_eq_unshifted
#check normalizedTranslatedVinogradovMomentMod_eq_solutionCount
#check normalizedTranslatedVinogradovMomentMod_eq_unshifted
#check norm_normalizedTranslatedVinogradovMomentMod_sq_le_primeCubic_completeBlockSaving
