import ZeroFreeRegion.VinogradovKorobov.VinogradovMixedRecurrence

open ZeroFreeRegion.VinogradovKorobov

#check VinogradovMixedMainFarScalePairMem
#check vinogradovResidueSolutionPairSet
#check card_vinogradovResidueSolutionPairSet
#check vinogradovMixedMainFarScalePairSet
#check mem_vinogradovMixedMainFarScalePairSet_iff
#check vinogradovMixedMainAffineCoordinatePair
#check vinogradovMixedMainAffineCoordinatePair_spec
#check vinogradovMixedMainFarScaleResidueMap
#check vinogradovMixedMainFarScaleResidueMap_mem
#check vinogradovMixedMainFarScaleResidueMap_injOn
#check card_vinogradovMixedMainFarScalePairSet_le_solutionCount
#check vinogradovMixedModConditionedSolutionSet_subset_mainFarScale_product
#check card_vinogradovMixedModConditionedSolutionSet_le_mainFarScale
#check card_vinogradovMixedModConditionedSolutionSet_le_solutionCount
#check norm_normalizedVinogradovMixedModConditionedMoment_le_mainFarScale
#check norm_normalizedVinogradovMixedModConditionedMoment_le_farScaleMoment
#check norm_normalizedVinogradovMixedModConditionedMoment_le_primePowerStrata
#check vinogradovUnitSeparatedCenterPairSet
#check mem_vinogradovUnitSeparatedCenterPairSet_iff
#check normalizedVinogradovUnitSeparatedMixedMomentSum
#check normalizedVinogradovUnitSeparatedMixedMomentSum_le_farScaleMoment
#check card_vinogradovUnitSeparatedCenterPairSet
#check normalizedVinogradovUnitSeparatedMixedMomentSum_le_farScaleMoment_explicit

#print axioms vinogradovMixedModConditionedSolutionSet_subset_mainFarScale_product
#print axioms card_vinogradovResidueSolutionPairSet
#print axioms vinogradovMixedMainFarScaleResidueMap_injOn
#print axioms card_vinogradovMixedMainFarScalePairSet_le_solutionCount
#print axioms card_vinogradovMixedModConditionedSolutionSet_le_mainFarScale
#print axioms card_vinogradovMixedModConditionedSolutionSet_le_solutionCount
#print axioms norm_normalizedVinogradovMixedModConditionedMoment_le_mainFarScale
#print axioms norm_normalizedVinogradovMixedModConditionedMoment_le_farScaleMoment
#print axioms norm_normalizedVinogradovMixedModConditionedMoment_le_primePowerStrata
#print axioms normalizedVinogradovUnitSeparatedMixedMomentSum_le_farScaleMoment
#print axioms card_vinogradovUnitSeparatedCenterPairSet
#print axioms normalizedVinogradovUnitSeparatedMixedMomentSum_le_farScaleMoment_explicit
