import ZeroFreeRegion.VinogradovKorobov.VinogradovScaleStableBlock

open ZeroFreeRegion.VinogradovKorobov

#check divisionBlockCount_mul_le_two_length
#check primeCubic_blockCover_gain_of_threshold
#check primeCubicBlockCoverGain
#check primeCubicBlockCoverGain_lt_one
#check norm_normalizedTranslatedVinogradovMomentMod_le_primeCubicBlockCoverGain_mul_trivial
#check primeCubic_completeBlockCoverFactor_lt_trivial
#check norm_normalizedTranslatedVinogradovMomentMod_lt_trivial_of_primeCubic_blockCoverSaving
#check norm_normalizedTranslatedVinogradovMomentMod_lt_trivial_of_primeCubic_threshold
