import ZeroFreeRegion.VinogradovKorobov.VinogradovCompleteBlockMain

open ZeroFreeRegion.VinogradovKorobov

#check card_vinogradovMixedMainSolutionPairSet_completeBlock_le
#check norm_normalizedVinogradovMixedModConditionedMoment_sq_le_completeMainBlock_factorialTail
#check norm_normalizedVinogradovMixedModConditionedMoment_sq_le_primeCompleteBlock_balancedTail
#check norm_normalizedVinogradovMomentMod_le_primeCubic_completeBlockSaving
#check norm_normalizedVinogradovMomentMod_sq_le_primeCubic_completeBlockSaving
