import ZeroFreeRegion.VinogradovKorobov.VinogradovScaleSelection

open ZeroFreeRegion.VinogradovKorobov

#check vinogradovSolutionCountNat_le_mod
#check vinogradovSolutionCountNat_mono_length
#check vinogradovSolutionCountNat_le_norm_normalizedTranslatedVinogradovMomentMod
#check vinogradovSolutionCountNat_le_primeCubicBlockCoverGain_mul_trivial
#check primeCubicBlockCoverGain_sq
#check primeCubicBlockCoverGain_nonneg
#check exists_primeCubicBlockCoverGain_sq_lt
#check vinogradovSolutionCountNat_lt_cubicScalePowerSaving
#check vinogradovCubicScale
#check le_vinogradovCubicEnvelope
#check vinogradovCubicEnvelope_le_sixtyFour_mul
#check vinogradovSolutionCountNat_lt_cubicEnvelopePowerSaving
#check vinogradovSolutionCountNat_lt_sixtyFourMulPowerSaving
#check vinogradovSolutionCountNat_lt_inverseLinearSavingSix
#check vinogradovSolutionCountNat_lt_powerSavingOne
