import PrimeNumberTheorem.VKEdgeTargetPairAnnihilator

open PrimeNumberTheorem.VKEdgePiOverTwo

#check symmetricFrequencyAnnihilator
#check symmetricFrequencyAnnihilator_cosineZeroPair
#check symmetricFrequencyAnnihilator_targetPair_eq_zero
#check annihilatedNormalizedPsiError
#check annihilatedNormalizedPsiError_eq_residual
#check annihilatedNormalizedPsiError_eq_threeScale
#check sq_symmetricFrequencyAnnihilator_le
#check integral_sq_symmetricFrequencyAnnihilator_le_of_shifted
#check integral_annihilatedNormalizedPsiError_sq_le_of_residual_shifts
#check no_positive_lower_bound_on_pure_target_pair
#check symmetricFrequencyAnnihilator_cosineZeroPair_eq_zero_iff
