import PrimeNumberTheorem.VKEdgeResidualAmplification

open PrimeNumberTheorem.VKEdgePiOverTwo

#print axioms MathlibAux.sqrt_integral_sq_sub_lower
#print axioms MathlibAux.integral_sq_sub_lower_of_integral_sq_bounds
#print axioms intervalIntegral_cosinePairModel_sq
#print axioms integral_Icc_cosinePairModel_sq_le
#print axioms measurable_normalizedCosineModelPair
#print axioms measurable_normalizedPsiModelResidual
#print axioms integrableOn_normalizedCosineModelPair_sq_Icc
#print axioms integrableOn_normalizedPsiModelResidual_sq_Icc
#print axioms integral_Icc_normalizedCosineModelPair_sq_le
#print axioms one_div_pi_le_sharpenedMissingHarmonicDenominator
#print axioms one_le_centeredSharpenedProjectedPsiKernelEnvelopeConstant
#print axioms centeredSharpenedSweptOrdinaryL2Constant_lt_cosineModelHalfEnergy
#print axioms integral_Icc_normalizedPsiModelResidual_sq_lower
#print axioms integral_Icc_normalizedCosineModelPair_sq_le_epsilonLogWindow
#print axioms integral_Icc_normalizedPsiModelResidual_sq_lower_epsilonLogWindow
