import PrimeNumberTheorem.VKEdgeTargetPairAnnihilator

#print axioms PrimeNumberTheorem.VKEdgePiOverTwo.symmetricFrequencyAnnihilator_cosineZeroPair
#print axioms PrimeNumberTheorem.VKEdgePiOverTwo.symmetricFrequencyAnnihilator_targetPair_eq_zero
#print axioms PrimeNumberTheorem.VKEdgePiOverTwo.annihilatedNormalizedPsiError_eq_residual
#print axioms PrimeNumberTheorem.VKEdgePiOverTwo.annihilatedNormalizedPsiError_eq_threeScale
#print axioms PrimeNumberTheorem.VKEdgePiOverTwo.sq_symmetricFrequencyAnnihilator_le
#print axioms PrimeNumberTheorem.VKEdgePiOverTwo.integral_sq_symmetricFrequencyAnnihilator_le_of_shifted
#print axioms PrimeNumberTheorem.VKEdgePiOverTwo.integral_annihilatedNormalizedPsiError_sq_le_of_residual_shifts
#print axioms PrimeNumberTheorem.VKEdgePiOverTwo.no_positive_lower_bound_on_pure_target_pair
#print axioms PrimeNumberTheorem.VKEdgePiOverTwo.symmetricFrequencyAnnihilator_cosineZeroPair_eq_zero_iff
