import PrimeNumberTheorem.VKEdgePiOverTwoProjectedPsiWindow

#print axioms PrimeNumberTheorem.VKEdgePiOverTwo.localizedPsiGaussianAverage_eq_logarithmic
#print axioms PrimeNumberTheorem.VKEdgePiOverTwo.neg_re_localizedPsiGaussianAverage_div_pi_eq
#print axioms PrimeNumberTheorem.VKEdgePiOverTwo.eventually_bddAbove_normalizedWindowValues
#print axioms PrimeNumberTheorem.VKEdgePiOverTwo.tendsto_projectedPsiTailRemainder
#print axioms PrimeNumberTheorem.VKEdgePiOverTwo.eventually_projectedPsiWindow_upper_bound
