import PrimeNumberTheorem.VKEdgePiOverTwoCenteredPsiWindow

#print axioms PrimeNumberTheorem.VKEdgePiOverTwo.localizedPsiGaussianAverageAtCenter_eq_logarithmic
#print axioms PrimeNumberTheorem.VKEdgePiOverTwo.neg_re_localizedPsiGaussianAverageAtCenter_div_pi_eq
#print axioms PrimeNumberTheorem.VKEdgePiOverTwo.neg_re_mul_localizedPsiGaussianAverageAtCenter_div_pi_eq
#print axioms PrimeNumberTheorem.VKEdgePiOverTwo.tendsto_projectedPsiTailRemainderAtCenter
#print axioms PrimeNumberTheorem.VKEdgePiOverTwo.tendsto_relativeProjectedPsiTailRemainderAtCenter
