import PrimeNumberTheorem.VKEdgePiOverTwoFarZeroFilter

#print axioms PrimeNumberTheorem.VKEdgePiOverTwo.localizedNearZeroFilter_eval_zero
#print axioms PrimeNumberTheorem.VKEdgePiOverTwo.mem_localizedNearZeroOffsets_of_isNontrivialZero
#print axioms PrimeNumberTheorem.VKEdgePiOverTwo.localizedGaussianWeight_nearZeroFilter_eq_zero
#print axioms PrimeNumberTheorem.VKEdgePiOverTwo.localizedZeroResidueSum_nearZeroFilter_eq_target_add_far
#print axioms PrimeNumberTheorem.VKEdgePiOverTwo.ConcreteLocalizedContourSlice.isNontrivialZero_of_mem
#print axioms PrimeNumberTheorem.VKEdgePiOverTwo.ConcreteLocalizedContourSlice.center_mem
#print axioms PrimeNumberTheorem.VKEdgePiOverTwo.selectedLocalizedZeroResidueSum_nearZeroFilter_eq_target_add_far
