import PrimeNumberTheorem.VKEdgePiOverTwoRightTailBound

#print axioms PrimeNumberTheorem.VKEdgePiOverTwo.norm_div_sub_one_right_vertical_le_two
#print axioms PrimeNumberTheorem.VKEdgePiOverTwo.norm_regularizedLogDeriv_right_vertical_le
#print axioms PrimeNumberTheorem.VKEdgePiOverTwo.norm_localizedRegularizedLogDerivIntegrand_right_le_gaussian
#print axioms PrimeNumberTheorem.VKEdgePiOverTwo.integral_sub_symmetric_intervalIntegral
#print axioms PrimeNumberTheorem.VKEdgePiOverTwo.norm_localizedRightEdgeTail_le_gaussian_of_linearHeight
#print axioms PrimeNumberTheorem.VKEdgePiOverTwo.norm_localizedRightEdgeTail_le_gaussian
#print axioms PrimeNumberTheorem.VKEdgePiOverTwo.tendsto_localizedRightEdgeTail_linearHeight
#print axioms PrimeNumberTheorem.VKEdgePiOverTwo.exists_goodHeight_linearScale_norm_localizedContourRemainder_le
#print axioms PrimeNumberTheorem.VKEdgePiOverTwo.exists_goodHeight_linearScale_localizedPsiGaussianAverage_eq_zeroSum
