import PrimeNumberTheorem.VKEdgePiOverTwoBellotti

open Complex Filter MeasureTheory Set

namespace PrimeNumberTheorem.VKEdgePiOverTwo

#check bellottiZeroLocationsFinset
#check mem_bellottiZeroLocationsFinset
#check bellottiZeroLocationCount
#check vinogradovKorobovEdgeWidth
#check bellottiZeroLocationCount_le_zeroDensityCount
#check exists_riemannZeta_ne_zero_at_oddHarmonic_of_bellottiCount_le
#check finiteStrictPiOverTwoOscillationConstant
#check pi_div_two_lt_finiteStrictPiOverTwoOscillationConstant
#check finiteStrictPiOverTwoOscillationConstant_le
#check exists_missing_oddHarmonic_with_uniform_gap_of_bellottiCount_le
#check eventually_exists_psiError_in_powerOnePlusEpsilonWindow_gt_uniformBellottiGap
#check eventually_positive_measure_in_epsilonLogWindow_gt_uniformBellottiGap
#check eventually_exists_psiError_in_powerOnePlusEpsilonWindow_gt_of_bellottiEdgeCount
#check eventually_positive_measure_in_epsilonLogWindow_gt_of_bellottiEdgeCount

end PrimeNumberTheorem.VKEdgePiOverTwo
