import PrimeNumberTheorem.VKEdgePiOverTwoRightMellin

#print axioms PrimeNumberTheorem.VKEdgePiOverTwo.ofReal_cpow_neg_add_split
#print axioms PrimeNumberTheorem.VKEdgePiOverTwo.neg_logDeriv_sub_pole_eq_mul_mellin
#print axioms PrimeNumberTheorem.VKEdgePiOverTwo.neg_logDeriv_sub_pole_rightEdge_eq_mul_mellin
#print axioms PrimeNumberTheorem.VKEdgePiOverTwo.integrableOn_psiErrorAboveOneComplex_mul_cpow
#print axioms PrimeNumberTheorem.VKEdgePiOverTwo.integral_rightEdgePolynomialGaussian_cpow_eq
#print axioms PrimeNumberTheorem.VKEdgePiOverTwo.localizedGaussianWeight_mul_regularizedLogDeriv_rightEdge_eq
#print axioms PrimeNumberTheorem.VKEdgePiOverTwo.integrable_rightEdgeMellinProduct
#print axioms PrimeNumberTheorem.VKEdgePiOverTwo.integral_rightEdgeGaussianFactor_mul_mellin_eq
#print axioms PrimeNumberTheorem.VKEdgePiOverTwo.integral_localizedGaussianWeight_mul_regularizedLogDeriv_rightEdge_eq
