import PrimeNumberTheorem.VKEdgeDynamicZeroPacketDrift

#print axioms PrimeNumberTheorem.VKEdgePiOverTwo.dynamicComplementMovingPacketContribution_eq_realBand_add_outside
#print axioms PrimeNumberTheorem.VKEdgePiOverTwo.dynamicComplementForwardMovingGaussianSecondMoment_le_realBand_add_outside
#print axioms PrimeNumberTheorem.VKEdgePiOverTwo.norm_dynamicComplementMovingPacketContribution_sub_frozen_le
#print axioms PrimeNumberTheorem.VKEdgePiOverTwo.dynamicComplementForwardMovingGaussianSecondMoment_le_centeredFrozen
#print axioms PrimeNumberTheorem.VKEdgePiOverTwo.exists_absorbableDynamicComplementPacket_of_forwardMovingGaussianL2_gt
#print axioms PrimeNumberTheorem.VKEdgePiOverTwo.exists_absorbableDynamicComplementRealBandPacket_of_forwardMovingGaussianL2_gt
#print axioms PrimeNumberTheorem.VKEdgePiOverTwo.exists_absorbableDynamicComplementRealBandPacket_of_fullMovingGaussianL2_gt
