import PrimeNumberTheorem.VKEdgePiOverTwoQuantitativeMeasure

open PrimeNumberTheorem.VKEdgePiOverTwo

#print axioms MathlibAux.weightedSecondMoment_sub_thresholdMass_le_envelope_mul_measure
#print axioms centeredThresholdEnergyGap_pos
#print axioms CenteredLocalizedContourData.eventually_secondMoment_sub_thresholdMass_gt_half_gap
#print axioms normalizedPsiError_abs_le_centeredWindowEnvelope
#print axioms centeredStrictPiOverTwoMeasureLowerBound_pos
#print axioms eventually_centeredSharpened_measure_gt_explicit_strictPiOverTwo
#print axioms exists_eventually_explicit_measure_in_epsilonLogWindow_gt_strictPiOverTwo
