import PrimeNumberTheorem.VKEdgePiOverTwoSweptL2

open PrimeNumberTheorem.VKEdgePiOverTwo

#print axioms exp_scaled_abs_mul_normalizedGaussian_le_sweptEnvelope
#print axioms integral_sweptGaussianEnvelope_le
#print axioms centeredSharpenedProjectedPsiKernel_abs_le_scaledEnvelope
#print axioms ordinarySecondMoment_linear_lower_of_sweptWeightedLower
#print axioms one_lt_epsilonSweepRatio
#print axioms localizedGaussianLogWindow_subset_epsilonWindow_of_mem_sweep
#print axioms exists_eventually_ordinarySecondMoment_in_epsilonLogWindow_gt_linear
