import PrimeNumberTheorem.VKEdgeProportionalWindowTransfer

#print axioms PrimeNumberTheorem.VKEdgePiOverTwo.eventually_exists_goodHeight_normalizedRemainder_to_fullMovingGaussianEnergy_proportional
#print axioms PrimeNumberTheorem.VKEdgePiOverTwo.initialEmptyClusterFullMovingGaussianL2Constant
#print axioms PrimeNumberTheorem.VKEdgePiOverTwo.exists_eventually_emptyClusterFullMovingGaussianSecondMoment_gt
