import PrimeNumberTheorem.VKEdgeTargetPairAnnihilatorAverage

open PrimeNumberTheorem.VKEdgePiOverTwo

#print axioms frequencyAnnihilatorMultiplier_target
#print axioms intervalIntegral_frequencyAnnihilatorMultiplier_sq
#print axioms tendsto_normalizedStepMultiplierEnergy
#print axioms eventually_two_le_normalizedStepMultiplierEnergy
#print axioms eventually_two_le_normalizedStepMultiplierEnergy_finset
#print axioms eventually_two_mul_coefficientEnergy_le_stepAveragedDiagonalEnergy
#print axioms abs_intervalIntegral_annihilatedExponentialPolynomial_sub_diagonal_le
#print axioms sameEdgeResidualPackage_eventually_stepEnergy_pos
#print axioms no_sameEdge_conclusion_from_target_pair_alone
