import PrimeNumberTheorem.VKEdgeCosineModelAnnihilator

#print axioms PrimeNumberTheorem.VKEdgePiOverTwo.symmetricFrequencyAnnihilator_cosinePairModel
#print axioms PrimeNumberTheorem.VKEdgePiOverTwo.symmetricFrequencyAnnihilator_cosineModelPair_eq_zero
#print axioms PrimeNumberTheorem.VKEdgePiOverTwo.annihilatedNormalizedPsiError_eq_modelResidual
#print axioms PrimeNumberTheorem.VKEdgePiOverTwo.annihilatedNormalizedPsiError_eq_threeScale
#print axioms PrimeNumberTheorem.VKEdgePiOverTwo.sq_symmetricFrequencyAnnihilator_le
#print axioms PrimeNumberTheorem.VKEdgePiOverTwo.integral_sq_symmetricFrequencyAnnihilator_le_of_shifted
#print axioms PrimeNumberTheorem.VKEdgePiOverTwo.integral_annihilatedNormalizedPsiError_sq_le_of_modelResidual_shifts
#print axioms PrimeNumberTheorem.VKEdgePiOverTwo.exists_mem_expandedInterval_sq_gt_of_detector_energy_pos
#print axioms PrimeNumberTheorem.VKEdgePiOverTwo.exists_mem_expandedInterval_normalizedPsiModelResidual_sq_gt
#print axioms PrimeNumberTheorem.VKEdgePiOverTwo.no_positive_lower_bound_on_pure_cosine_model
#print axioms PrimeNumberTheorem.VKEdgePiOverTwo.symmetricFrequencyAnnihilator_cosinePairModel_eq_zero_iff
