import PrimeNumberTheorem.VKEdgePiOverTwoGaussianMean

#print axioms PrimeNumberTheorem.VKEdgePiOverTwo.normalizedGaussian_pos
#print axioms PrimeNumberTheorem.VKEdgePiOverTwo.integral_normalizedGaussian
#print axioms PrimeNumberTheorem.VKEdgePiOverTwo.hasDerivAt_normalizedGaussian
#print axioms PrimeNumberTheorem.VKEdgePiOverTwo.integrable_normalizedGaussianDeriv
#print axioms PrimeNumberTheorem.VKEdgePiOverTwo.integral_abs_normalizedGaussianDeriv_le_inv_sqrt
#print axioms PrimeNumberTheorem.VKEdgePiOverTwo.exists_uniform_normalizedGaussian_periodicMean_bound
#print axioms PrimeNumberTheorem.VKEdgePiOverTwo.eventually_uniform_normalizedGaussian_periodicMean
