import PrimeNumberTheorem.VKEdgePiOverTwoFarZeroDecay

#print axioms PrimeNumberTheorem.VKEdgePiOverTwo.norm_localizedGaussianWeight_far_le
#print axioms PrimeNumberTheorem.VKEdgePiOverTwo.ConcreteLocalizedContourSlice.mem_nontrivialZerosFinset_linearHeight
#print axioms PrimeNumberTheorem.VKEdgePiOverTwo.norm_sub_center_le_linearHeight
#print axioms PrimeNumberTheorem.VKEdgePiOverTwo.norm_localizedFarZeroResidueSum_le_globalMultiplicity
#print axioms PrimeNumberTheorem.VKEdgePiOverTwo.norm_localizedFarZeroResidueSum_le_decayEnvelope
#print axioms PrimeNumberTheorem.VKEdgePiOverTwo.tendsto_localizedFarZeroDecayEnvelope
#print axioms PrimeNumberTheorem.VKEdgePiOverTwo.tendsto_selectedLocalizedFarZeroResidueSum
#print axioms PrimeNumberTheorem.VKEdgePiOverTwo.tendsto_selectedLocalizedZeroResidueSum_nearZeroFilter
#print axioms PrimeNumberTheorem.VKEdgePiOverTwo.tendsto_selectedLocalizedZeroResidueSum_nearZeroFilter_of_ne_zero
