import PrimeNumberTheorem.VKEdgeZeroDensityResidualL2

open PrimeNumberTheorem.VKEdgePiOverTwo

#print axioms norm_normalizedPositiveZeroDensityResidualContribution_le_count
#print axioms integral_normSq_normalizedPositiveZeroDensityResidualContribution_le_count_sq
#print axioms integral_normSq_normalizedPositiveZeroDensityResidualContribution_le_of_count_exp
#print axioms eventually_zeroDensityCount_exp_height_le_of_carlson
#print axioms eventually_integral_normSq_positiveZeroDensityResidual_le_of_carlson
#print axioms carlsonResidualDecayRate_pos
#print axioms exists_exponentialTruncationScale_iff
#print axioms no_exponentialTruncationScale_of_gap_le
