import PrimeNumberTheorem.VKEdgePiOverTwoRightTailBound

open Complex Polynomial
open PrimeNumberTheorem.VKEdgePiOverTwo

#check norm_div_sub_one_right_vertical_le_two
#check norm_regularizedLogDeriv_right_vertical_le
#check norm_localizedRegularizedLogDerivIntegrand_right_le_gaussian
#check integral_sub_symmetric_intervalIntegral
#check integrable_localizedRightEdgeGaussianMajorant
#check integral_localizedRightEdgeGaussianMajorant
#check norm_localizedRightEdgeTail_le_gaussian_of_linearHeight
#check norm_localizedRightEdgeTail_le_gaussian
#check tendsto_localizedRightEdgeTail_linearHeight
#check exists_goodHeight_linearScale_norm_localizedContourRemainder_le
