import PrimeNumberTheorem.VKEdgeZeroClusterResidual

open PrimeNumberTheorem.VKEdgePiOverTwo

#print axioms positiveZeroDensityResidualTopBandCluster_union_leftRemainder
#print axioms sum_order_positiveZeroDensityResidualTopBandCluster_le_count
#print axioms normalizedPositiveZeroDensityResidualContribution_eq_cluster_add_left
#print axioms norm_normalizedPositiveZeroDensityLeftRemainder_le_count
#print axioms integral_normSq_normalizedPositiveZeroDensityLeftRemainder_le_count_sq
#print axioms eventually_integral_normSq_positiveZeroDensityLeftRemainder_le_of_carlson
#print axioms integral_normSq_normalizedPositiveResidual_ge_half_cluster_sub_left
