import PrimeNumberTheorem.VKEdgePiOverTwoGaussianMellin

#print axioms PrimeNumberTheorem.VKEdgePiOverTwo.integral_verticalGaussian_eq
#print axioms PrimeNumberTheorem.VKEdgePiOverTwo.integral_verticalGaussian_monomial_zero_eq
#print axioms PrimeNumberTheorem.VKEdgePiOverTwo.integral_verticalPolynomialGaussian_zero_eq
#print axioms PrimeNumberTheorem.VKEdgePiOverTwo.integral_verticalGaussian_monomial_eq
#print axioms PrimeNumberTheorem.VKEdgePiOverTwo.integral_verticalPolynomialGaussian_eq
#print axioms PrimeNumberTheorem.VKEdgePiOverTwo.integrable_verticalPolynomialGaussian
#print axioms PrimeNumberTheorem.VKEdgePiOverTwo.integral_verticalPolynomialGaussian_add_mul_eq
#print axioms PrimeNumberTheorem.VKEdgePiOverTwo.integrable_verticalPolynomialGaussian_add_mul
