import PrimeNumberTheorem.VKEdgeDynamicZeroPacketDrift

#print axioms PrimeNumberTheorem.VKEdgePiOverTwo.norm_dynamicComplementMovingPacketContribution_sub_frozen_le
#print axioms PrimeNumberTheorem.VKEdgePiOverTwo.dynamicComplementForwardMovingGaussianSecondMoment_le_centeredFrozen
#print axioms PrimeNumberTheorem.VKEdgePiOverTwo.exists_absorbableDynamicComplementPacket_of_forwardMovingGaussianL2_gt
