import PrimeNumberTheorem.VKEdgePiOverTwoPolynomialGaussian

#print axioms PrimeNumberTheorem.VKEdgePiOverTwo.exists_polynomialGaussianKernel_sub_l1_bound
#print axioms PrimeNumberTheorem.VKEdgePiOverTwo.exists_polynomialGaussianKernelDeriv_l1_bound
#print axioms PrimeNumberTheorem.VKEdgePiOverTwo.exists_polynomialGaussianKernel_add_deriv_norm_le_exp_abs_mul
#print axioms PrimeNumberTheorem.VKEdgePiOverTwo.polynomialGaussianKernel_X_mul
