import WeilExtremalKernels.ArchimedeanActualTail

#print axioms WeilExtremalKernels.paperArchimedeanRankTwoPointwiseBudget_le_log_envelope
#print axioms WeilExtremalKernels.exists_T0_quadraticForm_paperActualArchimedeanRankTwoIncrement_nonneg
#print axioms WeilExtremalKernels.exists_T0_quadraticForm_paperActualArchimedeanRankTwoIncrement_le
#print axioms WeilExtremalKernels.integrableOn_Ioi_paperArchimedeanRankTwoLogEnvelope
#print axioms WeilExtremalKernels.integral_Ioi_paperArchimedeanRankTwoLogEnvelope
#print axioms WeilExtremalKernels.intervalIntegral_paperArchimedeanRankTwoLogEnvelope_le_tailBudget
#print axioms WeilExtremalKernels.exists_T0_quadraticForm_paperActualArchimedeanRankTwoIncrement_le_tailBudget
