import WeilExtremalKernels.ArchimedeanHPlus

#print axioms WeilExtremalKernels.analyticAt_Gamma_of_re_pos
#print axioms WeilExtremalKernels.analyticAt_digamma_of_re_pos
#print axioms WeilExtremalKernels.continuous_archimedeanHPlus
#print axioms WeilExtremalKernels.archimedeanHPlus_eq_two_mul_verticalGammaPhaseVelocity
#print axioms WeilExtremalKernels.tendsto_archimedeanHPlus_sub_log_model_atTop
#print axioms WeilExtremalKernels.exists_eventually_archimedeanHPlus_bounds
#print axioms WeilExtremalKernels.exists_one_le_eventually_archimedeanHPlus_bounds
#print axioms WeilExtremalKernels.continuous_paperArchimedeanWeight
#print axioms WeilExtremalKernels.paperArchimedeanWeight_nonneg
#print axioms WeilExtremalKernels.paperArchimedeanWeight_le_log_envelope
