import WeilExtremalKernels.ArchimedeanImproperTail

#print axioms WeilExtremalKernels.norm_paperActualArchimedeanRankTwoDensity_entry_le_logEnvelope
#print axioms WeilExtremalKernels.integrableOn_Ioi_paperActualArchimedeanRankTwoDensity_entry
#print axioms WeilExtremalKernels.tendsto_paperActualArchimedeanRankTwoIncrement_entry_atTop
#print axioms WeilExtremalKernels.tendsto_paperActualArchimedeanRankTwoIncrement_atTop
#print axioms WeilExtremalKernels.tendsto_quadraticForm_paperActualArchimedeanRankTwoIncrement_atTop
#print axioms WeilExtremalKernels.exists_T0_tendsto_paperActualArchimedeanRankTwoIncrement_and_quadraticForm_bounds
#print axioms WeilExtremalKernels.exists_T0_quadraticForm_add_paperActualArchimedeanRankTwoTail_nonneg_of_certificate
#print axioms WeilExtremalKernels.exists_T0_quadraticForm_add_paperActualArchimedeanRankTwoTail_neg_of_tailBudget
