import WeilExtremalKernels.FiniteQuadraticForm

#print axioms WeilExtremalKernels.abs_quadraticForm_sub_le_rowBound
#print axioms WeilExtremalKernels.quadraticForm_nonneg_of_interval
#print axioms WeilExtremalKernels.quadraticForm_pos_of_interval
