import WeilExtremalKernels.ArchimedeanRankTwoTail

#print axioms WeilExtremalKernels.quadraticForm_rankOneGramMatrix
#print axioms WeilExtremalKernels.quadraticForm_rankTwoGramMatrix
#print axioms WeilExtremalKernels.quadraticForm_rankTwoGramMatrix_nonneg
#print axioms WeilExtremalKernels.quadraticForm_rankTwoGramMatrix_le
#print axioms WeilExtremalKernels.cauchyTail_denominator_lower
#print axioms WeilExtremalKernels.cauchyTailVector_sq_le
#print axioms WeilExtremalKernels.sum_sq_cauchyTailVectors_le
#print axioms WeilExtremalKernels.quadraticForm_cauchyRankTwo_le
#print axioms WeilExtremalKernels.quadraticForm_weightedRankTwoGramMatrix
#print axioms WeilExtremalKernels.quadraticForm_weightedRankTwoGramMatrix_nonneg
#print axioms WeilExtremalKernels.quadraticForm_weightedCauchyRankTwo_le
#print axioms WeilExtremalKernels.abs_centeredIndexCoordinate_le
#print axioms WeilExtremalKernels.sum_sq_paperCauchyVectors_le
#print axioms WeilExtremalKernels.quadraticForm_paperArchimedeanRankTwoDensity_nonneg
#print axioms WeilExtremalKernels.quadraticForm_paperArchimedeanRankTwoDensity_le
