import WeilExtremalKernels.ArchimedeanActualTail

#print axioms WeilExtremalKernels.paperArchimedeanRankTwoPointwiseBudget_le_log_envelope
#print axioms WeilExtremalKernels.exists_T0_quadraticForm_paperActualArchimedeanRankTwoIncrement_nonneg
#print axioms WeilExtremalKernels.exists_T0_quadraticForm_paperActualArchimedeanRankTwoIncrement_le
