import WeilExtremalKernels.ArchimedeanRankTwoIntegral

#print axioms WeilExtremalKernels.intervalIntegrable_quadraticForm
#print axioms WeilExtremalKernels.quadraticForm_intervalIntegratedMatrix
#print axioms WeilExtremalKernels.quadraticForm_intervalIntegratedMatrix_nonneg
#print axioms WeilExtremalKernels.continuousOn_cauchyTailPlusVector
#print axioms WeilExtremalKernels.continuousOn_cauchyTailMinusVector
#print axioms WeilExtremalKernels.continuousOn_paperArchimedeanRankTwoDensity_entry
#print axioms WeilExtremalKernels.continuousOn_paperArchimedeanRankTwoPointwiseBudget
#print axioms WeilExtremalKernels.quadraticForm_paperArchimedeanRankTwoIncrement_nonneg
#print axioms WeilExtremalKernels.quadraticForm_paperArchimedeanRankTwoIncrement_le
