import WeilExtremalKernels.ArchimedeanImproperTailDecay

#print axioms WeilExtremalKernels.eventually_norm_paperActualArchimedeanRankTwoTail_entry_le_tailBudget
#print axioms WeilExtremalKernels.tendsto_paperActualArchimedeanRankTwoTail_entry_atTop
#print axioms WeilExtremalKernels.tendsto_paperActualArchimedeanRankTwoTail_atTop
#print axioms WeilExtremalKernels.eventually_quadraticForm_paperActualArchimedeanRankTwoTail_bounds
#print axioms WeilExtremalKernels.tendsto_quadraticForm_paperActualArchimedeanRankTwoTail_atTop
#print axioms WeilExtremalKernels.eventually_quadraticForm_add_paperActualArchimedeanRankTwoTail_stable_of_exactLDL_margin
#print axioms WeilExtremalKernels.exists_T_quadraticForm_add_paperActualArchimedeanRankTwoTail_stable_of_exactLDL_margin
#print axioms WeilExtremalKernels.eventually_quadraticForm_add_paperActualArchimedeanRankTwoTail_neg_of_witness
#print axioms WeilExtremalKernels.exists_T_quadraticForm_add_paperActualArchimedeanRankTwoTail_neg_of_witness
