import RiemannExplorer.XiFunction
import RiemannExplorer.LiCriterion
import RiemannExplorer.SchwarzSymmetric
import RiemannExplorer.LiReality

#print axioms RiemannExplorer.xiFunction_one_sub
#print axioms RiemannExplorer.xiFunction_zero
#print axioms RiemannExplorer.xiFunction_one
#print axioms RiemannExplorer.differentiable_xiFunction
#print axioms RiemannExplorer.xiFunction_eq_half_mul_completed
#print axioms RiemannExplorer.xiFunction_eq_classical
#print axioms RiemannExplorer.xiFunction_eq_classical_of_one_lt_re
#print axioms RiemannExplorer.xiFunction_eq_zero_iff
#print axioms RiemannExplorer.xiFunction_eq_zero_iff_isNontrivialZero
#print axioms RiemannExplorer.riemannHypothesis_iff_xi_zeros_on_critical_line
#print axioms RiemannExplorer.xiFunction_conj
#print axioms RiemannExplorer.xiFunction_critical_line_real
#print axioms RiemannExplorer.liCoefficient_zero
#print axioms RiemannExplorer.liCoefficient_zero_real
#print axioms RiemannExplorer.liCoefficient_zero_im
#print axioms RiemannExplorer.li_criterion_iff_rh_target_of_directions
#print axioms RiemannExplorer.deriv_schwarzSymmetricOn
#print axioms RiemannExplorer.differentiableOn_deriv
#print axioms RiemannExplorer.schwarzSymmetric_iteratedDeriv
#print axioms RiemannExplorer.iteratedDeriv_schwarz_real
#print axioms RiemannExplorer.liCoefficient_is_real
#print axioms RiemannExplorer.liCoefficient_im
#print axioms RiemannExplorer.liCriterionHolds_iff_re_pos
