import PrimeNumberTheorem.ZeroDensityLayerBudgetActualCarlsonTargetLineCaptureBudgetSufficiencyContract

open PrimeNumberTheorem

#print axioms positiveCoefficientMass_eq_capturedBoundaryMass_of_targetLine
#print axioms coefficientMass_eq_two_mul_capturedBoundaryMass_of_targetLine
#print axioms exists_targetLine_actualCarlsonFiniteSeedCanonicalBudgets_of_seedOutside_lt_half
