import PrimeNumberTheorem.ZeroDensityLayerBudgetActualCarlsonSelectedHeightDecay

open PrimeNumberTheorem

#print axioms actualCarlsonSelectedHeightPositiveZeroNormalizedSum_tendsto_zero
#print axioms actualCarlsonSelectedHeightFullZeroNormalizedSum_tendsto_zero
