import PrimeNumberTheorem.ZeroDensityLayerBudgetActualDynamicCarlsonAutomaticCountContract

#print axioms PrimeNumberTheorem.exists_actualDynamicCarlsonGapFamilyCountCertificate
#print axioms PrimeNumberTheorem.exists_constants_tendsto_actualDynamicCarlsonGapFamilyMass_zero
#print axioms PrimeNumberTheorem.exists_constants_tendsto_actualDynamicCarlsonGapStripUnion_mass_zero
