import PrimeNumberTheorem.ZeroDensityLayerBudgetJointTwoHeightNearOptimalTruncationParametersContract

open PrimeNumberTheorem

#print axioms exists_jointTwoHeightStrictMargins_of_outerExponentFeasible
#print axioms exists_jointTwoHeightNearOptimalTruncationParameters
