import PrimeNumberTheorem.ZeroDensityLayerBudgetFinitePhaseNaturalSampling

#print axioms PrimeNumberTheorem.norm_finitePhaseSum_sub_le
#print axioms PrimeNumberTheorem.tendsto_log_natFloor_sub_log
#print axioms PrimeNumberTheorem.tendsto_norm_finitePhaseSum_log_natFloor_sub
