import PrimeNumberTheorem.ZeroDensityLayerBudgetActualCarlsonBalancedPNTReverseTransfer

open PrimeNumberTheorem

#check selectedUniformGoodHeightActualCarlsonBalancedPNTEventualUpper_forces_emptyCluster_automatic
