import PrimeNumberTheorem.ZeroDensityLayerBudgetActualSelectedHeightNaturalRemainderDecay

namespace PrimeNumberTheorem

#check selectedPolynomialNaturalContourMajorant
#check selectedPolynomialNaturalContourMajorant_nonneg
#check
  cofinalPNTFormulaRemainderBound_zero_relative_le_selectedPolynomialMajorant
#check eventually_selectedPolynomialContourRelative_nonneg
#check eventually_selectedPolynomialContourRelative_le_majorant
#check selectedPolynomialNaturalContourMajorant_targetNegligible
#check selectedUniformGoodHeight_contourRelative_targetNegligible
#check selectedNaturalClosedLogRelative_targetNegligible
#check
  selectedUniformGoodHeightNaturalRemainderUpperBound_targetNegligible
#check selectedUniformGoodHeightNaturalRemainderMajorantCertificate
#check selectedUniformGoodHeight_actualNaturalRemainderCertificate

end PrimeNumberTheorem
