import PrimeNumberTheorem.ZeroForcedOscillationHilbertBound

#print axioms PrimeNumberTheorem.ZeroForcedOscillation.abs_finiteExponentialMeanSquare_sub_diagonal_le_localSeparation
#print axioms PrimeNumberTheorem.ZeroForcedOscillation.minimumPositiveFrequencySpacing_le_localFrequencySeparation
#print axioms PrimeNumberTheorem.ZeroForcedOscillation.sum_sqNorm_div_localFrequencySeparation_le_div_minimumSpacing
#print axioms PrimeNumberTheorem.ZeroForcedOscillation.abs_finiteExponentialMeanSquare_sub_diagonal_le_minimumSpacing
#print axioms PrimeNumberTheorem.ZeroForcedOscillation.abs_maximalZeroPackageFiniteExponentialMeanSquare_sub_diagonal_le
#print axioms PrimeNumberTheorem.ZeroForcedOscillation.exists_mem_Ioo_sqNorm_finiteExponentialSum_ge_hilbert
#print axioms PrimeNumberTheorem.ZeroForcedOscillation.exists_mem_Ioo_sqNorm_maximalZeroPackageContribution_ge_hilbert
#print axioms PrimeNumberTheorem.ZeroForcedOscillation.exists_mem_Ioo_sqNorm_maximalZeroPackageContribution_pos_of_hilbert
#print axioms PrimeNumberTheorem.ZeroForcedOscillation.maximalZeroPackageUnifiedCanonical_eq_exact_of_card_eq_one
#print axioms PrimeNumberTheorem.ZeroForcedOscillation.maximalZeroPackageUnifiedCanonicalIntervalLength_le_min_pairwise_hilbert
#print axioms PrimeNumberTheorem.ZeroForcedOscillation.maximalZeroPackageHilbertIntervalLengthThreshold_lt_pairwise_iff
#print axioms PrimeNumberTheorem.ZeroForcedOscillation.exists_mem_Ioo_sqNorm_maximalZeroPackageContribution_pos_of_exact
#print axioms PrimeNumberTheorem.ZeroForcedOscillation.exists_mem_Ioo_sqNorm_maximalZeroPackageContribution_pos_on_unified_canonical
