import PrimeNumberTheorem.ZeroDensityLayerBudgetPNTDynamicTailInconsistency

#print axioms PrimeNumberTheorem.exists_positiveOrdinate_nontrivialZero
#print axioms PrimeNumberTheorem.not_nonempty_rightEdgeTailCertificate_of_positiveZero_and_reflection
#print axioms PrimeNumberTheorem.not_nonempty_actualWeightedBalancedGoodHeightRightEdgeTailCertificate

