import PrimeNumberTheorem.ZeroDensityLayerBudgetActualCarlsonBalancedPNTSignedReverseTransfer

open PrimeNumberTheorem

#check selectedUniformGoodHeightActualCarlsonBalancedPNTEventualUpper_forces_emptyCluster_of_positiveWitness_automatic
#check selectedUniformGoodHeightActualCarlsonBalancedPNTEventualLower_forces_emptyCluster_of_negativeWitness_automatic
