import PrimeNumberTheorem.ZeroDensityLayerBudgetActualSelectedHeightStripProfileFeasibleSelection

open PrimeNumberTheorem

#print axioms ActualSelectedHeightFiniteStripProfile.isFeasible_of_optimalRobustMargin_pos
#print axioms optimalActualSelectedHeightFiniteStripProfile_optimalRobustMargin_pos_of_exists_feasible
#print axioms optimalActualSelectedHeightFiniteStripProfile_feasible_of_exists
#print axioms unified_actualBalancedHeight_of_optimalFiniteStripProfile_of_exists_feasible
