import PrimeNumberTheorem.ZeroDensityLayerBudgetActualDynamicBoundaryWitnessTransfer

open PrimeNumberTheorem

#check actualDynamicBoundaryMainWitness_naturalTransfer
#check actualDynamicBoundaryMainWitness_realTransfer
