import PrimeNumberTheorem.ZeroDensityLayerBudgetCarlsonStripEndpointCriterionContract

#print axioms PrimeNumberTheorem.targetAmplitudeStripEndpointExponent_eq_base_add_width
#print axioms PrimeNumberTheorem.targetAmplitudeStripEndpointExponent_nonneg
#print axioms PrimeNumberTheorem.exists_carlsonPolynomialHeight_stripEndpoint_decay_iff
#print axioms PrimeNumberTheorem.carlsonStripEndpointTargetThreshold_sub_classical
#print axioms PrimeNumberTheorem.carlsonClassicalTargetThreshold_lt_stripEndpoint
