import PrimeNumberTheorem.ZeroDensityLayerBudgetDynamicCarlsonWeightedGoodHeightPNTTransfer

open PrimeNumberTheorem

#check NaturalPointTargetAmplitudeNegligible.add
#check actualZetaFiniteStrips_weightedBalancedGoodHeight_dynamicCarlson_positiveTail_negligible
#check actualZetaFiniteStrips_weightedBalancedGoodHeight_dynamicCarlson_fullTail_negligible
#check relativeChebyshevPsi0Error_natural_weightedBalancedGoodHeight_dynamicCarlson_negligible
#check tendsto_relativeChebyshevPsi0Error_natural_dynamicCarlsonWeightedGoodHeight
