import PrimeNumberTheorem.ZeroDensityLayerBudgetActualSelectedHeightStripProfileCertifiedFiniteGridTransfer

open PrimeNumberTheorem

#check ActualSelectedHeightFiniteStripGrid.extremalProfile
#check ActualSelectedHeightFiniteStripGrid.extremalProfile_mem
#check ActualSelectedHeightFiniteStripGrid.monotoneRoundingCovers_extremalProfile
#check unified_actualBalancedHeight_of_certifiedExtremalFiniteStripGrid
