import PrimeNumberTheorem.ZeroDensityLayerBudgetActualCarlsonConjugateFiniteSeedBarrier

#check @PrimeNumberTheorem.finiteSeedExtension_sdiff_conjugationStable
#check @PrimeNumberTheorem.actualCarlsonSeedOutside_lt_half_localCoefficient_of_conjugateCanonicalExtension
#check @PrimeNumberTheorem.actualCarlsonSeedOutside_lt_half_localCoefficient_of_stableCanonicalExtension
#check @PrimeNumberTheorem.not_exists_conjugateActualCarlsonCanonicalFiniteExtension_of_halfCoefficient_le_seedOutside
#check @PrimeNumberTheorem.not_exists_loss_and_conjugateActualCarlsonCanonicalFiniteExtension_of_halfCoefficient_le_seedOutside
