import PrimeNumberTheorem.ZeroDensityLayerBudgetAdaptiveBoundaryLocalDensity

#check PrimeNumberTheorem.pntAdaptiveBoundaryLocalDensityLogMargin
#check PrimeNumberTheorem.IsAdaptiveBoundaryLocalDensityAdmissible
#check PrimeNumberTheorem.pntAdaptiveBoundaryLocalDensityNormalizedMajorant
#check PrimeNumberTheorem.tendsto_pntAdaptiveBoundaryLocalDensityNormalizedMajorant_zero
#check PrimeNumberTheorem.eventually_densityLogCost_lt_gap_mul_log_of_admissible
#check PrimeNumberTheorem.isAdaptiveBoundaryLocalDensityAdmissible_of_fraction
#check PrimeNumberTheorem.tendsto_abs_zero_of_le_adaptiveBoundaryLocalDensityMajorant
#check PrimeNumberTheorem.pntAdaptiveBoundaryLocalDensityLogMargin_fixedHeightCost
#check PrimeNumberTheorem.isAdaptiveBoundaryLocalDensityAdmissible_fixedHeightCost_iff
#check PrimeNumberTheorem.tendsto_actualDynamicBoundaryLocalDensityNormalizedMajorant_zero
