import PrimeNumberTheorem.ZeroDensityLayerBudgetActualCubicGaussianSecondMoment

#print axioms PrimeNumberTheorem.norm_actualCubicPhaseFaithfulCoefficient
#print axioms PrimeNumberTheorem.actualCubicDyadicStripGaussianSecondMomentExcluding_le_gram
#print axioms PrimeNumberTheorem.actualCubicDyadicStripGaussianSecondMomentExcluding_le_occupancy_mul_capacity
