import PrimeNumberTheorem.ZeroDensityLayerBudgetActualSelectedHeightStripProfileApproximateTransfer

open PrimeNumberTheorem

#print axioms unified_actualBalancedHeight_of_approximateOptimalFiniteStripProfile
