import PrimeNumberTheorem.ZeroDensityLayerBudgetPintzCarlsonTargetLayerContract

#print axioms PrimeNumberTheorem.PintzCarlsonTargetLayerBudget.targetAmplitudeNegligible
#print axioms PrimeNumberTheorem.targetAmplitudeNegligible_finset_sum_of_pintzCarlsonBudgets
#print axioms PrimeNumberTheorem.twoHeightTargetComplementControl_of_pintzCarlsonBudgets
