import PrimeNumberTheorem.ZeroDensityLayerBudgetActualZeroPackageAutomaticEnergyBoundaryBudgetContract

#print axioms PrimeNumberTheorem.actualEqualRealPartZeroPackageDiagonalEnergy_mono_of_subset
#print axioms PrimeNumberTheorem.exists_actualZeroPackage_energy_boundaryBudget
