import PrimeNumberTheorem.ZeroDensityLayerBudgetActualSelectedHeightStripProfileApproximateTransfer

open PrimeNumberTheorem

#check unified_actualBalancedHeight_of_approximateOptimalFiniteStripProfile
