import PrimeNumberTheorem.ZeroDensityLayerBudgetActualMovingClusterComplementMajorantContract

open PrimeNumberTheorem

#print axioms canonicalMovingSelectedLayer_subset_emptyPolynomialLayer
#print axioms selectedMovingPositiveOutsideClusterTail_targetAmplitudeNegligible
#print axioms movingRightEdgeRealOrdinateOutsideTailNorm_eq_zero
#print axioms selectedMovingRightEdgeOutsideClusterComplement_targetAmplitudeNegligible
