import PrimeNumberTheorem.ZeroDensityLayerBudgetActualCarlsonSelectedHeightPNTLowerTransfer

open PrimeNumberTheorem

#check hasFarNaturalPointTargetAmplitudeWitness_of_difference_negligible
#check selectedUniformGoodHeightActualCarlsonPNTLowerTransfer
