import PrimeNumberTheorem.ZeroDensityLayerBudgetDynamicCarlsonAutomaticBetaPNTTransfer

#print axioms PrimeNumberTheorem.realOrdinatePNTZeroBottleneck_lt_one
#print axioms PrimeNumberTheorem.dynamicCarlsonActualPNTBottleneck_lt_automaticTargetBeta
#print axioms PrimeNumberTheorem.dynamicCarlsonAutomaticTargetBeta_lt_one
#print axioms PrimeNumberTheorem.relativeChebyshevPsi0Error_natural_dynamicCarlsonAutomaticBeta_negligible
#print axioms PrimeNumberTheorem.tendsto_relativeChebyshevPsi0Error_natural_dynamicCarlsonAutomaticBeta
