import PrimeNumberTheorem.ZeroDensityLayerBudgetActualDyadicCarlsonSelectedHeightPNT

open PrimeNumberTheorem

#print axioms tendsto_actualSelectedHeightSevenEighthsLowMass_zero
#print axioms actualSelectedHeightMovingMiddle_le_low_add_dyadicAnchor
#print axioms tendsto_actualSelectedHeightMovingMiddleMass_zero_of_dyadic
#print axioms eventually_actualSelectedHeightMovingPositiveRightEdgeCap_of_dynamicZeroFree
#print axioms tendsto_relativeChebyshevPsi0Error_of_selectedUniformGoodHeightDyadicCarlson
