import PrimeNumberTheorem.ZeroDensityLayerBudgetActualAutomaticQuantitativeReverseFiniteHeightZeroFreeContract

open PrimeNumberTheorem

#print axioms not_hasFarTargetAmplitude_mul_of_eventually_abs_le_mul
#print axioms exists_automaticGoodHeight_globalRealPartBound_eventualUpper_finiteHeightZeroFree
