import PrimeNumberTheorem.ZeroDensityLayerBudgetVariableBoundaryFullTailBudgetContract

#print axioms PrimeNumberTheorem.abs_variableBoundaryComplement_div_le_two_positive_add_real
#print axioms PrimeNumberTheorem.variableBoundaryFullComplement_targetAmplitudeNegligible
#print axioms PrimeNumberTheorem.actualVariableBoundaryFullTailExplicitFormulaResidual_targetAmplitudeNegligible
