import PrimeNumberTheorem.ZeroDensityLayerBudgetActualCubicLowDyadicCapacity

#print axioms PrimeNumberTheorem.actualCubicLowDyadicL2BlockCapacityMajorant_eq_capacity_of_lt
#print axioms PrimeNumberTheorem.actualCubicLowDyadicL2BlockCapacityMajorant_eq_logFifth_of_ge
#print axioms PrimeNumberTheorem.exists_actualCubicNormalizedSmoothedStripEnergyUpTo_le_lowDyadicL2CapacityMajorant
