import PrimeNumberTheorem.ZeroDensityLayerBudgetActualPintzCarlsonFiniteRateRemainderDecay

#print axioms PrimeNumberTheorem.actualPintzCarlsonRateNaturalRemainderUpperBound_tendsto_zero
#print axioms PrimeNumberTheorem.actualPintzCarlsonRate_actualRemainder_tendsto_zero
#print axioms PrimeNumberTheorem.actualPintzCarlsonGoodHeightOptimalHeight_actualRemainder_tendsto_zero
