import PrimeNumberTheorem.ZeroDensityLayerBudgetCarlsonFiniteAffineActualSelectedHeightCoefficient

#check PrimeNumberTheorem.nonempty_actualSelectedHeightWeightedBalancedCountCoefficientCertificate
#check PrimeNumberTheorem.actualSelectedHeightWeightedBalancedCountCoefficientCertificate
#check PrimeNumberTheorem.eventually_actualSelectedHeightWeightedBalancedNormalizedLayerNormSum_le
#check PrimeNumberTheorem.tendsto_actualSelectedHeightWeightedBalancedNormalizedLayerNormSum_zero
