import PrimeNumberTheorem.ZeroDensityLayerBudgetPNTHybridActualSelectedHeightLowLayer

#print axioms PrimeNumberTheorem.actualHybridGlobalLowLayerMajorant_mono_height
#print axioms PrimeNumberTheorem.tendsto_dynamicPositiveOutsideClusterPNTLayerNorm_div_targetAmplitude_zero_of_hybrid_selectedHeight
#print axioms PrimeNumberTheorem.actualHybridOutsideClusterLowLayer_selectedHeight_targetAmplitudeNegligible
