import PrimeNumberTheorem.ZeroDensityLayerBudgetActualThetaOnlyQuantitativeReverseZeroFreeContract

open PrimeNumberTheorem

#print axioms exists_thetaOnlyAutomaticGoodHeight_globalRealPartBound_eventualUpper_finiteHeightZeroFree
