import PrimeNumberTheorem.ZeroDensityLayerBudgetActualSelectedHeightWeightedGoodHeightOptimality

open PrimeNumberTheorem

#check selectedUniformGoodHeight_div_rpow_tendsto_one
#check selectedUniformGoodHeight_log_div_log_tendsto
#check
  actualSelectedHeightFiniteStripWeightedBalancedGoodHeight_div_optimalScale_tendsto_one
#check
  actualSelectedHeightFiniteStripWeightedBalancedGoodHeight_logGrowth_tendsto_optimalExponent
