import PrimeNumberTheorem.ZeroDensityLayerBudgetPNTHybridAffineSelectedHeight

#print axioms PrimeNumberTheorem.pntHybridAffineBalancedExponent_marginCertificate
#print axioms PrimeNumberTheorem.pntHybridAffineOptimalMargin_pos
#print axioms PrimeNumberTheorem.pntHybridAffineSelectedGoodHeight_div_optimalScale_tendsto_one
#print axioms PrimeNumberTheorem.pntHybridAffineSelectedGoodHeight_logGrowth_tendsto_optimalExponent
