import PrimeNumberTheorem.ZeroDensityLayerBudgetActualSelectedHeightStripProfileCertifiedCostOptimality

open PrimeNumberTheorem

#print axioms ActualSelectedHeightFiniteStripProfile.robustDecayFactor_le_of_optimalRobustMargin_le
#print axioms ActualSelectedHeightFiniteStripProfile.robustDecayFactor_robustMarginAntitoneCost
#print axioms ActualSelectedHeightFiniteStripProfile.optimalRobustMargin_minimizes_antitoneCost
#print axioms ActualSelectedHeightFiniteStripProfile.optimalRobustMargin_minimizes_robustDecayFactor
