import PrimeNumberTheorem.ZeroDensityLayerBudgetCarlsonDynamicLayerCountContract

#print axioms PrimeNumberTheorem.carlsonMovingLayeredQuadraticLogEnvelope_admissible
#print axioms PrimeNumberTheorem.carlsonMovingLayeredQuadraticRatio_eq
#print axioms PrimeNumberTheorem.carlsonDynamicFiniteLayerMass_le_layeredQuadraticRatio
#print axioms PrimeNumberTheorem.tendsto_carlsonDynamicFiniteLayerMass_zero
