import PrimeNumberTheorem.ZeroDensityLayerBudgetActualSelectedHeightExponentFeasibility

namespace PrimeNumberTheorem

#print axioms exists_actualSelectedHeightExponent_stripEndpoint_decay_iff
#print axioms actualSelectedHeightStripExponent_spec

end PrimeNumberTheorem
