import PrimeNumberTheorem.ZeroDensityLayerBudgetThirdOrderZeroResidueRectangle

#print axioms PrimeNumberTheorem.ExplicitFormulaResidues.exists_boundaryRectIntegral_thirdOrderExplicitFormulaIntegrand_eq_residue_sum_explicit_zeroPole
