import PrimeNumberTheorem.ZeroDensityLayerBudgetActualPintzCarlsonFullBudgetRateOptimizer

#print axioms PrimeNumberTheorem.abs_relativeChebyshevPsi0Error_le_actualPintzCarlsonRateFullBudget
#print axioms PrimeNumberTheorem.actualPintzCarlsonRateFullRelativeBudget_tendsto_zero
#print axioms PrimeNumberTheorem.actualPintzCarlsonFullBudgetMinimum_tendsto_zero
#print axioms PrimeNumberTheorem.actualPintzCarlsonFullBudgetOptimal_relativeError_tendsto_zero
#print axioms PrimeNumberTheorem.exists_pintzConstant_actualPintzCarlsonFullBudgetOptimal_PNT_decay
