import PrimeNumberTheorem.ZeroDensityLayerBudgetAdaptiveBoundaryLocalDensity

#print axioms PrimeNumberTheorem.tendsto_pntAdaptiveBoundaryLocalDensityNormalizedMajorant_zero
#print axioms PrimeNumberTheorem.eventually_densityLogCost_lt_gap_mul_log_of_admissible
#print axioms PrimeNumberTheorem.isAdaptiveBoundaryLocalDensityAdmissible_of_fraction
#print axioms PrimeNumberTheorem.tendsto_abs_zero_of_le_adaptiveBoundaryLocalDensityMajorant
#print axioms PrimeNumberTheorem.pntAdaptiveBoundaryLocalDensityLogMargin_fixedHeightCost
#print axioms PrimeNumberTheorem.isAdaptiveBoundaryLocalDensityAdmissible_fixedHeightCost_iff
#print axioms PrimeNumberTheorem.tendsto_actualDynamicBoundaryLocalDensityNormalizedMajorant_zero
