import PrimeNumberTheorem.ZeroDensityLayerBudgetBidirectionalHeightStrategyContract

#print axioms PrimeNumberTheorem.isTargetAmplitudeAdmissibleHeight_pntPolynomialLowerLogHeight
#print axioms PrimeNumberTheorem.nonempty_bidirectionalPNTHeightStrategy
#print axioms PrimeNumberTheorem.BidirectionalPNTHeightStrategy.upperLogHeight_ne_lowerLogHeight
#print axioms PrimeNumberTheorem.pntSqrtLogHeight_ne_pntPolynomialLowerLogHeight
