import PrimeNumberTheorem.ZeroDensityLayerBudgetDynamicCarlsonAutomaticBetaPNTTransfer

open PrimeNumberTheorem

#check realOrdinatePNTZeroBottleneck
#check realOrdinatePNTZeroBottleneck_lt_one
#check dynamicCarlsonActualPNTBottleneck
#check dynamicCarlsonAutomaticTargetBeta
#check dynamicCarlsonActualPNTBottleneck_lt_automaticTargetBeta
#check dynamicCarlsonAutomaticTargetBeta_lt_one
#check carlsonStripEndpointTargetThreshold_lt_automaticTargetBeta
#check realOrdinateNontrivialZero_re_lt_automaticTargetBeta
#check relativeChebyshevPsi0Error_natural_dynamicCarlsonAutomaticBeta_negligible
#check tendsto_relativeChebyshevPsi0Error_natural_dynamicCarlsonAutomaticBeta
