import PrimeNumberTheorem.ZeroDensityLayerBudgetActualZeroPackageNaturalAutomaticRemainder

#print axioms PrimeNumberTheorem.actualZeroPackage_selectedUniformGoodHeight_naturalLowerTransfer
#print axioms PrimeNumberTheorem.actualZeroPackage_selectedUniformGoodHeight_naturalLowerTransfer_of_nonempty
