import PrimeNumberTheorem.ZeroDensityLayerBudgetActualSelectedHeightNaturalTransfer

#print axioms PrimeNumberTheorem.TargetAmplitudeNegligible.naturalPoint
#print axioms PrimeNumberTheorem.eventually_abs_naturalPoint_three_remainders_lt_half
#print axioms PrimeNumberTheorem.hasFarNaturalPointTargetAmplitudeWitness_of_three_remainders
#print axioms PrimeNumberTheorem.HasFarNaturalPointTargetAmplitudeWitness.toReal
#print axioms PrimeNumberTheorem.actualSelectedHeight_naturalPointRemainder_lowerTransfer
