import PrimeNumberTheorem.ZeroDensityLayerBudgetVariableBoundaryExponentTransferContract

#print axioms PrimeNumberTheorem.positiveOutside_variableBoundaryZeroPackage_re_lt
#print axioms PrimeNumberTheorem.relativeChebyshevPsi0Error_eq_variableBoundaryPackage_add_actualResiduals
#print axioms PrimeNumberTheorem.variableBoundaryMainWitness_naturalSignAlternativeTransfer
#print axioms PrimeNumberTheorem.HasFarPositiveTargetAmplitudeWitness.relativeChebyshevPsi0Error_to_unnormalized_variableExponent
#print axioms PrimeNumberTheorem.HasFarNegativeTargetAmplitudeWitness.relativeChebyshevPsi0Error_to_unnormalized_variableExponent
#print axioms PrimeNumberTheorem.variableBoundaryMainWitness_unnormalizedSignAlternativeTransfer
