import PrimeNumberTheorem.ZeroDensityLayerBudgetThirdOrderContourRemainder

#print axioms PrimeNumberTheorem.ExplicitFormulaResidues.norm_thirdOrderExplicitFormulaIntegrand_horizontal_le_of_logDeriv_le_of_re_le
#print axioms PrimeNumberTheorem.ExplicitFormulaResidues.norm_thirdOrderExplicitFormulaIntegrand_odd_vertical_le
#print axioms PrimeNumberTheorem.ExplicitFormulaResidues.norm_integral_thirdOrderHorizontal_le_of_logDeriv
#print axioms PrimeNumberTheorem.ExplicitFormulaResidues.norm_integral_thirdOrderOddVertical_le
#print axioms PrimeNumberTheorem.ExplicitFormulaResidues.norm_thirdOrderContourRemainder_le_edges
#print axioms PrimeNumberTheorem.ExplicitFormulaResidues.exists_goodHeight_Icc_norm_thirdOrderContourRemainder_le
