import PrimeNumberTheorem.ZeroDensityLayerBudgetActualThetaOnlyCubicStrictUnifiedTransferContract

open PrimeNumberTheorem

#print axioms exists_thetaOnlyCubicStrictAutomaticGoodHeight_globalRealPartBoundNaturalTargetTransfer
