import PrimeNumberTheorem.ZeroDensityLayerBudgetActualSelectedHeightStripProfileCertifiedOptimization

open PrimeNumberTheorem

#check ActualSelectedHeightFiniteStripProfile.AnalyticTransferCertificate
#check ActualSelectedHeightFiniteStripProfile.HasAnalyticTransferCertificate
#check ActualSelectedHeightFiniteStripProfile.AnalyticTransferCertificate.hasUnifiedTransferResult
#check analyticTransferCertifiedProfiles
#check mem_analyticTransferCertifiedProfiles_iff
#check analyticTransferCertifiedProfiles_nonempty
#check unified_actualBalancedHeight_of_optimalCertifiedFiniteStripProfile
