import PrimeNumberTheorem.ZeroDensityLayerBudgetThirdOrderZeroPoleContourIdentity

#print axioms PrimeNumberTheorem.ExplicitFormulaResidues.exists_scaledRightIntegral_eq_zeroPoleResidue_sum_sub_thirdOrderContourRemainder
