import PrimeNumberTheorem.ZeroDensityLayerBudgetActualZeroPackageNaturalSampling

#print axioms PrimeNumberTheorem.norm_finitePhaseSum_le_coefficientNormBudget
#print axioms PrimeNumberTheorem.tendsto_zero_mul_finitePhaseSum
#print axioms PrimeNumberTheorem.tendsto_norm_targetAmplitude_mul_finitePhaseSum_natFloor_sub_div
#print axioms PrimeNumberTheorem.tendsto_actualEqualRealPartZeroPackagePNTMain_natFloor_error

