import PrimeNumberTheorem.ZeroDensityLayerBudgetActualMovingRightEdgeSignedSeedStabilityTransferContract

#print axioms PrimeNumberTheorem.automaticGoodHeight_twoHeight_movingRightEdgeSignedSeedNaturalPointLowerTransfer
#print axioms PrimeNumberTheorem.unified_automaticGoodHeight_twoHeight_movingRightEdgeSignedSeedNaturalTargetTransfer
#print axioms PrimeNumberTheorem.exists_automaticGoodHeight_movingRightEdgeSignedSeedNaturalTargetTransfer
