import PrimeNumberTheorem.ZeroDensityLayerBudgetActualCarlsonDyadicReciprocalCount

#print axioms PrimeNumberTheorem.dyadic_rpow_div_eq_pntDyadicReciprocalDensityRatio
#print axioms PrimeNumberTheorem.carlsonDyadicModel_div_eq_logFourthMajorant
#print axioms PrimeNumberTheorem.CarlsonEventualMajorant.eventually_actualCarlsonDyadicReciprocalCount_le
#print axioms PrimeNumberTheorem.CarlsonEventualMajorant.summable_actualCarlsonDyadicReciprocalCount
#print axioms PrimeNumberTheorem.exists_summable_actualCarlsonDyadicReciprocalCount
