import PrimeNumberTheorem.ZeroDensityLayerBudgetSharpConstantTransfer

open PrimeNumberTheorem

#check HasFarNaturalPointTargetAmplitudeWitness.transfer_eventually_sub_lt
#check actualWeightedBalancedGoodHeightPNTSharpConstantTransfer
