import PrimeNumberTheorem.ZeroDensityLayerBudgetActualDynamicBoundaryDominatedTail

#print axioms PrimeNumberTheorem.actualCarlsonDynamicBoundaryWeightedPowerTerm_nonneg
#print axioms PrimeNumberTheorem.actualCarlsonDynamicBoundaryWeightedPowerTerm_tendsto_zero
#print axioms PrimeNumberTheorem.norm_actualCarlsonDynamicBoundaryWeightedPowerTerm_le
#print axioms PrimeNumberTheorem.actualCarlsonDynamicBoundaryWeightedPowerTail_tendsto_zero
#print axioms PrimeNumberTheorem.actualCarlsonDynamicBoundaryNormalizedKernelTail_tendsto_zero
#print axioms PrimeNumberTheorem.actualCarlsonDynamicBoundaryNormalizedKernelTail_tendsto_zero_of_rightEdge
