import PrimeNumberTheorem.ZeroDensityLayerBudgetPNTSharpNaturalOmega

#print axioms PrimeNumberTheorem.actualWeightedBalancedGoodHeightPNTHasFarNaturalPoint_belowClusterConstant
#print axioms PrimeNumberTheorem.actualWeightedBalancedGoodHeightPNTNonemptyCluster_not_eventually_le_belowConstant
