import PrimeNumberTheorem.ZeroDensityLayerBudgetDirectL2SharedOuterFeasibility

#print axioms PrimeNumberTheorem.directL2CriticalRightHeight_lt_sharedOuterCap_iff
#print axioms PrimeNumberTheorem.directL2CriticalRightHeight_shortInterval_iff
#print axioms PrimeNumberTheorem.directL2SharedOuterEpsilonThreshold_zero
#print axioms PrimeNumberTheorem.directL2Polylog_shortInterval_sharedOuter_iff
#print axioms PrimeNumberTheorem.directL2PolylogSharedOuterEpsilonThreshold_pos_iff
#print axioms PrimeNumberTheorem.directL2Polylog_shortInterval_sharedOuter
#print axioms PrimeNumberTheorem.exists_pos_directL2Polylog_sharedOuterEpsilon
#print axioms PrimeNumberTheorem.directL2SharedOuterEpsilonThreshold_eq_expanded
#print axioms PrimeNumberTheorem.directL2SharedOuterEpsilonThreshold_pos_iff
#print axioms PrimeNumberTheorem.exists_pos_directL2_sharedOuterEpsilon_iff
#print axioms PrimeNumberTheorem.directL2_thresholds_eq_at_threeFourths
#print axioms PrimeNumberTheorem.directL2_sharedThreshold_lt_intrinsic_of_lt_threeFourths
#print axioms PrimeNumberTheorem.directL2_intrinsicThreshold_lt_shared_of_threeFourths_lt
