import PrimeNumberTheorem.ZeroDensityLayerBudgetThirdOrderDynamicContourDecay

#print axioms PrimeNumberTheorem.ExplicitFormulaResidues.exists_uniform_goodHeight_Icc_norm_thirdOrderContourRemainder_le
#print axioms PrimeNumberTheorem.ExplicitFormulaResidues.tendsto_thirdOrderDynamicContourLogPowerMajorant
#print axioms PrimeNumberTheorem.ExplicitFormulaResidues.thirdOrderGoodHeightContourRemainderMajorant_le_dynamic
#print axioms PrimeNumberTheorem.ExplicitFormulaResidues.exists_uniform_eventually_goodHeight_norm_thirdOrderContourRemainder_lt
