import PrimeNumberTheorem.ZeroDensityLayerBudgetActualSelectedHeightAutomaticNaturalTransfer

namespace PrimeNumberTheorem

#check selectedUniformGoodHeight_actualNaturalPointRemainder_lowerTransfer
#check
  unified_parametricPNTUpper_selectedUniformGoodHeight_actualNaturalPointLower

end PrimeNumberTheorem
