import PrimeNumberTheorem.ZeroDensityLayerBudgetPNTHybridActualLowLayer

namespace PrimeNumberTheorem

#check PositiveZeroOutsideClusterBucketInput.layer_multiplicityMass_le_globalZeroMultiplicity
#check dynamicPositiveOutsideClusterPNTLayerNorm_le_globalMultiplicity_mul_stripEndpoint
#check exists_globalCoefficient_dynamicPositiveOutsideClusterPNTLayerNorm_le_actualHybridMajorant

end PrimeNumberTheorem
