import PrimeNumberTheorem.ZeroDensityLayerBudgetThirdOrderLSeriesBridge

#print axioms PrimeNumberTheorem.intervalIntegral_vonMangoldt_LSeries_thirdOrder_eq_tsum
#print axioms PrimeNumberTheorem.intervalIntegral_neg_logDeriv_riemannZeta_thirdOrder_eq_vonMangoldt_tsum
#print axioms PrimeNumberTheorem.thirdOrderPerronTerm_eq_kernel
#print axioms PrimeNumberTheorem.norm_intervalIntegral_thirdOrderPerronTerm_sub_sq_le
#print axioms PrimeNumberTheorem.norm_truncated_neg_logDeriv_riemannZeta_thirdOrder_sub_secondSmoothedPsi_le
#print axioms PrimeNumberTheorem.thirdOrderExplicitFormulaIntegrand_eq_negLogDerivPerron
#print axioms PrimeNumberTheorem.exists_thirdOrderExplicitFormula_secondSmoothedPsi_error_le
