import PrimeNumberTheorem.ZeroDensityLayerBudgetActualZeroPackageCarlsonTransfer

#print axioms PrimeNumberTheorem.TargetAmplitudeNegligible.const_mul_amplitude
#print axioms PrimeNumberTheorem.ClusterExcludedTargetComplementCertificate.const_mul_amplitude
#print axioms PrimeNumberTheorem.unified_parametricPNTUpper_actualZeroPackageEnergyCarlsonLower
