import PrimeNumberTheorem.ZeroDensityLayerBudgetPNTDynamicTailHalfBarrier

#print axioms PrimeNumberTheorem.PositiveZeroOutsideClusterBucketInput.half_lt_re_of_sigma_half
#print axioms PrimeNumberTheorem.no_positiveNontrivialZero_re_le_half_of_rightEdgeBucket
#print axioms PrimeNumberTheorem.ActualWeightedBalancedGoodHeightRightEdgeTailCertificate.positiveZeros_strictlyRightOfHalf
#print axioms PrimeNumberTheorem.not_nonempty_rightEdgeTailCertificate_of_positiveZero_re_le_half
