import PrimeNumberTheorem.ZeroDensityLayerBudgetVariableBoundaryMonotoneEndToEndSignTransferContract

#print axioms PrimeNumberTheorem.actualMonotoneVariableBoundaryAutomaticZeroTails_unnormalizedSignAlternativeTransfer
