import PrimeNumberTheorem.ZeroDensityLayerBudgetCarlsonActualSelectedHeightBidirectionalTransfer

open scoped Topology

namespace PrimeNumberTheorem

#check ActualCarlsonSelectedHeightPNTBidirectionalTransferCertificate
#check actualCarlsonSelectedHeightPNTBidirectionalTransfer

end PrimeNumberTheorem
