import PrimeNumberTheorem.ZeroDensityLayerBudgetActualDynamicBoundaryCanonicalBetaTransfer

#print axioms PrimeNumberTheorem.actualDynamicBoundaryCanonicalBetaThreshold_spec
#print axioms PrimeNumberTheorem.actualDynamicBoundaryCanonicalBetaPNTUpperTransfer
#print axioms PrimeNumberTheorem.actualDynamicBoundaryCanonicalBetaPNTBidirectionalTransfer
