import PrimeNumberTheorem.ZeroDensityLayerBudgetActualSelectedHeightStripProfileFiniteGridDirectionalSelection

open PrimeNumberTheorem

#check ActualSelectedHeightFiniteStripGrid.SigmaUpperCovers
#check ActualSelectedHeightFiniteStripGrid.TauLowerCovers
#check ActualSelectedHeightFiniteStripGrid.upperRoundedSigma
#check ActualSelectedHeightFiniteStripGrid.upperRoundedSigma_mem
#check ActualSelectedHeightFiniteStripGrid.le_upperRoundedSigma
#check ActualSelectedHeightFiniteStripGrid.lowerRoundedTau
#check ActualSelectedHeightFiniteStripGrid.lowerRoundedTau_mem
#check ActualSelectedHeightFiniteStripGrid.lowerRoundedTau_le
#check ActualSelectedHeightFiniteStripGrid.selectedRoundedProfile_mem_and_covers
#check unified_actualBalancedHeight_of_directionallyCoveringFiniteStripGrid
