import PrimeNumberTheorem.ZeroDensityLayerBudgetPNTHybridActualSelectedHeightFiniteStrips

#print axioms PrimeNumberTheorem.pntHybridAffineSelectedHeight_lowLayer_margin
#print axioms PrimeNumberTheorem.pntHybridAffineSelectedHeight_highLayer_margin
#print axioms PrimeNumberTheorem.actualHybridFiniteStripsOutsideCluster_optimizedSelectedHeight_eachLayer_negligible
#print axioms PrimeNumberTheorem.actualHybridFiniteStripsOutsideCluster_optimizedSelectedHeight_layerSum_negligible
#print axioms PrimeNumberTheorem.actualHybridFiniteStripsOutsideCluster_optimizedSelectedHeight_positiveTail_negligible
#print axioms PrimeNumberTheorem.actualHybridFiniteStripsOutsideCluster_optimizedSelectedHeight_fullTail_negligible
