import PrimeNumberTheorem.ZeroDensityLayerBudgetActualCarlsonSelectedHeightDecay

open PrimeNumberTheorem

#check actualCarlsonSelectedHeightPositiveZeroNormalizedSum
#check actualCarlsonSelectedHeightFullZeroNormalizedSum
#check actualCarlsonSelectedHeightPositiveZeroNormalizedSum_tendsto_zero
#check actualCarlsonSelectedHeightFullZeroNormalizedSum_tendsto_zero
