import PrimeNumberTheorem.ZeroDensityLayerBudgetActualSelectedHeightStripProfileCertifiedCostOptimality

open PrimeNumberTheorem

#print axioms ActualSelectedHeightFiniteStripProfile.robustDecayFactor_le_of_optimalRobustMargin_le
#print axioms ActualSelectedHeightFiniteStripProfile.robustDecayFactor_robustMarginAntitoneCost
#print axioms ActualSelectedHeightFiniteStripProfile.RobustMarginAntitoneCost.nonneg_const_mul
#print axioms ActualSelectedHeightFiniteStripProfile.RobustMarginAntitoneCost.add
#print axioms ActualSelectedHeightFiniteStripProfile.weightedRobustDecayEnvelope_robustMarginAntitoneCost
#print axioms ActualSelectedHeightFiniteStripProfile.optimalRobustMargin_minimizes_antitoneCost
#print axioms ActualSelectedHeightFiniteStripProfile.optimalRobustMargin_minimizes_robustDecayFactor
#print axioms ActualSelectedHeightFiniteStripProfile.optimalRobustMargin_minimizes_weightedRobustDecayEnvelope
#print axioms ActualSelectedHeightFiniteStripProfile.optimalRobustMargin_bounds_costBy_competitorEnvelope
