import PrimeNumberTheorem.ZeroDensityLayerBudgetActualSelectedHeightWeightedBalancedGoodHeightCharacterization

#check
  PrimeNumberTheorem.selectedUniformGoodHeight_ratio_tendsto_one_iff_exponent_eq
#check
  PrimeNumberTheorem.actualSelectedHeightFiniteStrip_optimalMarginCertificate_iff_goodHeightRatio_tendsto_one
