import PrimeNumberTheorem.ZeroDensityLayerBudgetActualSelectedHeightWeightedBalancedExponentUniqueness

#print axioms PrimeNumberTheorem.exists_strip_eq_actualSelectedHeightFiniteStripOptimalPhysicalMargin
#print axioms PrimeNumberTheorem.actualSelectedHeightFiniteStripWeightedBalancedExponent_unique
#print axioms PrimeNumberTheorem.actualSelectedHeightFiniteStrip_optimalMarginCertificate_iff

