import PrimeNumberTheorem.ZeroDensityLayerBudgetActualCubicCarlsonMovingTail

#print axioms PrimeNumberTheorem.Summable.tendsto_summableNatTail_zero
#print axioms PrimeNumberTheorem.CarlsonEventualMajorant.tendsto_actualCubicDyadicStripSquareCapacityExcludingTail_zero
#print axioms PrimeNumberTheorem.CarlsonEventualMajorant.tendsto_actualCubicDyadicStripSquareCapacityExcludingTail_comp_zero
