import PrimeNumberTheorem.ZeroDensityLayerBudgetActualSelectedHeightStripProfileCertifiedContourEnvelope

open PrimeNumberTheorem

#check
  ActualSelectedHeightFiniteStripProfile.balancedExponent_sub_contourTransition_eq_optimalRobustMargin
#check ActualSelectedHeightFiniteStripProfile.selectedBalancedContourNormalizedCost
#check selectedPolynomialNaturalContourMajorant_div_targetZeroPowerAmplitude
#check
  ActualSelectedHeightFiniteStripProfile.actualPolynomialRemainderTargetMajorant_balancedExponent_eq
#check
  ActualSelectedHeightFiniteStripProfile.selectedBalancedContourNormalizedCost_eq_weightedRobustDecayEnvelope
#check
  ActualSelectedHeightFiniteStripProfile.selectedBalancedContourNormalizedCost_robustMarginAntitoneCost
#check
  ActualSelectedHeightFiniteStripProfile.optimalRobustMargin_minimizes_selectedBalancedContourNormalizedCost
