import PrimeNumberTheorem.ZeroDensityLayerBudgetActualDynamicCarlsonGapFamilyContract

#print axioms PrimeNumberTheorem.actualDynamicCarlsonGapStripUnion_mass_eq_familyMass
#print axioms PrimeNumberTheorem.actualDynamicCarlsonTwoHeightBudget_le_pointwiseMajorant
#print axioms PrimeNumberTheorem.eventually_actualDynamicCarlsonGapLayerMass_le_ownRatio
#print axioms PrimeNumberTheorem.tendsto_actualDynamicCarlsonGapFamilyMass_zero
#print axioms PrimeNumberTheorem.tendsto_actualDynamicCarlsonGapStripUnion_mass_zero
