import PrimeNumberTheorem.ZeroDensityLayerBudgetPNTReverseClusterExclusion

#print axioms PrimeNumberTheorem.eventually_targetZeroPowerAmplitude_natural_pos
#print axioms PrimeNumberTheorem.NaturalPointTargetAmplitudeNegligible.not_hasFarNaturalPoint_mul
#print axioms PrimeNumberTheorem.actualWeightedBalancedGoodHeightPNTErrorNegligible_forces_emptyCluster
