import PrimeNumberTheorem.ZeroDensityLayerBudgetDynamicCarlsonWeightedGoodHeightPNTTransfer

#print axioms PrimeNumberTheorem.NaturalPointTargetAmplitudeNegligible.add
#print axioms PrimeNumberTheorem.actualZetaFiniteStrips_weightedBalancedGoodHeight_dynamicCarlson_positiveTail_negligible
#print axioms PrimeNumberTheorem.actualZetaFiniteStrips_weightedBalancedGoodHeight_dynamicCarlson_fullTail_negligible
#print axioms PrimeNumberTheorem.relativeChebyshevPsi0Error_natural_weightedBalancedGoodHeight_dynamicCarlson_negligible
#print axioms PrimeNumberTheorem.tendsto_relativeChebyshevPsi0Error_natural_dynamicCarlsonWeightedGoodHeight
