import PrimeNumberTheorem.ZeroDensityLayerBudgetActualSelectedHeightStripProfileRefinement

namespace PrimeNumberTheorem

#check actualSelectedHeightFiniteStripBottleneck_le_iff
#check le_actualSelectedHeightFiniteStripAlphaCeiling_iff
#check ActualSelectedHeightFiniteStripProfileRefinement
#check ActualSelectedHeightFiniteStripProfileRefinement.bottleneck_mono
#check ActualSelectedHeightFiniteStripProfileRefinement.alphaCeiling_mono
#check
  ActualSelectedHeightFiniteStripProfileRefinement.effectiveAlphaCeiling_mono
#check ActualSelectedHeightFiniteStripProfileRefinement.feasible
#check ActualSelectedHeightFiniteStripProfileRefinement.robustMargin_mono

end PrimeNumberTheorem
