import PrimeNumberTheorem.ZeroDensityLayerBudgetActualSelectedHeightWeightedBalancedExponent

open PrimeNumberTheorem

#check actualSelectedHeightStripCarlsonSlope
#check actualSelectedHeightStripPhysicalMargin
#check actualSelectedHeightStripPhysicalMargin_eq
#check actualSelectedHeightStripBalancedPhysicalMargin
#check actualSelectedHeightFiniteStripOptimalPhysicalMargin
#check actualSelectedHeightFiniteStripWeightedBalancedExponent
#check ActualSelectedHeightFiniteStripPhysicalMarginCertificate
#check actualSelectedHeightStripSlope_pos
#check actualSelectedHeightStripBalancedPhysicalMargin_pos
#check actualSelectedHeightStripBalancedPhysicalMargin_lt_beta
#check physicalMargin_le_stripBalancedPhysicalMargin
#check actualSelectedHeightFiniteStripOptimalPhysicalMargin_le_strip
#check le_actualSelectedHeightFiniteStripOptimalPhysicalMargin
#check actualSelectedHeightFiniteStripOptimalPhysicalMargin_pos
#check
  actualSelectedHeightFiniteStripWeightedBalancedExponent_marginCertificate
#check actualSelectedHeightFiniteStripWeightedBalancedExponent_maximizes
#check
  actualSelectedHeightFiniteStripWeightedBalancedExponent_endpointExponent_le
#check actualSelectedHeightFiniteStripWeightedBalancedExponent_spec
