import PrimeNumberTheorem.ZeroDensityLayerBudgetActualTargetAmplitudePositiveTailCompositionContract

open PrimeNumberTheorem

#print axioms canonicalOutsideClusterHighLayer_subset_actualPositiveCarlsonStrip
#print axioms dynamicPositiveOutsideClusterPNTTailNorm_le_lowTwoHeight_add_strip
#print axioms tendsto_actualPositiveOutsideClusterTailTargetAmplitudeNorm
