import PrimeNumberTheorem.ZeroDensityLayerBudgetActualSelectedHeightStripProfileCertifiedCostOptimality

open PrimeNumberTheorem

#check ActualSelectedHeightFiniteStripProfile.RobustMarginAntitoneCost
#check ActualSelectedHeightFiniteStripProfile.robustDecayFactor
#check ActualSelectedHeightFiniteStripProfile.robustDecayFactor_le_of_optimalRobustMargin_le
#check ActualSelectedHeightFiniteStripProfile.robustDecayFactor_robustMarginAntitoneCost
#check ActualSelectedHeightFiniteStripProfile.optimalRobustMargin_minimizes_antitoneCost
#check ActualSelectedHeightFiniteStripProfile.optimalRobustMargin_minimizes_robustDecayFactor
