import PrimeNumberTheorem.ZeroDensityLayerBudgetWeightedPowerBoundaryLimit

open PrimeNumberTheorem

#print axioms weightedPowerLayers_tendsto_boundaryMass_of_summable
#print axioms weightedPowerBoundaryMass_eq_zero_of_lt
