import PrimeNumberTheorem.ZeroDensityLayerBudgetTargetAmplitudeExponentCriterionContract

#print axioms PrimeNumberTheorem.targetAmplitudePintzCarlsonExponent_neg_iff
#print axioms PrimeNumberTheorem.targetAmplitudePintzCarlsonExponent_nonneg_of_target_le_strip
#print axioms PrimeNumberTheorem.not_targetAmplitudePintzCarlsonExponent_neg_of_target_le_strip
#print axioms PrimeNumberTheorem.polynomialHeight_targetAmplitudeExponent_neg_iff
#print axioms PrimeNumberTheorem.exists_polynomialHeight_targetAmplitude_decay_iff
