import PrimeNumberTheorem.ZeroDensityLayerBudgetActualCarlsonBoundaryMassFiniteComparison

#print axioms PrimeNumberTheorem.actualCarlsonCapturedBoundaryMass_le_finiteVisibleClusterCoefficientMass
#print axioms PrimeNumberTheorem.actualCarlsonCapturedBoundaryMass_eq_seed_add_extension
#print axioms PrimeNumberTheorem.actualCarlsonCapturedBoundaryMass_extension_add_outside_eq_seedOutside
#print axioms PrimeNumberTheorem.actualCarlsonSeedOutside_lt_add_of_extensionMass_lt_of_outside_lt
