import PrimeNumberTheorem.ZeroDensityLayerBudgetActualCarlsonWindowEnergyBidirectionalPNTTransfer

open PrimeNumberTheorem

#check exists_zeroSupportedActualCarlsonFiniteSeedWindowEnergyBidirectionalPNTCanonicalSharpRealTransfer
