import PrimeNumberTheorem.ZeroDensityLayerBudgetActualZeroPackageQuantitativeEnergyContract

#print axioms PrimeNumberTheorem.exists_actualEqualRealPartZeroPackageEnergy_gt
#print axioms PrimeNumberTheorem.exists_actualEqualRealPartZeroPackageEnergy_gt_diagonal_half
