import PrimeNumberTheorem.ZeroDensityLayerBudgetCarlsonBoundarySlopeFloor

#print axioms PrimeNumberTheorem.carlsonClassicalDensitySlope_le_of_le_on_rightHalf
#print axioms PrimeNumberTheorem.carlsonClassical_boundaryGap_exceeds_fixedBetaFloor
#print axioms PrimeNumberTheorem.eventually_fixedBetaGapFloor_of_movingCarlsonBoundaryDecay
#print axioms PrimeNumberTheorem.not_gap_tendsto_zero_of_movingCarlsonBoundaryDecay
#print axioms PrimeNumberTheorem.not_dynamicBoundaryGap_tendsto_zero_of_movingCarlsonStrips
