import PrimeNumberTheorem.ZeroDensityLayerBudgetActualCarlsonSelectedHeightPNTTransfer

open PrimeNumberTheorem

#print axioms actualCarlsonSelectedHeightOutsideClusterComplement_targetNegligible
#print axioms actualCarlsonSelectedHeightPNTClusterResidual_targetNegligible
#print axioms selectedUniformGoodHeightActualCarlsonPNTClusterResidual_targetNegligible
