import PrimeNumberTheorem.ZeroDensityLayerBudgetActualCarlsonBalancedBoundaryCapturedPNTTransfer

#print axioms PrimeNumberTheorem.eventually_abs_selectedUniformGoodHeightActualCarlsonBalancedBoundaryCapturedPNTClusterResidual_lt_automatic
#print axioms PrimeNumberTheorem.selectedUniformGoodHeightActualCarlsonBalancedBoundaryCapturedPNTHasFarNaturalPoint_belowClusterConstant
#print axioms PrimeNumberTheorem.selectedUniformGoodHeightActualCarlsonBalancedBoundaryCapturedPNTSharpSignedTransfer_automatic
