import PrimeNumberTheorem.ZeroForcedOscillation

#print axioms PrimeNumberTheorem.ZeroForcedOscillation.realExp_cpow_eq_growth_mul_oscillation
#print axioms PrimeNumberTheorem.ZeroForcedOscillation.im_injOn_of_re_eq
#print axioms PrimeNumberTheorem.ZeroForcedOscillation.equalRealPart_zeroPackage_eq_exponentialPolynomial
#print axioms PrimeNumberTheorem.ZeroForcedOscillation.abs_intervalIntegral_sqNorm_exponentialPolynomial_sub_diagonal_le
#print axioms PrimeNumberTheorem.ZeroForcedOscillation.abs_intervalIntegral_sqNorm_multiplicityWeightedExponentialPolynomial_sub_diagonal_le
#print axioms PrimeNumberTheorem.ZeroForcedOscillation.exists_mem_Ioo_sqNorm_exponentialPolynomial_ge
#print axioms PrimeNumberTheorem.ZeroForcedOscillation.exists_mem_Ioo_sqNorm_equalRealPart_zeroPackage_ge
