import PrimeNumberTheorem.ZeroDensityLayerBudgetActualSelectedHeightStripProfileCertifiedContourEnvelope

open PrimeNumberTheorem

#print axioms
  ActualSelectedHeightFiniteStripProfile.balancedExponent_sub_contourTransition_eq_optimalRobustMargin
#print axioms selectedPolynomialNaturalContourMajorant_div_targetZeroPowerAmplitude
#print axioms
  ActualSelectedHeightFiniteStripProfile.actualPolynomialRemainderTargetMajorant_balancedExponent_eq
#print axioms
  ActualSelectedHeightFiniteStripProfile.selectedBalancedContourNormalizedCost_eq_weightedRobustDecayEnvelope
#print axioms
  ActualSelectedHeightFiniteStripProfile.selectedBalancedContourNormalizedCost_robustMarginAntitoneCost
#print axioms
  ActualSelectedHeightFiniteStripProfile.optimalRobustMargin_minimizes_selectedBalancedContourNormalizedCost
