import PrimeNumberTheorem.ZeroDensityLayerBudgetActualCubicLowSummedGaussianL2

#print axioms PrimeNumberTheorem.actualCubicNormalizedLowDyadicGaussianGramExcluding_le_occupancy_mul_energy
#print axioms PrimeNumberTheorem.exists_actualCubicNormalizedLowDyadicGaussianGramExcluding_le_lowDyadicL2CapacityMajorant
