import PrimeNumberTheorem.ZeroDensityLayerBudgetActualSelectedHeightStripProfileFeasibilityCharacterization

open PrimeNumberTheorem

#print axioms ActualSelectedHeightFiniteStripProfile.optimalRobustMargin_pos_iff_isFeasible
#print axioms optimalActualSelectedHeightFiniteStripProfile_feasible_iff_exists
#print axioms optimalActualSelectedHeightFiniteStripProfile_optimalRobustMargin_pos_iff_exists
#print axioms optimalActualSelectedHeightFiniteStripProfile_optimalRobustMargin_nonpos_iff
