import PrimeNumberTheorem.ZeroDensityLayerBudgetActualSelectedHeightNaturalRemainderDecay

#print axioms PrimeNumberTheorem.cofinalPNTFormulaRemainderBound_zero_relative_le_selectedPolynomialMajorant
#print axioms PrimeNumberTheorem.selectedPolynomialNaturalContourMajorant_targetNegligible
#print axioms PrimeNumberTheorem.selectedNaturalClosedLogRelative_targetNegligible
#print axioms PrimeNumberTheorem.selectedUniformGoodHeightNaturalRemainderUpperBound_targetNegligible
#print axioms PrimeNumberTheorem.selectedUniformGoodHeight_actualNaturalRemainderCertificate
