import PrimeNumberTheorem.ZeroDensityLayerBudgetActualCarlsonZeroSupportedSelectorBudgetAlternative

#print axioms PrimeNumberTheorem.actualCarlsonFiniteExtensionCoefficientMass_ge_loss_of_halfCoefficient_le_seedOutside
#print axioms PrimeNumberTheorem.exists_zeroSupportedActualCarlsonFiniteSeedCanonicalGap_with_extensionMass_ge
