import PrimeNumberTheorem.ZeroDensityLayerBudgetJointTwoHeightCanonicalStrictTargetExponentContract

open PrimeNumberTheorem

#print axioms jointTwoHeightCanonicalStrictTargetExponent_spec
#print axioms theta_lt_improvedThreshold_canonicalStrictTargetExponent
