import PrimeNumberTheorem.ZeroDensityLayerBudgetCarlsonActualFiniteStripsContract

#print axioms PrimeNumberTheorem.dynamicPositivePNTTailNorm_le_sum_layerNorms
#print axioms PrimeNumberTheorem.targetZeroPowerAmplitude_eventually_pos
#print axioms PrimeNumberTheorem.actualZetaFiniteStrips_layerNormSum_targetAmplitudeNegligible
#print axioms PrimeNumberTheorem.actualZetaFiniteStrips_positiveTail_targetAmplitudeNegligible
