import PrimeNumberTheorem.ZeroDensityLayerBudgetJointTwoHeightPrescribedCapFeasibilityContract

open PrimeNumberTheorem

#print axioms exists_jointTwoHeightTargetAmplitudeMargins_of_endpoints
#print axioms exists_jointTwoHeightTargetAmplitudeParameters_above_cap
