import PrimeNumberTheorem.ZeroDensityLayerBudgetPNTSharpSignedOmega

#print axioms PrimeNumberTheorem.HasFarNaturalPointPositiveTargetAmplitudeWitness.transfer_eventually_sub_lt
#print axioms PrimeNumberTheorem.HasFarNaturalPointNegativeTargetAmplitudeWitness.transfer_eventually_sub_lt
#print axioms PrimeNumberTheorem.actualWeightedBalancedGoodHeightPNTSharpSignedOmega
