import PrimeNumberTheorem.ZeroDensityLayerBudgetActualCubicCarlsonCertificateSummability

#print axioms PrimeNumberTheorem.one_add_log_add_six_le_three_mul_log
#print axioms PrimeNumberTheorem.dyadic_succ_rpow_div_sixth_eq_actualCubicCarlsonRatio
#print axioms PrimeNumberTheorem.log_dyadic_succ_pow_five
#print axioms PrimeNumberTheorem.CarlsonEventualMajorant.eventually_actualCubicCertificateBlock_le_logFifth
#print axioms PrimeNumberTheorem.CarlsonEventualMajorant.summable_actualCubicDyadicStripSquareCapacityExcluding
