import PrimeNumberTheorem.ZeroDensityLayerBudgetActualSelectedHeightStripProfileMonotoneRoundingTransfer

open PrimeNumberTheorem

#print axioms actualSelectedHeightStripAlphaCeiling_mono_of_monotoneRounding
#print axioms monotoneRoundingCovers_refl
#print axioms monotoneRoundingCovers_trans
#print axioms stripAlphaCeilingCoversWithin_zero_of_monotoneRoundingCovers
#print axioms exists_feasibleActualSelectedHeightFiniteStripProfile_of_monotoneRounding
#print axioms unified_actualBalancedHeight_of_monotoneRoundedStripProfile
