import PrimeNumberTheorem.ZeroDensityLayerBudgetPNTDynamicSignedReverseTransfer

#print axioms PrimeNumberTheorem.actualWeightedBalancedGoodHeightPNTEventualUpper_globalZeroFree_of_dynamicPositiveWitness
#print axioms PrimeNumberTheorem.actualWeightedBalancedGoodHeightPNTEventualLower_globalZeroFree_of_dynamicNegativeWitness
