import PrimeNumberTheorem.ZeroDensityLayerBudgetVariableBoundaryMonotoneEndToEndSignedOmegaContract

#print axioms PrimeNumberTheorem.actualMonotoneVariableBoundaryAutomaticZeroTails_unnormalizedSignedOmega
