import PrimeNumberTheorem.ZeroForcedOscillation

#print axioms PrimeNumberTheorem.ZeroForcedOscillation.abs_intervalIntegral_sqNorm_exponentialPolynomial_sub_diagonal_le
#print axioms PrimeNumberTheorem.ZeroForcedOscillation.abs_intervalIntegral_sqNorm_multiplicityWeightedExponentialPolynomial_sub_diagonal_le
#print axioms PrimeNumberTheorem.ZeroForcedOscillation.exists_mem_Ioo_sqNorm_exponentialPolynomial_ge
