import PrimeNumberTheorem.ZeroDensityLayerBudgetWindowEnergySeparationScaled

open PrimeNumberTheorem

#print axioms HasFarWindowCardAdvantage.scaleBoth
#print axioms HasFarWindowEnergySeparation.toScaledWindowCardAdvantage
