import PrimeNumberTheorem.ZeroDensityLayerBudgetActualCubicCarlsonCertificateBlock

#print axioms PrimeNumberTheorem.CarlsonEventualMajorant.eventually_actualCubicDyadicCountMajorant_le
#print axioms PrimeNumberTheorem.actualCubicDyadicStripSquareCapacityExcluding_le_certificateBlock
#print axioms PrimeNumberTheorem.actualCubicCarlsonCertificatePolynomialExponent_le_neg_five
