import PrimeNumberTheorem.ZeroDensityLayerBudgetPNTSignedReverseClusterExclusion

#print axioms PrimeNumberTheorem.not_hasFarNaturalPointPositive_mul_of_eventually_le_mul
#print axioms PrimeNumberTheorem.not_hasFarNaturalPointNegative_mul_of_eventually_neg_mul_le
#print axioms PrimeNumberTheorem.actualWeightedBalancedGoodHeightPNTEventualUpper_forces_emptyCluster_of_positiveWitness
#print axioms PrimeNumberTheorem.actualWeightedBalancedGoodHeightPNTEventualLower_forces_emptyCluster_of_negativeWitness
