import PrimeNumberTheorem.ZeroDensityLayerBudgetActualSelectedHeightStripProfileCoverageTransfer

open PrimeNumberTheorem

#print axioms stripAlphaCeilingCoversWithin_refl
#print axioms stripAlphaCeilingCoversWithin_mono
#print axioms stripAlphaCeilingCoversWithin_trans
#print axioms alphaCeiling_approximation_of_stripAlphaCeilingCoverage
#print axioms effectiveAlphaCeiling_approximation_of_stripAlphaCeilingCoverage
#print axioms exists_feasibleActualSelectedHeightFiniteStripProfile_of_stripAlphaCeilingCoverage
#print axioms unified_actualBalancedHeight_of_stripAlphaCeilingCoverage
