import PrimeNumberTheorem.ZeroDensityLayerBudgetActualSelectedHeightStripProfileRefinement

namespace PrimeNumberTheorem

#check actualSelectedHeightFiniteStripBottleneck_le_iff
#check le_actualSelectedHeightFiniteStripAlphaCeiling_iff
#check ActualSelectedHeightFiniteStripProfileRefinement
#check ActualSelectedHeightFiniteStripProfileRefinement.refl
#check ActualSelectedHeightFiniteStripProfileRefinement.trans
#check ActualSelectedHeightFiniteStripProfileRefinement.bottleneck_mono
#check ActualSelectedHeightFiniteStripProfileRefinement.alphaCeiling_mono
#check
  ActualSelectedHeightFiniteStripProfileRefinement.effectiveAlphaCeiling_mono
#check ActualSelectedHeightFiniteStripProfileRefinement.feasible
#check ActualSelectedHeightFiniteStripProfileRefinement.robustMargin_mono
#check
  ActualSelectedHeightFiniteStripProfileRefinement.bottleneck_eq_of_mutual
#check
  ActualSelectedHeightFiniteStripProfileRefinement.alphaCeiling_eq_of_mutual
#check
  ActualSelectedHeightFiniteStripProfileRefinement.effectiveAlphaCeiling_eq_of_mutual
#check
  ActualSelectedHeightFiniteStripProfileRefinement.robustMargin_eq_of_mutual

end PrimeNumberTheorem
