import PrimeNumberTheorem.ZeroDensityLayerBudgetActualMovingExtensionAbsoluteMassContract

#print axioms PrimeNumberTheorem.selectedPositiveOutsideClusterPNTAbsoluteMass_targetAmplitudeNegligible
#print axioms PrimeNumberTheorem.selectedFullOutsideClusterPNTAbsoluteMass_targetAmplitudeNegligible
#print axioms PrimeNumberTheorem.selectedMovingRightEdgeExtension_targetAmplitudeNegligible
#print axioms PrimeNumberTheorem.exists_automaticGoodHeight_positiveOutsideClusterGapMovingSeedSignedNaturalTargetTransfer
