import PrimeNumberTheorem.ZeroDensityLayerBudgetActualCarlsonCanonicalFiniteSeedBarrier

#print axioms PrimeNumberTheorem.actualCarlsonSeedOutside_lt_localCoefficient_of_canonicalExtension
#print axioms PrimeNumberTheorem.not_exists_actualCarlsonCanonicalFiniteExtension_of_localCoefficient_le_seedOutside
#print axioms PrimeNumberTheorem.not_exists_loss_and_actualCarlsonCanonicalFiniteExtension_of_localCoefficient_le_seedOutside
