import PrimeNumberTheorem.ZeroDensityLayerBudgetVisibleClusterNormalizedCoefficientCap

open PrimeNumberTheorem

#check eventually_abs_dynamicVisibleClusterPNTMain_div_targetAmplitude_le_coefficientMass
#check HasFarWindowEnergyBudgets.visibleClusterNormalized_toEnergySeparation
