import PrimeNumberTheorem.ZeroDensityLayerBudgetActualSelectedHeightStripProfileBalancedExponentRefinement

open PrimeNumberTheorem

#check ActualSelectedHeightFiniteStripProfile.effectiveAlphaCeiling
#check ActualSelectedHeightFiniteStripProfile.balancedPolynomialScale
#check ActualSelectedHeightFiniteStripProfile.balancedExponent_le_iff
#check ActualSelectedHeightFiniteStripProfile.balancedExponent_lt_iff
#check ActualSelectedHeightFiniteStripProfile.Refines.balancedExponent_mono
#check ActualSelectedHeightFiniteStripProfile.Refines.balancedExponent_lt
#check ActualSelectedHeightFiniteStripProfile.Refines.balancedPolynomialScale_mono
#check ActualSelectedHeightFiniteStripProfile.Refines.balancedPolynomialScale_lt
