import PrimeNumberTheorem.ZeroDensityLayerBudgetActualSelectedHeightNaturalTransfer

namespace PrimeNumberTheorem

#check NaturalPointTargetAmplitudeNegligible
#check HasFarNaturalPointTargetAmplitudeWitness
#check TargetAmplitudeNegligible.naturalPoint
#check eventually_naturalPoint_pos_of_eventually_pos
#check eventually_abs_lt_mul_of_naturalPointTargetAmplitudeNegligible
#check eventually_abs_naturalPoint_three_remainders_lt_half
#check hasFarNaturalPointTargetAmplitudeWitness_of_three_remainders
#check HasFarNaturalPointTargetAmplitudeWitness.toReal
#check ActualSelectedHeightNaturalPointRemainderCertificate
#check actualSelectedHeight_naturalPointRemainder_lowerTransfer

end PrimeNumberTheorem
