import PrimeNumberTheorem.ZeroDensityLayerBudgetActualDynamicBoundaryWitnessTransfer

open PrimeNumberTheorem

#print axioms actualDynamicBoundaryMainWitness_naturalTransfer
#print axioms actualDynamicBoundaryMainWitness_realTransfer
