import PrimeNumberTheorem.ZeroDensityLayerBudgetActualSelectedHeightStripProfileFeasibilityCharacterization

open PrimeNumberTheorem

#check ActualSelectedHeightFiniteStripProfile.optimalRobustMargin_pos_iff_isFeasible
#check optimalActualSelectedHeightFiniteStripProfile_feasible_iff_exists
#check optimalActualSelectedHeightFiniteStripProfile_optimalRobustMargin_pos_iff_exists
#check optimalActualSelectedHeightFiniteStripProfile_optimalRobustMargin_nonpos_iff
