import PrimeNumberTheorem.ZeroDensityLayerBudgetPNTHybridCofinalOutsideClusterCap

#print axioms PrimeNumberTheorem.heightwiseOutsideClusterRealPartCap_iff_global
#print axioms PrimeNumberTheorem.hybridSelectedHeightOutsideClusterRealPartCap_iff_global
