import PrimeNumberTheorem.ZeroDensityLayerBudgetPNTHybridActualSelectedHeightLowLayer

namespace PrimeNumberTheorem

#check actualHybridGlobalLowLayerMajorant_mono_height
#check tendsto_dynamicPositiveOutsideClusterPNTLayerNorm_div_targetAmplitude_zero_of_hybrid_selectedHeight
#check actualHybridOutsideClusterLowLayer_selectedHeight_targetAmplitudeNegligible

end PrimeNumberTheorem
