import PrimeNumberTheorem.ZeroDensityLayerBudgetActualSelectedHeightFiniteStripCertificateChoice

namespace PrimeNumberTheorem

#check actualSelectedHeightFiniteStripChosenExponent
#check actualSelectedHeightFiniteStripChosenHeight
#check actualSelectedHeightFiniteStripChosenEpsilon
#check
  actualCarlsonOutsideClusterGoodHeightFiniteStripCertificate_of_thresholds

end PrimeNumberTheorem
