import PrimeNumberTheorem.ZeroDensityLayerBudgetActualSelectedHeightStripProfileFiniteGridExtremalSelection

open PrimeNumberTheorem

#check ActualSelectedHeightFiniteStripGrid.maxSigma
#check ActualSelectedHeightFiniteStripGrid.minTau
#check ActualSelectedHeightFiniteStripGrid.maxSigma_mem
#check ActualSelectedHeightFiniteStripGrid.minTau_mem
#check ActualSelectedHeightFiniteStripGrid.sigmaUpperCovers_of_le_maxSigma
#check ActualSelectedHeightFiniteStripGrid.tauLowerCovers_of_minTau_le
#check unified_actualBalancedHeight_of_extremalFiniteStripGridBounds
