import PrimeNumberTheorem.ZeroDensityLayerBudgetCarlsonFiniteAffineThresholdDecay

namespace PrimeNumberTheorem

#check carlsonFiniteAffineBalancedPowerMajorant_le_optimalPhysicalDecay
#check tendsto_carlsonFiniteAffineBalancedPowerMajorant_zero_of_threshold

end PrimeNumberTheorem
