import PrimeNumberTheorem.ZeroDensityLayerBudgetActualCarlsonBoundaryMassBudgetBarrier

#print axioms PrimeNumberTheorem.actualCarlsonSeedOutside_lt_loss_add_half_gap_of_extensionBudgets
#print axioms PrimeNumberTheorem.not_exists_actualCarlsonFiniteExtension_of_seedOutside_ge_loss_add_half_gap
#print axioms PrimeNumberTheorem.actualCarlsonSeedOutside_lt_loss_add_quarter_net_of_canonicalBudgets
#print axioms PrimeNumberTheorem.not_exists_actualCarlsonFiniteExtension_of_seedOutside_ge_canonicalAllowance
