import PrimeNumberTheorem.ZeroDensityLayerBudgetActualSelectedHeightStripProfileMonotoneRoundingTransfer

open PrimeNumberTheorem

#check actualSelectedHeightStripAlphaCeiling_mono_of_monotoneRounding
#check ActualSelectedHeightFiniteStripProfile.MonotoneRoundingCovers
#check monotoneRoundingCovers_refl
#check monotoneRoundingCovers_trans
#check stripAlphaCeilingCoversWithin_zero_of_monotoneRoundingCovers
#check exists_feasibleActualSelectedHeightFiniteStripProfile_of_monotoneRounding
#check unified_actualBalancedHeight_of_monotoneRoundedStripProfile
