import PrimeNumberTheorem.ZeroDensityLayerBudgetActualCarlsonPointwiseGapExtensionAbsoluteMassContract

open PrimeNumberTheorem

#print axioms truncatedPositiveZeroAbsoluteMass_div_target_le_low_add_CarlsonTail
#print axioms selectedPositiveOutsideClusterPNTAbsoluteMass_naturalPointNegligible_of_CarlsonPointwiseGap
#print axioms selectedFullOutsideClusterPNTAbsoluteMass_naturalPointNegligible_of_CarlsonPointwiseGap
#print axioms selectedMovingRightEdgeExtension_naturalPointNegligible_of_CarlsonPointwiseGap
#print axioms exists_automaticGoodHeight_CarlsonPointwiseGapMovingSeedSignedNaturalTargetTransfer
