import PrimeNumberTheorem.ZeroDensityLayerBudgetActualSelectedHeightWeightedGoodHeightUnifiedTransfer

open PrimeNumberTheorem

#check ActualWeightedBalancedGoodHeightUnifiedTransferCertificate
#check ActualWeightedBalancedGoodHeightUnifiedTransferCertificate.eventual_pnt_upper
#check ActualWeightedBalancedGoodHeightUnifiedTransferCertificate.pnt_relative_decay
#check ActualWeightedBalancedGoodHeightUnifiedTransferCertificate.oscillation_lower
#check ActualWeightedBalancedGoodHeightUnifiedTransferCertificate.selected_height_ratio
#check ActualWeightedBalancedGoodHeightUnifiedTransferCertificate.selected_height_log_growth
#check unified_actualWeightedBalancedGoodHeightSameFormulaTransfer
