import PrimeNumberTheorem.ZeroDensityLayerBudgetActualCubicLowGaussianL2Adapter

#print axioms PrimeNumberTheorem.actualCubicTargetNormalizedCoefficientSquare_nonneg
#print axioms PrimeNumberTheorem.actualCubicTargetNormalizedCoefficientMass_nonneg
#print axioms PrimeNumberTheorem.actualCubicTargetNormalizedCoefficientMass_sq_eq
#print axioms PrimeNumberTheorem.sum_actualCubicTargetNormalizedCoefficientMass_sq_eq_capacity
#print axioms PrimeNumberTheorem.actualCubicDyadicStripGaussianGramExcluding_le_occupancy_mul_capacity
