import PrimeNumberTheorem.ZeroDensityLayerBudgetActualCarlsonBoundarySelectedHeightBound

open PrimeNumberTheorem

#check eventually_actualCarlsonSelectedHeightPositiveZeroNormalizedSum_lt_boundaryMass_add
#check eventually_actualCarlsonSelectedHeightFullZeroNormalizedSum_lt_two_mul_boundaryMass_add
