import PrimeNumberTheorem.ZeroDensityLayerBudgetActualSelectedHeightStripProfileOptimalExponent

open PrimeNumberTheorem

#check ActualSelectedHeightFiniteStripProfile.optimalRobustMargin_eq_half_ceiling_gap
#check ActualSelectedHeightFiniteStripProfile.optimalRobustMargin_le_iff
#check ActualSelectedHeightFiniteStripProfile.optimalRobustMargin_lt_iff
#check ActualSelectedHeightFiniteStripProfile.optimalRobustMargin_le_iff_balancedExponent_le
#check ActualSelectedHeightFiniteStripProfile.optimalRobustMargin_lt_iff_balancedExponent_lt
#check optimalActualSelectedHeightFiniteStripProfile_effectiveAlphaCeiling_ge
#check optimalActualSelectedHeightFiniteStripProfile_balancedExponent_ge
#check optimalActualSelectedHeightFiniteStripProfile_balancedPolynomialScale_ge
