import PrimeNumberTheorem.ZeroDensityLayerBudgetCarlsonFiniteAffineActualCoefficientBridge

namespace PrimeNumberTheorem

#check CarlsonFiniteStripCountCoefficientCertificate
#check nonempty_carlsonPolynomialFiniteStripCountCoefficientCertificate
#check actualCarlsonFiniteAffineStripCoeff
#check actualCarlsonFiniteAffineStripCoeff_nonneg
#check actualCarlsonFiniteStripNormalizedLayerNormSum
#check actualCarlsonFiniteStripEndpointCoefficientLogMajorant
#check actualCarlsonFiniteStripEndpointCoefficientLogMajorant_eq_finiteAffine
#check eventually_actualCarlsonFiniteStripNormalizedLayerNormSum_le_majorant
#check eventually_actualCarlsonFiniteStripNormalizedLayerNormSum_le_finiteAffine

end PrimeNumberTheorem
