import PrimeNumberTheorem.ZeroDensityLayerBudgetThirdOrderActualSynchronizedFormula

#print axioms PrimeNumberTheorem.thirdOrderExplicitFormulaBoundary_of_goodHeight
#print axioms PrimeNumberTheorem.eventually_exists_goodHeight_thirdOrderActualPsiFormula_normalized_error_lt
