import PrimeNumberTheorem.ZeroDensityLayerBudgetActualSelectedHeightFiniteStripExponentFeasibility

namespace PrimeNumberTheorem

#print axioms exists_actualSelectedHeightExponent_finiteStrips_decay_iff
#print axioms actualSelectedHeightFiniteStripExponent_spec

end PrimeNumberTheorem
