import PrimeNumberTheorem.ZeroDensityLayerBudgetActualCarlsonBoundarySelectedHeightBound

open PrimeNumberTheorem

#print axioms eventually_actualCarlsonSelectedHeightPositiveZeroNormalizedSum_lt_boundaryMass_add
#print axioms eventually_actualCarlsonSelectedHeightFullZeroNormalizedSum_lt_two_mul_boundaryMass_add
