import PrimeNumberTheorem.ZeroDensityLayerBudgetActualCarlsonBalancedPNTSignedTransfer

open PrimeNumberTheorem

#print axioms selectedUniformGoodHeightActualCarlsonBalancedPNTSharpSignedTransfer_automatic
