import PrimeNumberTheorem.ZeroDensityLayerBudgetActualPintzCarlsonGoodHeightRateGrid

#print axioms PrimeNumberTheorem.pintzCarlsonHeight_mono_rate
#print axioms PrimeNumberTheorem.actualPintzCarlsonGoodHeightDynamicGrid
#print axioms PrimeNumberTheorem.eventually_actualPintzCarlsonGoodHeightOptimalHeight_interval_good
#print axioms PrimeNumberTheorem.actualPintzCarlsonGoodHeightOptimalHeight_truncatedCertificate
