import PrimeNumberTheorem.ZeroDensityLayerBudgetActualSelectedHeightStripProfileFiniteGridExtremalSelection

open PrimeNumberTheorem

#print axioms ActualSelectedHeightFiniteStripGrid.maxSigma_mem
#print axioms ActualSelectedHeightFiniteStripGrid.minTau_mem
#print axioms ActualSelectedHeightFiniteStripGrid.sigmaUpperCovers_of_le_maxSigma
#print axioms ActualSelectedHeightFiniteStripGrid.tauLowerCovers_of_minTau_le
#print axioms unified_actualBalancedHeight_of_extremalFiniteStripGridBounds
