import PrimeNumberTheorem.ZeroDensityLayerBudgetActualMovingRightEdgeSeedStabilityTransferContract

#print axioms PrimeNumberTheorem.automaticGoodHeight_twoHeight_movingRightEdgeSeedNaturalPointLowerTransfer
#print axioms PrimeNumberTheorem.unified_automaticGoodHeight_twoHeight_movingRightEdgeSeedNaturalTargetTransfer
#print axioms PrimeNumberTheorem.exists_automaticGoodHeight_movingRightEdgeSeedNaturalTargetTransfer
