import PrimeNumberTheorem.ZeroDensityLayerBudgetDyadicSquareMultiplicityCapacity

#print axioms PrimeNumberTheorem.squareMultiplicityCapacity_le_max_mul_linearMultiplicityCapacity
#print axioms PrimeNumberTheorem.squareMultiplicityCapacity_sdiff_le
#print axioms PrimeNumberTheorem.ExplicitFormulaAux.exists_analyticOrderNatAt_riemannZeta_le_log_im_of_nontrivialZero
#print axioms PrimeNumberTheorem.actualCarlsonDyadicZeroStrip_subset_shell
#print axioms PrimeNumberTheorem.actualCarlsonDyadicStripLinearMultiplicityCapacity_nonneg
#print axioms PrimeNumberTheorem.actualCarlsonDyadicStripLinearReciprocalSquareCapacity_nonneg
#print axioms PrimeNumberTheorem.actualCarlsonDyadicStripSquareReciprocalCapacity_nonneg
#print axioms PrimeNumberTheorem.actualCarlsonDyadicStripLinearMultiplicityCapacity_le_count
#print axioms PrimeNumberTheorem.actualCarlsonDyadicStripLinearReciprocalSquareCapacity_le_count_div_sq
#print axioms PrimeNumberTheorem.exists_actualCarlsonDyadicStrip_maxMultiplicity_le_log
#print axioms PrimeNumberTheorem.exists_actualCarlsonDyadicStripSquareReciprocalCapacity_le_count
#print axioms PrimeNumberTheorem.exists_actualCarlsonDyadicStripSquareReciprocalCapacityExcluding_le_count
#print axioms PrimeNumberTheorem.pntCarlsonClassicalDensityExponent_le_one
#print axioms PrimeNumberTheorem.pntCarlsonClassicalDensityExponent_sub_two_le_neg_one
#print axioms PrimeNumberTheorem.pntCarlsonClassicalDensityExponent_sub_two_lt_zero
#print axioms PrimeNumberTheorem.pntCarlsonClassicalDensityExponent_half_eq_one
