import PrimeNumberTheorem.ZeroDensityLayerBudgetActualCarlsonDynamicFullZeroDecay

open PrimeNumberTheorem

#print axioms actualCarlsonDynamicRealOrdinateNormalizedSum_tendsto_zero
#print axioms actualCarlsonDynamicTruncatedFullZeroNormalizedSum_tendsto_zero
