import PrimeNumberTheorem.ZeroDensityLayerBudgetFinitePhaseNaturalSampling

namespace PrimeNumberTheorem

#check finitePhaseSum
#check finitePhaseLipschitzBudget
#check norm_finitePhaseSum_sub_le
#check tendsto_log_natFloor_sub_log
#check tendsto_norm_finitePhaseSum_log_natFloor_sub

end PrimeNumberTheorem
