import PrimeNumberTheorem.ZeroDensityLayerBudgetActualSelectedHeightStripProfileFiniteGridTransfer

open PrimeNumberTheorem

#print axioms ActualSelectedHeightFiniteStripGrid.profile_mem_profiles_iff
#print axioms ActualSelectedHeightFiniteStripGrid.profiles_nonempty
#print axioms ActualSelectedHeightFiniteStripGrid.sigma_half_of_mem_profiles
#print axioms ActualSelectedHeightFiniteStripGrid.sigma_one_of_mem_profiles
#print axioms ActualSelectedHeightFiniteStripGrid.roundedProfile_mem_and_covers
#print axioms unified_actualBalancedHeight_of_finiteMonotoneStripGrid
