import PrimeNumberTheorem.ZeroDensityLayerBudgetActualCarlsonWindowEnergyBidirectionalPNTTransfer

open PrimeNumberTheorem

#print axioms exists_zeroSupportedActualCarlsonFiniteSeedWindowEnergyBidirectionalPNTCanonicalSharpRealTransfer
