import PrimeNumberTheorem.ZeroForcedOscillationHilbertBound

#print axioms PrimeNumberTheorem.ZeroForcedOscillation.abs_finiteExponentialMeanSquare_sub_diagonal_le_localSeparation
#print axioms PrimeNumberTheorem.ZeroForcedOscillation.minimumPositiveFrequencySpacing_le_localFrequencySeparation
#print axioms PrimeNumberTheorem.ZeroForcedOscillation.sum_sqNorm_div_localFrequencySeparation_le_div_minimumSpacing
#print axioms PrimeNumberTheorem.ZeroForcedOscillation.abs_finiteExponentialMeanSquare_sub_diagonal_le_minimumSpacing
#print axioms PrimeNumberTheorem.ZeroForcedOscillation.abs_maximalZeroPackageFiniteExponentialMeanSquare_sub_diagonal_le
#print axioms PrimeNumberTheorem.ZeroForcedOscillation.exists_mem_Ioo_sqNorm_finiteExponentialSum_ge_hilbert
#print axioms PrimeNumberTheorem.ZeroForcedOscillation.exists_mem_Ioo_sqNorm_maximalZeroPackageContribution_pos_of_hilbert
