import PrimeNumberTheorem.ZeroDensityLayerBudgetActualImprovedCapAutomaticTransferContract

open PrimeNumberTheorem

#print axioms exists_improvedCapAutomaticGoodHeight_globalRealPartBoundNaturalTargetTransfer
