import PrimeNumberTheorem.ZeroDensityLayerBudgetVisibleClusterNormalizedCoefficientCap

open PrimeNumberTheorem

#print axioms eventually_abs_dynamicVisibleClusterPNTMain_div_targetAmplitude_le_coefficientMass
#print axioms HasFarWindowEnergyBudgets.visibleClusterNormalized_toEnergySeparation
