import PrimeNumberTheorem.ZeroDensityLayerBudgetActualCubicCarlsonDiagonalTail

#print axioms PrimeNumberTheorem.CarlsonEventualMajorant.eventually_forall_actualCubicDyadicCountMajorant_le
#print axioms PrimeNumberTheorem.CarlsonEventualMajorant.eventually_forall_actualCubicCertificateBlock_le_logFifth
#print axioms PrimeNumberTheorem.CarlsonEventualMajorant.exists_eventually_forall_actualCubicCapacity_le_logFifth
#print axioms PrimeNumberTheorem.actualCubicCarlsonDyadicLogFifthTail_mul_coefficient
#print axioms PrimeNumberTheorem.CarlsonEventualMajorant.exists_eventually_actualCubicCarlsonDiagonalTail_le
#print axioms PrimeNumberTheorem.CarlsonEventualMajorant.eventually_actualCubicCarlsonNormalizedDiagonalTail_le
#print axioms PrimeNumberTheorem.actualCubicCarlsonNormalizedDiagonalTail_nonneg
#print axioms PrimeNumberTheorem.CarlsonEventualMajorant.tendsto_actualCubicCarlsonNormalizedDiagonalTail_zero
#print axioms PrimeNumberTheorem.exists_jointTwoHeightParameters_with_actualCubicCarlsonDiagonalTails
