import PrimeNumberTheorem.ZeroDensityLayerBudgetActualSelectedHeightStripProfileFiniteGridTransfer

open PrimeNumberTheorem

#check ActualSelectedHeightFiniteStripGrid
#check ActualSelectedHeightFiniteStripGrid.profile
#check ActualSelectedHeightFiniteStripGrid.profiles
#check ActualSelectedHeightFiniteStripGrid.profile_mem_profiles_iff
#check ActualSelectedHeightFiniteStripGrid.profiles_nonempty
#check ActualSelectedHeightFiniteStripGrid.sigma_half_of_mem_profiles
#check ActualSelectedHeightFiniteStripGrid.sigma_one_of_mem_profiles
#check ActualSelectedHeightFiniteStripGrid.roundedProfile_mem_and_covers
#check unified_actualBalancedHeight_of_finiteMonotoneStripGrid
