import PrimeNumberTheorem.ZeroDensityLayerBudgetActualCarlsonCanonicalTwoStripPNTTransfer

open PrimeNumberTheorem

#check pntHybridCanonicalTwoStripOutsideCluster_low_re_le
#check pntHybridCanonicalTwoStripOutsideCluster_low_cover
#check
  selectedUniformGoodHeightActualCarlsonCanonicalTwoStripPNTClusterResidual_targetNegligible
