import PrimeNumberTheorem.ZeroDensityLayerBudgetActualGlobalOptimalUnifiedTransferContract

open PrimeNumberTheorem

#print axioms exists_globallyNearOptimalAutomaticGoodHeight_globalRealPartBoundNaturalTargetTransfer
