import PrimeNumberTheorem.ZeroDensityLayerBudgetCarlsonDyadicEventualSummability

#print axioms PrimeNumberTheorem.summable_of_eventually_le_pntCarlsonDyadicLogFourthMajorant
#print axioms PrimeNumberTheorem.pntDyadicReciprocalWeightedCount_nonneg
#print axioms PrimeNumberTheorem.summable_pntDyadicReciprocalWeightedCount_of_eventually_le
