import PrimeNumberTheorem.ZeroDensityLayerBudgetWeightedPowerDominatedConvergence

#print axioms PrimeNumberTheorem.weightedPowerLayers_tendsto_zero_of_summable
#print axioms PrimeNumberTheorem.weightedComplexPowerLayerNorms_tendsto_zero_of_summable
