import PrimeNumberTheorem.ZeroDensityLayerBudgetActualCarlsonBalancedHeightFeasibility

open PrimeNumberTheorem

#print axioms actualCarlsonHeightRobustMargin_pos_iff
#print axioms actualCarlsonHeightWindow_nonempty_iff
#print axioms actualCarlsonBalancedHeightRobustMargin_pos_iff
#print axioms actualCarlsonHeightWindow_empty_of_not_balance
