import PrimeNumberTheorem.ZeroDensityLayerBudgetVariableBoundaryVisibleCarlsonTailContract

#print axioms PrimeNumberTheorem.variableBoundaryVisibleWeightedPowerTerm_tendsto_zero
#print axioms PrimeNumberTheorem.norm_variableBoundaryVisibleWeightedPowerTerm_le
#print axioms PrimeNumberTheorem.variableBoundaryVisibleWeightedPowerTail_tendsto_zero
#print axioms PrimeNumberTheorem.variableBoundaryVisibleNormalizedKernelTail_tendsto_zero
