import PrimeNumberTheorem.ZeroDensityLayerBudgetVariableBoundaryAmplitudeDominationContract

#print axioms PrimeNumberTheorem.NaturalPointTargetAmplitudeNegligible.mono_amplitude
#print axioms PrimeNumberTheorem.targetZeroPowerAmplitude_le_variableBoundaryTargetAmplitude
#print axioms PrimeNumberTheorem.naturalPointTargetAmplitudeNegligible_variableBoundary_of_fixed
