import PrimeNumberTheorem.ZeroDensityLayerBudgetDynamicActualZetaLayerContract

#print axioms PrimeNumberTheorem.dynamicPositivePNTLayerNorm_le_carlson_mul_pintz
#print axioms PrimeNumberTheorem.dynamicCarlsonLayerCount_nonneg
#print axioms PrimeNumberTheorem.dynamicPintzRelativeKernelBudget_pos
#print axioms PrimeNumberTheorem.dynamicPositivePNTLayerNorm_pintzCarlsonTargetLayerBudget
#print axioms PrimeNumberTheorem.dynamicPositivePNTLayerNorm_targetAmplitudeNegligible
