import PrimeNumberTheorem.ZeroDensityLayerBudgetActualPositiveOutsideClusterCapQuantitativeReverseZeroFreeContract

open PrimeNumberTheorem

#print axioms exists_automaticGoodHeight_positiveOutsideRightEdgeCap_eventualUpper_finiteHeightZeroFree
