import PrimeNumberTheorem.ZeroDensityLayerBudgetActualDynamicBoundaryZeroFreeTransfer

#print axioms PrimeNumberTheorem.globalNontrivialZeroRealPartCap_dynamicBoundaryRightEdges
#print axioms PrimeNumberTheorem.globalRightEdgeZeroFree_dynamicBoundaryRightEdges
#print axioms PrimeNumberTheorem.dynamicEqualRealPartZeroPackage_eq_empty_of_globalRightEdgeZeroFree
#print axioms PrimeNumberTheorem.actualDynamicBoundaryCanonicalBetaZeroFreePNTUpperTransfer
#print axioms PrimeNumberTheorem.actualDynamicBoundaryCanonicalBetaZeroFree_relativePNT_tendsto_zero
#print axioms PrimeNumberTheorem.actualDynamicBoundaryCanonicalBetaCappedPNTBidirectionalTransfer
