import PrimeNumberTheorem.ZeroDensityLayerBudgetActualTargetDyadicBlockGram

#print axioms PrimeNumberTheorem.VKEdgePiOverTwo.mem_actualSRelativeDyadicBucketPairs
#print axioms PrimeNumberTheorem.VKEdgePiOverTwo.mem_actualTargetDyadicBucketPairsExcluding
#print axioms PrimeNumberTheorem.VKEdgePiOverTwo.image_snd_actualTargetDyadicBucketPairsExcluding_subset
#print axioms PrimeNumberTheorem.VKEdgePiOverTwo.actualSRelativeDyadicBucketPairs_eq_target_of_re_le
#print axioms PrimeNumberTheorem.VKEdgePiOverTwo.actualTargetDyadicBucket_fibre_card_le_occupancy
#print axioms PrimeNumberTheorem.VKEdgePiOverTwo.sum_actualTargetDyadicBaseMass_sq_le_capacity
#print axioms PrimeNumberTheorem.VKEdgePiOverTwo.actualSRelativeDyadic_fartherRight_or_gram_le_capacity
#print axioms PrimeNumberTheorem.VKEdgePiOverTwo.exists_actualTargetDyadicOccupancy_le_log
#print axioms PrimeNumberTheorem.VKEdgePiOverTwo.exists_actualSRelativeDyadic_fartherRight_or_gram_le_count
