import PrimeNumberTheorem.ZeroDensityLayerBudgetActualZeroPackageSelectedHeightCarlsonTransfer

#print axioms PrimeNumberTheorem.unified_parametricPNTUpper_actualZeroPackageEnergySelectedHeightCarlsonLower
#print axioms PrimeNumberTheorem.unified_parametricPNTUpper_actualZeroPackageSelectedHeightCarlsonLower_of_nonempty
#print axioms PrimeNumberTheorem.unified_parametricPNTUpper_actualZeroPackageSelectedHeightCarlsonLower_of_nontrivialZero
