import PrimeNumberTheorem.ZeroDensityLayerBudgetActualCarlsonBalancedHeightStability

open PrimeNumberTheorem

#print axioms actualCarlsonHeightRobustMargin_eq_balanced_sub_abs
#print axioms actualCarlsonHeightRobustMargin_eq_balanced_iff
#print axioms actualCarlsonHeightRobustMargin_near_optimal_iff
