import PrimeNumberTheorem.ZeroDensityLayerBudgetActualCarlsonBoundaryCapturedMovingSeedSignedPNTTransferContract

open PrimeNumberTheorem

#print axioms exists_automaticGoodHeight_boundaryCapturedMovingSeedSignedNaturalTargetTransfer
