import PrimeNumberTheorem.ZeroDensityLayerBudgetActualSelectedHeightStripProfileFiniteGridDirectionalSelection

open PrimeNumberTheorem

#print axioms ActualSelectedHeightFiniteStripGrid.upperRoundedSigma_mem
#print axioms ActualSelectedHeightFiniteStripGrid.le_upperRoundedSigma
#print axioms ActualSelectedHeightFiniteStripGrid.lowerRoundedTau_mem
#print axioms ActualSelectedHeightFiniteStripGrid.lowerRoundedTau_le
#print axioms ActualSelectedHeightFiniteStripGrid.selectedRoundedProfile_mem_and_covers
#print axioms unified_actualBalancedHeight_of_directionallyCoveringFiniteStripGrid
