import PrimeNumberTheorem.ZeroDensityLayerBudgetActualSelectedHeightFiniteStripCertificateChoice

namespace PrimeNumberTheorem

#print axioms
  actualCarlsonOutsideClusterGoodHeightFiniteStripCertificate_of_thresholds

end PrimeNumberTheorem
