import PrimeNumberTheorem.ZeroDensityLayerBudgetActualSelectedHeightStripProfileApproximateFeasibility

open PrimeNumberTheorem

#check ActualSelectedHeightFiniteStripProfile.optimalRobustMargin_approximation
#check ActualSelectedHeightFiniteStripProfile.optimalRobustMargin_pos_of_approximation
#check ActualSelectedHeightFiniteStripProfile.isFeasible_of_approximation
#check exists_feasibleActualSelectedHeightFiniteStripProfile_of_approximation
#check optimalActualSelectedHeightFiniteStripProfile_feasible_of_approximation
