import PrimeNumberTheorem.ZeroDensityLayerBudgetActualCarlsonZeroSupportedFiniteCapture

#print axioms PrimeNumberTheorem.actualCarlsonBoundaryCaptureFinset_isNontrivialZero
#print axioms PrimeNumberTheorem.exists_zeroSupported_actualCarlsonOutsideClusterBoundaryMass_lt
#print axioms PrimeNumberTheorem.actualCarlsonConjugationClosure_isNontrivialZero
#print axioms PrimeNumberTheorem.exists_conjugationStable_zeroSupported_actualCarlsonOutsideClusterBoundaryMass_lt
#print axioms PrimeNumberTheorem.exists_conjugationStable_zeroSupported_actualCarlsonOutsideClusterBoundaryMass_two_mul_lt_gap
#print axioms PrimeNumberTheorem.actualCarlsonBoundaryClusterPart_isNontrivialZero
#print axioms PrimeNumberTheorem.exists_conjugationStable_zeroSupported_boundarySupported_actualCarlsonOutsideClusterBoundaryMass_two_mul_lt_gap
