import PrimeNumberTheorem.ZeroDensityLayerBudgetActualSelectedHeightWeightedBalancedExponent

open PrimeNumberTheorem

#print axioms actualSelectedHeightStripPhysicalMargin_eq
#print axioms actualSelectedHeightStripBalancedPhysicalMargin_pos
#print axioms actualSelectedHeightStripBalancedPhysicalMargin_lt_beta
#print axioms physicalMargin_le_stripBalancedPhysicalMargin
#print axioms actualSelectedHeightFiniteStripOptimalPhysicalMargin_le_strip
#print axioms le_actualSelectedHeightFiniteStripOptimalPhysicalMargin
#print axioms actualSelectedHeightFiniteStripOptimalPhysicalMargin_pos
#print axioms
  actualSelectedHeightFiniteStripWeightedBalancedExponent_marginCertificate
#print axioms actualSelectedHeightFiniteStripWeightedBalancedExponent_maximizes
#print axioms
  actualSelectedHeightFiniteStripWeightedBalancedExponent_endpointExponent_le
#print axioms actualSelectedHeightFiniteStripWeightedBalancedExponent_spec
