import PrimeNumberTheorem.ZeroDensityLayerBudgetActualCubicCarlsonQuantitativeMovingTail

#print axioms PrimeNumberTheorem.summable_actualCubicCarlsonLogFifthCore
#print axioms PrimeNumberTheorem.actualCubicCarlsonLogFifthConstant_nonneg
#print axioms PrimeNumberTheorem.actualCubicCarlsonDyadicLogFifthTail_le
#print axioms PrimeNumberTheorem.actualCubicCarlsonDyadicRatio_pow_cut_succ_le
#print axioms PrimeNumberTheorem.eventually_actualCubicDyadicPolynomialCut_add_two_le_log
#print axioms PrimeNumberTheorem.tendsto_rpow_mul_log_pow_atTop_nhds_zero
#print axioms PrimeNumberTheorem.eventually_actualCubicCarlsonNormalizedMovingLogFifthTail_le_majorant
#print axioms PrimeNumberTheorem.tendsto_actualCubicCarlsonNormalizedMovingLogFifthMajorant_zero
#print axioms PrimeNumberTheorem.tendsto_actualCubicCarlsonNormalizedMovingLogFifthTail_zero
#print axioms PrimeNumberTheorem.exists_jointTwoHeightParameters_with_quantitative_cubicCarlsonTails
