import PrimeNumberTheorem.ZeroDensityLayerBudgetActualSelectedHeightNaturalRemainderBridge

namespace PrimeNumberTheorem

#check
  TruncatedPNTErrorCertificate.norm_explicitFormulaApproxWithMultiplicity_sub_le
#check
  TruncatedPNTErrorCertificate.abs_actualPNTExplicitFormulaRelativeRemainder_le
#check selectedUniformGoodHeightNaturalRemainderUpperBound
#check eventually_abs_selectedUniformGoodHeight_actualRemainder_le
#check NaturalPointTargetAmplitudeNegligible.of_eventually_abs_le
#check SelectedUniformGoodHeightNaturalRemainderMajorantCertificate
#check SelectedUniformGoodHeightNaturalRemainderMajorantCertificate.actualRemainderCertificate

end PrimeNumberTheorem
