import PrimeNumberTheorem.ZeroDensityLayerBudgetActualSelectedHeightStripProfileBalancedExponentRefinement

open PrimeNumberTheorem

#print axioms ActualSelectedHeightFiniteStripProfile.balancedExponent_le_iff
#print axioms ActualSelectedHeightFiniteStripProfile.balancedExponent_lt_iff
#print axioms ActualSelectedHeightFiniteStripProfile.Refines.balancedExponent_mono
#print axioms ActualSelectedHeightFiniteStripProfile.Refines.balancedExponent_lt
#print axioms ActualSelectedHeightFiniteStripProfile.Refines.balancedPolynomialScale_mono
#print axioms ActualSelectedHeightFiniteStripProfile.Refines.balancedPolynomialScale_lt
