import PrimeNumberTheorem.ZeroDensityLayerBudgetActualSelectedHeightUnifiedTransfer

open Filter

namespace PrimeNumberTheorem

#check ActualSelectedHeightExplicitFormulaRemainderCertificate
#check
  ActualSelectedHeightExplicitFormulaRemainderCertificate.targetAmplitudeNegligible
#check
  unified_parametricPNTUpper_actualSelectedHeightRemainderCertificate

end PrimeNumberTheorem
