import PrimeNumberTheorem.ZeroDensityLayerBudgetThirdOrderExplicitFormulaResidues

#print axioms PrimeNumberTheorem.ExplicitFormulaResidues.exists_analyticOnNhd_div_id_regularization
#print axioms PrimeNumberTheorem.ExplicitFormulaResidues.thirdOrderExplicitFormulaIntegrand_eq_secondOrder_div
#print axioms PrimeNumberTheorem.ExplicitFormulaResidues.exists_explicitFormula_regularization_without_zero
#print axioms PrimeNumberTheorem.ExplicitFormulaResidues.exists_thirdOrderExplicitFormula_analytic_regularized_remainder
#print axioms PrimeNumberTheorem.ExplicitFormulaResidues.exists_boundaryRectIntegral_thirdOrderExplicitFormulaIntegrand_eq_residue_sum
#print axioms PrimeNumberTheorem.ExplicitFormulaResidues.exists_scaledRightIntegral_eq_residue_sum_sub_thirdOrderContourRemainder
