import PrimeNumberTheorem.ZeroDensityLayerBudgetActualSelectedHeightStripProfileApproximateFeasibility

open PrimeNumberTheorem

#print axioms ActualSelectedHeightFiniteStripProfile.optimalRobustMargin_approximation
#print axioms ActualSelectedHeightFiniteStripProfile.optimalRobustMargin_pos_of_approximation
#print axioms ActualSelectedHeightFiniteStripProfile.isFeasible_of_approximation
#print axioms exists_feasibleActualSelectedHeightFiniteStripProfile_of_approximation
#print axioms optimalActualSelectedHeightFiniteStripProfile_feasible_of_approximation
