import PrimeNumberTheorem.ZeroDensityLayerBudgetActualCarlsonWeightedPowerTail

#check PrimeNumberTheorem.ActualCarlsonDyadicZeroIndex
#check PrimeNumberTheorem.actualCarlsonDyadicZeroWeight
#check PrimeNumberTheorem.actualCarlsonDyadicZeroRealPart
#check PrimeNumberTheorem.actualCarlsonDyadicZeroWeight_nonneg
#check PrimeNumberTheorem.tsum_actualCarlsonDyadicZeroWeight_fiber
#check PrimeNumberTheorem.summable_actualCarlsonDyadicZeroWeight
#check PrimeNumberTheorem.actualCarlsonWeightedPowerTail_tendsto_zero
