import PrimeNumberTheorem.ZeroDensityLayerBudgetNaturalSamplingTransfer

#print axioms PrimeNumberTheorem.HasFarTargetAmplitudeWitness.toNatural_natFloor_of_eventually_sampling
#print axioms PrimeNumberTheorem.HasFarTargetAmplitudeWitness.toNatural_natFloor_of_normalized_stability
#print axioms PrimeNumberTheorem.targetZeroPowerAmplitude_natFloor_ratio_tendsto
#print axioms PrimeNumberTheorem.const_mul_targetZeroPowerAmplitude_natFloor_ratio_tendsto
