import PrimeNumberTheorem.ZeroDensityLayerBudgetActualCarlsonConjugateFiniteSeedBarrier

#print axioms PrimeNumberTheorem.finiteSeedExtension_sdiff_conjugationStable
#print axioms PrimeNumberTheorem.actualCarlsonSeedOutside_lt_half_localCoefficient_of_conjugateCanonicalExtension
#print axioms PrimeNumberTheorem.actualCarlsonSeedOutside_lt_half_localCoefficient_of_stableCanonicalExtension
#print axioms PrimeNumberTheorem.not_exists_conjugateActualCarlsonCanonicalFiniteExtension_of_halfCoefficient_le_seedOutside
#print axioms PrimeNumberTheorem.not_exists_loss_and_conjugateActualCarlsonCanonicalFiniteExtension_of_halfCoefficient_le_seedOutside
