import PrimeNumberTheorem.ZeroDensityLayerBudgetActualSelectedHeightWeightedGoodHeightNaturalTransfer

open PrimeNumberTheorem

#print axioms
  actualCarlsonOutsideClusterWeightedBalancedGoodHeightFiniteStripCertificate
#print axioms
  unified_parametricPNTUpper_actualWeightedBalancedGoodHeightNaturalLower
