import PrimeNumberTheorem.ZeroDensityLayerBudgetTwoHeightComplementSplitContract

#print axioms PrimeNumberTheorem.targetAmplitudeNegligible_zero
#print axioms PrimeNumberTheorem.TargetAmplitudeNegligible.add
#print axioms PrimeNumberTheorem.targetAmplitudeNegligible_finset_sum
#print axioms PrimeNumberTheorem.TwoHeightTargetComplementControl.combined_negligible
