import PrimeNumberTheorem.ZeroDensityLayerBudgetActualSelectedHeightStripProfileCertifiedMonotoneTransfer

open PrimeNumberTheorem

#check unified_actualBalancedHeight_of_optimalCertifiedMonotoneStripProfile
