import PrimeNumberTheorem.ZeroDensityLayerBudgetVisibleClusterSeedExtension

#print axioms PrimeNumberTheorem.dynamicVisibleClusterPNTZeroSum_eq_seed_add_extension
#print axioms PrimeNumberTheorem.dynamicVisibleClusterPNTMain_eq_seed_add_extension
#print axioms PrimeNumberTheorem.dynamicVisibleClusterPNTMain_sub_seed_eq_extension
#print axioms PrimeNumberTheorem.hasFarNaturalPointTargetAmplitudeWitness_visibleCluster_of_seed
#print axioms PrimeNumberTheorem.hasFarNaturalPointPositiveTargetAmplitudeWitness_visibleCluster_of_seed
#print axioms PrimeNumberTheorem.hasFarNaturalPointNegativeTargetAmplitudeWitness_visibleCluster_of_seed
