import PrimeNumberTheorem.ZeroDensityLayerBudgetActualZeroPackageAutomaticPNTSignAlternativeContract

#print axioms PrimeNumberTheorem.exists_targetLineSeed_actualCarlsonPNTUnnormalizedSignAlternative_automatic
