import PrimeNumberTheorem.ZeroDensityLayerBudgetActualCarlsonWindowCountBidirectionalPNTTransfer

open scoped Topology

open PrimeNumberTheorem

#check exists_zeroSupportedActualCarlsonFiniteSeedWindowCountBidirectionalPNTCanonicalSharpRealTransfer
#check exists_zeroSupportedActualCarlsonFiniteSeedWindowCountBidirectionalPNTCanonicalSharpSignedRealTransfer
