import PrimeNumberTheorem.ZeroDensityLayerBudgetWindowCountAntiCancellation

#check PrimeNumberTheorem.HasFarWindowCardAdvantage
#check @PrimeNumberTheorem.HasFarWindowCardAdvantage.exists_good_not_bad
#check @PrimeNumberTheorem.HasFarWindowCardAdvantage.unsignedTransfer
#check @PrimeNumberTheorem.HasFarWindowCardAdvantage.positiveTransfer
#check @PrimeNumberTheorem.HasFarWindowCardAdvantage.negativeTransfer
#check @PrimeNumberTheorem.hasFarNaturalPointTargetAmplitudeWitness_visibleCluster_of_seed_windowCount
#check @PrimeNumberTheorem.hasFarNaturalPointPositiveTargetAmplitudeWitness_visibleCluster_of_seed_windowCount
#check @PrimeNumberTheorem.hasFarNaturalPointNegativeTargetAmplitudeWitness_visibleCluster_of_seed_windowCount
