import PrimeNumberTheorem.ZeroDensityLayerBudgetActualGlobalRealPartBoundUnifiedTransferContract

open PrimeNumberTheorem

#print axioms exists_automaticGoodHeight_globalRealPartBoundNaturalTargetTransfer
