import PrimeNumberTheorem.ZeroDensityLayerBudgetActualZeroPackageEnergyPositive

namespace PrimeNumberTheorem

#check actualEqualRealPartZeroPackageEnergy_pos_of_offDiagonal_lt
#check exists_actualEqualRealPartZeroPackageEnergy_pos
#check actualEqualRealPartZeroPackageDiagonalEnergy_pos_of_nonempty
#check exists_actualEqualRealPartZeroPackageEnergy_pos_of_nonempty
#check unified_parametricPNTUpper_actualZeroPackageCarlsonLower_of_diagonalEnergy_pos
#check unified_parametricPNTUpper_actualZeroPackageCarlsonLower_of_nonempty

end PrimeNumberTheorem
