import PrimeNumberTheorem.ZeroDensityLayerBudgetActualClassicalDyadicCarlsonMiddleMassContract

#print axioms PrimeNumberTheorem.eventually_pintzCarlsonHeight_add_one_le_nat_rpow
#print axioms PrimeNumberTheorem.eventually_selectedClassicalAdmissibleGoodHeight_le_selectedUniformGoodHeight
#print axioms PrimeNumberTheorem.actualSelectedHeightSevenEighthsLowMass_mono
#print axioms PrimeNumberTheorem.tendsto_actualSelectedClassicalAdmissibleSevenEighthsLowMass_zero
#print axioms PrimeNumberTheorem.actualSelectedHeightMovingCarlsonMiddleMass_le_low_add_dyadicFixedAnchor
#print axioms PrimeNumberTheorem.tendsto_actualSelectedClassicalAdmissibleMovingMiddleMass_zero_of_dyadic
#print axioms PrimeNumberTheorem.exists_selectedClassicalAdmissibleDyadicCarlsonMiddleMassDecay
