import PrimeNumberTheorem.ZeroDensityLayerBudgetActualSelectedHeightStripProfileOptimalExponent

open PrimeNumberTheorem

#print axioms ActualSelectedHeightFiniteStripProfile.optimalRobustMargin_eq_half_ceiling_gap
#print axioms ActualSelectedHeightFiniteStripProfile.optimalRobustMargin_le_iff
#print axioms ActualSelectedHeightFiniteStripProfile.optimalRobustMargin_lt_iff
#print axioms ActualSelectedHeightFiniteStripProfile.optimalRobustMargin_le_iff_balancedExponent_le
#print axioms ActualSelectedHeightFiniteStripProfile.optimalRobustMargin_lt_iff_balancedExponent_lt
#print axioms optimalActualSelectedHeightFiniteStripProfile_effectiveAlphaCeiling_ge
#print axioms optimalActualSelectedHeightFiniteStripProfile_balancedExponent_ge
#print axioms optimalActualSelectedHeightFiniteStripProfile_balancedPolynomialScale_ge
