import PrimeNumberTheorem.ZeroDensityLayerBudgetActualSelectedHeightStripProfileFeasibleSelection

open PrimeNumberTheorem

#check ActualSelectedHeightFiniteStripProfile.isFeasible_of_optimalRobustMargin_pos
#check optimalActualSelectedHeightFiniteStripProfile_optimalRobustMargin_pos_of_exists_feasible
#check optimalActualSelectedHeightFiniteStripProfile_feasible_of_exists
#check unified_actualBalancedHeight_of_optimalFiniteStripProfile_of_exists_feasible
