import PrimeNumberTheorem.ZeroDensityLayerBudgetActualSelectedHeightBalancedExponentOptimality

namespace PrimeNumberTheorem

#check selectedHeightExponentMidpoint
#check selectedHeightExponentRobustMargin
#check selectedHeightExponentRobustMargin_midpoint
#check selectedHeightExponentRobustMargin_le_half_gap
#check selectedHeightExponentMidpoint_maximizes_robustMargin
#check selectedHeightExponentMidpoint_unique_maximizer
#check actualSelectedHeightFiniteStripEffectiveAlphaCeiling
#check actualSelectedHeightFiniteStripRobustMargin
#check actualSelectedHeightFiniteStripBalancedExponent_robustMargin
#check actualSelectedHeightFiniteStripBalancedExponent_maximizes
#check actualSelectedHeightFiniteStripBalancedExponent_unique_maximizer
#check actualSelectedHeightFiniteStripBalancedExponent_robustMargin_pos

end PrimeNumberTheorem
