import PrimeNumberTheorem.ZeroDensityLayerBudgetPNTUnnormalizedTargetAmplitudeTransfer

#print axioms PrimeNumberTheorem.self_mul_targetZeroPowerAmplitude
#print axioms PrimeNumberTheorem.chebyshevPsi0Error_eq_self_mul_relative
#print axioms PrimeNumberTheorem.HasFarTargetAmplitudeWitness.relativeChebyshevPsi0Error_to_unnormalized
#print axioms PrimeNumberTheorem.HasFarPositiveTargetAmplitudeWitness.relativeChebyshevPsi0Error_to_unnormalized
#print axioms PrimeNumberTheorem.HasFarNegativeTargetAmplitudeWitness.relativeChebyshevPsi0Error_to_unnormalized
#print axioms PrimeNumberTheorem.HasFarSignedTargetAmplitudeWitnesses.relativeChebyshevPsi0Error_to_unnormalized
