import PrimeNumberTheorem.ZeroDensityLayerBudgetActualNearOptimalUnifiedTransferContract

open PrimeNumberTheorem

#print axioms exists_nearOptimalAutomaticGoodHeight_globalRealPartBoundNaturalTargetTransfer
