import PrimeNumberTheorem.ZeroDensityLayerBudgetVariableBoundaryPositiveTailIndexBridgeContract

#print axioms PrimeNumberTheorem.finite_actualHighPositiveZeroKernelSum_le_variableBoundaryVisibleTail
#print axioms PrimeNumberTheorem.variableBoundaryVisiblePositiveTailMajorized_low
