import PrimeNumberTheorem.ZeroDensityLayerBudgetActualCarlsonCanonicalTwoStripPNTTransfer

open PrimeNumberTheorem

#print axioms pntHybridCanonicalTwoStripOutsideCluster_low_re_le
#print axioms pntHybridCanonicalTwoStripOutsideCluster_low_cover
#print axioms selectedUniformGoodHeightActualCarlsonCanonicalTwoStripPNTClusterResidual_targetNegligible
