import PrimeNumberTheorem.ZeroDensityLayerBudgetActualDynamicBoundaryGapBudget

#print axioms PrimeNumberTheorem.targetAmplitudeStripEndpointExponent_boundaryGap
#print axioms PrimeNumberTheorem.targetAmplitudeStripEndpointExponent_boundaryGap_lt_zero_iff
#print axioms PrimeNumberTheorem.carlsonClassical_boundaryGap_decay_iff
#print axioms PrimeNumberTheorem.carlsonClassical_boundaryGap_exceeds_contourFloor
#print axioms PrimeNumberTheorem.dynamicEqualRealPartOutsideGap_pos
#print axioms PrimeNumberTheorem.dynamicEqualRealPartOutsideGap_spec
#print axioms PrimeNumberTheorem.eventually_fixed_dynamicBoundaryGap_of_carlsonDensity
#print axioms PrimeNumberTheorem.not_dynamicBoundaryGap_tendsto_zero_of_carlsonDensity
