import PrimeNumberTheorem.ZeroDensityLayerBudgetThirdOrderZeroResidue

#print axioms PrimeNumberTheorem.ExplicitFormulaResidues.thirdOrderZeroCore_zero
#print axioms PrimeNumberTheorem.ExplicitFormulaResidues.exists_analyticAt_eventuallyEq_thirdOrderExplicitFormulaIntegrand_zeroPrincipalParts
