import PrimeNumberTheorem.ZeroDensityLayerBudgetCarlsonPolynomialHeightCompositionContract

#print axioms PrimeNumberTheorem.carlson_zeroDensity_polynomialHeight_isBigO
#print axioms PrimeNumberTheorem.eventually_carlsonPolynomialHeightCountMajorant_eq_countBudget
#print axioms PrimeNumberTheorem.carlson_zeroDensity_polynomialHeight_countBudget_isBigO
#print axioms PrimeNumberTheorem.tendsto_carlsonPolynomialCountBudget_mul_targetKernelRatio
#print axioms PrimeNumberTheorem.exists_carlsonPolynomialHeight_countBudget_targetNormalized
