import PrimeNumberTheorem.ZeroDensityLayerBudgetActualCarlsonPositiveCoefficientMassUpper

open PrimeNumberTheorem

#check actualCarlsonHighPositiveZeroValueEmbedding
#check finiteVisibleClusterCoefficientMass_map_highPositive_eq
#check finite_actualCarlsonHighPositiveZeroCoefficientMass_le_tsum
#check finiteVisibleClusterCoefficientMass_le_actualCarlsonPositiveZeroWeight_tsum
