import PrimeNumberTheorem.ZeroDensityLayerBudgetCarlsonDynamicGapDominationContract

#print axioms PrimeNumberTheorem.tendsto_carlsonDynamicGapLayeredCoarseLogPowerRatio_zero
#print axioms PrimeNumberTheorem.carlsonMovingBalancedLogPowerRatio_le_coarse_of_gap_le
#print axioms PrimeNumberTheorem.carlsonDynamicFiniteLayerMass_le_layeredCoarseLogPowerRatio
#print axioms PrimeNumberTheorem.tendsto_actualDynamicCarlsonGapFamilyMass_zero_of_minGap
#print axioms PrimeNumberTheorem.tendsto_actualDynamicCarlsonGapStripUnion_mass_zero_of_minGap
