import PrimeNumberTheorem.ZeroDensityLayerBudgetSharpConstantTransfer

#print axioms PrimeNumberTheorem.HasFarNaturalPointTargetAmplitudeWitness.transfer_eventually_sub_lt
#print axioms PrimeNumberTheorem.actualWeightedBalancedGoodHeightPNTSharpConstantTransfer
