import PrimeNumberTheorem.ZeroDensityLayerBudgetActualSelectedHeightStripProfileSearchMonotonicity

open PrimeNumberTheorem

#print axioms optimalActualSelectedHeightFiniteStripProfile_score_mono_of_subset
#print axioms optimalActualSelectedHeightFiniteStripProfile_score_ge_of_refinement
#print axioms optimalActualSelectedHeightFiniteStripProfile_ne_of_strictly_better
#print axioms optimalActualSelectedHeightFiniteStripProfile_ne_coarse_of_strict_refinement
