import PrimeNumberTheorem.ZeroDensityLayerBudgetActualCarlsonWindowCountBidirectionalPNTTransfer

open PrimeNumberTheorem

#print axioms exists_zeroSupportedActualCarlsonFiniteSeedWindowCountBidirectionalPNTCanonicalSharpRealTransfer
#print axioms exists_zeroSupportedActualCarlsonFiniteSeedWindowCountBidirectionalPNTCanonicalSharpSignedRealTransfer
