import PrimeNumberTheorem.ZeroDensityLayerBudgetActualSelectedHeightWeightedGoodHeightNaturalTransfer

open PrimeNumberTheorem

#check actualSelectedHeightFiniteStripWeightedBalancedGoodHeight
#check
  actualCarlsonOutsideClusterWeightedBalancedGoodHeightFiniteStripCertificate
#check
  unified_parametricPNTUpper_actualWeightedBalancedGoodHeightNaturalLower
