import PrimeNumberTheorem.ZeroDensityLayerBudgetCarlsonFiniteAffineActualCoefficientBridge

namespace PrimeNumberTheorem

#print axioms nonempty_carlsonPolynomialFiniteStripCountCoefficientCertificate
#print axioms actualCarlsonFiniteStripEndpointCoefficientLogMajorant_eq_finiteAffine
#print axioms eventually_actualCarlsonFiniteStripNormalizedLayerNormSum_le_majorant
#print axioms eventually_actualCarlsonFiniteStripNormalizedLayerNormSum_le_finiteAffine

end PrimeNumberTheorem
