import PrimeNumberTheorem.ZeroDensityLayerBudgetActualSelectedHeightStripProfileSearchMonotonicity

open PrimeNumberTheorem

#check optimalActualSelectedHeightFiniteStripProfile_score_mono_of_subset
#check optimalActualSelectedHeightFiniteStripProfile_score_ge_of_refinement
#check optimalActualSelectedHeightFiniteStripProfile_ne_of_strictly_better
#check optimalActualSelectedHeightFiniteStripProfile_ne_coarse_of_strict_refinement
