import PrimeNumberTheorem.ZeroDensityLayerBudgetActualCubicTwoHeightL2Tail

#print axioms PrimeNumberTheorem.actualCubicDyadicStripSquareCapacityExcluding_le
#print axioms PrimeNumberTheorem.actualCubicDyadicStripSquareCapacityExcluding_le_reciprocal
#print axioms PrimeNumberTheorem.exists_actualCubicDyadicStripSquareCapacityExcluding_le_count
#print axioms PrimeNumberTheorem.cubicDyadicCountProduct_eq_sixthPower
#print axioms PrimeNumberTheorem.pntCarlsonClassicalDensityExponent_sub_six_le_neg_five
#print axioms PrimeNumberTheorem.pntCarlsonClassicalDensityExponent_half_sub_six_eq_neg_five
#print axioms PrimeNumberTheorem.cubicCarlsonL2BlockExponent_lt_zero
#print axioms PrimeNumberTheorem.exists_actualCubicTwoHeightSquareTailCapacity_le
#print axioms PrimeNumberTheorem.exists_jointTwoHeightTargetAmplitudeParameters_with_cubicL2
