import PrimeNumberTheorem.ZeroDensityLayerBudgetThirdOrderZeroResidueContourIdentity

#print axioms PrimeNumberTheorem.ExplicitFormulaResidues.exists_scaledRightIntegral_eq_explicitZeroPoleResidue_sum_sub_thirdOrderContourRemainder
