import PrimeNumberTheorem.ZeroDensityLayerBudgetActualFullTailConjugationContract

#print axioms PrimeNumberTheorem.dynamicFullPNTZeroTailNorm_le_two_positive_add_real
#print axioms PrimeNumberTheorem.dynamicFullPNTZeroTailNorm_targetAmplitudeNegligible
