import PrimeNumberTheorem.ZeroDensityLayerBudgetActualCarlsonBoundaryTruncatedSplit

open PrimeNumberTheorem

#check pntPowerLayerToTargetRatio_le_one_of_le
#check summable_actualCarlsonOutsideClusterNormalizedKernelTerm_of_le
#check finite_actualHighPositiveZeroKernelSum_le_CarlsonTail_of_le
#check truncatedPositiveZeroKernelSum_div_target_le_low_add_CarlsonTail_of_le
