import PrimeNumberTheorem.ZeroDensityLayerBudgetActualCarlsonBoundaryPNTTransfer

open PrimeNumberTheorem

#print axioms eventually_actualCarlsonSelectedHeightPNTClusterResidual_normalized_lt_boundaryCoefficient_add
#print axioms eventually_abs_actualCarlsonSelectedHeightPNTClusterResidual_lt_boundaryCoefficient_mul_targetAmplitude
