import PrimeNumberTheorem.ZeroDensityLayerBudgetActualCarlsonBoundaryExtensionAbsoluteMassContract

open PrimeNumberTheorem

#print axioms truncatedPositiveZeroAbsoluteMass_div_target_le_low_add_CarlsonTail_of_le
#print axioms eventually_selectedPositiveOutsideClusterPNTAbsoluteMass_div_target_lt_boundaryMass_add
#print axioms eventually_selectedFullOutsideClusterPNTAbsoluteMass_div_target_lt_two_mul_boundaryMass_add
#print axioms eventually_selectedMovingRightEdgeExtension_div_target_lt_two_mul_boundaryMass_add
#print axioms exists_boundaryCapturedCluster_movingRightEdgeExtension_div_target_lt
