import PrimeNumberTheorem.ZeroDensityLayerBudgetActualTargetAmplitudeTwoHeightStrip

#print axioms PrimeNumberTheorem.rpow_stripEndpoint_div_targetZeroPowerAmplitude
#print axioms PrimeNumberTheorem.actualCarlsonTargetTwoHeightLowBudget_eq_shifted
#print axioms PrimeNumberTheorem.actualCarlsonTargetTwoHeightHighBudget_eq_shifted
#print axioms PrimeNumberTheorem.tendsto_actualCarlsonTargetTwoHeightLowBudget
#print axioms PrimeNumberTheorem.tendsto_actualCarlsonTargetTwoHeightHighBudget
#print axioms PrimeNumberTheorem.tendsto_actualPositiveCarlsonStripTargetAmplitudeMass_twoHeight
#print axioms PrimeNumberTheorem.exists_outerHeight_tendsto_actualPositiveCarlsonStripTargetAmplitudeMass
#print axioms PrimeNumberTheorem.exists_positiveWidth_actualCarlsonStripTargetAmplitudeMass_tendsto_zero
