import PrimeNumberTheorem.ZeroDensityLayerBudgetActualCarlsonWindowSecondMomentBidirectionalPNTTransfer

open PrimeNumberTheorem

#print axioms exists_zeroSupportedActualCarlsonFiniteSeedWindowSecondMomentBidirectionalPNTCanonicalSharpRealTransfer
#print axioms exists_zeroSupportedActualCarlsonFiniteSeedWindowSecondMomentBidirectionalPNTCanonicalSharpSignedRealTransfer
