import PrimeNumberTheorem.ZeroDensityLayerBudgetJointTwoHeightOptimalOuterExponentContract

open PrimeNumberTheorem

#print axioms jointTwoHeightOuterExponentFeasible_of_lt_ceiling
#print axioms le_jointTwoHeightOuterExponentCeiling_of_feasible
#print axioms exists_contourCompatible_jointTwoHeightOuterExponent_iff
#print axioms contourFloor_lt_jointTwoHeightOuterExponentCeiling_iff
#print axioms exists_contourCompatible_jointTwoHeightOuterExponent_iff_arithmetic
