import PrimeNumberTheorem.ZeroDensityLayerBudgetActualCubicGaussianSecondMoment

#print axioms PrimeNumberTheorem.norm_actualCubicPhaseFaithfulCoefficient
#print axioms PrimeNumberTheorem.actualCubicDyadicStripGaussianSecondMomentExcluding_le_gram
