import PrimeNumberTheorem.ZeroDensityLayerBudgetPNTHybridAffineSelectedHeight

namespace PrimeNumberTheorem

#check pntHybridAffineDensitySlope_pos
#check pntHybridAffineBalancedExponent_marginCertificate
#check pntHybridAffineOptimalMargin_pos
#check pntHybridAffineBalancedExponent_pos
#check pntHybridAffineSelectedGoodHeight_div_optimalScale_tendsto_one
#check pntHybridAffineSelectedGoodHeight_logGrowth_tendsto_optimalExponent
#check pntHybridAffineSelectedGoodHeight_tendsto_atTop

end PrimeNumberTheorem
