import PrimeNumberTheorem.ZeroDensityLayerBudgetActualClassicalDyadicCarlsonFullPNTTransferContract

#print axioms PrimeNumberTheorem.eventually_pintzCarlsonHeight_add_one_le_real_rpow
#print axioms PrimeNumberTheorem.tendsto_selectedClassicalAdmissibleGoodHeight_atTop
#print axioms PrimeNumberTheorem.eventually_selectedClassicalAdmissibleGoodHeight_le_polynomialHeight_real
#print axioms PrimeNumberTheorem.tendsto_actualSelectedClassicalAdmissibleCriticalHalfPNTLayerNorm_zero
#print axioms PrimeNumberTheorem.tendsto_dynamicRealOrdinatePNTZeroTailNorm_of_height_tendsto
#print axioms PrimeNumberTheorem.tendsto_selectedClassicalAdmissibleRealOrdinatePNTZeroTailNorm_zero
#print axioms PrimeNumberTheorem.actualSelectedHeightMovingCarlsonStripMass_le_dyadicFixedAnchor
#print axioms PrimeNumberTheorem.tendsto_actualSelectedClassicalAdmissibleMovingStripMass_zero_of_dyadic
#print axioms PrimeNumberTheorem.eventually_classicalAdmissibleDyadicCarlsonGapWidth_le
#print axioms PrimeNumberTheorem.eventually_classicalAdmissibleDyadicCarlsonGapWidth_le_sixteenth
#print axioms PrimeNumberTheorem.tendsto_dynamicPositivePNTTailNorm_of_selectedClassicalAdmissibleDyadicCarlson
#print axioms PrimeNumberTheorem.tendsto_dynamicFullPNTZeroTailNorm_of_selectedClassicalAdmissibleDyadicCarlson
#print axioms PrimeNumberTheorem.eventually_abs_selectedClassicalAdmissibleGoodHeight_actualRemainder_le
#print axioms PrimeNumberTheorem.tendsto_selectedClassicalAdmissibleNaturalRemainderUpperBound_zero
#print axioms PrimeNumberTheorem.selectedClassicalAdmissibleGoodHeight_actualNaturalRemainderCertificate
#print axioms PrimeNumberTheorem.exists_selectedClassicalAdmissibleDyadicCarlsonFullPNTTransfer
