import PrimeNumberTheorem.ZeroDensityLayerBudgetActualSelectedHeightWeightedBalancedGoodHeightUniqueness

#print axioms PrimeNumberTheorem.selectedUniformGoodHeight_div_selectedUniformGoodHeight_tendsto_one
#print axioms PrimeNumberTheorem.selectedUniformGoodHeight_optimalMargin_div_actualWeightedBalanced_tendsto_one

