import PrimeNumberTheorem.ZeroDensityLayerBudgetDynamicCarlsonWeightedGoodHeightTransfer

namespace PrimeNumberTheorem

#check eventually_selectedUniformGoodHeight_gt_one_le_self
#check
  actualZetaFiniteStrips_weightedBalancedGoodHeight_dynamicCarlson_layerNormSum_negligible

end PrimeNumberTheorem
