import PrimeNumberTheorem.ZeroDensityLayerBudgetActualMovingRightEdgeUnifiedTransferContract

open PrimeNumberTheorem

#print axioms automaticGoodHeight_twoHeight_movingRightEdgeNaturalPointLowerTransfer
#print axioms unified_automaticGoodHeight_twoHeight_movingRightEdgeNaturalTargetTransfer
#print axioms exists_automaticGoodHeight_movingRightEdgeNaturalTargetTransfer
