import PrimeNumberTheorem.ZeroDensityLayerBudgetActualSelectedHeightWeightedBalancedExponentUniqueness

#check PrimeNumberTheorem.exists_strip_eq_actualSelectedHeightFiniteStripOptimalPhysicalMargin
#check PrimeNumberTheorem.actualSelectedHeightFiniteStripWeightedBalancedExponent_unique
#check PrimeNumberTheorem.actualSelectedHeightFiniteStrip_optimalMarginCertificate_iff

