import PrimeNumberTheorem.ZeroDensityLayerBudgetActualSelectedHeightBalancedExponent

namespace PrimeNumberTheorem

#check actualSelectedHeightStripAlphaCeiling
#check contourTransition_lt_stripAlphaCeiling_iff
#check stripEndpointExponent_neg_iff_lt_alphaCeiling
#check actualSelectedHeightFiniteStripAlphaCeiling
#check contourTransition_lt_finiteStripAlphaCeiling_iff
#check lt_finiteStripAlphaCeiling_iff_all_exponents_neg
#check actualSelectedHeightFiniteStripBalancedExponent
#check actualSelectedHeightFiniteStripBalancedExponent_spec

end PrimeNumberTheorem
