import PrimeNumberTheorem.ZeroDensityLayerBudgetCarlsonActualStripTransferContract

#print axioms PrimeNumberTheorem.tendsto_carlsonStripEndpointNormalizedLogMajorant
#print axioms PrimeNumberTheorem.eventually_carlsonCountBudget_mul_stripEndpoint_div_targetAmplitude
#print axioms PrimeNumberTheorem.tendsto_carlsonCountBudget_mul_stripEndpoint_div_targetAmplitude
#print axioms PrimeNumberTheorem.tendsto_count_mul_kernel_div_amplitude_of_isBigO
#print axioms PrimeNumberTheorem.tendsto_dynamicCarlsonCount_mul_stripEndpoint_div_targetAmplitude
#print axioms PrimeNumberTheorem.actualZetaStrip_carlsonTargetLayerBudget
