import PrimeNumberTheorem.ZeroDensityLayerBudgetActualDynamicBoundaryFullyAutomaticTransfer

open PrimeNumberTheorem

#print axioms actualDynamicBoundaryFullyAutomaticPNTUpperTransfer
#print axioms actualDynamicBoundaryFullyAutomaticPNTBidirectionalTransfer
