import PrimeNumberTheorem.ZeroDensityLayerBudgetActualZeroPackageNaturalWitness

#print axioms PrimeNumberTheorem.tendsto_abs_actualEqualRealPartZeroPackagePNTMain_re_natFloor_error
#print axioms PrimeNumberTheorem.tendsto_abs_actualEqualRealPartZeroPackagePNTMain_re_natFloor_error_scaled
#print axioms PrimeNumberTheorem.tendsto_dynamicVisibleClusterPNTMain_actualZeroPackage_natFloor_error
#print axioms PrimeNumberTheorem.hasFarNaturalPointTargetAmplitudeWitness_actualZeroPackage_visibleCluster

