import PrimeNumberTheorem.ZeroDensityLayerBudgetTargetAmplitudeBarrier

#print axioms PrimeNumberTheorem.pntSubpolynomialContourToPowerRatio_tendsto_atTop
#print axioms PrimeNumberTheorem.not_tendsto_pntSubpolynomialContourToPowerRatio_zero
#print axioms PrimeNumberTheorem.pntContourKernelToTargetAmplitudeRatio_tendsto_atTop
#print axioms PrimeNumberTheorem.not_tendsto_pntContourKernelToTargetAmplitudeRatio_zero
