import PrimeNumberTheorem.ZeroDensityLayerBudgetSignedTargetAmplitudeRealTransfer

#check PrimeNumberTheorem.HasFarPositiveTargetAmplitudeWitness
#check PrimeNumberTheorem.HasFarNegativeTargetAmplitudeWitness
#check PrimeNumberTheorem.HasFarSignedTargetAmplitudeWitnesses
#check PrimeNumberTheorem.HasFarNaturalPointPositiveTargetAmplitudeWitness.toReal
#check PrimeNumberTheorem.HasFarNaturalPointNegativeTargetAmplitudeWitness.toReal
#check PrimeNumberTheorem.hasFarSignedTargetAmplitudeWitnesses_of_naturalPoint
