import PrimeNumberTheorem.ZeroDensityLayerBudgetActualDynamicBoundaryFullyAutomaticTransfer

open PrimeNumberTheorem

#check actualDynamicBoundaryFullyAutomaticPNTUpperTransfer
#check actualDynamicBoundaryFullyAutomaticPNTBidirectionalTransfer
