import PrimeNumberTheorem.ZeroDensityLayerBudgetVariableBoundaryGeometricRightEdgeUnifiedUpperSignedOmega

#print axioms PrimeNumberTheorem.IsVariableBoundaryRightEdge.toIndexedVisible
#print axioms PrimeNumberTheorem.actualMonotoneGeometricVariableBoundaryCanonicalGoodHeightUnifiedUpperSignedOmega
