import PrimeNumberTheorem.ZeroDensityLayerBudgetActualDynamicBoundaryDominatedTail

#check PrimeNumberTheorem.actualCarlsonDynamicBoundaryWeightedPowerTerm
#check PrimeNumberTheorem.actualCarlsonDynamicBoundaryWeightedPowerTerm_nonneg
#check PrimeNumberTheorem.actualCarlsonDynamicBoundaryWeightedPowerTerm_tendsto_zero
#check PrimeNumberTheorem.norm_actualCarlsonDynamicBoundaryWeightedPowerTerm_le
#check PrimeNumberTheorem.actualCarlsonDynamicBoundaryWeightedPowerTail_tendsto_zero
#check PrimeNumberTheorem.actualCarlsonDynamicBoundaryNormalizedKernelTail_tendsto_zero
#check PrimeNumberTheorem.actualCarlsonDynamicBoundaryNormalizedKernelTail_tendsto_zero_of_rightEdge
