import PrimeNumberTheorem.ZeroDensityLayerBudgetVariableBoundaryRealTailDecayContract

#print axioms PrimeNumberTheorem.variableBoundaryRealOrdinateFixedMajorant_tendsto_zero
#print axioms PrimeNumberTheorem.variableBoundaryRealNormalizedSum_le_fixedMajorant
#print axioms PrimeNumberTheorem.variableBoundaryRealNormalizedSum_tendsto_zero_of_fixed_gap
#print axioms PrimeNumberTheorem.actualVariableBoundaryFullTailExplicitFormulaResidual_targetAmplitudeNegligible_of_realGap
