import PrimeNumberTheorem.ZeroDensityLayerBudgetActualCarlsonSelectedHeightPNTTransfer

open PrimeNumberTheorem

#check actualCarlsonSelectedHeightOutsideClusterComplement_targetNegligible
#check actualCarlsonSelectedHeightPNTClusterResidual_targetNegligible
#check selectedUniformGoodHeightActualCarlsonPNTClusterResidual_targetNegligible
