import PrimeNumberTheorem.ZeroDensityLayerBudgetActualSelectedHeightStripProfileApproximation

open PrimeNumberTheorem

#print axioms ActualSelectedHeightFiniteStripProfile.balancedExponent_sub_eq_half_ceiling_sub
#print axioms ActualSelectedHeightFiniteStripProfile.optimalRobustMargin_sub_eq_half_ceiling_sub
#print axioms ActualSelectedHeightFiniteStripProfile.balancedExponent_sub_eq_optimalRobustMargin_sub
#print axioms optimalActualSelectedHeightFiniteStripProfile_balancedExponent_approximation
#print axioms optimalActualSelectedHeightFiniteStripProfile_optimalRobustMargin_approximation
#print axioms optimalActualSelectedHeightFiniteStripProfile_balancedPolynomialScale_approximation
