import PrimeNumberTheorem.ZeroDensityLayerBudgetActualSelectedHeightStripProfileCertifiedOptimization

open PrimeNumberTheorem

#print axioms ActualSelectedHeightFiniteStripProfile.AnalyticTransferCertificate.hasUnifiedTransferResult
#print axioms mem_analyticTransferCertifiedProfiles_iff
#print axioms analyticTransferCertifiedProfiles_nonempty
#print axioms unified_actualBalancedHeight_of_optimalCertifiedFiniteStripProfile
