import PrimeNumberTheorem.ZeroDensityLayerBudgetTargetAmplitudeTwoHeightExponent

#print axioms PrimeNumberTheorem.targetAmplitudeCarlsonTwoHeightLowExponent_balanced
#print axioms PrimeNumberTheorem.targetAmplitudeCarlsonTwoHeightHighExponent_balanced
#print axioms PrimeNumberTheorem.targetAmplitudeCarlsonTwoHeightBalancedExponent_lt_singleHeight
#print axioms PrimeNumberTheorem.exists_targetAmplitudeCarlsonTwoHeightBalancedDecay_iff
#print axioms PrimeNumberTheorem.exists_targetAmplitudeCarlsonTwoHeightStrictMargins
#print axioms PrimeNumberTheorem.targetAmplitudeCarlsonTwoHeightCanonical_feasible
#print axioms PrimeNumberTheorem.exists_targetAmplitudeCarlsonTwoHeightCanonicalStrictMargins
