import PrimeNumberTheorem.ZeroDensityLayerBudgetActualSelectedHeightFiniteStripBottleneck

namespace PrimeNumberTheorem

#check actualSelectedHeightFiniteStripBottleneck
#check carlsonStripEndpointTargetThreshold_le_bottleneck
#check exists_strip_eq_actualSelectedHeightFiniteStripBottleneck
#check actualSelectedHeightFiniteStripBottleneck_lt_iff
#check
  exists_actualSelectedHeightExponent_finiteStrips_decay_iff_bottleneck
#check not_exists_actualSelectedHeightExponent_of_le_bottleneck

end PrimeNumberTheorem
