import PrimeNumberTheorem.ZeroDensityLayerBudgetVariableBoundaryZeroFreeEnvelopeTransfer

#print axioms PrimeNumberTheorem.naturalRunningVisibleZeroBoundary_le_anchor_max_envelope
#print axioms PrimeNumberTheorem.isNaturalVariableBoundaryZeroFreeDecay_of_envelope
#print axioms PrimeNumberTheorem.actualSigmaOnlyZeroFreeEnvelopeUpperDecaySignedOmega
