import PrimeNumberTheorem.ZeroDensityLayerBudgetActualSelectedHeightCarlsonTransfer

#print axioms PrimeNumberTheorem.goodHeightInterval_le_carlsonPolynomialHeight
#print axioms PrimeNumberTheorem.eventually_selectedHeight_le_carlsonPolynomialHeight
#print axioms PrimeNumberTheorem.dynamicCarlsonLayerCount_mono_height
#print axioms PrimeNumberTheorem.tendsto_selectedDynamicCarlsonCount_mul_stripEndpoint_div_targetAmplitude
#print axioms PrimeNumberTheorem.actualZetaOutsideClusterStrip_selectedHeight_carlsonTargetLayerBudget
#print axioms PrimeNumberTheorem.actualZetaOutsideClusterStrip_goodHeight_carlsonTargetLayerBudget
