import PrimeNumberTheorem.ZeroDensityLayerBudgetActualCarlsonBalancedPNTReverseTransfer

open PrimeNumberTheorem

#print axioms selectedUniformGoodHeightActualCarlsonBalancedPNTEventualUpper_forces_emptyCluster_automatic
