import PrimeNumberTheorem.ZeroDensityLayerBudgetActualCarlsonHybridKernelTail

#check PrimeNumberTheorem.actualCarlsonHybridNormalizedKernelMajorant
#check PrimeNumberTheorem.actualCarlsonHybridNormalizedKernelMajorant_tendsto_zero
