import PrimeNumberTheorem.ZeroDensityLayerBudgetActualDynamicBoundaryGoodHeightTransfer

#print axioms PrimeNumberTheorem.actualDynamicBoundaryCanonicalSelectedGoodHeight_spec
#print axioms PrimeNumberTheorem.actualDynamicBoundaryCanonicalGoodHeightPNTUpperTransfer
#print axioms PrimeNumberTheorem.actualDynamicBoundaryCanonicalGoodHeightPNTBidirectionalTransfer
