import PrimeNumberTheorem.ZeroDensityLayerBudgetThirdOrderDynamicPerronTarget

#print axioms PrimeNumberTheorem.thirdOrderPerronErrorMajorant_eq
#print axioms PrimeNumberTheorem.tendsto_thirdOrderNormalizedDynamicPerronPowerMajorant
#print axioms PrimeNumberTheorem.tendsto_thirdOrderNormalizedDynamicPerronPowerMajorant_of_targetRange
#print axioms PrimeNumberTheorem.normalized_thirdOrderPerronErrorMajorant_le_dynamic
