import PrimeNumberTheorem.ZeroDensityLayerBudgetTargetAmplitudeTransfer

#print axioms PrimeNumberTheorem.eventually_abs_lt_mul_of_targetAmplitudeNegligible
#print axioms PrimeNumberTheorem.eventually_abs_realAxis_add_contour_add_complement_lt_half
#print axioms PrimeNumberTheorem.half_targetAmplitude_le_abs_error
#print axioms PrimeNumberTheorem.hasFarTargetAmplitudeWitness_of_three_normalized_remainders
