import PrimeNumberTheorem.ZeroDensityLayerBudgetActualZeroPackageNaturalSampling

open Filter
open scoped Topology

#check PrimeNumberTheorem.finitePhaseCoefficientNormBudget
#check PrimeNumberTheorem.norm_finitePhaseSum_le_coefficientNormBudget
#check PrimeNumberTheorem.tendsto_zero_mul_finitePhaseSum
#check PrimeNumberTheorem.tendsto_norm_targetAmplitude_mul_finitePhaseSum_natFloor_sub_div
#check PrimeNumberTheorem.tendsto_actualEqualRealPartZeroPackagePNTMain_natFloor_error
