import PrimeNumberTheorem.ZeroDensityLayerBudgetActualSelectedHeightStripProfileOptimization

namespace PrimeNumberTheorem

#check ActualSelectedHeightFiniteStripProfile
#check ActualSelectedHeightFiniteStripProfile.bottleneck
#check ActualSelectedHeightFiniteStripProfile.alphaCeiling
#check ActualSelectedHeightFiniteStripProfile.balancedExponent
#check ActualSelectedHeightFiniteStripProfile.optimalRobustMargin
#check ActualSelectedHeightFiniteStripProfile.IsFeasible
#check ActualSelectedHeightFiniteStripProfile.Refines
#check ActualSelectedHeightFiniteStripProfile.Refines.refl
#check ActualSelectedHeightFiniteStripProfile.Refines.trans
#check ActualSelectedHeightFiniteStripProfile.Refines.feasible
#check
  ActualSelectedHeightFiniteStripProfile.Refines.optimalRobustMargin_mono
#check IsOptimalActualSelectedHeightFiniteStripProfile
#check exists_optimalActualSelectedHeightFiniteStripProfile
#check optimalActualSelectedHeightFiniteStripProfile
#check optimalActualSelectedHeightFiniteStripProfile_spec
#check optimalActualSelectedHeightFiniteStripProfile_mem
#check optimalActualSelectedHeightFiniteStripProfile_score_ge
#check optimalActualSelectedHeightFiniteStripProfile_feasible

end PrimeNumberTheorem
