import PrimeNumberTheorem.ZeroDensityLayerBudgetCarlsonFiniteAffineActualSelectedHeightCoefficient

#print axioms PrimeNumberTheorem.nonempty_actualSelectedHeightWeightedBalancedCountCoefficientCertificate
#print axioms PrimeNumberTheorem.eventually_actualSelectedHeightWeightedBalancedNormalizedLayerNormSum_le
#print axioms PrimeNumberTheorem.tendsto_actualSelectedHeightWeightedBalancedNormalizedLayerNormSum_zero
