import PrimeNumberTheorem.ZeroDensityLayerBudgetActualCarlsonBoundaryMassClusterCapture

#print axioms PrimeNumberTheorem.summable_actualCarlsonOutsideClusterBoundaryTerm
#print axioms PrimeNumberTheorem.actualCarlsonOutsideClusterBoundaryMass_antitone
#print axioms PrimeNumberTheorem.actualCarlsonOutsideClusterBoundaryMass_eq_zero_of_boundary_captured
