import PrimeNumberTheorem.ZeroDensityLayerBudgetActualCarlsonBalancedPNTSignedReverseTransfer

open PrimeNumberTheorem

#print axioms selectedUniformGoodHeightActualCarlsonBalancedPNTEventualUpper_forces_emptyCluster_of_positiveWitness_automatic
#print axioms selectedUniformGoodHeightActualCarlsonBalancedPNTEventualLower_forces_emptyCluster_of_negativeWitness_automatic
