import PrimeNumberTheorem.ZeroDensityLayerBudgetActualCarlsonBoundaryPNTTransfer

open PrimeNumberTheorem

#check eventually_actualCarlsonSelectedHeightPNTClusterResidual_normalized_lt_boundaryCoefficient_add
#check eventually_abs_actualCarlsonSelectedHeightPNTClusterResidual_lt_boundaryCoefficient_mul_targetAmplitude
