import PrimeNumberTheorem.ZeroDensityLayerBudgetActualDynamicBoundaryExplicitFormulaTransfer

open PrimeNumberTheorem

#print axioms actualDynamicBoundarySignedComplement_targetAmplitudeNegligible
#print axioms actualDynamicBoundaryExplicitFormulaResidual_targetAmplitudeNegligible
