import PrimeNumberTheorem.ZeroDensityLayerBudgetActualSelectedHeightGoodHeightChoice

namespace PrimeNumberTheorem

#check UniformNaturalPointGoodHeightSelection
#check exists_uniformNaturalPointGoodHeightSelection
#check uniformNaturalPointGoodHeightSelection
#check selectedUniformGoodHeight
#check eventually_selectedUniformGoodHeight_mem
#check eventually_selectedUniformGoodHeight_good
#check selectedUniformGoodHeight_truncatedCertificate
#check exists_selectedUniformGoodHeightSchedule

end PrimeNumberTheorem
