import PrimeNumberTheorem.ZeroDensityLayerBudgetActualSelectedHeightStripProfileCoverageTransfer

open PrimeNumberTheorem

#check ActualSelectedHeightFiniteStripProfile.StripAlphaCeilingCoversWithin
#check stripAlphaCeilingCoversWithin_refl
#check stripAlphaCeilingCoversWithin_mono
#check stripAlphaCeilingCoversWithin_trans
#check alphaCeiling_approximation_of_stripAlphaCeilingCoverage
#check effectiveAlphaCeiling_approximation_of_stripAlphaCeilingCoverage
#check exists_feasibleActualSelectedHeightFiniteStripProfile_of_stripAlphaCeilingCoverage
#check unified_actualBalancedHeight_of_stripAlphaCeilingCoverage
