import PrimeNumberTheorem.ZeroDensityLayerBudgetActualCarlsonWindowEnergyAutomaticCapPNTTransfer

#print axioms
  PrimeNumberTheorem.HasFarWindowEnergyBudgets.visibleClusterNormalized_toActualPNTWitness
#print axioms
  PrimeNumberTheorem.HasFarWindowEnergyBudgets.visibleClusterNormalized_toCanonicalSharpRealPNTWitness
