import PrimeNumberTheorem.ZeroDensityLayerBudgetActualCarlsonCanonicalFiniteSeedBarrier

#check PrimeNumberTheorem.actualCarlsonSeedOutside_lt_localCoefficient_of_canonicalExtension
#check PrimeNumberTheorem.not_exists_actualCarlsonCanonicalFiniteExtension_of_localCoefficient_le_seedOutside
#check PrimeNumberTheorem.not_exists_loss_and_actualCarlsonCanonicalFiniteExtension_of_localCoefficient_le_seedOutside
