import PrimeNumberTheorem.ZeroDensityLayerBudgetActualZeroPackageFiniteHeightBoundaryCaptureContract

#print axioms PrimeNumberTheorem.exists_height_targetLineSeed_subset_equalRealPartZeroPackage
#print axioms PrimeNumberTheorem.exists_actualZeroPackage_boundaryMass_lt
