import PrimeNumberTheorem.ZeroDensityLayerBudgetTargetAmplitudeHeightIncompatibility

#print axioms PrimeNumberTheorem.tendsto_targetAmplitudeContourLogGap_atBot_of_subpolynomial
#print axioms PrimeNumberTheorem.not_isTargetAmplitudeAdmissibleHeight_of_subpolynomial
#print axioms PrimeNumberTheorem.tendsto_targetAmplitudeContourRatio_atTop_of_subpolynomial
#print axioms PrimeNumberTheorem.isPNTSubpolynomialLogHeight_pntSqrtLog
#print axioms PrimeNumberTheorem.not_isTargetAmplitudeAdmissibleHeight_pntSqrtLog
