import PrimeNumberTheorem.ZeroDensityLayerBudgetActualMovingExtensionShrinkingGapContract

open PrimeNumberTheorem

#print axioms shrinkingGapMassRate_of_exponentialMargin
#print axioms shrinkingGapCarlsonTwoHeightRate_of_budget_majorants
#print axioms tendsto_dynamicActualPositiveCarlsonStripTargetAmplitudeMass_of_shrinkingGap
#print axioms selectedFullOutsideClusterPNTAbsoluteMass_targetAmplitudeNegligible_of_shrinkingGap
#print axioms selectedMovingRightEdgeExtension_targetAmplitudeNegligible_of_shrinkingGap
#print axioms exists_shrinkingGap_positiveOutsideClusterMovingSeedSignedNaturalTargetTransfer
