import PrimeNumberTheorem.ZeroDensityLayerBudgetActualSelectedHeightStripProfileCertifiedCostOptimality

open PrimeNumberTheorem

#check ActualSelectedHeightFiniteStripProfile.RobustMarginAntitoneCost
#check ActualSelectedHeightFiniteStripProfile.robustDecayFactor
#check ActualSelectedHeightFiniteStripProfile.robustDecayFactor_le_of_optimalRobustMargin_le
#check ActualSelectedHeightFiniteStripProfile.robustDecayFactor_robustMarginAntitoneCost
#check ActualSelectedHeightFiniteStripProfile.RobustMarginAntitoneCost.const
#check ActualSelectedHeightFiniteStripProfile.RobustMarginAntitoneCost.nonneg_const_mul
#check ActualSelectedHeightFiniteStripProfile.RobustMarginAntitoneCost.add
#check ActualSelectedHeightFiniteStripProfile.weightedRobustDecayEnvelope
#check
  ActualSelectedHeightFiniteStripProfile.weightedRobustDecayEnvelope_robustMarginAntitoneCost
#check ActualSelectedHeightFiniteStripProfile.optimalRobustMargin_minimizes_antitoneCost
#check ActualSelectedHeightFiniteStripProfile.optimalRobustMargin_minimizes_robustDecayFactor
#check
  ActualSelectedHeightFiniteStripProfile.optimalRobustMargin_minimizes_weightedRobustDecayEnvelope
#check
  ActualSelectedHeightFiniteStripProfile.optimalRobustMargin_bounds_costBy_competitorEnvelope
