import PrimeNumberTheorem.ZeroDensityLayerBudgetJointTwoHeightCubicStrictTargetExponentContract

open PrimeNumberTheorem

#print axioms jointTwoHeightCubicStrictTargetExponent_spec
#print axioms tendsto_jointTwoHeightCubicStrictTargetExponent_cubicExcess
