import PrimeNumberTheorem.ZeroDensityLayerBudgetPNTHybridCanonicalAutomaticKernelGuardTransfer

#print axioms PrimeNumberTheorem.exists_positive_normLowerBound_of_isNontrivialZero
#print axioms PrimeNumberTheorem.actualHybridCanonicalAutomaticKernelGuardPNTBidirectionalTransfer
