import PrimeNumberTheorem.ZeroDensityLayerBudgetDynamicCarlsonTwoStageExponentOptimality

namespace PrimeNumberTheorem

#check dynamicCarlsonAutomaticWeightedHeightExponent
#check DynamicCarlsonTwoStageExponentCertificate
#check dynamicCarlsonAutomaticExponentPair_certificate
#check dynamicCarlsonAutomaticExponentPair_unique
#check dynamicCarlsonAutomaticExponentPair_margins_pos

end PrimeNumberTheorem
