import PrimeNumberTheorem.ZeroDensityLayerBudgetActualCarlsonWindowSecondMomentBidirectionalPNTTransfer

open PrimeNumberTheorem

#check exists_zeroSupportedActualCarlsonFiniteSeedWindowSecondMomentBidirectionalPNTCanonicalSharpRealTransfer
#check exists_zeroSupportedActualCarlsonFiniteSeedWindowSecondMomentBidirectionalPNTCanonicalSharpSignedRealTransfer
