import PrimeNumberTheorem.ZeroDensityLayerBudgetWindowCountAntiCancellation

#print axioms PrimeNumberTheorem.HasFarWindowCardAdvantage.exists_good_not_bad
#print axioms PrimeNumberTheorem.HasFarWindowCardAdvantage.unsignedTransfer
#print axioms PrimeNumberTheorem.HasFarWindowCardAdvantage.positiveTransfer
#print axioms PrimeNumberTheorem.HasFarWindowCardAdvantage.negativeTransfer
#print axioms PrimeNumberTheorem.hasFarNaturalPointTargetAmplitudeWitness_visibleCluster_of_seed_windowCount
#print axioms PrimeNumberTheorem.hasFarNaturalPointPositiveTargetAmplitudeWitness_visibleCluster_of_seed_windowCount
#print axioms PrimeNumberTheorem.hasFarNaturalPointNegativeTargetAmplitudeWitness_visibleCluster_of_seed_windowCount
