import PrimeNumberTheorem.ZeroDensityLayerBudgetCarlsonFiniteAffineActualOutsideClusterCoefficient

#print axioms PrimeNumberTheorem.eventually_actualCarlsonFiniteOutsideClusterNormalizedLayerNormSum_le_majorant
#print axioms PrimeNumberTheorem.tendsto_actualSelectedHeightWeightedBalancedOutsideClusterLayerNormSum_zero
#print axioms PrimeNumberTheorem.tendsto_actualSelectedHeightWeightedBalancedPositiveOutsideClusterTail_zero
