import PrimeNumberTheorem.ZeroDensityLayerBudgetActualCarlsonOutsideClusterBoundaryLimit

open PrimeNumberTheorem

#check actualCarlsonOutsideClusterBoundaryMass
#check actualCarlsonOutsideClusterRealPart_le
#check actualCarlsonOutsideClusterNormalizedKernelTail_tendsto_boundaryMass
#check actualCarlsonOutsideClusterBoundaryMass_eq_zero_of_lt
