import PrimeNumberTheorem.ZeroDensityLayerBudgetActualGlobalOptimalQuantitativeReverseZeroFreeContract

open PrimeNumberTheorem

#print axioms exists_globallyNearOptimalAutomaticGoodHeight_globalRealPartBound_eventualUpper_finiteHeightZeroFree
