import PrimeNumberTheorem.ZeroDensityLayerBudgetActualAutomaticJointParameterRealOrdinateClosedTransferContract

open PrimeNumberTheorem

#print axioms exists_automaticGoodHeight_jointParameterRealOrdinateClosedTransfer
