import PrimeNumberTheorem.ZeroDensityLayerBudgetActualSelectedHeightStripProfileCertifiedMonotoneTransfer

open PrimeNumberTheorem

#print axioms unified_actualBalancedHeight_of_optimalCertifiedMonotoneStripProfile
