import PrimeNumberTheorem.ZeroDensityLayerBudgetActualSelectedHeightStripRefinement

namespace PrimeNumberTheorem

#check carlsonStripEndpointTargetThreshold_mono_tau
#check carlsonStripEndpointTargetThreshold_strictMono_tau
#check actualSelectedHeightStripAlphaCeiling_antitone_tau
#check exists_strip_eq_actualSelectedHeightFiniteStripAlphaCeiling
#check actualSelectedHeightFiniteStripBottleneck_mono_of_tau_le
#check actualSelectedHeightFiniteStripAlphaCeiling_mono_of_tau_le
#check
  actualSelectedHeightFiniteStripEffectiveAlphaCeiling_mono_of_tau_le
#check
  actualSelectedHeightFiniteStripBalancedRobustMargin_mono_of_tau_le

end PrimeNumberTheorem
