import PrimeNumberTheorem.ZeroDensityLayerBudgetActualTargetAmplitudeLowLayerTwoHeightContract

open PrimeNumberTheorem

#print axioms positiveOutsideClusterLayer_eq_low_union_high
#print axioms positiveOutsideClusterLayerLowOrdinate_multiplicityMass_le
#print axioms dynamicOutsideClusterLayerMass_eq_low_add_high
#print axioms exists_globalCoefficient_dynamicOutsideClusterTwoHeightMass_le
#print axioms tendsto_dynamicOutsideClusterTwoHeightMass_div_target
#print axioms exists_lowLayerTwoHeight_strictMargins
#print axioms exists_lowLayerTwoHeight_parameters_of_twoThirds
