import PrimeNumberTheorem.ZeroDensityLayerBudgetThirdOrderZeroPoleRectangle

#print axioms PrimeNumberTheorem.ExplicitFormulaResidues.exists_boundaryRectIntegral_thirdOrderExplicitFormulaIntegrand_eq_residue_sum_zeroPole
