import PrimeNumberTheorem.ZeroDensityLayerBudgetJointTwoHeightOptimalPrescribedCapOuterExponentContract

open PrimeNumberTheorem

#print axioms jointTwoHeightPrescribedCapOuterExponentFeasible_of_lt_ceiling
#print axioms le_jointTwoHeightPrescribedCapOuterExponentCeiling_of_feasible
#print axioms exists_contourCompatible_jointTwoHeightPrescribedCapOuterExponent_iff
#print axioms contourFloor_lt_jointTwoHeightPrescribedCapOuterExponentCeiling_iff
#print axioms exists_contourCompatible_jointTwoHeightPrescribedCapOuterExponent_iff_arithmetic
