import PrimeNumberTheorem.ZeroDensityLayerBudgetCarlsonBoundarySlopeFloor

#check PrimeNumberTheorem.carlsonClassicalDensitySlope_le_of_le_on_rightHalf
#check PrimeNumberTheorem.carlsonClassical_boundaryGap_exceeds_fixedBetaFloor
#check PrimeNumberTheorem.eventually_fixedBetaGapFloor_of_movingCarlsonBoundaryDecay
#check PrimeNumberTheorem.not_gap_tendsto_zero_of_movingCarlsonBoundaryDecay
#check PrimeNumberTheorem.not_dynamicBoundaryGap_tendsto_zero_of_movingCarlsonStrips
