import PrimeNumberTheorem.ZeroDensityLayerBudgetNaturalSamplingTransfer

namespace PrimeNumberTheorem

#check HasFarTargetAmplitudeWitness.toNatural_natFloor_of_eventually_sampling
#check HasFarTargetAmplitudeWitness.toNatural_natFloor_of_normalized_stability

end PrimeNumberTheorem
