import PrimeNumberTheorem.ZeroDensityLayerBudgetActualZeroPackageNaturalPNTLowerTransfer

open Filter
open scoped Topology

#check PrimeNumberTheorem.NaturalPointTargetAmplitudeNegligible.const_mul_amplitude
#check PrimeNumberTheorem.actualZeroPackage_naturalPointRemainder_lowerTransfer

