import PrimeNumberTheorem.ZeroDensityLayerBudgetTargetAmplitudeHeightCriterion

#print axioms PrimeNumberTheorem.tendsto_pntTargetAmplitudeContourRatio_zero
#print axioms PrimeNumberTheorem.isTargetAmplitudeAdmissibleHeight_pntPolynomial
#print axioms PrimeNumberTheorem.pntPolynomialContourRatio_critical
#print axioms PrimeNumberTheorem.tendsto_pntPolynomialContourRatio_atTop_of_lt_critical
#print axioms PrimeNumberTheorem.tendsto_pntPolynomialContourRatio_zero_iff
