import PrimeNumberTheorem.ZeroDensityLayerBudgetActualCubicSmoothedHighToLowTransfer

#print axioms PrimeNumberTheorem.actualCubicDyadicStripSquareCapacityExcluding_nonneg
#print axioms PrimeNumberTheorem.actualCubicSmoothedStripEnergyUpTo_nonneg
#print axioms PrimeNumberTheorem.actualCubicSmoothedStripEnergyBetween_nonneg
#print axioms PrimeNumberTheorem.actualCubicNormalizedSmoothedStripEnergyBetween_nonneg
#print axioms PrimeNumberTheorem.actualCubicSmoothedStripEnergyUpTo_eq_add_between
#print axioms PrimeNumberTheorem.actualCubicNormalizedSmoothedStripEnergyUpTo_eq_add_between
#print axioms PrimeNumberTheorem.CarlsonEventualMajorant.actualCubicSmoothedStripEnergyBetween_le_diagonalTail
#print axioms PrimeNumberTheorem.CarlsonEventualMajorant.actualCubicNormalizedSmoothedStripEnergyBetween_le_diagonalTail
#print axioms PrimeNumberTheorem.CarlsonEventualMajorant.tendsto_actualCubicNormalizedSmoothedStripEnergyBetween_zero_of_tail
#print axioms PrimeNumberTheorem.CarlsonEventualMajorant.actualCubicSmoothedHighToLowTransfer_of_tail
#print axioms PrimeNumberTheorem.exists_jointTwoHeightParameters_with_actualCubicSmoothedHighToLowTransfers
