import PrimeNumberTheorem.ZeroDensityLayerBudgetActualThetaOnlyUnifiedTransferContract

open PrimeNumberTheorem

#print axioms exists_thetaOnlyAutomaticGoodHeight_globalRealPartBoundNaturalTargetTransfer
