import PrimeNumberTheorem.ZeroDensityLayerBudgetActualSelectedHeightStripProfileOptimalTransfer

open PrimeNumberTheorem

#print axioms ActualSelectedHeightFiniteStripProfile.HasUnifiedTransferResult
#print axioms unified_actualBalancedHeight_of_optimalFiniteStripProfile
