import PrimeNumberTheorem.ZeroDensityLayerBudgetCarlsonTargetRegionContract

#print axioms PrimeNumberTheorem.sigma_lt_carlsonClassicalTargetThreshold
#print axioms PrimeNumberTheorem.carlsonClassicalTargetThreshold_lt_one
#print axioms PrimeNumberTheorem.exists_carlsonPolynomialHeight_targetAmplitude_decay_iff
#print axioms PrimeNumberTheorem.exists_carlsonPolynomialHeight_targetAmplitude_strictMargin
#print axioms PrimeNumberTheorem.carlson_zeroDensity_with_targetAmplitude_height
