import PrimeNumberTheorem.ZeroDensityLayerBudgetActualDyadicCarlsonMinimalLayerHeights

open PrimeNumberTheorem

#print axioms carlsonPointwiseHeightConditions_of_threeFourths
#print axioms isCarlsonMovingQuadraticLogPowerGap_of_dyadic
#print axioms tendsto_dyadicCarlsonBalancedHeightFloor_atTop
#print axioms actualDynamicDyadicCarlsonMinimalHeightConditions
#print axioms exists_constants_tendsto_actualDyadicCarlsonMinimalFixedAnchorMass_zero_automatic
