import PrimeNumberTheorem.ZeroDensityLayerBudgetActualSelectedHeightStripProfileApproximation

open PrimeNumberTheorem

#check ActualSelectedHeightFiniteStripProfile.balancedExponent_sub_eq_half_ceiling_sub
#check ActualSelectedHeightFiniteStripProfile.optimalRobustMargin_sub_eq_half_ceiling_sub
#check ActualSelectedHeightFiniteStripProfile.balancedExponent_sub_eq_optimalRobustMargin_sub
#check optimalActualSelectedHeightFiniteStripProfile_balancedExponent_approximation
#check optimalActualSelectedHeightFiniteStripProfile_optimalRobustMargin_approximation
#check optimalActualSelectedHeightFiniteStripProfile_balancedPolynomialScale_approximation
