import PrimeNumberTheorem.ZeroDensityLayerBudgetWindowEnergySeparationScaled

open PrimeNumberTheorem

#check HasFarWindowCardAdvantage.scaleBoth
#check HasFarWindowEnergySeparation.toScaledWindowCardAdvantage
