import PrimeNumberTheorem.ZeroDensityLayerBudgetVariableBoundaryVisibleResidualAssemblyContract

#print axioms PrimeNumberTheorem.variableBoundaryVisibleComplement_targetAmplitudeNegligible
#print axioms PrimeNumberTheorem.actualVariableBoundaryExplicitFormulaResidual_targetAmplitudeNegligible
