import PrimeNumberTheorem.VKEdgeDesmoothedLeftNegativeAmplitude

#print axioms PrimeNumberTheorem.ExplicitFormulaResidues.norm_intervalIntegral_desmoothedCubicLeftContourIntegrand_neg_le
#print axioms PrimeNumberTheorem.ExplicitFormulaResidues.norm_add_intervalIntegral_desmoothedCubicLeftContourIntegrand_le
#print axioms PrimeNumberTheorem.ExplicitFormulaResidues.exists_dynamicCubicLeftBoundary_negative_interval_oscillatory_bound
