import PrimeNumberTheorem.VKEdgeDesmoothedLeftAmplitude

#print axioms PrimeNumberTheorem.ExplicitFormulaResidues.norm_deriv_cubicKernelMultiplier_le_eight_div_norm
#print axioms PrimeNumberTheorem.ExplicitFormulaResidues.desmoothedCubicLeftContourIntegrand_eq_rpow_mul_amplitude_mul_cexp
#print axioms PrimeNumberTheorem.ExplicitFormulaResidues.norm_desmoothedLeftOscillatoryAmplitude_le
#print axioms PrimeNumberTheorem.ExplicitFormulaResidues.differentiableAt_desmoothedLeftOscillatoryAmplitude
#print axioms PrimeNumberTheorem.ExplicitFormulaResidues.norm_deriv_desmoothedLeftOscillatoryAmplitude_le
#print axioms PrimeNumberTheorem.ExplicitFormulaResidues.norm_intervalIntegral_desmoothedLeftOscillatoryAmplitude_mul_cexp_le
#print axioms PrimeNumberTheorem.ExplicitFormulaResidues.norm_intervalIntegral_desmoothedCubicLeftContourIntegrand_le
#print axioms PrimeNumberTheorem.ExplicitFormulaResidues.exists_dynamicCubicLeftBoundary_logDeriv_and_deriv_le
#print axioms PrimeNumberTheorem.ExplicitFormulaResidues.exists_dynamicCubicLeftBoundary_positive_interval_oscillatory_bound
