import PrimeNumberTheorem.ZeroDensityLayerBudgetNormalizedCofinalLowerWitnessObstruction

#print axioms PrimeNumberTheorem.not_isNormalizedCofinalPNTLowerWitness_of_eventually_upper
#print axioms PrimeNumberTheorem.exists_automaticBestPNTMajorant_with_normalizedLowerWitnessObstruction
