import PrimeNumberTheorem.ZeroDensityLayerBudgetPNTLowDensityDecay

#check PrimeNumberTheorem.eventually_one_add_log_height_add_six_le_four_mul_log_pow_four
#check PrimeNumberTheorem.exists_pintzConstant_globalLowDensityGrowthMajorant_tendsto
#check PrimeNumberTheorem.exists_pintzConstant_adaptiveGlobalLowDensityGrowthMajorant_tendsto
