import PrimeNumberTheorem.ZeroDensityLayerBudgetThirdOrderPerronKernel

#print axioms PrimeNumberTheorem.ExplicitFormulaResidues.thirdOrderExplicitFormulaIntegrand_eq_explicitFormulaIntegrand_div_sq
#print axioms PrimeNumberTheorem.ExplicitFormulaResidues.thirdOrderExplicitFormulaIntegrand_eq_neg_logDeriv_kernel
#print axioms PrimeNumberTheorem.ExplicitFormulaResidues.simplePoleTerm_div_sq_eq
#print axioms PrimeNumberTheorem.ExplicitFormulaResidues.integral_Ioi_rpow_neg_three
#print axioms PrimeNumberTheorem.ExplicitFormulaResidues.integral_Ioi_rpow_neg_three_eq_inv_sq
