import PrimeNumberTheorem.ZeroDensityLayerBudgetActualZeroPackageAutomaticEnergyBoundaryBudget

#check PrimeNumberTheorem.actualEqualRealPartZeroPackageDiagonalEnergy_mono_of_subset
#check PrimeNumberTheorem.exists_actualZeroPackage_energy_boundaryBudget
