import PrimeNumberTheorem.ZeroDensityLayerBudgetAttainedGlobalRightEdgeRealClosedReciprocalOmega

#print axioms PrimeNumberTheorem.actualZeroPackage_reciprocalPNTSignAlternative_of_packageRealGap
#print axioms PrimeNumberTheorem.exists_targetLineSeed_actualReciprocalPNTUnnormalizedOmegaAlternative_of_packageRealGap_automatic
#print axioms PrimeNumberTheorem.attainedGlobalRightEdgeRealClosed_actualReciprocalPNTUnnormalizedOmegaAlternative
