import PrimeNumberTheorem.ZeroDensityLayerBudgetCubicKernelSecondDifference

#check PrimeNumberTheorem.secondLogForwardDifference
#check PrimeNumberTheorem.cubicKernelSecondDifferenceFactor
#check PrimeNumberTheorem.secondLogForwardDifference_exp_div_cube
#check PrimeNumberTheorem.secondLogForwardDifference_exp_div_cube_normalized
#check PrimeNumberTheorem.secondLogForwardDifference_const_mul_exp_div_cube_normalized
