import PrimeNumberTheorem.ZeroDensityLayerBudgetActualSelectedUniformGoodHeightPNT

#print axioms PrimeNumberTheorem.eventually_selectedUniformGoodHeight_le_polynomialHeight
#print axioms PrimeNumberTheorem.tendsto_actualSelectedUniformGoodHeightMovingCarlsonStripMass_zero
#print axioms PrimeNumberTheorem.tendsto_actualSelectedUniformGoodHeightCriticalHalfPNTLayerNorm_zero
#print axioms PrimeNumberTheorem.tendsto_dynamicPositivePNTTailNorm_of_selectedUniformGoodHeightMovingCarlson
#print axioms PrimeNumberTheorem.tendsto_dynamicRealOrdinatePNTZeroTailNorm_of_selectedUniformGoodHeight
#print axioms PrimeNumberTheorem.eventually_actualSelectedHeightMovingPositiveRightEdgeCap_of_globalCap
#print axioms PrimeNumberTheorem.tendsto_dynamicFullPNTZeroTailNorm_of_selectedUniformGoodHeightMovingCarlson
#print axioms PrimeNumberTheorem.tendsto_relativeChebyshevPsi0Error_of_selectedUniformGoodHeight_fullTail
#print axioms PrimeNumberTheorem.tendsto_relativeChebyshevPsi0Error_of_selectedUniformGoodHeightMovingCarlson
#print axioms PrimeNumberTheorem.tendsto_relativeChebyshevPsi0Error_of_selectedUniformGoodHeightMovingCarlson_globalCap
