import PrimeNumberTheorem.ZeroDensityLayerBudgetHeightNormalizedContourObstruction

#print axioms PrimeNumberTheorem.heightNormalizedContourMainRatio_eq
#print axioms PrimeNumberTheorem.tendsto_heightNormalizedContourMainRatio_atTop
#print axioms PrimeNumberTheorem.tendsto_selectedPolynomialHeightNormalizedContourRatio_atTop
#print axioms PrimeNumberTheorem.not_tendsto_selectedPolynomialHeightNormalizedContourRatio_zero
