import PrimeNumberTheorem.ZeroDensityLayerBudgetThirdOrderPerronKernel

open MeasureTheory Set

#check PrimeNumberTheorem.ExplicitFormulaResidues.thirdOrderExplicitFormulaIntegrand
#check PrimeNumberTheorem.ExplicitFormulaResidues.thirdOrderExplicitFormulaIntegrand_eq_explicitFormulaIntegrand_div_sq
#check PrimeNumberTheorem.ExplicitFormulaResidues.thirdOrderExplicitFormulaIntegrand_eq_neg_logDeriv_kernel
#check PrimeNumberTheorem.ExplicitFormulaResidues.simplePoleTerm_div_sq_eq
#check PrimeNumberTheorem.ExplicitFormulaResidues.integral_Ioi_rpow_neg_three
#check PrimeNumberTheorem.ExplicitFormulaResidues.integral_Ioi_rpow_neg_three_eq_inv_sq
