import PrimeNumberTheorem.ZeroDensityLayerBudgetVariableBoundaryAmplitudeDomination

#check PrimeNumberTheorem.NaturalPointTargetAmplitudeNegligible.mono_amplitude
#check PrimeNumberTheorem.targetZeroPowerAmplitude_le_variableBoundaryTargetAmplitude
#check PrimeNumberTheorem.naturalPointTargetAmplitudeNegligible_variableBoundary_of_fixed
