import PrimeNumberTheorem.ZeroDensityLayerBudgetActualImprovedCapAutomaticTransfer

namespace PrimeNumberTheorem

#check exists_improvedCapAutomaticGoodHeight_globalRealPartBoundNaturalTargetTransfer

end PrimeNumberTheorem
