import PrimeNumberTheorem.ZeroDensityLayerBudgetClassicalAdmissibleGoodHeight

#print axioms PrimeNumberTheorem.eventually_selectedClassicalAdmissibleGoodHeight_good
#print axioms PrimeNumberTheorem.selectedClassicalAdmissibleGoodHeight_truncatedCertificate
#print axioms PrimeNumberTheorem.selectedClassicalAdmissibleGoodHeight_contourRelative_tendsto
