import PrimeNumberTheorem.ZeroDensityLayerBudgetCubicKernelLocalFactorLowerBound

#print axioms PrimeNumberTheorem.tendsto_cubicKernelSecondDifferenceFactor_one
#print axioms PrimeNumberTheorem.eventually_norm_cubicKernelSecondDifferenceFactor_gt_half
#print axioms PrimeNumberTheorem.eventually_secondLogForwardDifference_exp_div_cube_norm_gt_half
