import PrimeNumberTheorem.ZeroDensityLayerBudgetCubicResidueSecondDifferenceKernel

#check PrimeNumberTheorem.ExplicitFormulaResidues.cubicPoleOneSecondDifference
#check PrimeNumberTheorem.ExplicitFormulaResidues.cubicZeroResidueSecondDifference
#check PrimeNumberTheorem.ExplicitFormulaResidues.cubicContourSecondDifference
#check PrimeNumberTheorem.ExplicitFormulaResidues.one_mem_cubicPoleFinset_of_complete
#check PrimeNumberTheorem.ExplicitFormulaResidues.cubicResidueSum_secondDifference_eq
#check PrimeNumberTheorem.ExplicitFormulaResidues.cubicExplicitFormulaApproximant_secondDifference_eq
#check PrimeNumberTheorem.ExplicitFormulaResidues.cubicExplicitFormulaApproximant_realSecondDifference_eq
#check PrimeNumberTheorem.ExplicitFormulaResidues.exists_cubicZeroKernelSum_chebyshevPsi_bounds
