import PrimeNumberTheorem.ZeroDensityLayerBudgetCubicResidueSecondDifferenceKernel

#print axioms PrimeNumberTheorem.ExplicitFormulaResidues.cubicResidueSum_secondDifference_eq
#print axioms PrimeNumberTheorem.ExplicitFormulaResidues.cubicExplicitFormulaApproximant_secondDifference_eq
#print axioms PrimeNumberTheorem.ExplicitFormulaResidues.exists_cubicZeroKernelSum_chebyshevPsi_bounds
