import PrimeNumberTheorem.ZeroDensityLayerBudgetQuadraticKernelMovingPNTTransfer

#check PrimeNumberTheorem.reciprocalPolynomialHeightTargetAmplitude
#check PrimeNumberTheorem.reciprocalPolynomialHeightVariableTargetAmplitude
#check PrimeNumberTheorem.quadraticKernelNaturalRemainderMajorant
#check PrimeNumberTheorem.quadraticKernelNaturalRemainderMajorant_reciprocalHeightNegligible
#check PrimeNumberTheorem.eventually_reciprocalPolynomialHeightVariableTargetAmplitude_pos
#check PrimeNumberTheorem.reciprocalPolynomialHeightTargetAmplitude_le_variable
#check PrimeNumberTheorem.naturalPointReciprocalHeightNegligible_variableBoundary_of_quadraticMajorant
#check PrimeNumberTheorem.QuadraticKernelMovingPNTCertificate
#check PrimeNumberTheorem.QuadraticKernelMovingPNTCertificate.residual_negligible
#check PrimeNumberTheorem.QuadraticKernelMovingPNTCertificate.relativeSignAlternative
