import PrimeNumberTheorem.ZeroDensityLayerBudgetActualZeroPackageAutomaticReciprocalOmega

/-!
# Reciprocal Omega from an attained global right edge

An explicit certificate that one nontrivial zeta zero attains the global
maximum real part automatically supplies the finite target-line seed and the
outside real-part cap required by the reciprocal Omega alternative.
-/

namespace PrimeNumberTheorem

open scoped Topology
open Complex ZeroForcedOscillation

noncomputable section

/-- `rho` is a nontrivial zeta zero whose real part is a global maximum among
all nontrivial zeta zeros.  Attainment is explicit and is not inferred from a
supremum. -/
def IsAttainedGlobalNontrivialZeroRealPart (rho : ℂ) : Prop :=
  RiemannHypothesis.IsNontrivialZero rho ∧
    ∀ z : ℂ, RiemannHypothesis.IsNontrivialZero z → z.re ≤ rho.re

/-- The conjugate pair generated by an attained right-edge zero is a nonempty
target-line seed and automatically supplies the global outside cap. -/
theorem attainedGlobalNontrivialZeroRealPart_conjugatePair_spec
    {rho : ℂ} (hattained : IsAttainedGlobalNontrivialZeroRealPart rho) :
    IsTargetRealPartNontrivialZeroSeed rho.re
        {rho, (starRingEnd ℂ) rho} ∧
      ({rho, (starRingEnd ℂ) rho} : Finset ℂ).Nonempty ∧
      OutsideClusterRealPartCap {rho, (starRingEnd ℂ) rho} rho.re := by
  have hconjZero :
      RiemannHypothesis.IsNontrivialZero ((starRingEnd ℂ) rho) :=
    RiemannVonMangoldt.isNontrivialZero_conj hattained.1
  have hseed : IsTargetRealPartNontrivialZeroSeed rho.re
      {rho, (starRingEnd ℂ) rho} := by
    intro z hz
    simp only [Finset.mem_insert, Finset.mem_singleton] at hz
    rcases hz with rfl | rfl
    · exact ⟨hattained.1, rfl⟩
    · exact ⟨hconjZero, by simp⟩
  have hnonempty : ({rho, (starRingEnd ℂ) rho} : Finset ℂ).Nonempty := by
    exact ⟨rho, by simp⟩
  have hcap : OutsideClusterRealPartCap
      {rho, (starRingEnd ℂ) rho} rho.re := by
    intro z hz _
    exact hattained.2 z hz
  exact ⟨hseed, hnonempty, hcap⟩

/-- An attained global right-edge nontrivial zero forces either an
`Omega_+` or an `Omega_-` witness for the actual Chebyshev error at its exact
`x^(rho.re)` scale, under explicit real-ordinate strictness. -/
theorem attainedGlobalRightEdge_actualReciprocalPNTUnnormalizedOmegaAlternative
    {rho : ℂ} {sigma q heightDelta : ℝ}
    (selection : UniformNaturalPointGoodHeightSelection)
    (hattained : IsAttainedGlobalNontrivialZeroRealPart rho)
    (hhalf : 1 / 2 < sigma) (hone : sigma < 1)
    (hsigmaBeta : sigma < rho.re) (hbetaOne : rho.re < 1)
    (hheightDelta : 0 < heightDelta) (hheightDeltaBeta : heightDelta < rho.re)
    (hrealStrict : ∀ z : ℂ,
      RiemannHypothesis.IsNontrivialZero z →
        z.im = 0 → z.re < rho.re)
    (hq : 0 < q) (hqOne : q < 1) :
    ∃ T L coefficient : ℝ,
      0 ≤ T ∧ 0 < L ∧ 0 < coefficient ∧
      (∀ z ∈ ({rho, (starRingEnd ℂ) rho} : Finset ℂ),
        z ∈ equalRealPartZeroPackage T rho.re) ∧
      0 < actualEqualRealPartZeroPackageEnergy T rho.re L ∧
      (HasFarPositiveTargetAmplitudeWitness chebyshevPsi0Error
          (fun x : ℝ => coefficient * x ^ rho.re) ∨
        HasFarNegativeTargetAmplitudeWitness chebyshevPsi0Error
          (fun x : ℝ => coefficient * x ^ rho.re)) := by
  rcases attainedGlobalNontrivialZeroRealPart_conjugatePair_spec hattained with
    ⟨hseed, hnonempty, hcap⟩
  exact exists_targetLineSeed_actualReciprocalPNTUnnormalizedOmegaAlternative_automatic
    selection hseed hnonempty hhalf hone hsigmaBeta hbetaOne
    hheightDelta hheightDeltaBeta hcap hrealStrict hq hqOne

end
end PrimeNumberTheorem
