import PrimeNumberTheorem.ZeroDensityLayerBudgetActualZeroPackageMovingRightEdgeOmega

#print axioms PrimeNumberTheorem.exists_targetLineSeed_actualZeroPackageMovingRightEdgeUnnormalizedOmega
#print axioms PrimeNumberTheorem.attainedGlobalRightEdgeRealClosed_actualZeroPackageMovingRightEdgeUnnormalizedOmega
