import PrimeNumberTheorem.ZeroDensityLayerBudgetCarlsonMovingCoefficientGrowthContract

#print axioms PrimeNumberTheorem.carlsonMovingPowerGap_lower
#print axioms PrimeNumberTheorem.carlsonMovingPowerGap_pos
#print axioms PrimeNumberTheorem.carlsonMovingPowerGap_inv_le
#print axioms PrimeNumberTheorem.carlsonQuarterRpowGap
#print axioms PrimeNumberTheorem.carlsonQuarterRpowGap_pos
#print axioms PrimeNumberTheorem.carlsonQuarterRpowGap_le_moving
#print axioms PrimeNumberTheorem.carlsonMovingNegativePowerGap_inv_le
#print axioms PrimeNumberTheorem.carlsonMovingHalfGap_inv_le_four
#print axioms PrimeNumberTheorem.carlsonMovingRightGap_eq
#print axioms PrimeNumberTheorem.carlsonMovingExplicitSharpCoefficient
#print axioms PrimeNumberTheorem.carlsonMovingSharpCoefficientEnvelope
#print axioms PrimeNumberTheorem.carlsonMovingExplicitSharpCoefficient_le_envelope
#print axioms PrimeNumberTheorem.carlsonMovingExplicitCoefficient
#print axioms PrimeNumberTheorem.carlsonMovingCoefficientEnvelope
#print axioms PrimeNumberTheorem.carlsonMovingExplicitCoefficient_le_envelope
#print axioms PrimeNumberTheorem.carlsonMovingSharpCoefficientConstantTerm
#print axioms PrimeNumberTheorem.carlsonMovingSharpCoefficientLinearTerm
#print axioms PrimeNumberTheorem.carlsonMovingSharpCoefficientQuadraticTerm
#print axioms PrimeNumberTheorem.carlsonMovingSharpCoefficientQuadraticConstant
#print axioms PrimeNumberTheorem.carlsonMovingSharpCoefficientEnvelope_laurent
#print axioms PrimeNumberTheorem.carlsonMovingSharpCoefficientConstantTerm_nonneg
#print axioms PrimeNumberTheorem.carlsonMovingSharpCoefficientLinearTerm_nonneg
#print axioms PrimeNumberTheorem.carlsonMovingSharpCoefficientQuadraticTerm_nonneg
#print axioms PrimeNumberTheorem.carlsonMovingSharpCoefficientEnvelope_le_quadratic
