import PrimeNumberTheorem.ZeroDensityLayerBudgetNearOptimalPrescribedHeightAnchorTransfer

namespace PrimeNumberTheorem

#print axioms prescribedHeightAnchorFloor_le_of_window
#print axioms nearOptimalPrescribedHeightBeta0_within
#print axioms nearOptimalPrescribedHeightParameters_spec
#print axioms nearOptimalPrescribedHeightSelectedHeight_spec
#print axioms actualNearOptimalPrescribedHeightUnifiedUpperSignedOmega

end PrimeNumberTheorem
