import PrimeNumberTheorem.ZeroDensityLayerBudgetAttainedGlobalRightEdgeReciprocalOmega

#print axioms PrimeNumberTheorem.attainedGlobalNontrivialZeroRealPart_conjugatePair_spec
#print axioms PrimeNumberTheorem.attainedGlobalRightEdge_actualReciprocalPNTUnnormalizedOmegaAlternative
