import PrimeNumberTheorem.ZeroDensityLayerBudgetMultiplicityWeightedKernel

#print axioms PrimeNumberTheorem.pntRelativeZeroContribution_eq_multiplicity_mul_simpleKernel
#print axioms PrimeNumberTheorem.norm_pntRelativeZeroContribution_eq_multiplicity_mul_norm
#print axioms PrimeNumberTheorem.sum_norm_pntRelativeZeroContribution_le_kernel_mul_multiplicityMass
#print axioms PrimeNumberTheorem.sum_norm_pntRelativeZeroContribution_le_kernel_mul_of_mass_le
#print axioms PrimeNumberTheorem.PositiveZeroBucketInput.sum_norm_pntRelativeZeroContribution_layer_le_count
