import PrimeNumberTheorem.ZeroDensityLayerBudgetActualTargetAmplitudeLowLayerTwoHeight

namespace PrimeNumberTheorem

#check positiveOutsideClusterLayerLowOrdinate
#check positiveOutsideClusterLayerHighAnnulus
#check positiveOutsideClusterLayer_eq_low_union_high
#check positiveOutsideClusterLayerLowOrdinate_multiplicityMass_le
#check positiveOutsideClusterLayerHighAnnulus_multiplicityMass_le
#check dynamicOutsideClusterLowOrdinateMass
#check dynamicOutsideClusterHighAnnulusMass
#check dynamicOutsideClusterLayerMass_eq_low_add_high
#check dynamicOutsideClusterLowOrdinateMass_le
#check dynamicOutsideClusterHighAnnulusMass_le
#check polynomial_highAnnulusKernel_eq_shiftedEndpoint
#check exists_globalCoefficient_dynamicOutsideClusterTwoHeightMass_le
#check tendsto_actualHybridGlobalLowLayerMajorant_div_target
#check tendsto_dynamicOutsideClusterTwoHeightMass_div_target
#check lowLayerTwoHeight_balanced_exponents
#check exists_lowLayerTwoHeight_strictMargins
#check exists_lowLayerTwoHeight_parameters_of_twoThirds

end PrimeNumberTheorem
