import PrimeNumberTheorem.ZeroDensityLayerBudgetActualCriticalHalfDecay

namespace PrimeNumberTheorem

#check actualCriticalHalfCanonicalInput
#check actualCriticalHalfCanonicalInput_low_re_le
#check tendsto_actualCriticalHalfCanonicalPNTLayerNorm

end PrimeNumberTheorem
