import PrimeNumberTheorem.ZeroDensityLayerBudgetActualMovingCarlsonWindowHeightDecay

#print axioms PrimeNumberTheorem.actualPositiveCarlsonStrip_mono_height
#print axioms PrimeNumberTheorem.actualSelectedHeightMovingCarlsonStripMass_le_exact
#print axioms PrimeNumberTheorem.eventually_selectedHeight_le_polynomialHeight_of_unitWindow
#print axioms PrimeNumberTheorem.tendsto_actualSelectedHeightMovingCarlsonStripMass_zero
