import PrimeNumberTheorem.ZeroDensityLayerBudgetJointTwoHeightOptimalOuterExponent

namespace PrimeNumberTheorem

#check IsJointTwoHeightOuterExponentFeasible
#check jointTwoHeightOuterExponentCeiling
#check jointTwoHeightOuterExponentFeasible_of_lt_ceiling
#check le_jointTwoHeightOuterExponentCeiling_of_feasible
#check exists_contourCompatible_jointTwoHeightOuterExponent_iff
#check contourFloor_lt_jointTwoHeightOuterExponentCeiling_iff
#check exists_contourCompatible_jointTwoHeightOuterExponent_iff_arithmetic

end PrimeNumberTheorem
