import PrimeNumberTheorem.ZeroDensityLayerBudgetQuadraticKernelMovingPNTTransfer

#print axioms PrimeNumberTheorem.quadraticKernelNaturalRemainderMajorant_reciprocalHeightNegligible
#print axioms PrimeNumberTheorem.naturalPointReciprocalHeightNegligible_variableBoundary_of_quadraticMajorant
#print axioms PrimeNumberTheorem.QuadraticKernelMovingPNTCertificate.residual_negligible
#print axioms PrimeNumberTheorem.QuadraticKernelMovingPNTCertificate.relativeSignAlternative
