import PrimeNumberTheorem.ZeroDensityLayerBudgetCubicContourKernelFactorization

#print axioms PrimeNumberTheorem.ExplicitFormulaResidues.explicitFormulaIntegrand_mul_exp_shift
#print axioms PrimeNumberTheorem.ExplicitFormulaResidues.thirdOrderExplicitFormulaIntegrand_secondDifference_div_sq_eq
#print axioms PrimeNumberTheorem.ExplicitFormulaResidues.intervalIntegral_thirdOrder_secondDifference_div_sq_eq
