import PrimeNumberTheorem.ZeroDensityLayerBudgetPintzCarlsonAdaptiveHeight

#print axioms PrimeNumberTheorem.pintzCarlsonFiniteLayerBudget_nonneg
#print axioms PrimeNumberTheorem.exists_pintzConstant_adaptiveFiniteHeightBudget_tendsto
