import PrimeNumberTheorem.ZeroDensityLayerBudgetHeightNormalizedContourObstruction

#check PrimeNumberTheorem.heightNormalizedContourMainRatio
#check PrimeNumberTheorem.heightNormalizedContourMainRatio_eq
#check PrimeNumberTheorem.tendsto_heightNormalizedContourMainRatio_atTop
#check PrimeNumberTheorem.selectedPolynomialHeightNormalizedContourRatio
#check PrimeNumberTheorem.tendsto_selectedPolynomialHeightNormalizedContourRatio_atTop
#check PrimeNumberTheorem.not_tendsto_selectedPolynomialHeightNormalizedContourRatio_zero
