import PrimeNumberTheorem.ZeroDensityLayerBudgetActualCarlsonBoundaryExtensionAbsoluteMass

namespace PrimeNumberTheorem

#check truncatedPositiveZeroAbsoluteMass_div_target_le_low_add_CarlsonTail_of_le
#check eventually_selectedPositiveOutsideClusterPNTAbsoluteMass_div_target_lt_boundaryMass_add
#check eventually_selectedFullOutsideClusterPNTAbsoluteMass_div_target_lt_two_mul_boundaryMass_add
#check eventually_selectedMovingRightEdgeExtension_div_target_lt_two_mul_boundaryMass_add
#check exists_boundaryCapturedCluster_movingRightEdgeExtension_div_target_lt

end PrimeNumberTheorem

