import PrimeNumberTheorem.ZeroDensityLayerBudgetJointTwoHeightGlobalOptimalTruncationParameters

namespace PrimeNumberTheorem

#check jointTwoHeightOptimalDensityThreshold
#check jointTwoHeightOptimalDensityThreshold_spec
#check eq_jointTwoHeightOptimalDensityThreshold_of_optimizer
#check jointTwoHeightGlobalOuterExponentCeiling
#check jointTwoHeightGlobalOuterExponentCeiling_eq
#check jointTwoHeightPrescribedCapOuterExponentCeiling_le_global
#check exists_jointTwoHeightGloballyNearOptimalTruncationParameters

end PrimeNumberTheorem
