import PrimeNumberTheorem.ZeroDensityLayerBudgetPNTTwoStripDensityDecay

#print axioms PrimeNumberTheorem.pntTwoStripBucketInput
#print axioms PrimeNumberTheorem.exists_pintzConstant_fixedGlobalLowDensityBudget_tendsto
#print axioms PrimeNumberTheorem.exists_pintzConstant_fixedClassicalCarlsonDensity_tendsto
#print axioms PrimeNumberTheorem.exists_pintzConstant_fixedExactHeight_highDensityTerm_tendsto
#print axioms PrimeNumberTheorem.exists_pintzConstant_fixedHybridDensityBudget_tendsto
#print axioms PrimeNumberTheorem.exists_pintzConstant_pntTwoStripHybridDensityBudget_tendsto
