import PrimeNumberTheorem.ZeroDensityLayerBudgetPintzCarlsonGap

#print axioms PrimeNumberTheorem.tendsto_pintzCarlsonSqrtLogScale_atTop
#print axioms PrimeNumberTheorem.tendsto_pintzCarlsonGap_rpow_mul_exp
#print axioms PrimeNumberTheorem.tendsto_carlsonExponent_pintzGap
