import PrimeNumberTheorem.ZeroDensityLayerBudgetNearOptimalPrescribedHeightMovingWindowUnifiedTransfer

#print axioms PrimeNumberTheorem.nearOptimalPrescribedHeightMovingPackageWitness_of_windowMeanSquare
#print axioms PrimeNumberTheorem.actualNearOptimalPrescribedHeightUnifiedUpperSignAlternative_of_windowMeanSquare_reciprocal
