import PrimeNumberTheorem.ZeroDensityLayerBudgetPNTLowDensityDecay

#print axioms PrimeNumberTheorem.eventually_one_add_log_height_add_six_le_four_mul_log_pow_four
#print axioms PrimeNumberTheorem.exists_pintzConstant_globalLowDensityGrowthMajorant_tendsto
#print axioms PrimeNumberTheorem.exists_pintzConstant_adaptiveGlobalLowDensityGrowthMajorant_tendsto
