import PrimeNumberTheorem.ZeroDensityLayerBudgetJointSlopeOptimalPolynomialHeightWindow

#print axioms PrimeNumberTheorem.jointPolynomialHeightConstraints_iff_effectiveSlope
#print axioms PrimeNumberTheorem.jointPolynomialHeightCommonSafetyMargin_le_optimal
#print axioms PrimeNumberTheorem.jointOptimalPolynomialHeightWindow_equalMargins
#print axioms PrimeNumberTheorem.carlsonFullTransferEffectiveSlope_eq_one
#print axioms PrimeNumberTheorem.carlsonFullTransferJointOptimizer_eq_unweighted
#print axioms PrimeNumberTheorem.fullTransferMargin_implies_carlsonDensityMargin
#print axioms PrimeNumberTheorem.exists_carlsonDensityMargin_without_fullTransferMargin
