import PrimeNumberTheorem.ZeroDensityLayerBudgetNormalizedCofinalLowerWitnessObstruction

#check PrimeNumberTheorem.IsNormalizedCofinalPNTLowerWitness
#check PrimeNumberTheorem.not_isNormalizedCofinalPNTLowerWitness_of_eventually_upper
#check PrimeNumberTheorem.exists_automaticBestPNTMajorant_with_normalizedLowerWitnessObstruction
