import PrimeNumberTheorem.ZeroDensityLayerBudgetPowerToSqrtLogAmplitudeTransfer

#print axioms PrimeNumberTheorem.tendsto_targetZeroPowerAmplitude_div_pntSqrtLogExponentialAmplitude_zero
#print axioms PrimeNumberTheorem.NaturalPointTargetAmplitudeNegligible.toSqrtLogExponentialAmplitude
#print axioms PrimeNumberTheorem.tendsto_actualStrictMarginRateIndependentResidual_div_amplitude_zero_of_tail
