import PrimeNumberTheorem.ZeroDensityLayerBudgetActualZeroPackageAutomaticReciprocalSignAlternative

#print axioms PrimeNumberTheorem.exists_targetLineSeed_actualReciprocalPNTSignAlternative_automatic
