import PrimeNumberTheorem.ZeroDensityLayerBudgetActualClosedRealAxisTargetDecay

namespace PrimeNumberTheorem

#check actualPNTClosedRealAxisNumerator
#check actualPNTClosedRealAxisRelativeTerm_eq
#check tendsto_log_one_sub_rpow_neg_two_atTop
#check tendsto_actualPNTClosedRealAxisNumerator
#check actualPNTClosedRealAxisRelativeTerm_targetAmplitudeNegligible

end PrimeNumberTheorem
