import PrimeNumberTheorem.ZeroDensityAmplificationAudit

#print axioms PrimeNumberTheorem.disjointWindowFamilyLowerCount_eventually_le_zeroDensity
#print axioms PrimeNumberTheorem.finiteDisjointWindowFamily_gap_not_tendsto_atTop
#print axioms PrimeNumberTheorem.disjointWindowFamily_carlson_contradiction
#print axioms PrimeNumberTheorem.disjointWindowFamily_carlson_instance_contradiction
#print axioms PrimeNumberTheorem.HalfIsolatedDetectorContractOutput
#print axioms PrimeNumberTheorem.halfIsolatedDetectorOutput_survives_signed_witnesses
#print axioms PrimeNumberTheorem.halfIsolatedDetectorOutput_survives_along_dynamic_budget
