import PrimeNumberTheorem.ZeroDensityLayerBudgetActualCubicLowVerticalIntegral

#print axioms PrimeNumberTheorem.analyticAt_thirdOrderExplicitFormulaIntegrand_of_analyticAt_logDeriv
#print axioms PrimeNumberTheorem.norm_integral_actualCubicLowVertical_le_of_analyticAt
#print axioms PrimeNumberTheorem.exists_norm_integral_actualCubicLowVertical_le
