import PrimeNumberTheorem.ZeroDensityLayerBudgetActualMovingCarlsonCertificate

#check PrimeNumberTheorem.actualMovingCarlsonStripMass
#check PrimeNumberTheorem.IsActualMovingCarlsonTwoHeightCertificate
#check PrimeNumberTheorem.actualMovingCarlsonStripMass_le_quadraticRatio
#check PrimeNumberTheorem.actualMovingCarlsonStripMass_nonneg
#check PrimeNumberTheorem.tendsto_actualMovingCarlsonStripMass_zero
