import PrimeNumberTheorem.ZeroDensityLayerBudgetCarlsonMovingBalancedDecay

#print axioms PrimeNumberTheorem.carlsonMovingBalancedNormalizedRatio
#print axioms PrimeNumberTheorem.tendsto_carlsonMovingBalancedNormalizedRatio_zero
#print axioms PrimeNumberTheorem.tendsto_zero_of_le_const_mul_carlsonMovingBalancedNormalizedRatio
#print axioms PrimeNumberTheorem.carlsonMovingBalancedCoefficientLogMargin
#print axioms PrimeNumberTheorem.IsCarlsonMovingBalancedCoefficientAdmissible
#print axioms PrimeNumberTheorem.carlsonMovingBalancedCoefficientRatio
#print axioms PrimeNumberTheorem.tendsto_carlsonMovingBalancedCoefficientRatio_zero
#print axioms PrimeNumberTheorem.tendsto_zero_of_le_carlsonMovingBalancedCoefficientRatio
