import PrimeNumberTheorem.ZeroDensityLayerBudgetStrictMarginOptimalRateRecovery

#print axioms PrimeNumberTheorem.theta_mul_classicalAdmissibleBalancedRate_le
#print axioms PrimeNumberTheorem.classicalAdmissibleBalancedRate_div_le_strictMarginRate
#print axioms PrimeNumberTheorem.exists_constants_automaticStrictMarginRateRecovery_PNT_upper
