import PrimeNumberTheorem.ZeroDensityLayerBudgetJointTwoHeightMidpointSigmaImprovement

namespace PrimeNumberTheorem

#check jointTwoHeightMidpointDensityThreshold
#check jointTwoHeightMidpointDensityThreshold_spec
#check jointTwoHeightPrescribedCapOuterExponentCeiling_midpoint_gt_capAligned
#check exists_jointTwoHeightStrictlyImprovedMidpointSigmaParameters

end PrimeNumberTheorem
