import PrimeNumberTheorem.ZeroDensityLayerBudgetActualCubicCompactLowLeft

#print axioms PrimeNumberTheorem.exists_analyticAt_norm_logDeriv_riemannZeta_bound_on_right_thickening_of_imaginary_segment
#print axioms PrimeNumberTheorem.exists_norm_logDeriv_riemannZeta_bound_on_right_thickening_of_imaginary_segment
