import PrimeNumberTheorem.ZeroDensityLayerBudgetActualFixedCarlsonCoverBarrier

namespace PrimeNumberTheorem

#check not_mem_actualPositiveCarlsonFiniteStripUnion_of_upper_lt_re
#check re_le_of_actualPositiveCarlsonRightCover_of_endpoint_cap
#check not_actualPositiveCarlsonRightCover_of_escapingZero
#check eventually_not_actualPositiveCarlsonRightCover_of_escapingZeros

end PrimeNumberTheorem
