import PrimeNumberTheorem.ZeroDensityLayerBudgetActualStrictMarginFiniteZeroMajorant

#print axioms PrimeNumberTheorem.eventually_actualPintzCarlsonRate_finiteZeroRelative_le_strictMarginMajorant
#print axioms PrimeNumberTheorem.exists_constants_actualPintzCarlsonGrid_finiteZeroRelative_le_strictMarginMajorant
