import PrimeNumberTheorem.ZeroDensityLayerBudgetCarlsonMovingBalancedDecay

#print axioms PrimeNumberTheorem.carlsonMovingBalancedNormalizedRatio
#print axioms PrimeNumberTheorem.tendsto_carlsonMovingBalancedNormalizedRatio_zero
