import PrimeNumberTheorem.ZeroDensityLayerBudgetClassicalStrictMarginGridFullBudgetTransfer

#print axioms PrimeNumberTheorem.classicalStrictMarginZeroFreeRate_mul_lt
#print axioms PrimeNumberTheorem.classicalStrictMarginRateFullBudgetEnvelope_le_grid
#print axioms PrimeNumberTheorem.eventually_abs_relativeChebyshevPsi0Error_le_strictMarginGridEnvelope
