import PrimeNumberTheorem.ZeroDensityLayerBudgetPNTAnchoredMovingSigma

#print axioms PrimeNumberTheorem.pintzCarlsonHybridDensityBudget_le_anchoredMajorant
#print axioms PrimeNumberTheorem.exists_pintzConstant_anchoredMovingSigmaDensityMajorant_tendsto
#print axioms PrimeNumberTheorem.exists_pintzConstant_anchoredUniformMovingSigmaDensityDecay
#print axioms PrimeNumberTheorem.exists_fixedRate_anchoredMovingSigma_relativeChebyshevPsi0Error_tendsto
