import PrimeNumberTheorem.ZeroDensityLayerBudgetActualPositiveOutsideClusterCapUnifiedTransfer

namespace PrimeNumberTheorem

#check PositiveOutsideClusterRealPartCap
#check positiveOutsideClusterRealPartCap_of_global
#check PositiveOutsideClusterRealPartCap.mono_cluster
#check PositiveOutsideClusterRealPartCap.adjoinRealOrdinateZeros
#check exists_automaticGoodHeight_positiveOutsideClusterRealPartCapNaturalTargetTransfer

end PrimeNumberTheorem
