import PrimeNumberTheorem.ZeroDensityLayerBudgetPintzCarlsonConcreteUnified

/-! Compile-time contract for the concrete unified Pintz--Carlson transfer. -/

#check PrimeNumberTheorem.pintzCarlsonClassicalAggregatedDensityLayerTerm
#check PrimeNumberTheorem.constructAdaptiveClassicalCarlsonUnifiedDynamicZeroTransfer
#check PrimeNumberTheorem.constructAdaptiveClassicalCarlsonUnifiedDynamicSignedZeroTransfer
