import PrimeNumberTheorem.ZeroDensityLayerBudgetActualPintzCertifiedGoodHeightRemainderEnvelopeTransfer
import PrimeNumberTheorem.ZeroDensityLayerBudgetVariableBoundarySigmaOnlyUnifiedUpperSignedOmega

/-!
# Unified PNT transfer at the actual Pintz-optimized good height

The certified pointwise optimizer, its visible zero package, its natural
running right edge, and its actual explicit-formula remainder are assembled in
one sigma-only transfer.  A common candidate zero-free envelope then upgrades
the Carlson-scale upper estimate to relative PNT decay.

Positive and negative main-cluster witnesses remain explicit assumptions.
Nothing here proves unconditional Omega or RH.
-/

namespace PrimeNumberTheorem

open Filter Topology

/-- The certified Pintz optimizer at the automatic sigma-only polynomial
exponent. -/
noncomputable def sigmaOnlyActualPintzCertifiedOptimalHeight
    {ι : Type*} [Fintype ι]
    (cost : ℝ → ℝ → ℝ) (sigma : ℝ)
    (hhalf : 1 / 2 < sigma) (hone : sigma < 1)
    (family : ActualPintzGoodHeightCandidateFamily ι) : ℝ → ℝ :=
  actualPintzCertifiedOptimalHeight cost
    (actualDynamicBoundaryBalancedGoodHeightExponent sigma)
    (sigmaOnlyRunningBoundaryParameters_spec hhalf hone).1 family

/-- The natural running visible-zero boundary generated by the exact optimized
height rather than by the older canonical selector. -/
noncomputable def sigmaOnlyActualPintzRunningBoundary
    {ι : Type*} [Fintype ι]
    (cost : ℝ → ℝ → ℝ) (sigma : ℝ)
    (hhalf : 1 / 2 < sigma) (hone : sigma < 1)
    (family : ActualPintzGoodHeightCandidateFamily ι) : ℝ → ℝ :=
  naturalRunningVisibleZeroBoundaryReal
    (sigmaOnlyActualPintzCertifiedOptimalHeight
      cost sigma hhalf hone family)
    (sigmaOnlyRunningBoundaryBeta0 sigma)

/-- The visible multiplicity-aware explicit-formula main term at the same
optimized height and running boundary. -/
noncomputable def sigmaOnlyActualPintzVisibleMain
    {ι : Type*} [Fintype ι]
    (cost : ℝ → ℝ → ℝ) (sigma : ℝ)
    (hhalf : 1 / 2 < sigma) (hone : sigma < 1)
    (family : ActualPintzGoodHeightCandidateFamily ι)
    (m : ℕ) : ℝ :=
  dynamicVisibleClusterPNTMain
    (sigmaOnlyActualPintzCertifiedOptimalHeight
      cost sigma hhalf hone family)
    (variableBoundaryZeroPackage
      (sigmaOnlyActualPintzCertifiedOptimalHeight
        cost sigma hhalf hone family)
      (sigmaOnlyActualPintzRunningBoundary
        cost sigma hhalf hone family) (m : ℝ))
    (m : ℝ)

/-- Complete sigma-only Carlson upper transfer and conditional signed Omega at
the exact certified Pintz optimizer. -/
theorem actualSigmaOnlyPintzCertifiedOptimalHeightUnifiedUpperSignedOmega
    {ι : Type*} [Fintype ι]
    (cost : ℝ → ℝ → ℝ) {sigma eta c loss : ℝ}
    (hhalf : 1 / 2 < sigma) (hone : sigma < 1)
    (heta : 0 < eta) (hloss : 0 < loss) (hlossC : loss < c)
    (family : ActualPintzGoodHeightCandidateFamily ι)
    (hmainPos :
      HasFarNaturalPointPositiveTargetAmplitudeWitness
        (sigmaOnlyActualPintzVisibleMain
          cost sigma hhalf hone family)
        (fun m => c * variableBoundaryTargetAmplitude
          (sigmaOnlyActualPintzRunningBoundary
            cost sigma hhalf hone family) (m : ℝ)))
    (hmainNeg :
      HasFarNaturalPointNegativeTargetAmplitudeWitness
        (sigmaOnlyActualPintzVisibleMain
          cost sigma hhalf hone family)
        (fun m => c * variableBoundaryTargetAmplitude
          (sigmaOnlyActualPintzRunningBoundary
            cost sigma hhalf hone family) (m : ℝ))) :
    (∀ᶠ m : ℕ in atTop,
      |relativeChebyshevPsi0Error (m : ℝ)| <
        (actualCarlsonDynamicBoundaryCoefficientCapConstant sigma + eta) *
          variableBoundaryTargetAmplitude
            (sigmaOnlyActualPintzRunningBoundary
              cost sigma hhalf hone family) (m : ℝ)) ∧
      0 < c - loss ∧
        HasFarSignedTargetAmplitudeWitnesses chebyshevPsi0Error
          (fun x => (c - loss) * x ^
            sigmaOnlyActualPintzRunningBoundary
              cost sigma hhalf hone family x) := by
  let alpha := actualDynamicBoundaryBalancedGoodHeightExponent sigma
  let epsilon := sigmaOnlyRunningBoundaryEpsilon sigma
  let beta0 := sigmaOnlyRunningBoundaryBeta0 sigma
  let H := sigmaOnlyActualPintzCertifiedOptimalHeight
    cost sigma hhalf hone family
  let beta := sigmaOnlyActualPintzRunningBoundary
    cost sigma hhalf hone family
  rcases sigmaOnlyRunningBoundaryParameters_spec hhalf hone with
    ⟨halpha, halphaOne, hepsilon, hbeta0, hremainderMargin,
      hcarlsonMargin, hreal⟩
  have hbetaLower : ∀ᶠ m : ℕ in atTop, beta0 ≤ beta (m : ℝ) := by
    filter_upwards [] with m
    simpa [beta, beta0, sigmaOnlyActualPintzRunningBoundary,
      naturalRunningVisibleZeroBoundaryReal] using
      beta0_le_naturalRunningVisibleZeroBoundary H beta0 m
  have hbetaMono : Monotone (fun m : ℕ => beta (m : ℝ)) := by
    simpa [beta, beta0, sigmaOnlyActualPintzRunningBoundary] using
      naturalRunningVisibleZeroBoundaryReal_sampled_monotone H beta0
  have hheightMemReal :=
    eventually_actualPintzCertifiedOptimalHeight_mem
      cost halpha family
  have hheightMemNat :=
    tendsto_natCast_atTop_atTop.eventually hheightMemReal
  have hheightUpper :
      ∀ᶠ m : ℕ in atTop, H (m : ℝ) ≤ carlsonPolynomialHeight alpha (m : ℝ) := by
    filter_upwards [hheightMemNat] with m hm
    simpa [H, alpha, sigmaOnlyActualPintzCertifiedOptimalHeight,
      carlsonPolynomialHeight] using hm.2
  have hheightTendsto :
      Tendsto (fun m : ℕ => H (m : ℝ)) atTop atTop := by
    have hrealTop :=
      actualPintzCertifiedOptimalHeight_tendsto_atTop
        cost alpha halpha family
    have hnatTop := hrealTop.comp tendsto_natCast_atTop_atTop
    simpa [H, alpha, sigmaOnlyActualPintzCertifiedOptimalHeight] using hnatTop
  have hright :
      IsIndexedVariableBoundaryVisibleRightEdge (sigma := sigma) H beta := by
    simpa [beta, beta0, sigmaOnlyActualPintzRunningBoundary] using
      naturalRunningVisibleZeroBoundaryReal_indexedVisibleRightEdge
        (sigma := sigma) H beta0
  have hremainder :
      ActualSelectedHeightNaturalPointRemainderCertificate beta0 H := by
    have hcert :=
      actualPintzCertifiedOptimalHeight_actualNaturalRemainderCertificate
        cost hbeta0 halpha halphaOne hremainderMargin family
    simpa [H, alpha, beta0,
      sigmaOnlyActualPintzCertifiedOptimalHeight] using hcert
  have htransfer :=
    actualMonotoneVariableBoundaryUnifiedUpperSignedOmega
      (sigma := sigma) (beta0 := beta0) (alpha := alpha)
      (epsilon := epsilon) (H := H) (beta := beta)
      heta hloss hlossC hbeta0 hbetaLower hbetaMono
      hheightUpper hheightTendsto halpha hepsilon hcarlsonMargin
      hreal hhalf hone hright hremainder hmainPos hmainNeg
  simpa [H, beta, alpha, beta0, epsilon,
    sigmaOnlyActualPintzVisibleMain] using htransfer

/-- A common candidate zero-free envelope and effective log-gap turn the same
optimized-height upper transfer into relative PNT decay, while retaining the
conditional signed witnesses. -/
theorem
    actualSigmaOnlyPintzCertifiedOptimalHeightZeroFreeEnvelopeUpperDecaySignedOmega
    {ι : Type*} [Fintype ι]
    (cost : ℝ → ℝ → ℝ) {sigma eta c loss : ℝ} {gap : ℕ → ℝ}
    (hhalf : 1 / 2 < sigma) (hone : sigma < 1)
    (heta : 0 < eta) (hloss : 0 < loss) (hlossC : loss < c)
    (family : ActualPintzGoodHeightCandidateFamily ι)
    (hgapAnti : Antitone gap)
    (henvelope :
      ∀ i, IsNaturalPositiveZeroFreeEnvelope
        (actualPintzCandidateHeight
          (actualDynamicBoundaryBalancedGoodHeightExponent sigma)
          (family.selector i)) gap)
    (heffective :
      Tendsto
        (fun m : ℕ =>
          naturalRunningBoundaryEffectiveGap
              (sigmaOnlyRunningBoundaryBeta0 sigma) gap m *
            Real.log (m : ℝ))
        atTop atTop)
    (hmainPos :
      HasFarNaturalPointPositiveTargetAmplitudeWitness
        (sigmaOnlyActualPintzVisibleMain
          cost sigma hhalf hone family)
        (fun m => c * variableBoundaryTargetAmplitude
          (sigmaOnlyActualPintzRunningBoundary
            cost sigma hhalf hone family) (m : ℝ)))
    (hmainNeg :
      HasFarNaturalPointNegativeTargetAmplitudeWitness
        (sigmaOnlyActualPintzVisibleMain
          cost sigma hhalf hone family)
        (fun m => c * variableBoundaryTargetAmplitude
          (sigmaOnlyActualPintzRunningBoundary
            cost sigma hhalf hone family) (m : ℝ))) :
    Tendsto (fun m : ℕ => relativeChebyshevPsi0Error (m : ℝ))
        atTop (nhds 0) ∧
      0 < c - loss ∧
        HasFarSignedTargetAmplitudeWitnesses chebyshevPsi0Error
          (fun x => (c - loss) * x ^
            sigmaOnlyActualPintzRunningBoundary
              cost sigma hhalf hone family x) := by
  rcases actualSigmaOnlyPintzCertifiedOptimalHeightUnifiedUpperSignedOmega
      cost hhalf hone heta hloss hlossC family hmainPos hmainNeg with
    ⟨hupper, hcoefficient, hsigned⟩
  let alpha := actualDynamicBoundaryBalancedGoodHeightExponent sigma
  let beta0 := sigmaOnlyRunningBoundaryBeta0 sigma
  let H := sigmaOnlyActualPintzCertifiedOptimalHeight
    cost sigma hhalf hone family
  let beta := sigmaOnlyActualPintzRunningBoundary
    cost sigma hhalf hone family
  have halpha : 0 < alpha := by
    simpa [alpha] using
      (sigmaOnlyRunningBoundaryParameters_spec hhalf hone).1
  have hoptimizerEnvelope : IsNaturalPositiveZeroFreeEnvelope H gap := by
    have htransfer :=
      actualPintzCertifiedOptimalHeight_isNaturalPositiveZeroFreeEnvelope
        cost halpha family gap henvelope
    simpa [H, alpha, sigmaOnlyActualPintzCertifiedOptimalHeight] using htransfer
  have hbeta0 : 0 < beta0 := by
    simpa [beta0] using
      (sigmaOnlyRunningBoundaryParameters_spec hhalf hone).2.2.2.1
  have hzeroFree : IsNaturalVariableBoundaryZeroFreeDecay beta := by
    have htransfer := isNaturalVariableBoundaryZeroFreeDecay_of_envelope
      hbeta0 hgapAnti hoptimizerEnvelope heffective
    simpa [H, beta, beta0, sigmaOnlyActualPintzRunningBoundary] using htransfer
  have htarget :=
    variableBoundaryTargetAmplitude_tendsto_zero_of_zeroFreeDecay hzeroFree
  have hmajorant :
      Tendsto
        (fun m : ℕ =>
          (actualCarlsonDynamicBoundaryCoefficientCapConstant sigma + eta) *
            variableBoundaryTargetAmplitude beta (m : ℝ))
        atTop (nhds 0) := by
    simpa only [mul_zero] using
      htarget.const_mul
        (actualCarlsonDynamicBoundaryCoefficientCapConstant sigma + eta)
  have habs :
      Tendsto (fun m : ℕ => |relativeChebyshevPsi0Error (m : ℝ)|)
        atTop (nhds 0) := by
    refine squeeze_zero'
      (Filter.Eventually.of_forall fun m => abs_nonneg _) ?_ hmajorant
    filter_upwards [hupper] with m hm
    simpa [beta] using hm.le
  have hdecay :
      Tendsto (fun m : ℕ => relativeChebyshevPsi0Error (m : ℝ))
        atTop (nhds 0) :=
    tendsto_zero_iff_norm_tendsto_zero.mpr habs
  exact ⟨hdecay, hcoefficient, hsigned⟩

end PrimeNumberTheorem
