import PrimeNumberTheorem.ZeroDensityLayerBudgetActualClusterComplementUnifiedTransfer

namespace PrimeNumberTheorem

#check ActualCarlsonOutsideClusterFiniteStripCertificate
#check
  ActualCarlsonOutsideClusterFiniteStripCertificate.fullTail_negligible
#check
  ActualCarlsonOutsideClusterFiniteStripCertificate.signedComplementCertificate
#check
  unified_parametricPNTUpper_actualCarlsonOutsideClusterLower

end PrimeNumberTheorem
