import PrimeNumberTheorem.ZeroDensityLayerBudgetDyadicSquareMultiplicityCapacity

open Complex Filter Set Topology
open scoped BigOperators

namespace PrimeNumberTheorem

#check squareMultiplicityCapacity_le_max_mul_linearMultiplicityCapacity
#check squareMultiplicityCapacity_sdiff_le
#check ExplicitFormulaAux.exists_analyticOrderNatAt_riemannZeta_le_log_im_of_nontrivialZero
#check actualCarlsonDyadicZeroStrip
#check actualCarlsonDyadicStripLinearMultiplicityCapacity_le_count
#check actualCarlsonDyadicStripLinearReciprocalSquareCapacity_le_count_div_sq
#check exists_actualCarlsonDyadicStrip_maxMultiplicity_le_log
#check exists_actualCarlsonDyadicStripSquareReciprocalCapacity_le_count
#check exists_actualCarlsonDyadicStripSquareReciprocalCapacityExcluding_le_count
#check pntCarlsonClassicalDensityExponent_sub_two_le_neg_one
#check pntCarlsonClassicalDensityExponent_sub_two_lt_zero
#check pntCarlsonClassicalDensityExponent_half_eq_one

end PrimeNumberTheorem
