import PrimeNumberTheorem.ZeroDensityLayerBudgetJointTwoHeightCanonicalStrictTargetExponent

namespace PrimeNumberTheorem

#check jointTwoHeightCanonicalStrictTargetExponent
#check jointTwoHeightCanonicalStrictTargetExponent_spec
#check jointTwoHeightCanonicalStrictTargetExponent_lower
#check jointTwoHeightCanonicalStrictTargetExponent_lt_one
#check theta_lt_jointTwoHeightCanonicalStrictTargetExponent
#check theta_lt_improvedThreshold_canonicalStrictTargetExponent

end PrimeNumberTheorem
