import PrimeNumberTheorem.ZeroDensityLayerBudgetActualSelectedHeightCriticalHalfDecay

#check PrimeNumberTheorem.actualSelectedHeightCriticalHalfCanonicalInput
#check PrimeNumberTheorem.eventually_selectedHeight_le_polynomialHeight_of_unitWindow_real
#check PrimeNumberTheorem.tendsto_selectedHeight_atTop_of_unitWindow
#check PrimeNumberTheorem.tendsto_actualSelectedHeightCriticalHalfPNTLayerNorm_zero
