import PrimeNumberTheorem.ZeroDensityLayerBudgetActualCubicCarlsonCertificateSummability

#check PrimeNumberTheorem.one_add_log_add_six_le_three_mul_log
#check PrimeNumberTheorem.dyadic_succ_rpow_div_sixth_eq_actualCubicCarlsonRatio
#check PrimeNumberTheorem.CarlsonEventualMajorant.eventually_actualCubicCertificateBlock_le_logFifth
#check PrimeNumberTheorem.CarlsonEventualMajorant.summable_actualCubicDyadicStripSquareCapacityExcluding
