import PrimeNumberTheorem.ZeroDensityLayerBudgetAutomaticOptimalStrictMarginPNTGrid

#print axioms PrimeNumberTheorem.actualStrictMarginOptimalSingletonGrid
#print axioms PrimeNumberTheorem.exists_constants_automaticOptimalStrictMarginGrid_PNT_upper
