import PrimeNumberTheorem.ZeroDensityLayerBudgetActualMovingClusterComplementReciprocal

#print axioms PrimeNumberTheorem.movingPositiveOutsideClusterPNTTailNorm_le_rpow_mul_globalReciprocal
#print axioms PrimeNumberTheorem.tendsto_movingPositiveOutsideClusterPNTTailNorm_div_target_zero_reciprocal
#print axioms PrimeNumberTheorem.selectedMovingRightEdgeOutsideClusterComplement_targetAmplitudeNegligible_reciprocal
