import PrimeNumberTheorem.ZeroDensityLayerBudgetStrictMarginFullRateGapClosure

#print axioms PrimeNumberTheorem.tendsto_pntSqrtLog_div_sqrt_natCast_zero
#print axioms PrimeNumberTheorem.tendsto_cofinalPNTZeroDepthTail_div_sqrtLogAmplitude_zero
#print axioms PrimeNumberTheorem.tendsto_actualStrictMarginGridFullPNTErrorMajorant_strictRateGap
#print axioms PrimeNumberTheorem.no_cofinalPNTLowerWitness_at_sqrtLogAmplitude
