import PrimeNumberTheorem.ZeroDensityLayerBudgetJointTwoHeightCubicCapDeficitAsymptotic

namespace PrimeNumberTheorem

#check jointTwoHeightImprovedGlobalCapThreshold_cubicDeficit_eq
#check jointTwoHeightImprovedGlobalCapThreshold_deficitRatio_eq
#check tendsto_jointTwoHeightImprovedGlobalCapThreshold_cubicDeficit
#check tendsto_jointTwoHeightImprovedGlobalCapThreshold_deficitRatio_zero

end PrimeNumberTheorem
