import PrimeNumberTheorem.ZeroDensityLayerBudgetPintzCarlsonAdaptiveHeight

#print axioms PrimeNumberTheorem.pintzCarlsonFiniteLayerBudget_nonneg
#print axioms PrimeNumberTheorem.tendsto_adaptive_pintzCarlsonHeight_atTop
#print axioms PrimeNumberTheorem.adaptive_pintzCarlsonHeight_pos
#print axioms PrimeNumberTheorem.exists_pintzConstant_adaptiveFiniteHeightBudget_tendsto
#print axioms PrimeNumberTheorem.exists_pintzConstant_dominatedAdaptiveLayerBudget_tendsto
