import PrimeNumberTheorem.ZeroDensityLayerBudgetActualMovingCarlsonPositiveTailTransfer

#print axioms PrimeNumberTheorem.actualCriticalHalfCanonicalInput_high_subset_movingMiddle_union_strip
#print axioms PrimeNumberTheorem.actualCriticalHalfCanonicalInput_highLayerNorm_le_movingMasses
#print axioms PrimeNumberTheorem.dynamicPositivePNTTailNorm_le_criticalHalf_add_movingMasses
#print axioms PrimeNumberTheorem.tendsto_dynamicPositivePNTTailNorm_of_actualMovingCarlson
