import PrimeNumberTheorem.ZeroDensityLayerBudgetActualReciprocalOutsideClusterFullResidual

#print axioms PrimeNumberTheorem.eventually_actualCarlsonSelectedHeightFullZeroNormalizedSum_lt_two_mul_boundaryMass_add_reciprocal
#print axioms PrimeNumberTheorem.eventually_actualCarlsonSelectedHeightPNTClusterResidual_normalized_lt_boundaryCoefficient_add_reciprocal
#print axioms PrimeNumberTheorem.eventually_abs_actualCarlsonSelectedHeightPNTClusterResidual_lt_boundaryCoefficient_mul_targetAmplitude_reciprocal
