import PrimeNumberTheorem.ZeroDensityLayerBudgetKernelOrderReciprocalHeightCriterion

#check PrimeNumberTheorem.kernelOrderReciprocalHeightRemainderRatio
#check PrimeNumberTheorem.kernelOrderReciprocalHeightRemainderRatio_eq
#check PrimeNumberTheorem.tendsto_kernelOrderReciprocalHeightRemainderRatio_zero
#check PrimeNumberTheorem.tendsto_quadraticKernelReciprocalHeightRemainderRatio_zero
#check PrimeNumberTheorem.quadraticKernelReciprocalHeightRemainderRatio_eq
#check PrimeNumberTheorem.linearKernelReciprocalHeightRemainderRatio_eq
