import PrimeNumberTheorem.ZeroDensityLayerBudgetActualSelectedHeightMovingCarlsonPNTTransfer

#print axioms PrimeNumberTheorem.tendsto_dynamicRealOrdinatePNTZeroTailNorm_of_selectedHeightUnitWindow
#print axioms PrimeNumberTheorem.tendsto_dynamicFullPNTZeroTailNorm_of_selectedHeightMovingCarlson
#print axioms PrimeNumberTheorem.tendsto_relativeChebyshevPsi0Error_of_selectedHeightMovingCarlson
