import PrimeNumberTheorem.ZeroDensityLayerBudgetCarlsonWeightedOptimalPolynomialHeightWindow

namespace PrimeNumberTheorem

#check carlsonPolynomialDensitySlope
#check carlsonWeightedPolynomialCriticalRealPart
#check carlsonWeightedPolynomialHeightFeasibilityGap
#check carlsonWeightedOptimalPolynomialHeightSafetyMargin
#check carlsonWeightedOptimalPolynomialHeightInnerExponent
#check carlsonWeightedOptimalPolynomialHeightOuterExponent
#check carlsonWeightedOptimalPolynomialHeightEpsilon
#check @carlsonPolynomialDensitySlope_nonneg
#check @carlsonPolynomialDensitySlope_pos
#check @carlsonWeightedPolynomialCriticalRealPart_spec
#check @carlsonWeightedPolynomialHeightFeasibilityGap_pos_iff
#check @carlsonWeightedPolynomialCriticalRealPart_lt_criticalHalf
#check @carlsonWeightedOptimalPolynomialHeightWindow_spec
#check @carlsonWeightedOptimalPolynomialSelectedHeight_spec

end PrimeNumberTheorem
