import PrimeNumberTheorem.ZeroDensityLayerBudgetActualCriticalHalfDecay

#print axioms PrimeNumberTheorem.actualCriticalHalfCanonicalInput_low_re_le
#print axioms PrimeNumberTheorem.tendsto_actualCriticalHalfCanonicalPNTLayerNorm
