import PrimeNumberTheorem.ZeroDensityLayerBudgetActualDyadicCarlsonMinimalLayerHeights

#check PrimeNumberTheorem.carlsonPointwiseHeightConditions_of_threeFourths
#check PrimeNumberTheorem.isCarlsonMovingQuadraticLogPowerGap_of_dyadic
#check PrimeNumberTheorem.dyadicCarlsonBalancedHeightFloor
#check PrimeNumberTheorem.tendsto_dyadicCarlsonBalancedHeightFloor_atTop
#check PrimeNumberTheorem.tendsto_log_dyadicCarlsonBalancedHeightFloor_atTop
#check PrimeNumberTheorem.actualDynamicDyadicCarlsonMinimalHeightConditions
#check PrimeNumberTheorem.exists_constants_tendsto_actualDyadicCarlsonMinimalFixedAnchorMass_zero_automatic
