import PrimeNumberTheorem.ZeroDensityLayerBudgetActualAutomaticGoodHeightNaturalUnifiedTransfer

namespace PrimeNumberTheorem

#check eventually_selectedUniformGoodHeight_nonneg_le_polynomial
#check automaticGoodHeight_twoHeight_naturalPointLowerTransfer
#check unified_automaticGoodHeight_twoHeight_naturalTargetTransfer

end PrimeNumberTheorem
