import PrimeNumberTheorem.ZeroDensityLayerBudgetActualMovingExtensionShrinkingGap

namespace PrimeNumberTheorem

#check HasShrinkingGapMassRate
#check shrinkingGapMassRate_of_exponentialMargin
#check HasShrinkingGapCarlsonTwoHeightRate
#check shrinkingGapCarlsonTwoHeightRate_of_budget_majorants
#check tendsto_dynamicActualPositiveCarlsonStripTargetAmplitudeMass_of_shrinkingGap
#check selectedPositiveOutsideClusterPNTAbsoluteMass_targetAmplitudeNegligible_of_shrinkingGap
#check selectedFullOutsideClusterPNTAbsoluteMass_targetAmplitudeNegligible_of_shrinkingGap
#check selectedMovingRightEdgeExtension_targetAmplitudeNegligible_of_shrinkingGap
#check exists_shrinkingGap_positiveOutsideClusterMovingSeedSignedNaturalTargetTransfer

end PrimeNumberTheorem
