import PrimeNumberTheorem.ZeroDensityLayerBudgetActualCubicTwoHeightDyadicCuts

#check PrimeNumberTheorem.actualCubicDyadicPolynomialCut
#check PrimeNumberTheorem.actualCubicLowDyadicCut
#check PrimeNumberTheorem.actualCubicOuterDyadicCut
#check PrimeNumberTheorem.tendsto_actualCubicDyadicPolynomialCut_atTop
#check PrimeNumberTheorem.tendsto_actualCubicLowDyadicCut_atTop
#check PrimeNumberTheorem.tendsto_actualCubicOuterDyadicCut_atTop
#check PrimeNumberTheorem.eventually_actualCubicLowDyadicCut_le_outer
#check PrimeNumberTheorem.CarlsonEventualMajorant.tendsto_actualCubicTail_at_lowDyadicCut_zero
#check PrimeNumberTheorem.CarlsonEventualMajorant.tendsto_actualCubicTail_at_outerDyadicCut_zero
