import PrimeNumberTheorem.ZeroDensityLayerBudgetNearOptimalPrescribedHeightAnchorTransfer

namespace PrimeNumberTheorem

#check prescribedHeightAnchorFloor
#check nearOptimalPrescribedHeightBeta0
#check nearOptimalPrescribedHeightInnerExponent
#check prescribedHeightAnchorFloor_le_of_window
#check nearOptimalPrescribedHeightBeta0_within
#check nearOptimalPrescribedHeightParameters_spec
#check nearOptimalPrescribedHeightSelectedHeight_spec
#check actualNearOptimalPrescribedHeightUnifiedUpperSignedOmega

end PrimeNumberTheorem
