import PrimeNumberTheorem.ZeroDensityLayerBudgetActualClassicalDyadicCarlsonGap

#check PrimeNumberTheorem.classicalAdmissibleDyadicCarlsonGapWidth
#check PrimeNumberTheorem.classicalAdmissibleDyadicCarlsonGapWidth_pos
#check PrimeNumberTheorem.classicalAdmissibleDyadicCarlsonGapWidth_nonneg
#check PrimeNumberTheorem.eventually_classicalAdmissibleDyadicCarlsonGapWidth_le_eighth
#check PrimeNumberTheorem.isCarlsonMovingDyadicLogPowerGap_classicalAdmissible
#check PrimeNumberTheorem.isSelectedHeightDynamicZeroFree_selectedClassicalAdmissible
#check PrimeNumberTheorem.exists_selectedClassicalAdmissibleDyadicCarlsonZeroFreeGap

