import PrimeNumberTheorem.ZeroDensityLayerBudgetActualZeroPackageMovingRightEdgeOmegaReciprocal

#print axioms PrimeNumberTheorem.automaticGoodHeight_movingRightEdgeSeedNaturalPointLowerTransfer_reciprocal
#print axioms PrimeNumberTheorem.exists_targetLineSeed_actualZeroPackageMovingRightEdgeUnnormalizedOmega_reciprocal
#print axioms PrimeNumberTheorem.attainedGlobalRightEdgeRealClosed_actualZeroPackageMovingRightEdgeUnnormalizedOmega_reciprocal
