import PrimeNumberTheorem.ZeroDensityClusterComparison

#print axioms PrimeNumberTheorem.localClusterLowerBound_le_card
#print axioms PrimeNumberTheorem.finite_localClusterLowerBound_eventually_le_diverging_upper
#print axioms PrimeNumberTheorem.eventually_upper_lt_lower_of_gap_tendsto_atTop
#print axioms PrimeNumberTheorem.false_of_eventually_lower_count_upper_separated
#print axioms PrimeNumberTheorem.cluster_density_contradiction_of_gap_tendsto_atTop
