import PrimeNumberTheorem.ZeroDensityLayerBudgetActualPositiveZeroOrderedCoverTransfer

#print axioms PrimeNumberTheorem.actualPositiveCarlsonRightCover_of_endpoints
#print axioms PrimeNumberTheorem.actualCriticalHalfCanonicalInput_high_subset_stripUnion
#print axioms PrimeNumberTheorem.actualCriticalHalfCanonicalInput_highLayerNorm_le_stripUnion
#print axioms PrimeNumberTheorem.dynamicPositivePNTTailNorm_le_criticalHalf_add_orderedStripUnion
#print axioms PrimeNumberTheorem.tendsto_dynamicPositivePNTTailNorm_of_orderedCarlsonRightCover
#print axioms PrimeNumberTheorem.tendsto_dynamicPositivePNTTailNorm_of_eventually_orderedCarlsonRightCover
#print axioms PrimeNumberTheorem.tendsto_dynamicPositivePNTTailNorm_of_orderedCarlsonEndpoints
#print axioms PrimeNumberTheorem.tendsto_dynamicPositivePNTTailNorm_of_eventually_orderedCarlsonEndpoints
