import PrimeNumberTheorem.ZeroDensityLayerBudgetVariableBoundaryMovingWindowMeanSquareHandoff

#print axioms PrimeNumberTheorem.HasFarWindowStrictMeanSquareLowerBound.toNaturalPointWitness
#print axioms PrimeNumberTheorem.HasFarWindowStrictMeanSquareLowerBound.normalized_to_mul_amplitude
#print axioms PrimeNumberTheorem.actualNaturalRunningMaximumMovingPackageWitness_of_windowMeanSquare
#print axioms PrimeNumberTheorem.actualNaturalRunningMaximumBoundaryCanonicalGoodHeightUnifiedUpperSignAlternative_of_windowMeanSquare_reciprocal
