import PrimeNumberTheorem.ZeroDensityLayerBudgetThirdOrderExplicitFormulaResidues

#check PrimeNumberTheorem.ExplicitFormulaResidues.exists_boundaryRectIntegral_thirdOrderExplicitFormulaIntegrand_eq_residue_sum
