import PrimeNumberTheorem.ZeroDensityLayerBudgetActualThetaOnlyUnifiedTransfer

namespace PrimeNumberTheorem

#check exists_thetaOnlyAutomaticGoodHeight_globalRealPartBoundNaturalTargetTransfer

end PrimeNumberTheorem
