import PrimeNumberTheorem.ZeroDensityLayerBudgetActualDynamicCarlsonAutomaticCount

namespace PrimeNumberTheorem

#check ActualDynamicCarlsonGapFamilyHeightConditions
#check exists_actualDynamicCarlsonGapFamilyCountCertificate
#check exists_constants_tendsto_actualDynamicCarlsonGapFamilyMass_zero
#check exists_constants_tendsto_actualDynamicCarlsonGapStripUnion_mass_zero

end PrimeNumberTheorem
