import PrimeNumberTheorem.ZeroDensityLayerBudgetCubicKernelNearOne

#check PrimeNumberTheorem.ExplicitFormulaResidues.cubicKernelDifferenceQuotient
#check PrimeNumberTheorem.ExplicitFormulaResidues.cubicKernelMultiplier_eq_differenceQuotient_sq
#check PrimeNumberTheorem.ExplicitFormulaResidues.norm_cubicKernelDifferenceQuotient_sub_one_le
#check PrimeNumberTheorem.ExplicitFormulaResidues.norm_cubicKernelMultiplier_sub_one_le_three_mul
#check PrimeNumberTheorem.ExplicitFormulaResidues.norm_multiplier_bounds_of_sub_one_le
#check PrimeNumberTheorem.ExplicitFormulaResidues.norm_cubicZeroResidueSecondDifference_correctScale_bounds
#check PrimeNumberTheorem.ExplicitFormulaResidues.exists_pos_forall_mem_norm_cubicKernelMultiplier_sub_one_lt
