import PrimeNumberTheorem.ZeroDensityLayerBudgetActualSelectedHeightMovingCarlsonPositiveTailTransfer

#print axioms PrimeNumberTheorem.actualSelectedHeightCriticalHalf_high_subset_movingMiddle_union_strip
#print axioms PrimeNumberTheorem.actualSelectedHeightCriticalHalf_highLayerNorm_le_movingMasses
#print axioms PrimeNumberTheorem.dynamicPositivePNTTailNorm_le_selectedCriticalHalf_add_movingMasses
#print axioms PrimeNumberTheorem.tendsto_dynamicPositivePNTTailNorm_of_selectedHeightMovingCarlson
