import PrimeNumberTheorem.ZeroDensityLayerBudgetCubicKernelLocalFactorLowerBound

#check PrimeNumberTheorem.tendsto_cubicKernelSecondDifferenceFactor_one
#check PrimeNumberTheorem.eventually_norm_cubicKernelSecondDifferenceFactor_gt_half
#check PrimeNumberTheorem.eventually_secondLogForwardDifference_exp_div_cube_norm_gt_half
