import PrimeNumberTheorem.ZeroDensityLayerBudgetPNTFormulaRemainderDecay

#print axioms PrimeNumberTheorem.cofinalPNTFormulaRemainderBound_zero_relative_le_majorant
#print axioms PrimeNumberTheorem.cofinalPNTZeroDepthRelativeRemainderMajorant_tendsto
#print axioms PrimeNumberTheorem.cofinalPNTFormulaRemainderBound_zero_relative_tendsto
