import PrimeNumberTheorem.ZeroDensityLayerBudgetStrictMarginExponentialCoreRateGap

#print axioms PrimeNumberTheorem.actualStrictMarginGridFullPNTErrorMajorant_eq_core_add_residual
#print axioms PrimeNumberTheorem.tendsto_actualStrictMarginGridExponentialCore_div_amplitude_zero
#print axioms PrimeNumberTheorem.tendsto_actualStrictMarginGridFullPNTErrorMajorant_div_amplitude_zero
