import PrimeNumberTheorem.ZeroDensityLayerBudgetPintzCarlsonTargetLayer

/-!
# Exponent criterion for target-amplitude Pintz--Carlson layers

After normalizing a strip at real part `sigma` by a target zero at real part
`beta`, the kernel contributes the power gap `sigma - beta`.  If the
zero-density count at the chosen height contributes exponent `d`, the absolute
Pintz--Carlson budget has total exponent

`d + sigma - beta`.

This file proves the exact arithmetic threshold for decay and the feasibility
criterion for a polynomial lower truncation height.  It does not assert that a
particular Carlson theorem supplies any chosen exponent.
-/

namespace PrimeNumberTheorem

/-- Total power exponent of a target-normalized absolute strip budget. -/
def targetAmplitudePintzCarlsonExponent
    (beta sigma densityExponent : ℝ) : ℝ :=
  densityExponent + sigma - beta

/-- A target-normalized strip budget decays at the power-exponent level exactly
when the density cost is smaller than the real-part gap to the target. -/
theorem targetAmplitudePintzCarlsonExponent_neg_iff
    (beta sigma densityExponent : ℝ) :
    targetAmplitudePintzCarlsonExponent beta sigma densityExponent < 0 ↔
      densityExponent < beta - sigma := by
  unfold targetAmplitudePintzCarlsonExponent
  constructor <;> intro h <;> linarith

/-- If the density cost is nonnegative and the strip reaches the target real
part, its absolute Pintz--Carlson exponent cannot be negative. -/
theorem targetAmplitudePintzCarlsonExponent_nonneg_of_target_le_strip
    {beta sigma densityExponent : ℝ}
    (hdensity : 0 ≤ densityExponent) (hbetaSigma : beta ≤ sigma) :
    0 ≤ targetAmplitudePintzCarlsonExponent beta sigma densityExponent := by
  unfold targetAmplitudePintzCarlsonExponent
  linarith

/-- Consequently, pure count-times-absolute-kernel control cannot make a strip
on or to the right of the target line target-amplitude negligible at the power
level.  Such zeros must be moved into the main cluster or treated by
cancellation rather than this absolute majorant. -/
theorem not_targetAmplitudePintzCarlsonExponent_neg_of_target_le_strip
    {beta sigma densityExponent : ℝ}
    (hdensity : 0 ≤ densityExponent) (hbetaSigma : beta ≤ sigma) :
    ¬ targetAmplitudePintzCarlsonExponent beta sigma densityExponent < 0 :=
  not_lt_of_ge
    (targetAmplitudePintzCarlsonExponent_nonneg_of_target_le_strip
      hdensity hbetaSigma)

/-- Density exponent generated by a polynomial truncation height `T = x^alpha`
when a density theorem has height slope `A * (1 - sigma)`. -/
def carlsonPolynomialHeightDensityExponent
    (alpha A sigma : ℝ) : ℝ :=
  alpha * (A * (1 - sigma))

/-- For a polynomial height, target-layer exponent decay is exactly the
inequality `alpha * A * (1 - sigma) < beta - sigma`. -/
theorem polynomialHeight_targetAmplitudeExponent_neg_iff
    (beta sigma alpha A : ℝ) :
    targetAmplitudePintzCarlsonExponent beta sigma
        (carlsonPolynomialHeightDensityExponent alpha A sigma) < 0 ↔
      alpha * (A * (1 - sigma)) < beta - sigma := by
  exact targetAmplitudePintzCarlsonExponent_neg_iff _ _ _

/-- Suppose the density slope `A * (1 - sigma)` is positive.  There exists a
polynomial height exponent that is simultaneously above the contour threshold
`1 - beta` and below the Carlson strip threshold precisely when the density
cost at the contour threshold is smaller than the strip's real-part gap. -/
theorem exists_polynomialHeight_targetAmplitude_decay_iff
    {beta sigma A : ℝ} (hslope : 0 < A * (1 - sigma)) :
    (∃ alpha : ℝ,
        1 - beta < alpha ∧
        targetAmplitudePintzCarlsonExponent beta sigma
          (carlsonPolynomialHeightDensityExponent alpha A sigma) < 0) ↔
      (1 - beta) * (A * (1 - sigma)) < beta - sigma := by
  let slope : ℝ := A * (1 - sigma)
  constructor
  · rintro ⟨alpha, hcontour, hlayer⟩
    have hlayer' : alpha * slope < beta - sigma := by
      simpa [slope, carlsonPolynomialHeightDensityExponent] using
        (targetAmplitudePintzCarlsonExponent_neg_iff
          beta sigma
          (carlsonPolynomialHeightDensityExponent alpha A sigma)).mp hlayer
    have hthreshold :
        (1 - beta) * slope < alpha * slope :=
      mul_lt_mul_of_pos_right hcontour (by simpa [slope] using hslope)
    simpa [slope] using lt_trans hthreshold hlayer'
  · intro hfeasible
    have hslope' : 0 < slope := by
      simpa [slope] using hslope
    have hlowerUpper :
        1 - beta < (beta - sigma) / slope := by
      exact (lt_div_iff₀ hslope').2 (by simpa [slope] using hfeasible)
    let alpha : ℝ :=
      ((1 - beta) + (beta - sigma) / slope) / 2
    have hcontour : 1 - beta < alpha := by
      dsimp [alpha]
      linarith
    have halphaUpper : alpha < (beta - sigma) / slope := by
      dsimp [alpha]
      linarith
    have hlayerSlope : alpha * slope < beta - sigma :=
      (lt_div_iff₀ hslope').mp halphaUpper
    refine ⟨alpha, hcontour, ?_⟩
    rw [targetAmplitudePintzCarlsonExponent_neg_iff]
    simpa [carlsonPolynomialHeightDensityExponent, slope] using hlayerSlope

end PrimeNumberTheorem
