import PrimeNumberTheorem.ZeroDensityLayerBudgetJointTwoHeightNearOptimalTruncationParameters

namespace PrimeNumberTheorem

#check exists_jointTwoHeightStrictMargins_of_outerExponentFeasible
#check exists_jointTwoHeightNearOptimalTruncationParameters

end PrimeNumberTheorem
