import PrimeNumberTheorem.ZeroDensityLayerBudgetActualCarlsonSeedWitnessHalfThresholdSignedPNTTransfer

namespace PrimeNumberTheorem

#check exists_seedWitness_actualCarlsonHalfThresholdSignedPNTTransfer

end PrimeNumberTheorem
