import PrimeNumberTheorem.ZeroDensityLayerBudgetActualTargetAmplitudeTwoHeightStrip

namespace PrimeNumberTheorem

#check rpow_stripEndpoint_div_targetZeroPowerAmplitude
#check actualCarlsonTargetTwoHeightLowBudget
#check actualCarlsonTargetTwoHeightHighBudget
#check actualCarlsonTargetTwoHeightLowBudget_eq_shifted
#check actualCarlsonTargetTwoHeightHighBudget_eq_shifted
#check tendsto_actualCarlsonTargetTwoHeightLowBudget
#check tendsto_actualCarlsonTargetTwoHeightHighBudget
#check actualPositiveCarlsonStripTargetAmplitudeMass
#check
  actualPositiveCarlsonStripTargetAmplitudeMass_le_twoHeightBudget
#check
  tendsto_actualPositiveCarlsonStripTargetAmplitudeMass_twoHeight
#check
  exists_outerHeight_tendsto_actualPositiveCarlsonStripTargetAmplitudeMass
#check
  exists_positiveWidth_actualCarlsonStripTargetAmplitudeMass_tendsto_zero

end PrimeNumberTheorem
