import PrimeNumberTheorem.ZeroDensityLayerBudgetCubicKernelNearOne

#print axioms PrimeNumberTheorem.ExplicitFormulaResidues.norm_cubicKernelDifferenceQuotient_sub_one_le
#print axioms PrimeNumberTheorem.ExplicitFormulaResidues.norm_cubicKernelMultiplier_sub_one_le_three_mul
#print axioms PrimeNumberTheorem.ExplicitFormulaResidues.norm_cubicZeroResidueSecondDifference_correctScale_bounds
#print axioms PrimeNumberTheorem.ExplicitFormulaResidues.exists_pos_forall_mem_norm_cubicKernelMultiplier_sub_one_lt
