import PrimeNumberTheorem.ZeroDensityLayerBudgetActualSelectedHeightStripProfileMonotoneRoundingTransfer

/-!
# Finite parameter grids for zero-loss unified transfer

This module turns finite `sigma` and `tau` value sets into an actual finite
family of fixed-cardinality strip profiles.  A one-sided rounded parameter
choice is automatically a member of that family and monotonically covers
the benchmark profile.  The finite optimizer can therefore be run without
an externally supplied candidate family or nonemptiness certificate.
-/

namespace PrimeNumberTheorem

/-- A nonempty finite parameter grid for fixed-cardinality strip profiles.
The `sigma` values carry the Carlson half-strip admissibility conditions. -/
structure ActualSelectedHeightFiniteStripGrid where
  stripCount : ℕ
  sigmaValues : Finset ℝ
  tauValues : Finset ℝ
  sigmaValues_nonempty : sigmaValues.Nonempty
  tauValues_nonempty : tauValues.Nonempty
  sigma_half : ∀ sigma ∈ sigmaValues, 1 / 2 < sigma
  sigma_one : ∀ sigma ∈ sigmaValues, sigma < 1

/-- Build a profile with the grid's fixed strip count. -/
def ActualSelectedHeightFiniteStripGrid.profile
    (grid : ActualSelectedHeightFiniteStripGrid)
    (sigma tau : Fin (grid.stripCount + 1) → ℝ) :
    ActualSelectedHeightFiniteStripProfile :=
  ⟨grid.stripCount, sigma, tau⟩

@[simp] theorem ActualSelectedHeightFiniteStripGrid.profile_stripCount
    (grid : ActualSelectedHeightFiniteStripGrid)
    (sigma tau : Fin (grid.stripCount + 1) → ℝ) :
    (grid.profile sigma tau).stripCount = grid.stripCount :=
  rfl

@[simp] theorem ActualSelectedHeightFiniteStripGrid.profile_sigma
    (grid : ActualSelectedHeightFiniteStripGrid)
    (sigma tau : Fin (grid.stripCount + 1) → ℝ) :
    (grid.profile sigma tau).sigma = sigma :=
  rfl

@[simp] theorem ActualSelectedHeightFiniteStripGrid.profile_tau
    (grid : ActualSelectedHeightFiniteStripGrid)
    (sigma tau : Fin (grid.stripCount + 1) → ℝ) :
    (grid.profile sigma tau).tau = tau :=
  rfl

/-- All profiles whose coordinate values lie in the two finite grids.
Finiteness follows by enumerating functions into the finite subtypes. -/
noncomputable def ActualSelectedHeightFiniteStripGrid.profiles
    (grid : ActualSelectedHeightFiniteStripGrid) :
    Finset ActualSelectedHeightFiniteStripProfile := by
  classical
  exact Finset.image
    (fun parameters :
      (Fin (grid.stripCount + 1) → {sigma // sigma ∈ grid.sigmaValues}) ×
        (Fin (grid.stripCount + 1) → {tau // tau ∈ grid.tauValues}) =>
      grid.profile
        (fun i => parameters.1 i)
        (fun i => parameters.2 i))
    Finset.univ

/-- Membership in the finite profile family is exactly coordinatewise grid
membership. -/
theorem ActualSelectedHeightFiniteStripGrid.profile_mem_profiles_iff
    (grid : ActualSelectedHeightFiniteStripGrid)
    (sigma tau : Fin (grid.stripCount + 1) → ℝ) :
    grid.profile sigma tau ∈ grid.profiles ↔
      (∀ i, sigma i ∈ grid.sigmaValues) ∧
        ∀ i, tau i ∈ grid.tauValues := by
  classical
  constructor
  · intro hprofile
    rw [ActualSelectedHeightFiniteStripGrid.profiles] at hprofile
    obtain ⟨parameters, -, hparameters⟩ :=
      Finset.mem_image.mp hprofile
    cases hparameters
    constructor
    · intro i
      exact (parameters.1 i).property
    · intro i
      exact (parameters.2 i).property
  · rintro ⟨hsigma, htau⟩
    let parameters :
        (Fin (grid.stripCount + 1) →
            {value // value ∈ grid.sigmaValues}) ×
          (Fin (grid.stripCount + 1) →
            {value // value ∈ grid.tauValues}) :=
      (fun i => ⟨sigma i, hsigma i⟩,
        fun i => ⟨tau i, htau i⟩)
    rw [ActualSelectedHeightFiniteStripGrid.profiles]
    apply Finset.mem_image.mpr
    exact ⟨parameters, Finset.mem_univ _, rfl⟩

/-- Every nonempty parameter grid generates a nonempty finite profile
family. -/
theorem ActualSelectedHeightFiniteStripGrid.profiles_nonempty
    (grid : ActualSelectedHeightFiniteStripGrid) :
    grid.profiles.Nonempty := by
  obtain ⟨sigma, hsigma⟩ := grid.sigmaValues_nonempty
  obtain ⟨tau, htau⟩ := grid.tauValues_nonempty
  refine
    ⟨grid.profile (fun _ => sigma) (fun _ => tau), ?_⟩
  exact
    (grid.profile_mem_profiles_iff
      (fun _ => sigma) (fun _ => tau)).2
      ⟨fun _ => hsigma, fun _ => htau⟩

/-- Every profile generated by the grid lies strictly to the right of the
critical half-line. -/
theorem ActualSelectedHeightFiniteStripGrid.sigma_half_of_mem_profiles
    (grid : ActualSelectedHeightFiniteStripGrid)
    {profile : ActualSelectedHeightFiniteStripProfile}
    (hprofile : profile ∈ grid.profiles) :
    ∀ i, 1 / 2 < profile.sigma i := by
  classical
  rw [ActualSelectedHeightFiniteStripGrid.profiles] at hprofile
  obtain ⟨parameters, -, rfl⟩ := Finset.mem_image.mp hprofile
  intro i
  exact grid.sigma_half _ (parameters.1 i).property

/-- Every profile generated by the grid has strip endpoints below one. -/
theorem ActualSelectedHeightFiniteStripGrid.sigma_one_of_mem_profiles
    (grid : ActualSelectedHeightFiniteStripGrid)
    {profile : ActualSelectedHeightFiniteStripProfile}
    (hprofile : profile ∈ grid.profiles) :
    ∀ i, profile.sigma i < 1 := by
  classical
  rw [ActualSelectedHeightFiniteStripGrid.profiles] at hprofile
  obtain ⟨parameters, -, rfl⟩ := Finset.mem_image.mp hprofile
  intro i
  exact grid.sigma_one _ (parameters.1 i).property

/-- Coordinatewise one-sided rounding inside a grid supplies both candidate
membership and monotone coverage of the benchmark profile. -/
theorem
    ActualSelectedHeightFiniteStripGrid.roundedProfile_mem_and_covers
    (grid : ActualSelectedHeightFiniteStripGrid)
    (benchmarkSigma benchmarkTau roundedSigma roundedTau :
      Fin (grid.stripCount + 1) → ℝ)
    (hroundedSigmaMem : ∀ i, roundedSigma i ∈ grid.sigmaValues)
    (hroundedTauMem : ∀ i, roundedTau i ∈ grid.tauValues)
    (hsigma : ∀ i, benchmarkSigma i ≤ roundedSigma i)
    (htau : ∀ i, roundedTau i ≤ benchmarkTau i) :
    grid.profile roundedSigma roundedTau ∈ grid.profiles ∧
      (grid.profile benchmarkSigma benchmarkTau).MonotoneRoundingCovers
        (grid.profile roundedSigma roundedTau) := by
  constructor
  · exact
      (grid.profile_mem_profiles_iff roundedSigma roundedTau).2
        ⟨hroundedSigmaMem, hroundedTauMem⟩
  · intro j
    exact ⟨j, hsigma j, htau j⟩

/-- A concrete finite parameter grid plus one-sided rounding runs the
zero-loss optimal unified transfer.  The candidate family, its nonemptiness,
candidate membership, and all candidate `sigma` admissibility facts are
generated internally.

The target-cluster witness `hmain` remains an explicit hypothesis. -/
theorem unified_actualBalancedHeight_of_finiteMonotoneStripGrid
    (threshold : ℝ) (hhalf : 1 / 2 < threshold) (hlt : threshold < 1)
    {beta : ℝ} (hbeta : 0 < beta) (hbetaOne : beta < 1)
    (grid : ActualSelectedHeightFiniteStripGrid)
    (benchmarkSigma benchmarkTau roundedSigma roundedTau :
      Fin (grid.stripCount + 1) → ℝ)
    (hroundedSigmaMem : ∀ i, roundedSigma i ∈ grid.sigmaValues)
    (hroundedTauMem : ∀ i, roundedTau i ∈ grid.tauValues)
    (hbenchmarkHalf : ∀ i, 1 / 2 < benchmarkSigma i)
    (hbenchmarkTau : ∀ i, benchmarkTau i ≤ beta)
    (hsigmaRounding : ∀ i, benchmarkSigma i ≤ roundedSigma i)
    (htauRounding : ∀ i, roundedTau i ≤ benchmarkTau i)
    (hbenchmarkMargin :
      0 <
        (grid.profile benchmarkSigma benchmarkTau).optimalRobustMargin beta)
    (selection : UniformNaturalPointGoodHeightSelection)
    {S : Finset ℂ}
    (input :
      (x : ℝ) →
        PositiveZeroOutsideClusterBucketInput
          (actualSelectedHeightFiniteStripBalancedHeight
            beta
            (optimalActualSelectedHeightFiniteStripProfile
              beta grid.profiles grid.profiles_nonempty).sigma
            (optimalActualSelectedHeightFiniteStripProfile
              beta grid.profiles grid.profiles_nonempty).tau
            selection x)
          S
          ((optimalActualSelectedHeightFiniteStripProfile
              beta grid.profiles grid.profiles_nonempty).stripCount + 1))
    (kappa :
      Fin ((optimalActualSelectedHeightFiniteStripProfile
        beta grid.profiles grid.profiles_nonempty).stripCount + 1) → ℝ)
    (hS : IsConjugationInvariantCluster S)
    (hfixedSigma :
      ∀ i x,
        (input x).sigma i =
          (optimalActualSelectedHeightFiniteStripProfile
            beta grid.profiles grid.profiles_nonempty).sigma i)
    (hkappa : ∀ i, 0 < kappa i)
    (hnorm :
      ∀ i x, ∀ rho ∈ (input x).layer i, kappa i ≤ ‖rho‖)
    (hre :
      ∀ i x, ∀ rho ∈ (input x).layer i,
        rho.re ≤
          (optimalActualSelectedHeightFiniteStripProfile
            beta grid.profiles grid.profiles_nonempty).tau i)
    (hreal :
      ∀ rho ∈
        realOrdinateNontrivialZerosOutsideClusterFinset 0 S,
        rho.re < beta)
    (hmain :
      HasFarNaturalPointTargetAmplitudeWitness
        (fun m : ℕ =>
          dynamicVisibleClusterPNTMain
            (actualSelectedHeightFiniteStripBalancedHeight
              beta
              (optimalActualSelectedHeightFiniteStripProfile
                beta grid.profiles grid.profiles_nonempty).sigma
              (optimalActualSelectedHeightFiniteStripProfile
                beta grid.profiles grid.profiles_nonempty).tau
              selection)
            S (m : ℝ))
        (fun m : ℕ => targetZeroPowerAmplitude beta (m : ℝ))) :
    let benchmark := grid.profile benchmarkSigma benchmarkTau
    let chosen :=
      optimalActualSelectedHeightFiniteStripProfile
        beta grid.profiles grid.profiles_nonempty
    (chosen ∈ grid.profiles ∧
        (∀ profile ∈ grid.profiles,
          profile.optimalRobustMargin beta ≤
            chosen.optimalRobustMargin beta) ∧
        chosen.HasUnifiedTransferResult beta) ∧
      benchmark.balancedExponent beta ≤
        chosen.balancedExponent beta ∧
      benchmark.optimalRobustMargin beta ≤
        chosen.optimalRobustMargin beta ∧
      ∀ x : ℝ, 1 ≤ x →
        benchmark.balancedPolynomialScale beta x ≤
          chosen.balancedPolynomialScale beta x := by
  let benchmark := grid.profile benchmarkSigma benchmarkTau
  let candidate := grid.profile roundedSigma roundedTau
  have hrounded :
      candidate ∈ grid.profiles ∧
        benchmark.MonotoneRoundingCovers candidate := by
    simpa [benchmark, candidate] using
      grid.roundedProfile_mem_and_covers
        benchmarkSigma benchmarkTau roundedSigma roundedTau
        hroundedSigmaMem hroundedTauMem hsigmaRounding htauRounding
  have hsigma :
      ∀ profile ∈ grid.profiles, ∀ i, 1 / 2 < profile.sigma i :=
    fun _ hprofile => grid.sigma_half_of_mem_profiles hprofile
  have hsigmaOne :
      ∀ profile ∈ grid.profiles, ∀ i, profile.sigma i < 1 :=
    fun _ hprofile => grid.sigma_one_of_mem_profiles hprofile
  have hbenchmarkHalf' : ∀ i, 1 / 2 < benchmark.sigma i := by
    simpa [benchmark] using hbenchmarkHalf
  have hbenchmarkTau' : ∀ i, benchmark.tau i ≤ beta := by
    simpa [benchmark] using hbenchmarkTau
  have hbenchmarkMargin' :
      0 < benchmark.optimalRobustMargin beta := by
    simpa [benchmark] using hbenchmarkMargin
  simpa [benchmark] using
    unified_actualBalancedHeight_of_monotoneRoundedStripProfile
      threshold hhalf hlt hbeta hbetaOne
      grid.profiles grid.profiles_nonempty benchmark hrounded.1
      hsigma hsigmaOne hbenchmarkHalf' hbenchmarkTau'
      hrounded.2 hbenchmarkMargin' selection input kappa hS
      hfixedSigma hkappa hnorm hre hreal hmain

end PrimeNumberTheorem
