import PrimeNumberTheorem.ZeroDensityLayerBudgetCarlsonMovingHeightConditions

#print axioms PrimeNumberTheorem.tendsto_movingPolynomialHeight_atTop
#print axioms PrimeNumberTheorem.tendsto_log_movingPolynomialHeight_atTop
#print axioms PrimeNumberTheorem.eventually_carlsonPointwiseHeightConditions_of_tendsto
#print axioms PrimeNumberTheorem.eventually_balancedCarlsonPointwiseHeightConditions
#print axioms PrimeNumberTheorem.eventually_fixedCarlsonPointwiseHeightConditions
