import PrimeNumberTheorem.ZeroDensityLayerBudgetVariableBoundaryRealTailDecay

#check PrimeNumberTheorem.variableBoundaryRealOrdinateFixedMajorant
#check PrimeNumberTheorem.variableBoundaryRealOrdinateFixedMajorant_tendsto_zero
#check PrimeNumberTheorem.variableBoundaryRealNormalizedSum_le_fixedMajorant
#check PrimeNumberTheorem.variableBoundaryRealNormalizedSum_tendsto_zero_of_fixed_gap
#check PrimeNumberTheorem.actualVariableBoundaryFullTailExplicitFormulaResidual_targetAmplitudeNegligible_of_realGap
