import PrimeNumberTheorem.ZeroDensityLayerBudgetKernelOrderReciprocalHeightCriterion

#print axioms PrimeNumberTheorem.kernelOrderReciprocalHeightRemainderRatio_eq
#print axioms PrimeNumberTheorem.tendsto_kernelOrderReciprocalHeightRemainderRatio_zero
#print axioms PrimeNumberTheorem.tendsto_quadraticKernelReciprocalHeightRemainderRatio_zero
#print axioms PrimeNumberTheorem.quadraticKernelReciprocalHeightRemainderRatio_eq
#print axioms PrimeNumberTheorem.linearKernelReciprocalHeightRemainderRatio_eq
