import PrimeNumberTheorem.ZeroDensityLayerBudgetGoodHeightDesmoothedCentralContourContract

open PrimeNumberTheorem ExplicitFormulaResidues

#print axioms two_pi_mul_goodHeightCubicWidth
#print axioms cubicBottomContourPoint_goodHeightCubicWidth
#print axioms cubicTopContourPoint_goodHeightCubicWidth
#print axioms exists_goodHeight_Icc_norm_desmoothedCubicCentralContourIntegrals_le
#print axioms exists_goodHeight_Icc_norm_desmoothedCubicCentralHorizontalSum_le
