import PrimeNumberTheorem.ZeroDensityLayerBudgetDyadicSquareMultiplicityCapacityContract

open PrimeNumberTheorem

#print axioms squareMultiplicityCapacity_le_max_mul_linearMultiplicityCapacity
#print axioms squareMultiplicityCapacity_sdiff_le
#print axioms ExplicitFormulaAux.exists_analyticOrderNatAt_riemannZeta_le_log_im_of_nontrivialZero
#print axioms actualCarlsonDyadicStripLinearMultiplicityCapacity_le_count
#print axioms actualCarlsonDyadicStripLinearReciprocalSquareCapacity_le_count_div_sq
#print axioms exists_actualCarlsonDyadicStrip_maxMultiplicity_le_log
#print axioms exists_actualCarlsonDyadicStripSquareReciprocalCapacity_le_count
#print axioms exists_actualCarlsonDyadicStripSquareReciprocalCapacityExcluding_le_count
#print axioms pntCarlsonClassicalDensityExponent_sub_two_lt_zero
