import PrimeNumberTheorem.ZeroDensityLayerBudgetInnerZeroFreeHorizontalBudgetContract

open PrimeNumberTheorem ExplicitFormulaResidues

#print axioms norm_logDeriv_cubicBottomContourPoint_le_innerZeroFreeHorizontalLogBudget
#print axioms norm_logDeriv_cubicTopContourPoint_le_innerZeroFreeHorizontalLogBudget
#print axioms norm_desmoothedCubicBottomInnerZeroFreeContourIntegral_le
#print axioms norm_desmoothedCubicTopInnerZeroFreeContourIntegral_le
#print axioms exists_actual_innerZeroFreeHorizontalContourBudgets
