import PrimeNumberTheorem.ZeroDensityLayerBudgetActualDynamicBoundaryReciprocalTransfer

#print axioms PrimeNumberTheorem.actualDynamicBoundarySignedComplement_targetAmplitudeNegligible_reciprocal
#print axioms PrimeNumberTheorem.actualDynamicBoundaryExplicitFormulaResidual_targetAmplitudeNegligible_reciprocal
#print axioms PrimeNumberTheorem.actualDynamicBoundaryAutomaticPNTUpperTransfer_reciprocal
#print axioms PrimeNumberTheorem.actualDynamicBoundaryAutomaticPNTWitnessTransfer_reciprocal
#print axioms PrimeNumberTheorem.actualDynamicBoundaryAutomaticPNTBidirectionalTransfer_reciprocal
#print axioms PrimeNumberTheorem.actualDynamicBoundaryFullyAutomaticPNTUpperTransfer_reciprocal
#print axioms PrimeNumberTheorem.actualDynamicBoundaryFullyAutomaticPNTBidirectionalTransfer_reciprocal
