import PrimeNumberTheorem.ZeroDensityLayerBudgetTargetAmplitudeTwoHeightExponent

namespace PrimeNumberTheorem

#check targetAmplitudeCarlsonTwoHeightLowExponent
#check targetAmplitudeCarlsonTwoHeightHighExponent
#check targetAmplitudeCarlsonTwoHeightBalancedSlope
#check targetAmplitudeCarlsonTwoHeightBalancedExponent
#check targetAmplitudeCarlsonTwoHeightBalancedSlope_pos
#check targetAmplitudeCarlsonTwoHeightLowExponent_balanced
#check targetAmplitudeCarlsonTwoHeightHighExponent_balanced
#check
  targetAmplitudeCarlsonTwoHeightBalancedExponent_lt_singleHeight
#check exists_targetAmplitudeCarlsonTwoHeightBalancedDecay_iff
#check exists_targetAmplitudeCarlsonTwoHeightStrictMargins
#check carlsonTwoHeightDensityExponent_lt_one
#check targetAmplitudeCarlsonTwoHeightBalancedSlope_lt_half
#check targetAmplitudeCarlsonTwoHeightCanonicalThreshold
#check targetAmplitudeCarlsonTwoHeightCanonicalThreshold_spec
#check targetAmplitudeCarlsonTwoHeightCanonical_feasible
#check exists_targetAmplitudeCarlsonTwoHeightCanonicalStrictMargins

end PrimeNumberTheorem
