import PrimeNumberTheorem.ZeroDensityLayerBudgetAutomaticOptimalHeightCarlsonBridge

#print axioms PrimeNumberTheorem.eventually_actualStrictMarginOptimalCandidateHeight_eq_selectedClassical
#print axioms PrimeNumberTheorem.eventually_dynamicFullPNTZeroTailNorm_actualStrictMarginOptimal_eq_selectedClassical
#print axioms PrimeNumberTheorem.isSelectedHeightDynamicZeroFree_actualStrictMarginOptimal_of_selectedClassical
