import PrimeNumberTheorem.ZeroDensityLayerBudgetPNTHybridUpper

#check PrimeNumberTheorem.naturalPointPintzPNTHybridCeilingUpperBudget
#check PrimeNumberTheorem.naturalPointPintzPNTHybridCeilingRelativeUpperBudget
#check PrimeNumberTheorem.naturalPointPintzPNTCeilingDensityUpperBudget_le_hybrid
#check PrimeNumberTheorem.naturalPointPintzPNTCeilingDensityRelativeUpperBudget_le_hybrid
#check PrimeNumberTheorem.exists_naturalPoint_pintzCarlson_goodHeight_hybrid_PNT_upper
