import PrimeNumberTheorem.ZeroDensityLayerBudgetCommonPoleCubicTripleTransfer

#check PrimeNumberTheorem.ExplicitFormulaResidues.cubicExplicitFormulaApproximant
#check PrimeNumberTheorem.ExplicitFormulaResidues.cubicPerronTruncationBudget
#check PrimeNumberTheorem.ExplicitFormulaResidues.mem_cubic_closedRectangle_of_strict
#check PrimeNumberTheorem.ExplicitFormulaResidues.cubicPoleFinset_eq_of_complete
#check PrimeNumberTheorem.ExplicitFormulaResidues.exists_commonPole_cubicApproximants_chebyshevPsi_bounds
