import PrimeNumberTheorem.ZeroDensityLayerBudgetAutomaticBestOfDirectAndCarlsonFullPNT

#print axioms PrimeNumberTheorem.tendsto_bestOfDirectAndCarlsonPNTErrorMajorant_zero
#print axioms PrimeNumberTheorem.eventually_abs_relativeChebyshevPsi0Error_le_bestOfMajorants
#print axioms PrimeNumberTheorem.exists_automaticBestOfDirectAndCarlsonFullPNT
