import PrimeNumberTheorem.ZeroDensityLayerBudgetActualCarlsonTargetLineCaptureBudgetSufficiency

namespace PrimeNumberTheorem

#check positiveCoefficientMass_eq_capturedBoundaryMass_of_targetLine
#check coefficientMass_eq_two_mul_capturedBoundaryMass_of_targetLine
#check exists_targetLine_actualCarlsonFiniteSeedCanonicalBudgets_of_seedOutside_lt_half

end PrimeNumberTheorem
