import PrimeNumberTheorem.ZeroDensityLayerBudgetActualCubicTwoHeightL2TailContract

open PrimeNumberTheorem

#print axioms actualCubicDyadicStripSquareCapacityExcluding_le
#print axioms actualCubicDyadicStripSquareCapacityExcluding_le_reciprocal
#print axioms exists_actualCubicDyadicStripSquareCapacityExcluding_le_count
#print axioms cubicDyadicCountProduct_eq_sixthPower
#print axioms pntCarlsonClassicalDensityExponent_sub_six_le_neg_five
#print axioms cubicCarlsonL2BlockExponent_lt_zero
#print axioms exists_actualCubicTwoHeightSquareTailCapacity_le
#print axioms exists_jointTwoHeightTargetAmplitudeParameters_with_cubicL2
