import PrimeNumberTheorem.ZeroDensityLayerBudgetQuadraticHingeSecondDifference

#print axioms PrimeNumberTheorem.quadraticHingeSecondDifferenceNumerator_bounds
#print axioms PrimeNumberTheorem.quadraticHingeSecondDifferenceNumerator_eq_sq_of_nonneg
#print axioms PrimeNumberTheorem.quadraticHingeSecondDifferenceNumerator_eq_zero_of_add_two_mul_nonpos
#print axioms PrimeNumberTheorem.normalizedQuadraticHingeSecondDifference_mem_unitInterval
#print axioms PrimeNumberTheorem.normalizedQuadraticHingeSecondDifference_eq_one_of_nonneg
#print axioms PrimeNumberTheorem.normalizedQuadraticHingeSecondDifference_eq_zero_of_add_two_mul_nonpos
