import PrimeNumberTheorem.ZeroDensityLayerBudgetActualMovingClusterComplementMajorant

namespace PrimeNumberTheorem

#check canonicalMovingSelectedLayer_subset_emptyPolynomialLayer
#check canonicalMovingSelectedLowLayerNorm_le_emptyPolynomialTwoHeightMass
#check canonicalMovingSelectedHighLayer_subset_polynomialCarlsonStrip
#check movingSelectedPositiveOutsideClusterPNTTailNorm_le
#check selectedMovingPositiveOutsideClusterTail_targetAmplitudeNegligible
#check movingRightEdgeRealOrdinateOutsideTailNorm_eq_zero
#check movingRightEdgeFullOutsideClusterPNTZeroTailNorm
#check selectedMovingRightEdgeFullOutsideClusterTail_targetAmplitudeNegligible
#check selectedMovingRightEdgeOutsideClusterComplement_targetAmplitudeNegligible

end PrimeNumberTheorem
