import PrimeNumberTheorem.ZeroDensityLayerBudgetCubicExplicitFormula

#check PrimeNumberTheorem.ExplicitFormulaResidues.thirdOrderContourRemainder
#check PrimeNumberTheorem.ExplicitFormulaResidues.exists_scaledRightIntegral_eq_residue_sum_sub_thirdOrderContourRemainder
#check PrimeNumberTheorem.ExplicitFormulaResidues.exists_norm_residue_sum_sub_thirdOrderContourRemainder_sub_secondRieszPsi_le
