import PrimeNumberTheorem.ZeroDensityLayerBudgetPintzCarlsonConcreteUnified

/-!
# Finite adaptive Pintz--Carlson rate grids

This module constructs a dynamic height grid from a finite set of exponential
rates and extracts the rate selected by the finite-grid cost optimizer.
-/

open Filter Topology

namespace PrimeNumberTheorem

/-- Data needed to turn a finite set of positive rates into a Pintz-envelope
dynamic grid. `baseRate` is a least element used for the diverging lower
envelope. -/
structure PintzCarlsonRateGridInput (zeroFree : ℝ → ℝ → Prop) : Type where
  rates : Finset ℝ
  baseRate : ℝ
  baseRate_mem : baseRate ∈ rates
  rates_pos : ∀ k ∈ rates, 0 < k
  baseRate_le : ∀ k ∈ rates, baseRate ≤ k
  eventually_rate_zeroFree :
    ∀ᶠ x in atTop, ∀ k ∈ rates, zeroFree x (pintzCarlsonHeight k x)

/-- Candidate truncation heights generated from all rates at scale `x`. -/
noncomputable def PintzCarlsonRateGridInput.candidates
    {zeroFree : ℝ → ℝ → Prop} (input : PintzCarlsonRateGridInput zeroFree)
    (x : ℝ) : FiniteHeightGrid where
  heights := input.rates.image (fun k => pintzCarlsonHeight k x)
  nonempty := ⟨pintzCarlsonHeight input.baseRate x,
    Finset.mem_image.mpr ⟨input.baseRate, input.baseRate_mem, rfl⟩⟩
  positive := by
    intro T hT
    obtain ⟨k, hk, rfl⟩ := Finset.mem_image.mp hT
    exact pintzCarlsonHeight_pos k x

/-- A finite positive rate grid canonically gives a Pintz-envelope dynamic
height input. -/
noncomputable def PintzCarlsonRateGridInput.toPintzEnvelopeDynamicGridInput
    {zeroFree : ℝ → ℝ → Prop} (input : PintzCarlsonRateGridInput zeroFree) :
    PintzEnvelopeDynamicGridInput zeroFree where
  envelope := fun x => pintzCarlsonHeight input.baseRate x
  candidates := input.candidates
  envelope_tendsto_atTop :=
    tendsto_pintzCarlsonHeight_atTop
      (input.rates_pos input.baseRate input.baseRate_mem)
  envelope_le_candidates := by
    intro x T hT
    obtain ⟨k, hk, rfl⟩ := Finset.mem_image.mp hT
    apply Real.exp_le_exp.mpr
    exact mul_le_mul_of_nonneg_right
      (input.baseRate_le k hk) (Real.sqrt_nonneg _)
  eventually_candidate_zeroFree := by
    filter_upwards [input.eventually_rate_zeroFree] with x hx T hT
    obtain ⟨k, hk, rfl⟩ := Finset.mem_image.mp hT
    exact hx k hk

/-- The optimal height in the induced grid is generated by some rate in the
original finite rate set. -/
theorem PintzCarlsonRateGridInput.exists_rate_optimalHeight_eq
    {zeroFree : ℝ → ℝ → Prop} (input : PintzCarlsonRateGridInput zeroFree)
    (cost : ℝ → ℝ → ℝ) (x : ℝ) :
    ∃ k ∈ input.rates,
      dynamicFiniteGridOptimalHeight cost
          input.toPintzEnvelopeDynamicGridInput.toDynamicFiniteHeightGrid x =
        pintzCarlsonHeight k x := by
  have hmem :=
    dynamicFiniteGridOptimalHeight_mem cost
      input.toPintzEnvelopeDynamicGridInput.toDynamicFiniteHeightGrid x
  obtain ⟨k, hk, heq⟩ := Finset.mem_image.mp hmem
  exact ⟨k, hk, heq.symm⟩

/-- The rate selected by the finite-grid cost optimizer. -/
noncomputable def PintzCarlsonRateGridInput.optimalRate
    {zeroFree : ℝ → ℝ → Prop} (input : PintzCarlsonRateGridInput zeroFree)
    (cost : ℝ → ℝ → ℝ) (x : ℝ) : ℝ :=
  Classical.choose (input.exists_rate_optimalHeight_eq cost x)

theorem PintzCarlsonRateGridInput.optimalRate_mem
    {zeroFree : ℝ → ℝ → Prop} (input : PintzCarlsonRateGridInput zeroFree)
    (cost : ℝ → ℝ → ℝ) (x : ℝ) :
    input.optimalRate cost x ∈ input.rates :=
  (Classical.choose_spec (input.exists_rate_optimalHeight_eq cost x)).1

theorem PintzCarlsonRateGridInput.optimalHeight_eq
    {zeroFree : ℝ → ℝ → Prop} (input : PintzCarlsonRateGridInput zeroFree)
    (cost : ℝ → ℝ → ℝ) (x : ℝ) :
    dynamicFiniteGridOptimalHeight cost
        input.toPintzEnvelopeDynamicGridInput.toDynamicFiniteHeightGrid x =
      pintzCarlsonHeight (input.optimalRate cost x) x :=
  (Classical.choose_spec (input.exists_rate_optimalHeight_eq cost x)).2

end PrimeNumberTheorem
