import PrimeNumberTheorem.ZeroDensityLayerBudgetActualCubicTwoHeightL2Tail

namespace PrimeNumberTheorem

#check actualCubicDyadicStripSquareCapacity
#check actualCubicDyadicStripSquareCapacityExcluding
#check actualCubicDyadicStripSquareCapacityExcluding_le
#check actualCubicDyadicStripSquareCapacityExcluding_le_reciprocal
#check exists_actualCubicDyadicStripSquareCapacityExcluding_le_count
#check cubicDyadicCountProduct_eq_sixthPower
#check cubicCarlsonL2BlockExponent
#check pntCarlsonClassicalDensityExponent_sub_six_le_neg_five
#check pntCarlsonClassicalDensityExponent_half_sub_six_eq_neg_five
#check cubicCarlsonL2BlockExponent_lt_zero
#check actualCubicDyadicCountMajorant
#check actualCubicTwoHeightSquareTailCapacity
#check exists_actualCubicTwoHeightSquareTailCapacity_le
#check exists_jointTwoHeightTargetAmplitudeParameters_with_cubicL2

end PrimeNumberTheorem
