import PrimeNumberTheorem.ZeroDensityLayerBudgetNearOptimalPrescribedHeightMovingWindowUnifiedTransfer

#check PrimeNumberTheorem.nearOptimalPrescribedHeightMovingPackageWitness_of_windowMeanSquare
#check PrimeNumberTheorem.actualNearOptimalPrescribedHeightUnifiedUpperSignAlternative_of_windowMeanSquare_reciprocal
