import PrimeNumberTheorem.ZeroDensityLayerBudgetJointTwoHeightExactSigmaOptimizer

namespace PrimeNumberTheorem

#check carlsonTwoHeightDensityExponent_antitoneOn_half_one
#check targetAmplitudeCarlsonTwoHeightBalancedSlope_antitoneOn_half_one
#check jointTwoHeightSigmaBalancePolynomial
#check continuous_jointTwoHeightSigmaBalancePolynomial
#check IsJointTwoHeightSigmaOptimizer
#check exists_jointTwoHeightSigmaOptimizer
#check jointTwoHeightPrescribedCapOuterExponentCeiling_eq_of_sigmaOptimizer
#check jointTwoHeightPrescribedCapOuterExponentCeiling_le_at_sigmaOptimizer

end PrimeNumberTheorem
