import PrimeNumberTheorem.ZeroDensityLayerBudgetCarlsonKernelAdapter

#print axioms PrimeNumberTheorem.CarlsonKernelMajorantLayerAdapter.toKernelDensityFactorization
#print axioms PrimeNumberTheorem.CarlsonKernelMajorantLayerAdapter.toFiniteDynamicLayerDecay
#print axioms PrimeNumberTheorem.dynamicExplicitFormulaUpper_tendsto_zero_of_carlsonMajorant
#print axioms PrimeNumberTheorem.hasFarNormWitness_add_of_carlsonMajorant
#print axioms PrimeNumberTheorem.hasFarSignedWitnesses_add_of_carlsonMajorant
