import PrimeNumberTheorem.ZeroDensityLayerBudgetActualMovingCarlsonWindowHeightDecay

#check PrimeNumberTheorem.actualSelectedHeightMovingCarlsonStripMass
#check PrimeNumberTheorem.actualPositiveCarlsonStrip_mono_height
#check PrimeNumberTheorem.actualSelectedHeightMovingCarlsonStripMass_le_exact
#check PrimeNumberTheorem.eventually_selectedHeight_le_polynomialHeight_of_unitWindow
#check PrimeNumberTheorem.tendsto_actualSelectedHeightMovingCarlsonStripMass_zero
