import PrimeNumberTheorem.ZeroDensityLayerBudgetPintzKernelAutomatic

#check PrimeNumberTheorem.norm_pntRelativeSimpleZeroKernel_eq_exp_neg_zeroCost
#check PrimeNumberTheorem.norm_pntRelativeSimpleZeroKernel_le_exp_neg_pintzEnvelope
#check PrimeNumberTheorem.PositiveZeroBucketInput.norm_positive_pntRelativeZeroContribution_sum_le_pintz
#check PrimeNumberTheorem.PositiveZeroBucketInput.norm_full_pntRelativeZeroContribution_sum_le_pintz
