import PrimeNumberTheorem.ZeroDensityLayerBudgetAttainedGlobalRightEdgeRealClosedSeed

#check PrimeNumberTheorem.attainedGlobalRightEdgeRealClosedSeed
#check PrimeNumberTheorem.attainedGlobalRightEdgeRealClosedSeed_spec
