import PrimeNumberTheorem.ZeroDensityLayerBudgetPNTRealOrdinateDecay

#check PrimeNumberTheorem.realOrdinateNontrivialZerosFinset_eq_zeroHeight
#check PrimeNumberTheorem.tendsto_norm_pntRelativeSimpleZeroKernel_atTop
#check PrimeNumberTheorem.tendsto_pntRelativeZeroContribution_atTop
#check PrimeNumberTheorem.tendsto_realOrdinateRelativeZeroResidual_zeroHeight
#check PrimeNumberTheorem.tendsto_realOrdinateRelativeZeroResidual_of_eventually_nonneg
#check PrimeNumberTheorem.cofinalTrivialZeroContribution_zero
