import PrimeNumberTheorem.ZeroDensityLayerBudgetClassicalAdmissibleBalancedRate

#print axioms PrimeNumberTheorem.classicalAdmissibleBalancedRate_le_zeroFreeRate
#print axioms PrimeNumberTheorem.classicalAdmissibleBalancedRate_isOptimal
