import PrimeNumberTheorem.ZeroDensityLayerBudgetVariableBoundaryNaturalRunningMaximumReciprocalSignAlternative

#print axioms PrimeNumberTheorem.actualMonotoneVariableBoundaryUnifiedUpperSignAlternative_reciprocal
#print axioms PrimeNumberTheorem.actualNaturalRunningMaximumBoundaryCanonicalGoodHeightUnifiedUpperSignAlternative_reciprocal
