import PrimeNumberTheorem.ZeroDensityLayerBudgetAutomaticCubicContourIntegrability

#print axioms PrimeNumberTheorem.ExplicitFormulaResidues.intervalIntegrable_thirdOrderExplicitFormulaIntegrand_bottom
#print axioms PrimeNumberTheorem.ExplicitFormulaResidues.intervalIntegrable_thirdOrderExplicitFormulaIntegrand_top
#print axioms PrimeNumberTheorem.ExplicitFormulaResidues.intervalIntegrable_thirdOrderExplicitFormulaIntegrand_left
#print axioms PrimeNumberTheorem.ExplicitFormulaResidues.intervalIntegral_bottom_thirdOrder_secondDifference_div_sq_eq
#print axioms PrimeNumberTheorem.ExplicitFormulaResidues.intervalIntegral_top_thirdOrder_secondDifference_div_sq_eq
#print axioms PrimeNumberTheorem.ExplicitFormulaResidues.intervalIntegral_left_thirdOrder_secondDifference_div_sq_eq
