import PrimeNumberTheorem.ZeroDensityLayerBudgetVariableBoundaryMonotoneAbsorptionGap

#check PrimeNumberTheorem.variableBoundaryAbsorptionOrGap_of_monotone
#check PrimeNumberTheorem.variableBoundaryVisibleNormalizedKernelTail_tendsto_zero_of_monotone
