import PrimeNumberTheorem.ZeroDensityLayerBudgetQuadraticHingeSecondDifference

#check PrimeNumberTheorem.quadraticHinge
#check PrimeNumberTheorem.quadraticHingeSecondDifferenceNumerator
#check PrimeNumberTheorem.quadraticHingeSecondDifferenceNumerator_bounds
#check PrimeNumberTheorem.quadraticHingeSecondDifferenceNumerator_eq_sq_of_nonneg
#check PrimeNumberTheorem.quadraticHingeSecondDifferenceNumerator_eq_zero_of_add_two_mul_nonpos
#check PrimeNumberTheorem.normalizedQuadraticHingeSecondDifference
#check PrimeNumberTheorem.normalizedQuadraticHingeSecondDifference_mem_unitInterval
#check PrimeNumberTheorem.normalizedQuadraticHingeSecondDifference_eq_one_of_nonneg
#check PrimeNumberTheorem.normalizedQuadraticHingeSecondDifference_eq_zero_of_add_two_mul_nonpos
