import PrimeNumberTheorem.ZeroDensityLayerBudgetPintzGrid

#print axioms PrimeNumberTheorem.PintzEnvelopeDynamicGridInput.toDynamicFiniteHeightGrid
#print axioms PrimeNumberTheorem.PintzEnvelopeDynamicGridInput.toEventuallyZeroFreeHeightCertificate
#print axioms PrimeNumberTheorem.PintzEnvelopeDynamicGridInput.envelope_le_optimalHeight
#print axioms PrimeNumberTheorem.PintzEnvelopeDynamicGridInput.optimalHeight_tendsto_atTop
#print axioms PrimeNumberTheorem.PintzEnvelopeDynamicGridInput.eventually_optimalHeight_zeroFree
