import PrimeNumberTheorem.ZeroDensityLayerBudgetNormalizedDesmoothedExplicitFormula

#print axioms PrimeNumberTheorem.ExplicitFormulaResidues.cubicContourSecondDifference_div_sq_eq_desmoothed
#print axioms PrimeNumberTheorem.ExplicitFormulaResidues.norm_desmoothedCubicContourRemainder_le
#print axioms PrimeNumberTheorem.ExplicitFormulaResidues.cubicPoleZeroContour_secondDifference_div_sq_eq
