import PrimeNumberTheorem.ZeroDensityLayerBudgetActualCubicSharedVerticalTailsContract

#print axioms PrimeNumberTheorem.norm_integral_actualCubicVerticalTail_le_of_pointwise
#print axioms PrimeNumberTheorem.exists_norm_integral_actualCubicTwoSidedVerticalTails_le
