import PrimeNumberTheorem.ZeroDensityLayerBudgetJointTwoHeightOptimalPrescribedCapOuterExponent

namespace PrimeNumberTheorem

#check IsJointTwoHeightPrescribedCapOuterExponentFeasible
#check jointTwoHeightPrescribedCapOuterExponentCeiling
#check jointTwoHeightPrescribedCapOuterExponentFeasible_of_lt_ceiling
#check le_jointTwoHeightPrescribedCapOuterExponentCeiling_of_feasible
#check exists_contourCompatible_jointTwoHeightPrescribedCapOuterExponent_iff
#check contourFloor_lt_jointTwoHeightPrescribedCapOuterExponentCeiling_iff
#check exists_contourCompatible_jointTwoHeightPrescribedCapOuterExponent_iff_arithmetic

end PrimeNumberTheorem

