import PrimeNumberTheorem.ZeroDensityLayerBudgetActualCubicCarlsonCertificateSummability

#print axioms PrimeNumberTheorem.dyadic_succ_rpow_div_sixth_eq_actualCubicCarlsonRatio
#print axioms PrimeNumberTheorem.CarlsonEventualMajorant.eventually_actualCubicCertificateBlock_le_logFifth
#print axioms PrimeNumberTheorem.CarlsonEventualMajorant.summable_actualCubicDyadicStripSquareCapacityExcluding
