import PrimeNumberTheorem.ZeroDensityLayerBudgetPintzKernelAutomatic

#print axioms PrimeNumberTheorem.norm_pntRelativeSimpleZeroKernel_eq_exp_neg_zeroCost
#print axioms PrimeNumberTheorem.norm_pntRelativeSimpleZeroKernel_le_exp_neg_pintzEnvelope
#print axioms PrimeNumberTheorem.PositiveZeroBucketInput.norm_positive_pntRelativeZeroContribution_sum_le_pintz
#print axioms PrimeNumberTheorem.PositiveZeroBucketInput.norm_full_pntRelativeZeroContribution_sum_le_pintz
