import PrimeNumberTheorem.ZeroDensityLayerBudgetActualSelectedHeightTwoHeightFullTail

namespace PrimeNumberTheorem

#check canonicalSelectedLayer_subset_polynomialLayer
#check canonicalSelectedLowLayerNorm_le_polynomialTwoHeightMass
#check canonicalSelectedHighLayer_subset_polynomialCarlsonStrip
#check dynamicSelectedPositiveOutsideClusterPNTTailNorm_le
#check selectedPositiveOutsideClusterTail_targetAmplitudeNegligible
#check selectedFullOutsideClusterTail_targetAmplitudeNegligible

end PrimeNumberTheorem
