import PrimeNumberTheorem.ZeroDensityLayerBudgetActualZeroPackageNaturalSignAlternative
namespace PrimeNumberTheorem
#check HasFarNaturalPointTargetAmplitudeWitness.signAlternative
#check actualZeroPackage_visibleCluster_naturalPoint_signAlternative
end PrimeNumberTheorem
