import PrimeNumberTheorem.ZeroDensityLayerBudgetActualCubicCarlsonMovingTail

#check PrimeNumberTheorem.summableNatTail
#check PrimeNumberTheorem.Summable.tendsto_summableNatTail_zero
#check PrimeNumberTheorem.actualCubicDyadicStripSquareCapacityExcludingTail
#check PrimeNumberTheorem.CarlsonEventualMajorant.tendsto_actualCubicDyadicStripSquareCapacityExcludingTail_zero
#check PrimeNumberTheorem.CarlsonEventualMajorant.tendsto_actualCubicDyadicStripSquareCapacityExcludingTail_comp_zero
