import PrimeNumberTheorem.ZeroDensityLayerBudgetActualCubicCarlsonCertificateBlock

#check PrimeNumberTheorem.actualCubicCarlsonCertificateBlockMajorant
#check PrimeNumberTheorem.CarlsonEventualMajorant.eventually_actualCubicDyadicCountMajorant_le
#check PrimeNumberTheorem.actualCubicDyadicStripSquareCapacityExcluding_le_certificateBlock
#check PrimeNumberTheorem.actualCubicCarlsonCertificatePolynomialExponent_le_neg_five
