import PrimeNumberTheorem.ZeroDensityLayerBudgetPositiveZeroConjugation

/-! Contract for positive/negative zero conjugation recovery. -/

#check PrimeNumberTheorem.finiteZeroSum_eq_positive_add_negative_add_real
#check PrimeNumberTheorem.sum_negative_eq_conj_sum_positive
#check PrimeNumberTheorem.PositiveZeroBucketInput.norm_full_sum_le_two_mul_pintzCarlsonBudget_add_real
