import PrimeNumberTheorem.ZeroDensityLayerBudgetPowerToSqrtLogAmplitudeTransfer

#check PrimeNumberTheorem.tendsto_targetZeroPowerAmplitude_div_pntSqrtLogExponentialAmplitude_zero
#check PrimeNumberTheorem.NaturalPointTargetAmplitudeNegligible.toSqrtLogExponentialAmplitude
#check PrimeNumberTheorem.classicalClosedLogRelativeMajorant_sqrtLogAmplitudeNegligible
#check PrimeNumberTheorem.actualPNTClosedRealAxisRelativeTerm_sqrtLogAmplitudeNegligible
#check PrimeNumberTheorem.tendsto_actualStrictMarginRateIndependentResidual_div_amplitude_zero_of_tail
