import PrimeNumberTheorem.ZeroDensityLayerBudgetCarlsonWeightedOptimalPolynomialHeightWindow

#print axioms PrimeNumberTheorem.carlsonWeightedPolynomialCriticalRealPart_spec
#print axioms PrimeNumberTheorem.carlsonWeightedPolynomialHeightFeasibilityGap_pos_iff
#print axioms PrimeNumberTheorem.carlsonWeightedPolynomialCriticalRealPart_lt_criticalHalf
#print axioms PrimeNumberTheorem.carlsonWeightedOptimalPolynomialHeightWindow_spec
#print axioms PrimeNumberTheorem.carlsonWeightedOptimalPolynomialSelectedHeight_spec
