import PrimeNumberTheorem.ZeroDensityLayerBudgetInnerZeroFreeHorizontalBudget
import PrimeNumberTheorem.CentralHorizontalEdge

open Complex MeasureTheory Set
open scoped BigOperators Interval

namespace PrimeNumberTheorem
namespace ExplicitFormulaResidues

/-- Convert an ordinary explicit-formula height `T` to the cubic contour
parameter whose horizontal edges have imaginary parts `-T` and `+T`. -/
noncomputable def goodHeightCubicWidth (T : ℝ) : ℝ :=
  T / (2 * Real.pi)

@[simp] theorem two_pi_mul_goodHeightCubicWidth (T : ℝ) :
    2 * Real.pi * goodHeightCubicWidth T = T := by
  unfold goodHeightCubicWidth
  field_simp [Real.pi_ne_zero]

theorem goodHeightCubicWidth_pos {T : ℝ} (hT : 0 < T) :
    0 < goodHeightCubicWidth T := by
  unfold goodHeightCubicWidth
  positivity

@[simp] theorem cubicHorizontalEdgeRadius_goodHeightCubicWidth
    (c T : ℝ) :
    cubicHorizontalEdgeRadius c (goodHeightCubicWidth T) = c + T := by
  unfold cubicHorizontalEdgeRadius
  rw [two_pi_mul_goodHeightCubicWidth]

@[simp] theorem cubicBottomContourPoint_goodHeightCubicWidth
    (T sigma : ℝ) :
    cubicBottomContourPoint (goodHeightCubicWidth T) sigma =
      (sigma : ℂ) + I * (-T) := by
  have hwidth := two_pi_mul_goodHeightCubicWidth T
  apply Complex.ext <;> simp [cubicBottomContourPoint]

@[simp] theorem cubicTopContourPoint_goodHeightCubicWidth
    (T sigma : ℝ) :
    cubicTopContourPoint (goodHeightCubicWidth T) sigma =
      (sigma : ℂ) + I * T := by
  have hwidth := two_pi_mul_goodHeightCubicWidth T
  apply Complex.ext <;> simp [cubicTopContourPoint]

/-- In every sufficiently high unit window, one actual-zeta good height
simultaneously bounds both complete positive-real-part horizontal edges of the
de-smoothed cubic contour.  The logarithmic derivative input is generated by
Shifted Jensen plus quantitative separation, not assumed by the caller. -/
theorem exists_goodHeight_Icc_norm_desmoothedCubicCentralContourIntegrals_le :
    ∃ C : ℝ, 0 ≤ C ∧ ∀ A : ℝ, 4 ≤ A →
      ∃ T ∈ Set.Icc A (A + 1),
        ExplicitFormulaAux.goodHeight T ∧
          ∀ x h a c : ℝ, 0 < x → 1 ≤ x → 0 < a → a ≤ c → c ≤ 2 →
            0 < h → h * (c + T) ≤ 1 →
            ‖desmoothedCubicBottomContourIntegral x h a c
                (goodHeightCubicWidth T)‖ ≤
              desmoothedCubicPointwiseBudget x h c T
                  (C * (1 + Real.log (A + 6)) ^ 2) (c + T) * |c - a| ∧
            ‖desmoothedCubicTopContourIntegral x h a c
                (goodHeightCubicWidth T)‖ ≤
              desmoothedCubicPointwiseBudget x h c T
                  (C * (1 + Real.log (A + 6)) ^ 2) (c + T) * |c - a| := by
  rcases exists_goodHeight_Icc_norm_logDeriv_central_band_le_log_sq with
    ⟨C, hC, hchoose⟩
  refine ⟨C, hC, ?_⟩
  intro A hA
  rcases hchoose A hA with ⟨T, hT, hgood, hlog⟩
  refine ⟨T, hT, hgood, ?_⟩
  intro x h a c hx hx1 ha hac hc2 hh hsmall
  have hTpos : 0 < T := by linarith [hA, hT.1]
  have hWpos : 0 < goodHeightCubicWidth T :=
    goodHeightCubicWidth_pos hTpos
  have hLnonneg : 0 ≤ C * (1 + Real.log (A + 6)) ^ 2 :=
    mul_nonneg hC (sq_nonneg _)
  have hsmall' :
      h * cubicHorizontalEdgeRadius c (goodHeightCubicWidth T) ≤ 1 := by
    simpa using hsmall
  have hbottomLog : ∀ sigma ∈ Ι a c,
      ‖logDeriv riemannZeta
          (cubicBottomContourPoint (goodHeightCubicWidth T) sigma)‖ ≤
        C * (1 + Real.log (A + 6)) ^ 2 := by
    intro sigma hsigma
    have hsigma' : a < sigma ∧ sigma ≤ c := by
      rw [Set.uIoc_of_le hac] at hsigma
      exact hsigma
    have hbound := hlog (-T) (by simp [abs_of_pos hTpos]) sigma
      (by linarith) (hsigma'.2.trans hc2)
    simpa using hbound
  have htopLog : ∀ sigma ∈ Ι a c,
      ‖logDeriv riemannZeta
          (cubicTopContourPoint (goodHeightCubicWidth T) sigma)‖ ≤
        C * (1 + Real.log (A + 6)) ^ 2 := by
    intro sigma hsigma
    have hsigma' : a < sigma ∧ sigma ≤ c := by
      rw [Set.uIoc_of_le hac] at hsigma
      exact hsigma
    have hbound := hlog T (abs_of_pos hTpos) sigma
      (by linarith) (hsigma'.2.trans hc2)
    simpa using hbound
  have hbottom := norm_desmoothedCubicBottomContourIntegral_le
    hx hx1 ha hac hWpos hLnonneg hbottomLog hh hsmall'
  have htop := norm_desmoothedCubicTopContourIntegral_le
    hx hx1 ha hac hWpos hLnonneg htopLog hh hsmall'
  simpa using And.intro hbottom htop

/-- The selected top and bottom horizontal norms have a common summed budget.
This is the form directly consumed by the contour-remainder triangle estimate. -/
theorem exists_goodHeight_Icc_norm_desmoothedCubicCentralHorizontalSum_le :
    ∃ C : ℝ, 0 ≤ C ∧ ∀ A : ℝ, 4 ≤ A →
      ∃ T ∈ Set.Icc A (A + 1),
        ExplicitFormulaAux.goodHeight T ∧
          ∀ x h a c : ℝ, 0 < x → 1 ≤ x → 0 < a → a ≤ c → c ≤ 2 →
            0 < h → h * (c + T) ≤ 1 →
            ‖desmoothedCubicBottomContourIntegral x h a c
                (goodHeightCubicWidth T)‖ +
              ‖desmoothedCubicTopContourIntegral x h a c
                (goodHeightCubicWidth T)‖ ≤
              2 * (desmoothedCubicPointwiseBudget x h c T
                  (C * (1 + Real.log (A + 6)) ^ 2) (c + T) * |c - a|) := by
  rcases exists_goodHeight_Icc_norm_desmoothedCubicCentralContourIntegrals_le with
    ⟨C, hC, hchoose⟩
  refine ⟨C, hC, ?_⟩
  intro A hA
  rcases hchoose A hA with ⟨T, hT, hgood, hbound⟩
  refine ⟨T, hT, hgood, ?_⟩
  intro x h a c hx hx1 ha hac hc2 hh hsmall
  rcases hbound x h a c hx hx1 ha hac hc2 hh hsmall with ⟨hb, ht⟩
  linarith

end ExplicitFormulaResidues
end PrimeNumberTheorem
