import PrimeNumberTheorem.ZeroDensityLayerBudgetActualPintzCertifiedGoodHeightCostCoverTransfer
import PrimeNumberTheorem.ZeroDensityLayerBudgetPNTGoodHeightCarlsonCeiling

/-!
# An actual good-height Pintz--Carlson rate grid

The abstract exponential candidates `pintzCarlsonHeight k x` are replaced by
analytic good heights in the unit interval immediately below those ceilings.
The pointwise optimizer therefore selects both a genuine Pintz rate and the
actual truncated-formula certificate at that height.

This module does not yet assert continuous-rate optimality, unconditional
Omega, or RH.
-/

namespace PrimeNumberTheorem

open Filter Topology

/-- A finite nonempty positive rate grid with a least rate and one global
uniform good-height selector. -/
structure ActualPintzCarlsonGoodHeightRateGrid where
  rates : Finset ℝ
  baseRate : ℝ
  baseRate_mem : baseRate ∈ rates
  rates_pos : ∀ k ∈ rates, 0 < k
  baseRate_le : ∀ k ∈ rates, baseRate ≤ k
  selection : UniformNaturalPointGoodHeightSelection

/-- The Pintz--Carlson ceiling is monotone in its rate. -/
theorem pintzCarlsonHeight_mono_rate
    {k l : ℝ} (hkl : k ≤ l) (x : ℝ) :
    pintzCarlsonHeight k x ≤ pintzCarlsonHeight l x := by
  apply Real.exp_le_exp.mpr
  exact mul_le_mul_of_nonneg_right hkl (Real.sqrt_nonneg _)

/-- The actual good-height candidate associated with rate `k`, regularized by
a positive fallback before its good-height base is admissible. -/
noncomputable def actualPintzCarlsonRateCandidateHeight
    (grid : ActualPintzCarlsonGoodHeightRateGrid)
    (k x : ℝ) : ℝ :=
  if 9 ≤ pintzCarlsonHeight k x then
    grid.selection.height (pintzCarlsonGoodHeightBase k x)
  else
    8

theorem actualPintzCarlsonRateCandidateHeight_pos
    (grid : ActualPintzCarlsonGoodHeightRateGrid)
    (k x : ℝ) :
    0 < actualPintzCarlsonRateCandidateHeight grid k x := by
  by_cases hlarge : 9 ≤ pintzCarlsonHeight k x
  · have hbase : 8 ≤ pintzCarlsonGoodHeightBase k x := by
      dsimp [pintzCarlsonGoodHeightBase]
      linarith
    have hmem := grid.selection.height_mem
      (pintzCarlsonGoodHeightBase k x) hbase
    simp only [actualPintzCarlsonRateCandidateHeight, if_pos hlarge]
    exact lt_of_lt_of_le (by linarith : 0 < pintzCarlsonGoodHeightBase k x)
      hmem.1
  · simp [actualPintzCarlsonRateCandidateHeight, hlarge]

/-- Regularized lower envelope generated by the least rate. -/
noncomputable def actualPintzCarlsonRateLowerEnvelope
    (grid : ActualPintzCarlsonGoodHeightRateGrid) (x : ℝ) : ℝ :=
  if 9 ≤ pintzCarlsonHeight grid.baseRate x then
    pintzCarlsonGoodHeightBase grid.baseRate x
  else
    0

theorem actualPintzCarlsonRateLowerEnvelope_tendsto_atTop
    (grid : ActualPintzCarlsonGoodHeightRateGrid) :
    Tendsto (actualPintzCarlsonRateLowerEnvelope grid) atTop atTop := by
  have hbasePos : 0 < grid.baseRate :=
    grid.rates_pos grid.baseRate grid.baseRate_mem
  have hheight := tendsto_pintzCarlsonHeight_atTop hbasePos
  refine tendsto_atTop.2 ?_
  intro b
  have hlarge :
      ∀ᶠ x : ℝ in atTop,
        max 9 (b + 1) ≤ pintzCarlsonHeight grid.baseRate x :=
    (tendsto_atTop.1 hheight) (max 9 (b + 1))
  filter_upwards [hlarge] with x hx
  have hx9 : 9 ≤ pintzCarlsonHeight grid.baseRate x :=
    (le_max_left _ _).trans hx
  have hxb : b + 1 ≤ pintzCarlsonHeight grid.baseRate x :=
    (le_max_right _ _).trans hx
  rw [actualPintzCarlsonRateLowerEnvelope, if_pos hx9]
  dsimp [pintzCarlsonGoodHeightBase]
  linarith

/-- Actual selected good heights from all rates at one scale. -/
noncomputable def actualPintzCarlsonRateFiniteGrid
    (grid : ActualPintzCarlsonGoodHeightRateGrid)
    (x : ℝ) : FiniteHeightGrid where
  heights := grid.rates.image
    (fun k => actualPintzCarlsonRateCandidateHeight grid k x)
  nonempty :=
    ⟨actualPintzCarlsonRateCandidateHeight grid grid.baseRate x,
      Finset.mem_image.mpr ⟨grid.baseRate, grid.baseRate_mem, rfl⟩⟩
  positive := by
    intro T hT
    rcases Finset.mem_image.mp hT with ⟨k, _hk, rfl⟩
    exact actualPintzCarlsonRateCandidateHeight_pos grid k x

theorem actualPintzCarlsonRateLowerEnvelope_le
    (grid : ActualPintzCarlsonGoodHeightRateGrid)
    (x T : ℝ)
    (hT : T ∈ (actualPintzCarlsonRateFiniteGrid grid x).heights) :
    actualPintzCarlsonRateLowerEnvelope grid x ≤ T := by
  rcases Finset.mem_image.mp hT with ⟨k, hk, rfl⟩
  by_cases hbaseLarge : 9 ≤ pintzCarlsonHeight grid.baseRate x
  · have hraw := pintzCarlsonHeight_mono_rate (grid.baseRate_le k hk) x
    have hkLarge : 9 ≤ pintzCarlsonHeight k x := hbaseLarge.trans hraw
    have hkBase : 8 ≤ pintzCarlsonGoodHeightBase k x := by
      dsimp [pintzCarlsonGoodHeightBase]
      linarith
    have hmem := grid.selection.height_mem
      (pintzCarlsonGoodHeightBase k x) hkBase
    rw [actualPintzCarlsonRateLowerEnvelope, if_pos hbaseLarge,
      actualPintzCarlsonRateCandidateHeight, if_pos hkLarge]
    exact (sub_le_sub_right hraw 1).trans hmem.1
  · rw [actualPintzCarlsonRateLowerEnvelope, if_neg hbaseLarge]
    exact (actualPintzCarlsonRateCandidateHeight_pos grid k x).le

/-- Dynamic finite grid of actual Pintz good heights. -/
noncomputable def actualPintzCarlsonGoodHeightDynamicGrid
    (grid : ActualPintzCarlsonGoodHeightRateGrid) :
    DynamicFiniteHeightGrid where
  grid := actualPintzCarlsonRateFiniteGrid grid
  lowerEnvelope := actualPintzCarlsonRateLowerEnvelope grid
  lowerEnvelope_tendsto_atTop :=
    actualPintzCarlsonRateLowerEnvelope_tendsto_atTop grid
  lowerEnvelope_le := actualPintzCarlsonRateLowerEnvelope_le grid

/-- Pointwise cost optimizer over the actual finite Pintz rate grid. -/
noncomputable def actualPintzCarlsonGoodHeightOptimalHeight
    (cost : ℝ → ℝ → ℝ)
    (grid : ActualPintzCarlsonGoodHeightRateGrid)
    (x : ℝ) : ℝ :=
  dynamicFiniteGridOptimalHeight cost
    (actualPintzCarlsonGoodHeightDynamicGrid grid) x

/-- The optimized actual good height is generated by a rate in the supplied
finite grid. -/
theorem actualPintzCarlsonGoodHeightOptimalHeight_eq_candidate
    (cost : ℝ → ℝ → ℝ)
    (grid : ActualPintzCarlsonGoodHeightRateGrid)
    (x : ℝ) :
    ∃ k ∈ grid.rates,
      actualPintzCarlsonGoodHeightOptimalHeight cost grid x =
        actualPintzCarlsonRateCandidateHeight grid k x := by
  have hmem := dynamicFiniteGridOptimalHeight_mem cost
    (actualPintzCarlsonGoodHeightDynamicGrid grid) x
  rcases Finset.mem_image.mp hmem with ⟨k, hk, heq⟩
  exact ⟨k, hk, heq.symm⟩

/-- Exact pointwise cost optimality against every certified rate. -/
theorem actualPintzCarlsonGoodHeightOptimalHeight_le_candidate
    (cost : ℝ → ℝ → ℝ)
    (grid : ActualPintzCarlsonGoodHeightRateGrid)
    (x : ℝ) {k : ℝ} (hk : k ∈ grid.rates) :
    cost x (actualPintzCarlsonGoodHeightOptimalHeight cost grid x) ≤
      cost x (actualPintzCarlsonRateCandidateHeight grid k x) := by
  apply dynamicFiniteGridOptimalHeight_le_of_mem cost
    (actualPintzCarlsonGoodHeightDynamicGrid grid)
  exact Finset.mem_image.mpr ⟨k, hk, rfl⟩

theorem actualPintzCarlsonGoodHeightOptimalHeight_tendsto_atTop
    (cost : ℝ → ℝ → ℝ)
    (grid : ActualPintzCarlsonGoodHeightRateGrid) :
    Tendsto (actualPintzCarlsonGoodHeightOptimalHeight cost grid)
      atTop atTop :=
  dynamicFiniteGridOptimalHeight_tendsto_atTop cost
    (actualPintzCarlsonGoodHeightDynamicGrid grid)

/-- Eventually the optimizer is an actual good height in the unit interval
below the Pintz ceiling of its selected rate. -/
theorem eventually_actualPintzCarlsonGoodHeightOptimalHeight_interval_good
    (cost : ℝ → ℝ → ℝ)
    (grid : ActualPintzCarlsonGoodHeightRateGrid) :
    ∀ᶠ x : ℝ in atTop,
      ∃ k ∈ grid.rates,
        actualPintzCarlsonGoodHeightOptimalHeight cost grid x ∈
          Set.Icc (pintzCarlsonGoodHeightBase k x)
            (pintzCarlsonGoodHeightBase k x + 1) ∧
        ExplicitFormulaAux.goodHeight
          (actualPintzCarlsonGoodHeightOptimalHeight cost grid x) := by
  have hbasePos : 0 < grid.baseRate :=
    grid.rates_pos grid.baseRate grid.baseRate_mem
  have hlarge :
      ∀ᶠ x : ℝ in atTop, 9 ≤ pintzCarlsonHeight grid.baseRate x :=
    (tendsto_atTop.1 (tendsto_pintzCarlsonHeight_atTop hbasePos)) 9
  filter_upwards [hlarge] with x hx
  rcases actualPintzCarlsonGoodHeightOptimalHeight_eq_candidate
      cost grid x with ⟨k, hk, heq⟩
  have hraw := pintzCarlsonHeight_mono_rate (grid.baseRate_le k hk) x
  have hkLarge : 9 ≤ pintzCarlsonHeight k x := hx.trans hraw
  have hkBase : 8 ≤ pintzCarlsonGoodHeightBase k x := by
    dsimp [pintzCarlsonGoodHeightBase]
    linarith
  refine ⟨k, hk, ?_, ?_⟩
  · rw [heq]
    simpa [actualPintzCarlsonRateCandidateHeight, hkLarge] using
      grid.selection.height_mem (pintzCarlsonGoodHeightBase k x) hkBase
  · rw [heq]
    simpa [actualPintzCarlsonRateCandidateHeight, hkLarge] using
      grid.selection.good_height (pintzCarlsonGoodHeightBase k x) hkBase

/-- At every sufficiently large natural sample, the optimized rate and height
carry the exact truncated explicit-formula certificate with the common selector
constant. -/
theorem actualPintzCarlsonGoodHeightOptimalHeight_truncatedCertificate
    (cost : ℝ → ℝ → ℝ)
    (grid : ActualPintzCarlsonGoodHeightRateGrid)
    (m N : ℕ) (hm : 3 ≤ m)
    (hlarge : 9 ≤ pintzCarlsonHeight grid.baseRate (m : ℝ)) :
    ∃ k ∈ grid.rates,
      ∃ certificate : TruncatedPNTErrorCertificate (m : ℝ)
          (actualPintzCarlsonGoodHeightOptimalHeight cost grid (m : ℝ)),
        certificate.trivialContribution =
            cofinalTrivialZeroContribution m N ∧
          certificate.remainderBound =
            cofinalPNTFormulaRemainderBound grid.selection.constant
              (pintzCarlsonGoodHeightBase k (m : ℝ))
              (actualPintzCarlsonGoodHeightOptimalHeight
                cost grid (m : ℝ)) m N := by
  rcases actualPintzCarlsonGoodHeightOptimalHeight_eq_candidate
      cost grid (m : ℝ) with ⟨k, hk, heq⟩
  have hraw :=
    pintzCarlsonHeight_mono_rate (grid.baseRate_le k hk) (m : ℝ)
  have hkLarge : 9 ≤ pintzCarlsonHeight k (m : ℝ) := hlarge.trans hraw
  have hkBase : 8 ≤ pintzCarlsonGoodHeightBase k (m : ℝ) := by
    dsimp [pintzCarlsonGoodHeightBase]
    linarith
  have hheight :
      actualPintzCarlsonGoodHeightOptimalHeight cost grid (m : ℝ) =
        grid.selection.height
          (pintzCarlsonGoodHeightBase k (m : ℝ)) := by
    rw [heq]
    simp [actualPintzCarlsonRateCandidateHeight, hkLarge]
  refine ⟨k, hk, ?_⟩
  rw [hheight]
  exact grid.selection.truncated_certificate
    (pintzCarlsonGoodHeightBase k (m : ℝ)) hkBase m N hm

end PrimeNumberTheorem
