import PrimeNumberTheorem.ZeroDensityLayerBudgetPNTHybridDensityDecay

#print axioms PrimeNumberTheorem.exists_pintzConstant_adaptiveGlobalLowDensityBudget_tendsto
#print axioms PrimeNumberTheorem.exists_pintzConstant_exactHeight_highDensityTerm_tendsto
#print axioms PrimeNumberTheorem.exists_pintzConstant_adaptiveHybridDensityBudget_tendsto
