import PrimeNumberTheorem.ZeroDensityLayerBudgetCarlsonMovingBalancedDecay

namespace PrimeNumberTheorem

#check carlsonMovingBalancedNormalizedRatio
#check tendsto_carlsonMovingBalancedNormalizedRatio_zero

end PrimeNumberTheorem
