import PrimeNumberTheorem.ZeroDensityLayerBudgetActualCubicTwoHeightDyadicCuts

#print axioms PrimeNumberTheorem.tendsto_actualCubicDyadicPolynomialCut_atTop
#print axioms PrimeNumberTheorem.tendsto_actualCubicLowDyadicCut_atTop
#print axioms PrimeNumberTheorem.tendsto_actualCubicOuterDyadicCut_atTop
#print axioms PrimeNumberTheorem.eventually_actualCubicLowDyadicCut_le_outer
#print axioms PrimeNumberTheorem.CarlsonEventualMajorant.tendsto_actualCubicTail_at_lowDyadicCut_zero
#print axioms PrimeNumberTheorem.CarlsonEventualMajorant.tendsto_actualCubicTail_at_outerDyadicCut_zero
