import PrimeNumberTheorem.ZeroDensityLayerBudgetCarlsonActualTwoHeightSplit

namespace PrimeNumberTheorem

#check actualPositiveCarlsonStrip
#check actualPositiveCarlsonLowStrip
#check actualPositiveCarlsonHighRectangle
#check actualPositiveCarlsonStrip_eq_low_union_high
#check actualPositiveCarlsonLowStrip_disjoint_high
#check norm_pntRelativeSimpleZeroKernel_le_realThreshold
#check sum_norm_actualPositiveCarlsonLowStrip_le
#check sum_norm_actualPositiveCarlsonHighRectangle_le
#check sum_norm_actualPositiveCarlsonStrip_le_twoHeightBudget
#check tendsto_actualCarlsonTwoHeightLowBudget
#check tendsto_actualCarlsonTwoHeightHighBudget
#check tendsto_sum_norm_actualPositiveCarlsonStrip_twoHeight

end PrimeNumberTheorem
