import PrimeNumberTheorem.ZeroDensityLayerBudgetQuadraticKernelMovingPNTUnnormalizedTransfer

#print axioms PrimeNumberTheorem.self_mul_reciprocalPolynomialHeightVariableTargetAmplitude
#print axioms PrimeNumberTheorem.HasFarPositiveTargetAmplitudeWitness.relativeChebyshevPsi0Error_to_unnormalized_reciprocalPolynomialHeight
#print axioms PrimeNumberTheorem.HasFarNegativeTargetAmplitudeWitness.relativeChebyshevPsi0Error_to_unnormalized_reciprocalPolynomialHeight
#print axioms PrimeNumberTheorem.QuadraticKernelMovingPNTCertificate.unnormalizedSignAlternative
