import PrimeNumberTheorem.ZeroDensityLayerBudgetJointTwoHeightPrescribedCapFeasibility

namespace PrimeNumberTheorem

#check exists_jointTwoHeightTargetAmplitudeMargins_of_endpoints
#check exists_jointTwoHeightTargetAmplitudeParameters_above_cap

end PrimeNumberTheorem

