import PrimeNumberTheorem.ZeroDensityLayerBudgetWeightedOptimalPolynomialHeightWindow

#print axioms PrimeNumberTheorem.weightedPolynomialHeightCommonSafetyMargin_le_optimal
#print axioms PrimeNumberTheorem.weightedOptimalPolynomialHeightWindow_equalMargins
#print axioms PrimeNumberTheorem.weightedOptimalPolynomialHeight_q_one
#print axioms PrimeNumberTheorem.weightedOptimalPolynomialHeightWindow_spec
#print axioms PrimeNumberTheorem.weightedOptimalPolynomialSelectedHeight_spec
