import PrimeNumberTheorem.ZeroDensityLayerBudgetActualAutomaticQuantitativeReverseFiniteHeightZeroFree

namespace PrimeNumberTheorem

#check not_hasFarTargetAmplitude_mul_of_eventually_abs_le_mul
#check exists_automaticGoodHeight_globalRealPartBound_eventualUpper_finiteHeightZeroFree

end PrimeNumberTheorem

