import PrimeNumberTheorem.ZeroDensityLayerBudgetCubicContourKernelFactorization

#check PrimeNumberTheorem.ExplicitFormulaResidues.desmoothedCubicContourIntegrand
#check PrimeNumberTheorem.ExplicitFormulaResidues.explicitFormulaIntegrand_mul_exp_shift
#check PrimeNumberTheorem.ExplicitFormulaResidues.thirdOrderExplicitFormulaIntegrand_secondDifference_div_sq_eq
#check PrimeNumberTheorem.ExplicitFormulaResidues.intervalIntegral_thirdOrder_secondDifference_div_sq_eq
