import PrimeNumberTheorem.ZeroDensityLayerBudgetFiniteZeroSumBridge

#print axioms PrimeNumberTheorem.sum_pntFiniteZeroContribution_eq_neg_finiteNontrivialZeroSumWithMultiplicity
#print axioms PrimeNumberTheorem.sum_pntRelativeZeroContribution_eq_inv_mul_neg_finiteNontrivialZeroSumWithMultiplicity
#print axioms PrimeNumberTheorem.norm_sum_pntRelativeZeroContribution_eq_norm_finiteNontrivialZeroSumWithMultiplicity_div
#print axioms PrimeNumberTheorem.PositiveZeroBucketInput.norm_finiteNontrivialZeroSumWithMultiplicity_le_pintz
