import PrimeNumberTheorem.ZeroDensityLayerBudgetPNTGoodHeightCarlsonCeiling

#print axioms PrimeNumberTheorem.pintzCarlsonClassicalAggregatedDensityLayerTerm_mono_height
#print axioms PrimeNumberTheorem.exists_naturalPoint_pintzCarlson_goodHeight_ceiling_PNT_upper
#print axioms PrimeNumberTheorem.exists_pintzConstant_exactHeight_classicalDensityTerm_tendsto
