import PrimeNumberTheorem.ZeroDensityLayerBudgetCanonicalPolynomialHeightWindow

#print axioms PrimeNumberTheorem.canonicalPolynomialHeightWindow_spec
#print axioms PrimeNumberTheorem.canonicalPolynomialSelectedHeight_spec
