import PrimeNumberTheorem.ZeroDensityLayerBudgetActualCubicDynamicLowLeft

#print axioms PrimeNumberTheorem.exists_dynamicCubicLowLeft_analyticAt_logDeriv_budget
#print axioms PrimeNumberTheorem.exists_dynamicCubicLowLeft_logDeriv_budget
