import PrimeNumberTheorem.ZeroDensityLayerBudgetJointTwoHeightImprovedGlobalCapThreshold

namespace PrimeNumberTheorem

#check jointTwoHeightSigmaBalanceValue
#check jointTwoHeightSigmaBalanceValue_strictAnti
#check jointTwoHeightImprovedGlobalCapThreshold
#check jointTwoHeightImprovedGlobalCapThreshold_spec
#check contourFloor_lt_jointTwoHeightGlobalOuterExponentCeiling_iff
#check exists_pos_lt_jointTwoHeightGlobalContourGap_of_lt_improvedThreshold

end PrimeNumberTheorem
