import PrimeNumberTheorem.ZeroDensityLayerBudgetPNTFixedResidualDecay

#print axioms PrimeNumberTheorem.tendsto_naturalPoint_realOrdinateRelativeZeroResidual_of_eventually_nonneg
#print axioms PrimeNumberTheorem.tendsto_naturalPoint_fixedPNTConstants_zeroDepth_relative
#print axioms PrimeNumberTheorem.tendsto_naturalPoint_fixedRelativeResidual_zeroDepth
