import PrimeNumberTheorem.ZeroDensityLayerBudgetCarlsonDynamicLayerCount

/-!
# Contract for dynamic Carlson layer-count aggregation
-/

namespace PrimeNumberTheorem

#check carlsonDynamicLayerCountLogCost
#check carlsonMovingLayeredQuadraticLogEnvelope
#check IsCarlsonMovingQuadraticLayerCountGap
#check carlsonMovingLayeredQuadraticLogEnvelope_admissible
#check carlsonMovingLayeredQuadraticRatio_eq
#check carlsonDynamicFiniteLayerMass
#check carlsonDynamicFiniteLayerMass_le_layeredQuadraticRatio
#check tendsto_carlsonDynamicFiniteLayerMass_zero

end PrimeNumberTheorem
