import PrimeNumberTheorem.ZeroDensityLayerBudgetCubicKernelFactorization

#print axioms PrimeNumberTheorem.ExplicitFormulaResidues.ofReal_mul_exp_cpow_eq_cpow_mul_exp
#print axioms PrimeNumberTheorem.ExplicitFormulaResidues.cubicZeroResidueSecondDifference_div_sq_eq_simple_mul_multiplier
#print axioms PrimeNumberTheorem.ExplicitFormulaResidues.norm_cubicZeroResidueSecondDifference_div_sq_eq
#print axioms PrimeNumberTheorem.ExplicitFormulaResidues.cubicPoleOneSecondDifference_div_sq_eq
