import PrimeNumberTheorem.ZeroDensityLayerBudgetCubicKernelFactorization

#check PrimeNumberTheorem.ExplicitFormulaResidues.cubicKernelMultiplier
#check PrimeNumberTheorem.ExplicitFormulaResidues.cubicSimpleZeroKernel
#check PrimeNumberTheorem.ExplicitFormulaResidues.ofReal_mul_exp_cpow_eq_cpow_mul_exp
#check PrimeNumberTheorem.ExplicitFormulaResidues.cubicZeroResidueSecondDifference_div_sq_eq_simple_mul_multiplier
#check PrimeNumberTheorem.ExplicitFormulaResidues.norm_cubicSimpleZeroKernel_eq
#check PrimeNumberTheorem.ExplicitFormulaResidues.norm_cubicZeroResidueSecondDifference_div_sq_eq
#check PrimeNumberTheorem.ExplicitFormulaResidues.cubicPoleOneSecondDifference_div_sq_eq
