import PrimeNumberTheorem.ZeroDensityLayerBudgetPNTHybridUpper

#print axioms PrimeNumberTheorem.naturalPointPintzPNTCeilingDensityUpperBudget_le_hybrid
#print axioms PrimeNumberTheorem.naturalPointPintzPNTCeilingDensityRelativeUpperBudget_le_hybrid
#print axioms PrimeNumberTheorem.exists_naturalPoint_pintzCarlson_goodHeight_hybrid_PNT_upper
