import PrimeNumberTheorem.ZeroDensityLayerBudgetActualSelectedHeightCriticalHalfDecay

#print axioms PrimeNumberTheorem.eventually_selectedHeight_le_polynomialHeight_of_unitWindow_real
#print axioms PrimeNumberTheorem.tendsto_selectedHeight_atTop_of_unitWindow
#print axioms PrimeNumberTheorem.tendsto_actualSelectedHeightCriticalHalfPNTLayerNorm_zero
