import PrimeNumberTheorem.ZeroDensityLayerBudgetCarlsonMovingHeightScale

#print axioms PrimeNumberTheorem.tendsto_delta_mul_log_of_quadraticLogPowerGap
#print axioms PrimeNumberTheorem.three_mul_alpha_mul_delta_le_carlsonMovingBalancedCut
#print axioms PrimeNumberTheorem.tendsto_carlsonMovingBalancedCut_mul_log
