import PrimeNumberTheorem.ZeroDensityLayerBudgetCarlsonMovingLogPowerAbsorption

#check PrimeNumberTheorem.carlsonMovingQuadraticLogPowerEnvelope
#check PrimeNumberTheorem.IsCarlsonMovingQuadraticLogPowerGap
#check PrimeNumberTheorem.carlsonMovingQuadraticLogPowerEnvelope_admissible
#check PrimeNumberTheorem.tendsto_carlsonMovingQuadraticLogPowerCoefficientRatio_zero
