import PrimeNumberTheorem.ZeroDensityLayerBudgetVariableBoundaryMovingWindowMeanSquareHandoff

#check PrimeNumberTheorem.HasFarWindowStrictMeanSquareLowerBound
#check PrimeNumberTheorem.HasFarWindowStrictMeanSquareLowerBound.toNaturalPointWitness
#check PrimeNumberTheorem.HasFarWindowStrictMeanSquareLowerBound.normalized_to_mul_amplitude
#check PrimeNumberTheorem.actualNaturalRunningMaximumMovingPackageWitness_of_windowMeanSquare
#check PrimeNumberTheorem.actualNaturalRunningMaximumBoundaryCanonicalGoodHeightUnifiedUpperSignAlternative_of_windowMeanSquare_reciprocal
