import PrimeNumberTheorem.ZeroDensityLayerBudgetActualMovingRightEdgeUnifiedTransfer

namespace PrimeNumberTheorem

#check automaticGoodHeight_twoHeight_movingRightEdgeNaturalPointLowerTransfer
#check unified_automaticGoodHeight_twoHeight_movingRightEdgeNaturalTargetTransfer
#check exists_automaticGoodHeight_movingRightEdgeNaturalTargetTransfer

end PrimeNumberTheorem
