import PrimeNumberTheorem.ZeroDensityLayerBudgetNormalizedDesmoothedExplicitFormula

#check PrimeNumberTheorem.ExplicitFormulaResidues.desmoothedCubicContourRemainder
#check PrimeNumberTheorem.ExplicitFormulaResidues.cubicContourSecondDifference_div_sq_eq_desmoothed
#check PrimeNumberTheorem.ExplicitFormulaResidues.norm_desmoothedCubicContourRemainder_le
#check PrimeNumberTheorem.ExplicitFormulaResidues.cubicPoleZeroContour_secondDifference_div_sq_eq
