import PrimeNumberTheorem.ZeroDensityLayerBudgetPNTFullRelativeDecay

#print axioms PrimeNumberTheorem.singletonZeroThresholdBucketInput
#print axioms PrimeNumberTheorem.exists_pintzConstant_singletonZeroThresholdHybridDensity_tendsto
#print axioms PrimeNumberTheorem.exists_fixedRatePNTUpperSchedule
#print axioms PrimeNumberTheorem.FixedRatePNTUpperSchedule.relativeBudget_tendsto
#print axioms PrimeNumberTheorem.FixedRatePNTUpperSchedule.relativeError_tendsto
#print axioms PrimeNumberTheorem.exists_fixedRate_relativeChebyshevPsi0Error_tendsto
