import PrimeNumberTheorem.ZeroDensityLayerBudgetPintzCarlsonGap

#print axioms PrimeNumberTheorem.tendsto_pintzCarlsonSqrtLogScale_atTop
#print axioms PrimeNumberTheorem.exists_eventually_two_mul_sqrt_mul_scale_le_pintzZeroEnvelope
#print axioms PrimeNumberTheorem.pintzEnvelope_exp_kernel_le_gapKernel
#print axioms PrimeNumberTheorem.tendsto_pintzCarlsonGap_rpow_mul_exp
#print axioms PrimeNumberTheorem.tendsto_carlsonExponent_pintzGap
#print axioms PrimeNumberTheorem.tendsto_const_mul_carlsonExponent_pintzGap
#print axioms PrimeNumberTheorem.tendsto_carlsonFourthPower_pintzGap
