import PrimeNumberTheorem.ZeroDensityLayerBudgetActualThetaOnlyCubicStrictUnifiedTransfer

namespace PrimeNumberTheorem

#check exists_thetaOnlyCubicStrictAutomaticGoodHeight_globalRealPartBoundNaturalTargetTransfer

end PrimeNumberTheorem
