import PrimeNumberTheorem.ZeroDensityLayerBudgetJointTwoHeightCubicStrictTargetExponent

namespace PrimeNumberTheorem

#check jointTwoHeightCubicStrictTargetExponent
#check jointTwoHeightCubicStrictTargetExponent_spec
#check jointTwoHeightCubicStrictTargetExponent_lower
#check jointTwoHeightCubicStrictTargetExponent_lt_one
#check theta_lt_jointTwoHeightCubicStrictTargetExponent
#check theta_lt_improvedThreshold_cubicStrictTargetExponent
#check tendsto_jointTwoHeightCubicStrictTargetExponent_cubicExcess

end PrimeNumberTheorem
