import Lake
open Lake DSL

package «riemann-pnt» where
  version := v!"0.1.0"

@[default_target]
lean_lib RiemannPNT where
  roots := #[
    `RiemannPNT,
    `RiemannExplorer,
    `RiemannExplorer.Conrey40,
    `GammaResidue,
    `HardyTheorem,
    `EulerAndLfunctions,
    `PrimeNumberTheorem,
    `PrimeNumberTheorem.FirstOrderPerron,
    `PrimeNumberTheorem.FirstOrderLSeriesPerron,
    `PrimeNumberTheorem.FirstOrderExplicitFormula,
    `PrimeNumberTheorem.QuantitativeGoodHeight,
    `PrimeNumberTheorem.GlobalZeroCount,
    `PrimeNumberTheorem.CentralHorizontalEdge,
    `PrimeNumberTheorem.CofinalExplicitFormula,
    `PrimeNumberTheorem.RHNaturalPsiError,
    `PrimeNumberTheorem.RHPrimeCountingConverse,
    `PrimeNumberTheorem.ExplicitFormulaAllHeights,
    `PrimeNumberTheorem.ZetaDerivativeZero,
    `PrimeNumberTheorem.NontrivialZeroMultiplicity,
    `PrimeNumberTheorem.PerronTruncation,
    `PrimeNumberTheorem.VonMangoldtPerronTruncated,
    `PrimeNumberTheorem.PerronExplicitError,
    `PrimeNumberTheorem.LSeriesPerron,
    `PrimeNumberTheorem.CompletePerron,
    `PrimeNumberTheorem.SecondOrderExplicitFormula,
    `PrimeNumberTheorem.SafeSecondOrderExplicitFormula,
    `PrimeNumberTheorem.RightHorizontalEdge,
    `PrimeNumberTheorem.ExplicitFormulaAux,
    `ZeroFreeRegion,
    `ZeroFreeRegion.MeromorphicAux,
    `ZeroFreeRegion.PhragmenLindelofZeta,
    `ZeroFreeRegion.ShiftedJensen,
    `HardyTheorem.Phase1Aux,
    `HardyTheorem.AFE,
    `HardyTheorem.HardyIntegralBasics,
    `HardyTheorem.OscillatoryIntegral,
    `Test.HardyFirstApproximationContract,
    `Test.HardyIntegralBasicsContract,
    `Test.HardyPhaseContract,
    `MathlibAux.RectangleResidue,
    `MathlibAux.BoundaryRectResidue,
    `PrimeNumberTheorem.ExplicitFormulaTruncated,
    `Test.ExplicitFormulaAllHeightsContract,
    `Test.ExplicitFormulaAllHeightsRateContract,
    `Test.ExplicitFormulaBoundedGapContract,
    `Test.CofinalExplicitFormulaContract,
    `Test.CofinalWeightedApproxContract,
    `Test.CompleteHorizontalRateContract,
    `Test.UniformNaturalPerronContract,
    `Test.UniformNaturalContourContract,
    `Test.RHNaturalPsiErrorContract,
    `Test.RHPrimeCountingConverseContract,
    `Test.UniformNaturalTruncatedExplicitFormulaContract,
    `Test.ContourRemainderRateContract,
    `Test.ExplicitFormulaMultiplicityContract,
    `Test.ExplicitFormulaTruncatedUniformContract,
    `Test.FarLeftHorizontalRateContract,
    `Test.FiniteZeroMultiplicityMassContract,
    `Test.FirstOrderExplicitFormulaRateContract,
    `Test.FirstOrderPerronRateContract,
    `Test.GlobalZeroCountContract,
    `Test.LocalZeroContributionBoundContract,
    `Test.LocalZeroMultiplicityBoundContract,
    `Test.MultiplicityAxiomAudit,
    `Test.NontrivialZeroContributionBoundContract,
    `Test.NontrivialZeroDivisorMultiplicityContract,
    `Test.NontrivialZeroMultiplicitySymmetryContract,
    `Test.SelectedHeightAbsorbedLeftEdgeContract,
    `Test.SelectedHeightExplicitFormulaApproxRateContract,
    `Test.SelectedHeightTruncatedExplicitFormulaRateContract,
    `Test.TrivialZeroTailRateContract,
    `Test.ZetaDerivativeZeroContract,
    `Test.ExplicitFormulaTruncatedTargetContract
  ]

require mathlib from "./vendor/mathlib"
