import PrimeNumberTheorem.HalfIsolatedZetaDyadicCapacityBridge

namespace PrimeNumberTheorem.VKEdgePiOverTwo

#print axioms zetaRightDyadicPositiveMassSquareExcluding_eq_sum_image
#print axioms zetaDyadicBaseMassAt_sq_le_capacity_weight
#print axioms zetaRightDyadicPositiveZerosExcluding_subset_adjacentCarlson
#print axioms zetaRightDyadicPositiveMassSquareExcluding_le_adjacentCapacity
#print axioms actualCarlsonAdjacentDyadicStripSquareReciprocalCapacityExcluding_le_add
#print axioms zetaRightDyadicPositiveMassSquareExcluding_le_twoCarlsonCapacities

end PrimeNumberTheorem.VKEdgePiOverTwo
