import WeilExtremalKernels.ArchimedeanTailBudget

/-!
# Rank-two archimedean-tail density

This module constructs the two Cauchy vectors which occur in the finite
Guinand-Weil dictionary and verifies the pointwise rank-two tail estimate.
For the centered coordinates `-N, ..., N`, the vectors have entries

`(T / rho - n)⁻¹` and `(T / rho + n)⁻¹`.

Their weighted Gram matrix is positive semidefinite.  When `rho * N < T`,
its quadratic form is bounded by

`weight * 2 * (2 * N + 1) * (rho / (T - rho * N))² * ‖x‖²`.

This is the unintegrated matrix density and vector-norm budget.  It does not
yet define the matrix-valued improper tail integral, insert the analytic
archimedean weight, derive the final scalar constant `B_T`, verify the basis
transfer, or connect a finite certificate to the infinite Weil criterion.
-/

namespace WeilExtremalKernels

open scoped BigOperators

/-- The rank-one Gram matrix generated by a finite real vector. -/
def rankOneGramMatrix {n : ℕ} (v : FiniteVector n) : FiniteMatrix n :=
  fun i j => v i * v j

/-- The sum of the two rank-one Gram matrices generated by `p` and `q`. -/
def rankTwoGramMatrix {n : ℕ} (p q : FiniteVector n) : FiniteMatrix n :=
  rankOneGramMatrix p + rankOneGramMatrix q

theorem quadraticForm_rankOneGramMatrix {n : ℕ}
    (v x : FiniteVector n) :
    quadraticForm (rankOneGramMatrix v) x =
      (∑ i, x i * v i) ^ 2 := by
  unfold quadraticForm rankOneGramMatrix
  rw [pow_two, Finset.sum_mul_sum]
  apply Finset.sum_congr rfl
  intro i _
  apply Finset.sum_congr rfl
  intro j _
  ring

theorem quadraticForm_rankTwoGramMatrix {n : ℕ}
    (p q x : FiniteVector n) :
    quadraticForm (rankTwoGramMatrix p q) x =
      (∑ i, x i * p i) ^ 2 + (∑ i, x i * q i) ^ 2 := by
  rw [rankTwoGramMatrix, quadraticForm_add,
    quadraticForm_rankOneGramMatrix, quadraticForm_rankOneGramMatrix]

theorem quadraticForm_rankTwoGramMatrix_nonneg {n : ℕ}
    (p q x : FiniteVector n) :
    0 ≤ quadraticForm (rankTwoGramMatrix p q) x := by
  rw [quadraticForm_rankTwoGramMatrix]
  positivity

/-- Cauchy-Schwarz controls the rank-two quadratic form by the sum of the
two squared vector norms. -/
theorem quadraticForm_rankTwoGramMatrix_le {n : ℕ}
    (p q x : FiniteVector n) :
    quadraticForm (rankTwoGramMatrix p q) x ≤
      ((∑ i, (p i) ^ 2) + ∑ i, (q i) ^ 2) * squaredNorm x := by
  rw [quadraticForm_rankTwoGramMatrix]
  have hp := Finset.sum_mul_sq_le_sq_mul_sq Finset.univ x p
  have hq := Finset.sum_mul_sq_le_sq_mul_sq Finset.univ x q
  unfold squaredNorm
  calc
    (∑ i, x i * p i) ^ 2 + (∑ i, x i * q i) ^ 2 ≤
        ((∑ i, x i ^ 2) * ∑ i, p i ^ 2) +
          ((∑ i, x i ^ 2) * ∑ i, q i ^ 2) :=
      add_le_add hp hq
    _ = (∑ i, p i ^ 2 + ∑ i, q i ^ 2) * ∑ i, x i ^ 2 := by ring

noncomputable def cauchyTailPlusVector {n : ℕ}
    (rho T : ℝ) (coordinate : FiniteVector n) : FiniteVector n :=
  fun i => (T / rho - coordinate i)⁻¹

noncomputable def cauchyTailMinusVector {n : ℕ}
    (rho T : ℝ) (coordinate : FiniteVector n) : FiniteVector n :=
  fun i => (T / rho + coordinate i)⁻¹

theorem cauchyTail_denominator_lower {n : ℕ}
    (coordinate : FiniteVector n) {rho radius T : ℝ}
    (hrho : 0 < rho)
    (hcoordinate : ∀ i, |coordinate i| ≤ radius) (i : Fin n) :
    (T - rho * radius) / rho ≤ T / rho - coordinate i ∧
      (T - rho * radius) / rho ≤ T / rho + coordinate i := by
  have hcoordUpper : coordinate i ≤ radius :=
    (le_abs_self (coordinate i)).trans (hcoordinate i)
  have hcoordLower : -radius ≤ coordinate i := by
    have := neg_abs_le (coordinate i)
    linarith [hcoordinate i]
  constructor <;>
    apply (div_le_iff₀ hrho).2 <;>
    field_simp <;>
    nlinarith

theorem cauchyTailVector_sq_le {n : ℕ}
    (coordinate : FiniteVector n) {rho radius T : ℝ}
    (hrho : 0 < rho) (hT : rho * radius < T)
    (hcoordinate : ∀ i, |coordinate i| ≤ radius) (i : Fin n) :
    (cauchyTailPlusVector rho T coordinate i) ^ 2 ≤
        (rho / (T - rho * radius)) ^ 2 ∧
      (cauchyTailMinusVector rho T coordinate i) ^ 2 ≤
        (rho / (T - rho * radius)) ^ 2 := by
  have hbase : 0 < (T - rho * radius) / rho := by
    exact div_pos (sub_pos.mpr hT) hrho
  rcases cauchyTail_denominator_lower coordinate hrho hcoordinate i with
    ⟨hplus, hminus⟩
  have hplusPos : 0 < T / rho - coordinate i := hbase.trans_le hplus
  have hminusPos : 0 < T / rho + coordinate i := hbase.trans_le hminus
  have hinvPlus :
      (T / rho - coordinate i)⁻¹ ≤ ((T - rho * radius) / rho)⁻¹ :=
    (inv_le_inv₀ hplusPos hbase).2 hplus
  have hinvMinus :
      (T / rho + coordinate i)⁻¹ ≤ ((T - rho * radius) / rho)⁻¹ :=
    (inv_le_inv₀ hminusPos hbase).2 hminus
  have hrewrite :
      ((T - rho * radius) / rho)⁻¹ =
        rho / (T - rho * radius) := by
    field_simp
  unfold cauchyTailPlusVector cauchyTailMinusVector
  rw [hrewrite] at hinvPlus hinvMinus
  have hrightPos : 0 < rho / (T - rho * radius) := by
    exact div_pos hrho (sub_pos.mpr hT)
  constructor
  · exact (sq_le_sq₀ (inv_nonneg.mpr hplusPos.le) hrightPos.le).2 hinvPlus
  · exact (sq_le_sq₀ (inv_nonneg.mpr hminusPos.le) hrightPos.le).2 hinvMinus

theorem sum_sq_cauchyTailVectors_le {n : ℕ}
    (coordinate : FiniteVector n) {rho radius T : ℝ}
    (hrho : 0 < rho) (hT : rho * radius < T)
    (hcoordinate : ∀ i, |coordinate i| ≤ radius) :
    (∑ i, (cauchyTailPlusVector rho T coordinate i) ^ 2) +
        ∑ i, (cauchyTailMinusVector rho T coordinate i) ^ 2 ≤
      2 * n * (rho / (T - rho * radius)) ^ 2 := by
  have hp :
      (∑ i, (cauchyTailPlusVector rho T coordinate i) ^ 2) ≤
        n * (rho / (T - rho * radius)) ^ 2 := by
    calc
      (∑ i, (cauchyTailPlusVector rho T coordinate i) ^ 2) ≤
          ∑ _i : Fin n, (rho / (T - rho * radius)) ^ 2 := by
        apply Finset.sum_le_sum
        intro i _
        exact (cauchyTailVector_sq_le coordinate hrho hT hcoordinate i).1
      _ = n * (rho / (T - rho * radius)) ^ 2 := by simp
  have hq :
      (∑ i, (cauchyTailMinusVector rho T coordinate i) ^ 2) ≤
        n * (rho / (T - rho * radius)) ^ 2 := by
    calc
      (∑ i, (cauchyTailMinusVector rho T coordinate i) ^ 2) ≤
          ∑ _i : Fin n, (rho / (T - rho * radius)) ^ 2 := by
        apply Finset.sum_le_sum
        intro i _
        exact (cauchyTailVector_sq_le coordinate hrho hT hcoordinate i).2
      _ = n * (rho / (T - rho * radius)) ^ 2 := by simp
  nlinarith

theorem quadraticForm_cauchyRankTwo_le {n : ℕ}
    (coordinate x : FiniteVector n) {rho radius T : ℝ}
    (hrho : 0 < rho) (hT : rho * radius < T)
    (hcoordinate : ∀ i, |coordinate i| ≤ radius) :
    quadraticForm
        (rankTwoGramMatrix
          (cauchyTailPlusVector rho T coordinate)
          (cauchyTailMinusVector rho T coordinate)) x ≤
      (2 * n * (rho / (T - rho * radius)) ^ 2) * squaredNorm x := by
  calc
    quadraticForm
        (rankTwoGramMatrix
          (cauchyTailPlusVector rho T coordinate)
          (cauchyTailMinusVector rho T coordinate)) x ≤
      ((∑ i, (cauchyTailPlusVector rho T coordinate i) ^ 2) +
        ∑ i, (cauchyTailMinusVector rho T coordinate i) ^ 2) *
        squaredNorm x :=
      quadraticForm_rankTwoGramMatrix_le _ _ _
    _ ≤ (2 * n * (rho / (T - rho * radius)) ^ 2) *
        squaredNorm x :=
      mul_le_mul_of_nonneg_right
        (sum_sq_cauchyTailVectors_le coordinate hrho hT hcoordinate)
        (squaredNorm_nonneg x)

def weightedRankTwoGramMatrix {n : ℕ}
    (weight : ℝ) (p q : FiniteVector n) : FiniteMatrix n :=
  fun i j => weight * (rankTwoGramMatrix p q i j)

theorem quadraticForm_weightedRankTwoGramMatrix {n : ℕ}
    (weight : ℝ) (p q x : FiniteVector n) :
    quadraticForm (weightedRankTwoGramMatrix weight p q) x =
      weight * quadraticForm (rankTwoGramMatrix p q) x := by
  unfold quadraticForm weightedRankTwoGramMatrix
  rw [Finset.mul_sum]
  apply Finset.sum_congr rfl
  intro i _
  rw [Finset.mul_sum]
  apply Finset.sum_congr rfl
  intro j _
  ring

theorem quadraticForm_weightedRankTwoGramMatrix_nonneg {n : ℕ}
    {weight : ℝ} (hweight : 0 ≤ weight) (p q x : FiniteVector n) :
    0 ≤ quadraticForm (weightedRankTwoGramMatrix weight p q) x := by
  rw [quadraticForm_weightedRankTwoGramMatrix]
  exact mul_nonneg hweight (quadraticForm_rankTwoGramMatrix_nonneg p q x)

theorem quadraticForm_weightedCauchyRankTwo_le {n : ℕ}
    (coordinate x : FiniteVector n) {weight rho radius T : ℝ}
    (hweight : 0 ≤ weight) (hrho : 0 < rho) (hT : rho * radius < T)
    (hcoordinate : ∀ i, |coordinate i| ≤ radius) :
    quadraticForm
        (weightedRankTwoGramMatrix weight
          (cauchyTailPlusVector rho T coordinate)
          (cauchyTailMinusVector rho T coordinate)) x ≤
      (weight * (2 * n * (rho / (T - rho * radius)) ^ 2)) *
        squaredNorm x := by
  rw [quadraticForm_weightedRankTwoGramMatrix]
  have h :=
    quadraticForm_cauchyRankTwo_le coordinate x hrho hT hcoordinate
  nlinarith [quadraticForm_rankTwoGramMatrix_nonneg
    (cauchyTailPlusVector rho T coordinate)
    (cauchyTailMinusVector rho T coordinate) x]

/-- The paper's coordinate list `-N, ..., N`, indexed by `Fin (2N+1)`. -/
def centeredIndexCoordinate (N : ℕ) : FiniteVector (2 * N + 1) :=
  fun i => (i.val : ℝ) - N

theorem abs_centeredIndexCoordinate_le (N : ℕ) (i : Fin (2 * N + 1)) :
    |centeredIndexCoordinate N i| ≤ N := by
  rw [abs_le]
  have hN : 0 ≤ (N : ℝ) := Nat.cast_nonneg N
  have hiNat : i.val ≤ 2 * N := by omega
  have hi : (i.val : ℝ) ≤ 2 * (N : ℝ) := by exact_mod_cast hiNat
  constructor <;> unfold centeredIndexCoordinate <;> linarith

noncomputable def paperCauchyPlusVector (N : ℕ) (rho T : ℝ) :
    FiniteVector (2 * N + 1) :=
  cauchyTailPlusVector rho T (centeredIndexCoordinate N)

noncomputable def paperCauchyMinusVector (N : ℕ) (rho T : ℝ) :
    FiniteVector (2 * N + 1) :=
  cauchyTailMinusVector rho T (centeredIndexCoordinate N)

/-- The paper's explicit squared-norm budget for its two Cauchy vectors. -/
theorem sum_sq_paperCauchyVectors_le
    (N : ℕ) {rho T : ℝ} (hrho : 0 < rho) (hT : rho * N < T) :
    (∑ i, (paperCauchyPlusVector N rho T i) ^ 2) +
        ∑ i, (paperCauchyMinusVector N rho T i) ^ 2 ≤
      2 * ((2 * N + 1 : ℕ) : ℝ) * (rho / (T - rho * N)) ^ 2 := by
  simpa only [paperCauchyPlusVector, paperCauchyMinusVector] using
    sum_sq_cauchyTailVectors_le (centeredIndexCoordinate N) hrho hT
      (abs_centeredIndexCoordinate_le N)

/-- The unintegrated weighted rank-two archimedean-tail kernel. It is positive
semidefinite when `weight` is nonnegative, as proved below. -/
noncomputable def paperArchimedeanRankTwoDensity
    (N : ℕ) (weight rho T : ℝ) : FiniteMatrix (2 * N + 1) :=
  weightedRankTwoGramMatrix weight
    (paperCauchyPlusVector N rho T)
    (paperCauchyMinusVector N rho T)

theorem quadraticForm_paperArchimedeanRankTwoDensity_nonneg
    (N : ℕ) {weight rho T : ℝ} (hweight : 0 ≤ weight)
    (x : FiniteVector (2 * N + 1)) :
    0 ≤ quadraticForm
      (paperArchimedeanRankTwoDensity N weight rho T) x := by
  exact quadraticForm_weightedRankTwoGramMatrix_nonneg hweight _ _ x

/-- Pointwise operator-norm budget for the paper's rank-two density. -/
theorem quadraticForm_paperArchimedeanRankTwoDensity_le
    (N : ℕ) {weight rho T : ℝ}
    (hweight : 0 ≤ weight) (hrho : 0 < rho) (hT : rho * N < T)
    (x : FiniteVector (2 * N + 1)) :
    quadraticForm (paperArchimedeanRankTwoDensity N weight rho T) x ≤
      (weight *
        (2 * ((2 * N + 1 : ℕ) : ℝ) * (rho / (T - rho * N)) ^ 2)) *
        squaredNorm x := by
  exact quadraticForm_weightedCauchyRankTwo_le
    (centeredIndexCoordinate N) x hweight hrho hT
      (abs_centeredIndexCoordinate_le N)

end WeilExtremalKernels
