import WeilExtremalKernels.WeilArchimedeanLoewner
import WeilExtremalKernels.WeilPoleKernelIdentity

/-!
# Source-function definition of the global truncated Weil kernel

The finite Guinand-Weil dictionary naturally defines each prime, pole, and
archimedean block through scalar source value and derivative data.  Its
matrix is the associated integer Loewner kernel.

This module makes that source representation the primary global object.
Auxiliary and CCM closed forms can then be treated as independent evaluators
of the same source kernel rather than as definitions of the infinite object.
-/

namespace WeilExtremalKernels

/-- Value and derivative data of one scalar Weil source. -/
structure WeilSourceData where
  value : Int -> Real
  derivative : Int -> Real

/-- Integer Loewner kernel generated by source data. -/
def WeilSourceData.kernel
    (source : WeilSourceData) : Int -> Int -> Real :=
  integerLoewnerKernel source.value source.derivative

/-- Sum of two source functions and their derivative data. -/
def WeilSourceData.add
    (left right : WeilSourceData) : WeilSourceData where
  value := fun n => left.value n + right.value n
  derivative := fun n => left.derivative n + right.derivative n

theorem WeilSourceData.kernel_add
    (left right : WeilSourceData) (m n : Int) :
    (left.add right).kernel m n =
      left.kernel m n + right.kernel m n := by
  exact integerLoewnerKernel_add
    left.value left.derivative
    right.value right.derivative m n

/-- Prime, pole, and archimedean source data of the cutoff-free truncated
finite dictionary.  Signs are included in the individual source data. -/
def totalWeilSourceData
    (prime pole archimedean : WeilSourceData) : WeilSourceData :=
  (prime.add pole).add archimedean

theorem totalWeilSourceData_kernel_decomposition
    (prime pole archimedean : WeilSourceData)
    (m n : Int) :
    (totalWeilSourceData prime pole archimedean).kernel m n =
      prime.kernel m n + pole.kernel m n +
        archimedean.kernel m n := by
  unfold totalWeilSourceData
  rw [WeilSourceData.kernel_add,
    WeilSourceData.kernel_add]
  ring

/-- Centered finite section generated by scalar source data. -/
def sourceCutoffMatrix
    (source : WeilSourceData) (N : Nat) :
    FiniteMatrix (2 * N + 1) :=
  integerKernelCutoffMatrix source.kernel N

/-- Source-defined cutoffs are automatically exact centered principal
sections of every larger cutoff. -/
theorem sourceCutoffMatrix_centered_nested
    (source : WeilSourceData)
    {M N : Nat} (hMN : M <= N) :
    sourceCutoffMatrix source M =
      centeredPrincipalSection hMN (sourceCutoffMatrix source N) := by
  exact integerKernelCutoffMatrix_centered_nested source.kernel hMN

/-- Positive semidefiniteness of one source cutoff passes to all smaller
centered cutoffs. -/
theorem sourceCutoffMatrix_all_smaller_nonneg
    (source : WeilSourceData) (N : Nat)
    (hN :
      forall x,
        0 <= quadraticForm (sourceCutoffMatrix source N) x) :
    forall M (hMN : M <= N) x,
      0 <= quadraticForm (sourceCutoffMatrix source M) x := by
  intro M hMN x
  rw [sourceCutoffMatrix_centered_nested source hMN]
  exact quadraticForm_centeredPrincipalSection_nonneg
    hMN (sourceCutoffMatrix source N) hN x

/-- Strict positivity of one source cutoff passes to all smaller centered
cutoffs. -/
theorem sourceCutoffMatrix_all_smaller_pos
    (source : WeilSourceData) (N : Nat)
    (hN :
      forall x, x != 0 ->
        0 < quadraticForm (sourceCutoffMatrix source N) x) :
    forall M (hMN : M <= N) x, x != 0 ->
      0 < quadraticForm (sourceCutoffMatrix source M) x := by
  exact integerKernelCutoffMatrix_all_smaller_pos
    source.kernel N hN

/-- A pole source is compatible with factorized CCM pole data when its
Loewner kernel equals the rank-two pole kernel pointwise. -/
def PoleSourceCompatible
    (pole : WeilSourceData)
    (poleC poleS : Int -> Real) : Prop :=
  forall m n,
    pole.kernel m n =
      rankTwoPoleKernel poleC poleS m n

/-- The source-defined total kernel equals the abstract CCM kernel whenever
the pole source has the factorized rank-two representation. -/
theorem totalWeilSourceData_kernel_eq_ccm
    (prime pole archimedean : WeilSourceData)
    (poleC poleS : Int -> Real)
    (hpole : PoleSourceCompatible pole poleC poleS)
    (m n : Int) :
    (totalWeilSourceData prime pole archimedean).kernel m n =
      ccmIntegerKernel
        (fun k => prime.value k + archimedean.value k)
        (fun k =>
          prime.derivative k + archimedean.derivative k)
        poleC poleS m n := by
  rw [totalWeilSourceData_kernel_decomposition]
  unfold ccmIntegerKernel
  rw [integerLoewnerKernel_add, hpole]
  ring

/-- The source and CCM descriptions therefore give identical matrices at
every finite cutoff. -/
theorem totalWeilSourceData_cutoff_eq_ccm
    (prime pole archimedean : WeilSourceData)
    (poleC poleS : Int -> Real)
    (hpole : PoleSourceCompatible pole poleC poleS)
    (N : Nat) :
    sourceCutoffMatrix
        (totalWeilSourceData prime pole archimedean) N =
      integerKernelCutoffMatrix
        (ccmIntegerKernel
          (fun k => prime.value k + archimedean.value k)
          (fun k =>
            prime.derivative k + archimedean.derivative k)
          poleC poleS) N := by
  apply integerKernelCutoffMatrix_eq_of_pointwise
  intro m n
  exact totalWeilSourceData_kernel_eq_ccm
    prime pole archimedean poleC poleS hpole m n

/-- The exact abstract gate for using source cutoffs in an infinite target
space.  It still requires positivity for every cutoff, not one selected
certificate. -/
theorem infinite_nonneg_of_all_source_cutoffs
    {X : Type*} [TopologicalSpace X]
    (source : WeilSourceData)
    (q : X -> Real)
    (embed : (Int ->₀ Real) -> X)
    (hcutoffs :
      forall (N : Nat) (x : FiniteVector (2 * N + 1)),
        0 <= quadraticForm (sourceCutoffMatrix source N) x)
    (hcoordinate :
      forall z : Int ->₀ Real,
        exists (N : Nat) (x : FiniteVector (2 * N + 1)),
          q (embed z) =
            quadraticForm (sourceCutoffMatrix source N) x)
    (hdense : Dense (Set.range embed))
    (hcontinuous : Continuous q) :
    forall y : X, 0 <= q y := by
  exact infinite_nonneg_of_all_centered_cutoffs
    source.kernel q embed hcutoffs hcoordinate
    hdense hcontinuous

end WeilExtremalKernels
