import PrimeNumberTheorem.HalfIsolatedZetaFullDyadicCapacityBridge

open PrimeNumberTheorem
open PrimeNumberTheorem.VKEdgePiOverTwo

#print axioms mem_conjugateFinset_iff
#print axioms not_mem_conjugateFinset_iff
#print axioms mem_zeroOrdinateUnitBucket_conj_iff
#print axioms conjugateBucketPair_involutive
#print axioms conjugateBucketPair_injective
#print axioms mem_zetaRightDyadicBucketPairs_conjugate_iff
#print axioms conjugateBucketPair_mem_positiveExcluding_iff
#print axioms zetaRightDyadicNegativeMassSquareExcluding_eq_positive_conjugateFinset
#print axioms zetaRightDyadicNegativeMassSquareExcluding_le_twoCarlsonCapacities
#print axioms zetaRightDyadicPositive_add_negativeMassSquareExcluding_eq_full
#print axioms zetaRightDyadicFullMassSquareExcluding_le_fourCarlsonCapacities
