import PrimeNumberTheorem.ExceptionalZeroSharpEnergyLowerWitnessAdapter

open PrimeNumberTheorem
open PrimeNumberTheorem.VKEdgePiOverTwo

#print axioms eventually_rightHigherDyadicRange_fartherRight_of_energy_lowerBound
